dhis2/dhis2-android-sdk

build.gradle, core/src/main/java/org/hisp/dhis/android/core/user/UserCall.java, core/src/test/java/org/hisp/dhis/android/core/user/UserCallTests.java, gradle.properties
This fixes an issue that occurs after, when feeding the retrieved User with assigned OrganisationUnits (with null paths) to OrganisationUnitCall, causing an exception.
Bumped the sdk version.
=> Changed UserCall to download paths for OrganisationUnits + version bump

core/src/main/java/org/hisp/dhis/android/sdk/ui/adapters/rows/events/EventItemRow.java
Quick fix to show event date when no element is marked as "display in reports"
=> Show event date if no elements to display

build.gradle, core/build.gradle, ui/build.gradle
These changes would allow updating the Android Gradle plugin to version 3.0.1 and Gradle to version 4.1
=> Migration from deprecated android-apt to annotationProcessor

.gitignore, build.gradle, core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeValueStoreShould.java, core/src/main/java/org/hisp/dhis/android/core/D2.java, core/src/main/java/org/hisp/dhis/android/core/calls/TrackerEntitiesDataCall.java, core/src/main/java/org/hisp/dhis/android/core/data/database/DbOpenHelper.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/TeiQuery.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/TeisEndPointCall.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceEndPointCall.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceService.java, gradle.properties
It adds the funcionality of downloading several TrackedEntityInstances per org.unit (A revision of the sync method is needed)
=> Download TrackedEntityInstances per Org.Unit

core/src/androidTest/java/org/hisp/dhis/android/core/MetadataCallRealIntegrationShould.java
Includes a test that performs sync only once in MetadataCallRealIntegrationShould.java, to speed up manual testing with real servers.
=> metadata-real-integration-sync-once

core/src/main/java/org/hisp/dhis/android/core/data/api/InFilter.java, core/src/test/java/org/hisp/dhis/android/core/data/api/FilterConverterShould.java
Fixes in filter for empty value set. Previously, when values were empty no filter was being generated, which was producing the download of all entities instead of none of them.
=> In filter empty values

core/src/androidTest/java/org/hisp/dhis/android/core/common/IdentifiableModelAbstractShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/common/NameableModelAbstractShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/dataset/DataSetModelShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/datavalue/DataValueModelShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/indicator/IndicatorModelShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/indicator/IndicatorTypeModelShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/legendset/LegendModelShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/legendset/LegendSetModelShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueModelShould.java, core/src/test/java/org/hisp/dhis/android/core/category/CategoryOptionModelBuilderShould.java, core/src/test/java/org/hisp/dhis/android/core/common/IdentifiableModelBuilderAbstractShould.java, core/src/test/java/org/hisp/dhis/android/core/common/ModelBuilderAbstractShould.java, core/src/test/java/org/hisp/dhis/android/core/common/NameableModelBuilderAbstractShould.java, core/src/test/java/org/hisp/dhis/android/core/dataset/DataSetModelBuilderShould.java, core/src/test/java/org/hisp/dhis/android/core/datavalue/DataValueModelBuilderShould.java, core/src/test/java/org/hisp/dhis/android/core/indicator/IndicatorModelBuilderShould.java, core/src/test/java/org/hisp/dhis/android/core/indicator/IndicatorTypeModelBuilderShould.java, core/src/test/java/org/hisp/dhis/android/core/legendset/LegendModelBuilderShould.java, core/src/test/java/org/hisp/dhis/android/core/legendset/LegendSetModelBuilderShould.java, core/src/test/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitModelBuilderShould.java, core/src/test/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueModelBuilderShould.java
Removes pojos and pojoToModel testing in model tests, since conversion is no longer done in models but in ModelBuilders. In the cases where the conversion was tested there but there was no model builder test yet, it has been created.
=> Model builder tests

core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeValueModelBuilder.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceModelBuilder.java, core/src/test/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeValueModelBuilderShould.java, core/src/test/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceModelBuilderShould.java
TrackedEntityInstance and TrackedEntityAttributeValue model builders to the clients of the online search can easily transform the returned pojos into models. 
Related to [ANDROSDK-39](https://jira.dhis2.org/browse/ANDROSDK-39).
On top of #202
=> Tei model builders

core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/SearchGridMapper.java, core/src/test/java/org/hisp/dhis/android/core/trackedentity/search/SearchGridMapperShould.java
Solves [ANDROSDK-169](https://jira.dhis2.org/browse/ANDROSDK-169).
Organisation Unit name and inactive are ignored, since there are no place for them in the Pojo.
=> Tei search mapper

core/src/androidTest/java/org/hisp/dhis/android/core/TrackedEntityInstanceQueryCallRealIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/D2.java, core/src/main/java/org/hisp/dhis/android/core/common/D2CallException.java, core/src/main/java/org/hisp/dhis/android/core/datavalue/DataValueEndpointCall.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceService.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/SearchGridMapper.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQuery.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryCall.java, core/src/main/java/org/hisp/dhis/android/core/utils/Utils.java, core/src/test/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryCallShould.java
Solves TEIs online search. A method is exposed in D2 so that the can perform the query. A builder for the query is provided for maximum flexibility. Attributes and filter are passed as a list of strings, we can provide a new structure in the future.
I will set [ANDROSDK-39](https://jira.dhis2.org/browse/ANDROSDK-39) as "Coding Done". We can create new tickets for smaller issues and for the second step of the online search (persistence of downloaded TEIs). 
TrackedEntityInstanceQueryCallRealIntegrationShould tests functionality using D2 with a real server.
=> Tei search

core/src/main/java/org/hisp/dhis/android/core/D2.java, core/src/main/java/org/hisp/dhis/android/core/calls/MetadataCall.java, core/src/main/java/org/hisp/dhis/android/core/common/Unit.java, core/src/main/java/org/hisp/dhis/android/core/user/LogOutUserCallable.java, core/src/main/java/org/hisp/dhis/android/core/user/UserAuthenticateCall.java, core/src/test/java/org/hisp/dhis/android/core/user/LogOutUserCallableShould.java, core/src/test/java/org/hisp/dhis/android/core/user/UserAuthenticateCallUnitShould.java
Solves [ANDROSDK-235](https://jira.dhis2.org/browse/ANDROSDK-235). Only applied to MetadataSync, so it can be tested in the app. Other D2 calls, like wipeDb or syncAggregatedData must be reviewed as well.
=> metadata-call-not-null: make MetadataCall return unit

core/src/main/java/org/hisp/dhis/android/core/dataelement/DataElementEndpointCall.java, core/src/main/java/org/hisp/dhis/android/core/indicator/IndicatorEndpointCall.java, core/src/main/java/org/hisp/dhis/android/core/indicator/IndicatorTypeEndpointCall.java, core/src/main/java/org/hisp/dhis/android/core/option/OptionSetCall.java, core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageEndpointCall.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityTypeCall.java
Do not use "lastUpdated" filter in query by uid (linked to [ANDROSDK-244](https://jira.dhis2.org/browse/ANDROSDK-244))
=> uid-call-last-updated: remove lastUpdated filter in uidPayloadCall

core/src/main/java/org/hisp/dhis/android/core/common/BaseIdentifiableObject.java, core/src/main/java/org/hisp/dhis/android/core/common/ObjectWithDeleteInterface.java, core/src/main/java/org/hisp/dhis/android/core/enrollment/Enrollment.java, core/src/main/java/org/hisp/dhis/android/core/event/Event.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstance.java, core/src/main/java/org/hisp/dhis/android/core/utils/Utils.java
Creates an interface for objects with `delete()` method and use it in `Utils`, being able to remove 3 duplicated versions of `isDeleted()`.
=> object-with-delete: create interface and remove duplication

core/src/main/java/org/hisp/dhis/android/core/user/AuthenticatedUserModel.java
Removes id field from AuthenticatedUserModel, which is not necessary since it extends BaseModel, which already has the field.
=> authenticated-user-remove-id: remove unnecessarily overriden id in AhenticatedUserModel

core/src/androidTest/java/org/hisp/dhis/android/core/program/ProgramEndpointCallMockIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/program/ProgramTrackedEntityAttributeModelShould.java, core/src/main/java/org/hisp/dhis/android/core/program/ProgramTrackedEntityAttributeModel.java, core/src/main/java/org/hisp/dhis/android/core/program/ProgramTrackedEntityAttributeModelBuilder.java
Removes allowFutureDates inconsistency (POJO, web API and column were in singular, model field was in plural).
=> allow-future-dates-inconsistency: remove plural singular inconsistency

core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetCompleteRegistrationPayload.java
[ANDROSDK-340](https://jira.dhis2.org/browse/ANDROSDK-340)
=> ANDROSDK-340: d2.syncAggregatedData().call(); generates an exception in 2.30

core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipItem.java, core/src/test/java/org/hisp/dhis/android/core/relationship/RelationshipItemShould.java
Validates exactly one element is included in RelationshipItem. Otherwise it fails calling .build() in the builder with a IllegalArgumentException.
=> relationship-item-instantiation-validate: validate no more than one element is included in item

core/src/androidTest/java/org/hisp/dhis/android/core/category/CategoryModuleMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/arch/db/executors/CursorExecutor.java, core/src/main/java/org/hisp/dhis/android/core/arch/db/executors/CursorExecutorImpl.java, core/src/main/java/org/hisp/dhis/android/core/arch/db/stores/LinkModelChildStore.java, core/src/main/java/org/hisp/dhis/android/core/arch/db/stores/LinkModelChildStoreImpl.java, core/src/main/java/org/hisp/dhis/android/core/arch/db/tableinfos/LinkTableChildProjection.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/children/ChildrenAppender.java, core/src/main/java/org/hisp/dhis/android/core/category/CategoryCategoryComboLinkChildStore.java, core/src/main/java/org/hisp/dhis/android/core/category/CategoryCategoryComboLinkStore.java, core/src/main/java/org/hisp/dhis/android/core/category/CategoryCategoryComboLinkTableInfo.java, core/src/main/java/org/hisp/dhis/android/core/category/CategoryCategoryComboTableInfo.java, core/src/main/java/org/hisp/dhis/android/core/category/CategoryChildrenAppender.java, core/src/main/java/org/hisp/dhis/android/core/category/CategoryComboCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/category/CategoryOptionComboChildrenAppender.java, core/src/main/java/org/hisp/dhis/android/core/category/CategoryStore.java, core/src/main/java/org/hisp/dhis/android/core/common/ObjectStyleChildrenAppender.java, core/src/main/java/org/hisp/dhis/android/core/common/SQLStatementBuilder.java, core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipConstraintChildrenAppender.java, core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipItemChildrenAppender.java, core/src/test/java/org/hisp/dhis/android/core/common/SQLStatementBuilderShould.java
- Solves [ANDROSDK-405](ANDROSDK-405)
- Implements children appender for CategoryCategoryOption as use case of LinkTableChildStore, partially solving [ANDROSDK-409](https://jira.dhis2.org/browse/ANDROSDK-409)
- Makes ChildrenAppender a base class so we don't have to implement prepareChildren in most cases
=> [ANDROSDK-405] Implement generic link table child store

core/src/main/java/org/hisp/dhis/android/core/event/EventPostCall.java
Related to [ANDROSDK-347](https://jira.dhis2.org/browse/ANDROSDK-347). Catch error 409 and process the payload.
=> [ANDROSDK-347-2] Catch error 409 in SingleEventPostCall

.travis.yml, build.gradle
Upgrades Android Target SDK to API 27 (Android 8.1). It doesn't affect to the minimum SDK version supported.
=> android-sdk-28

core/src/androidTest/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitCallMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/category/Category.java, core/src/main/java/org/hisp/dhis/android/core/category/CategoryCombo.java, core/src/main/java/org/hisp/dhis/android/core/category/CategoryOption.java, core/src/main/java/org/hisp/dhis/android/core/category/CategoryOptionCombo.java, core/src/main/java/org/hisp/dhis/android/core/common/BaseIdentifiableObject.java, core/src/main/java/org/hisp/dhis/android/core/common/BaseModel.java, core/src/main/java/org/hisp/dhis/android/core/common/Model.java, core/src/main/java/org/hisp/dhis/android/core/dataelement/DataElement.java, core/src/main/java/org/hisp/dhis/android/core/dataset/DataSet.java, core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetElement.java, core/src/main/java/org/hisp/dhis/android/core/dataset/Section.java, core/src/main/java/org/hisp/dhis/android/core/indicator/Indicator.java, core/src/main/java/org/hisp/dhis/android/core/indicator/IndicatorType.java, core/src/main/java/org/hisp/dhis/android/core/legendset/Legend.java, core/src/main/java/org/hisp/dhis/android/core/legendset/LegendSet.java, core/src/main/java/org/hisp/dhis/android/core/option/Option.java, core/src/main/java/org/hisp/dhis/android/core/option/OptionSet.java, core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnit.java, core/src/main/java/org/hisp/dhis/android/core/program/Program.java, core/src/main/java/org/hisp/dhis/android/core/program/ProgramIndicator.java, core/src/main/java/org/hisp/dhis/android/core/program/ProgramRule.java, core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageSection.java, core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipType.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityDataValue.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityType.java, core/src/main/java/org/hisp/dhis/android/core/user/User.java, core/src/main/java/org/hisp/dhis/android/core/user/UserCredentials.java, core/src/sharedTest/java/org/hisp/dhis/android/core/data/organisationunit/OrganisationUnitSamples.java
Solves [ANDROSDK-449](https://jira.dhis2.org/browse/ANDROSDK-449).
Removed id from unified classes since annotations could be moved to interface. Id still has to be included in the builders.
=> [ANDROSDK-449] Remove explicit id in unified classes

core/src/main/java/org/hisp/dhis/android/core/common/StoreFactory.java
Solves [ANDROSDK-570](https://jira.dhis2.org/browse/ANDROSDK-570)
=> [ANDROSDK-570] Deprecate stores factory methods that don't use a TableInfo

core/src/main/java/org/hisp/dhis/android/core/option/OptionGroupEntityDIModule.java, core/src/main/java/org/hisp/dhis/android/core/option/OptionGroupHandler.java, core/src/main/java/org/hisp/dhis/android/core/program/ProgramModuleDownloader.java, core/src/test/java/org/hisp/dhis/android/core/program/ProgramModuleDownloaderShould.java
Solves [ANDROSDK-652-B](https://jira.dhis2.org/browse/ANDROSDK-652) and [ANDROSDK-660](https://jira.dhis2.org/browse/ANDROSDK-660).
=> [ANDROSDK-652-B] and [ANDROSDK-660] Not call for option groups on 2.29 and delete not downloaded option groups

core/src/androidTest/java/org/hisp/dhis/android/core/d2manager/D2ManagerRealIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/d2manager/D2Configuration.java, core/src/main/java/org/hisp/dhis/android/core/d2manager/D2Manager.java, core/src/main/java/org/hisp/dhis/android/core/d2manager/TLSSocketFactory.java, core/src/main/java/org/hisp/dhis/android/core/user/UserCredentialsStore.java
Solves [ANDROSDK-712](https://jira.dhis2.org/browse/ANDROSDK-712) and [ANDROSDK-713](https://jira.dhis2.org/browse/ANDROSDK-713).
Creates a manager which allow to create the D2 class without the need of passing a database adapter and an http client.
=> [ANDROSDK-712] and [ANDROSDK-713] Move databaseAdapter and OkHttpClient creation to sdk

core/src/main/java/org/hisp/dhis/android/core/common/ObjectStoreImpl.java
Also called inside `addObjectsToCollection()`
=> [ANDROSDK-789] Remove duplicated call to cursor.close()

core/src/main/java/org/hisp/dhis/android/core/period/internal/BiMonthlyPeriodGenerator.java, core/src/main/java/org/hisp/dhis/android/core/period/internal/NMonthlyPeriodGeneratorFactory.java
[ANDROSDK-885](https://jira.dhis2.org/browse/ANDROSDK-885)
=> fix: [ANDROSDK-885] Bad syntax on generated Bi-Monthly period ids

core/src/main/java/org/hisp/dhis/android/core/arch/helpers/GeometryHelper.java
Fix a typo on the containsAPoint() method from the GeometryHelper class.
=> refactor: [androsdk-913-2] Fix typo on geometry helper

core/src/main/java/org/hisp/dhis/android/core/fileresource/internal/FileResourceUtil.java
Solves [ANDROSDK-948](https://jira.dhis2.org/browse/ANDROSDK-948).
=> feat: [androsdk-948] Add a method to get a sdk cache resources directory

core/src/androidTest/java/org/hisp/dhis/android/testapp/arch/helpers/FileResizerHelperShould.java, core/src/androidTest/java/org/hisp/dhis/android/testapp/fileresource/FileResourceCollectionRepositoryMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/arch/helpers/FileResourceDirectoryHelper.java, core/src/main/java/org/hisp/dhis/android/core/fileresource/internal/FileResourceUtil.java
Solves [ANDROSDK-951](https://jira.dhis2.org/browse/ANDROSDK-951).
=> fix: [androsdk-951] Extract file resource directory methods outside internal packages

core/src/androidTest/java/org/hisp/dhis/android/core/organisationunit/internal/OrganisationUnitCallMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnit.java, core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitAncestorsAccessor.java, core/src/main/java/org/hisp/dhis/android/core/organisationunit/internal/OrganisationUnitCallFactory.java, core/src/main/java/org/hisp/dhis/android/core/organisationunit/internal/OrganisationUnitDisplayPathTransformer.java, core/src/main/java/org/hisp/dhis/android/core/organisationunit/internal/OrganisationUnitEntityDIModule.java, core/src/main/java/org/hisp/dhis/android/core/organisationunit/internal/SearchOrganisationUnitOnDemandCallFactory.java, core/src/test/java/org/hisp/dhis/android/core/organisationunit/internal/OrganisationUnitCallUnitShould.java, core/src/test/java/org/hisp/dhis/android/core/organisationunit/internal/OrganisationUnitDisplayPathGeneratorShould.java, core/src/test/java/org/hisp/dhis/android/core/organisationunit/internal/OrganisationUnitHandlerShould.java
Solves [ANDROSDK-960](https://jira.dhis2.org/browse/ANDROSDK-960).
=> refactor: [androsdk-960] Remove organisation unit ancestors method visibility from OrganisationUnit

core/plugins/gradle-mvn-push.gradle
Solves [ANDROSDK-978](https://jira.dhis2.org/browse/ANDROSDK-978).
=> feat: [androsdk-978] Exclude internal accessors from JavaDocs

core/src/androidTest/java/org/hisp/dhis/android/core/period/internal/PeriodStoreIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/period/internal/CalendarProvider.java, core/src/main/java/org/hisp/dhis/android/core/period/internal/CalendarProviderFactory.java, core/src/main/java/org/hisp/dhis/android/core/period/internal/FixedCalendarProvider.java, core/src/main/java/org/hisp/dhis/android/core/period/internal/ParentPeriodGeneratorImpl.java, core/src/main/java/org/hisp/dhis/android/core/period/internal/PeriodPackageDIModule.java, core/src/main/java/org/hisp/dhis/android/core/period/internal/RegularCalendarProvider.java
Solves [ANDROSDK-1054](https://jira.dhis2.org/browse/ANDROSDK-1054).
=> fix: [ANDROSDK-1054-2] Make Peroid related tests independent of current date

core/build.gradle, core/src/main/java/org/hisp/dhis/android/core/arch/db/access/internal/DbMigrationExecutor.java, core/src/main/java/org/hisp/dhis/android/core/arch/db/access/internal/DbMigrationParser.java
This also removes SQLBrite dependency.
=> feat: [ANDROSDK-3-D] Extract migration code to reuse in SQL cipher

core/src/main/java/org/hisp/dhis/android/core/common/Geometry.java
Solves [ANDROSDK-1064](https://jira.dhis2.org/browse/ANDROSDK-1064).
=> fix: [androsdk-1064] Delete not necessary id property for geometry object

core/src/main/java/org/hisp/dhis/android/core/event/internal/EventQueryBundleFactory.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceQueryBuilderFactory.java, core/src/test/java/org/hisp/dhis/android/core/event/internal/EventQueryBundleFactoryShould.java, core/src/test/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceQueryBuilderFactoryShould.java
Solves [ANDROSDK-1156](https://jira.dhis2.org/browse/ANDROSDK-1156)
=> fix: [ANDROSDK-1156] Use user defined limit and enrollment status only if global or program/event

core/src/main/java/org/hisp/dhis/android/core/user/internal/UserAuthenticateCallFactory.java
Solves [ANDROSDK-1166](https://jira.dhis2.org/browse/ANDROSDK-1166).
=> fix: [ANDROSDK-1166] Remove credentials in login when system info call fails

core/src/main/java/org/hisp/dhis/android/core/maintenance/D2Error.java
Solves [ANDROSDK-1189](https://jira.dhis2.org/browse/ANDROSDK-1189)
=> fix: [ANDROSDK-1189] Make D2Error errorComponent nullable

core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueManager.java, runChecks.sh
Solves [ANDROSDK-1291](https://jira.dhis2.org/browse/ANDROSDK-1291).
Now, no extra reserved values are downloaded when asking for a reserved value for enrollment outside of a org. unit pattern scope.
=> fix: [androsdk-1291] Fix remaining reserved values count

core/src/androidTest/java/org/hisp/dhis/android/core/systeminfo/SystemInfoModuleMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/event/internal/EventFilterCall.java, core/src/sharedTest/java/org/hisp/dhis/android/core/data/systeminfo/SystemInfoSamples.java, core/src/sharedTest/resources/systeminfo/system_info.json
Solves [ANDROSDK-1297](https://jira.dhis2.org/browse/ANDROSDK-1297).
=> fix: [androsdk-1297] Avoid to call EventFilterCall if version is not greater than 2.31

.gitignore, .idea/gradle.xml
Forces the use of JDK 1.8 in patch branch for 1.5. This is required by the version of gradle used in this branch.
=> fix: [JDK-1.8-PATCH-RELEASE] Force JDK 1.8 in patch release (1.5)

core/src/main/java/org/hisp/dhis/android/core/D2Manager.kt
Hi Victor, during a jira issue we found out that setting an AndroidSecure Storage was not enough because the credentials were always null (not sure if this changed because of multi user) and we had to set them on D2Manager. Perhaps we're missing something? Let us know. 
This is needed for UI test that need to skip the login process.
Thanks
=> fix: set credentials for UI Testing

core/src/main/java/org/hisp/dhis/android/core/user/AccountDeletionReason.kt, core/src/main/java/org/hisp/dhis/android/core/user/internal/AccountManagerImpl.kt, core/src/main/java/org/hisp/dhis/android/core/user/internal/LogInCall.kt, core/src/main/java/org/hisp/dhis/android/core/user/internal/UserAccountDisabledErrorCatcher.kt, core/src/test/java/org/hisp/dhis/android/core/user/internal/UserAccountDisabledErrorCatcherShould.kt
Solves [ANDROSDK-1534](https://jira.dhis2.org/browse/ANDROSDK-1534).
=> fix: [androsdk-1534] Update account manager to only emit on the delete account observable when the SDK itself deletes the account.

Jenkinsfile
Pull request id was not correctly parsed in Jenkinsfile. It was parsed as "null" string instead of a null value.
=> fix: [JENKINS-PULL-REQUEST-ID-FIX] Set PULL_REQUEST to null on pushes

core/src/main/java/org/hisp/dhis/android/core/settings/internal/SettingModuleDownloader.kt
The metadata synchronization used to throw a D2Error and stop if the call to catch the latestVersion responded with a 404, now it just logs the error and does not throw it.
=> fix: [ANDROSDK-1651] Fix metadataSync when latestVersion returns a 404 D2 error

core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryOnlineHelper.kt, core/src/test/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryOnlineHelperShould.kt
fix:
- ",", ";", ":" characters in filters need to be escaped with "/". The backend is fixed this issue only for the new importer, versions 40.1, 41.0 and newer.
=> fix: [ANDROSDK-1219] Escape ",", ";", ":" characters in queries' filters

core/build.gradle.kts, core/plugins/gradle-mvn-push.gradle
The update of Kotlin (1.9.0) and Gradle plugin had made Dokka task fail. 
- Update Dokka to a compatible version
- Remove explicit sources in Publish task. Source files seems to be automatically included in the publication.
=> fix: [ANDROSDK-1737-DEFECT] Update dokka; remove explicit sources in publish

core/src/main/java/org/hisp/dhis/android/core/D2Manager.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryCallFactory.kt, core/src/test/java/org/hisp/dhis/android/core/arch/api/executors/internal/CoroutineAPICallExecutorMock.kt
Wraps query to old tracker endpoint in coroutine error handler
=> fix: [ANDROSDK-1731-DEFECT] Wrap TEI query call in old tracker endpoints 

core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntitySearchItemHelper.kt
Solves [ANDROSDK-1743](https://dhis2.atlassian.net/browse/ANDROSDK-1743).
[ANDROSDK-1743]: https://dhis2.atlassian.net/browse/ANDROSDK-1743?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [ANDROSDK-1743-DEFECT] Not filter null values when returning attribute values

core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueManager.kt
fix:
- TrackedEntityAttributeReservedValueManager was refactor from Java/RxJava to Kotlin/Coroutines, some RxJava's code "onErrorComplete" was mistakenly skipped, so it was needed to add a `try/catch` ignoring the errors
=> fix: [ANDROSDK-1746] Reserved value is not returned if server is exhausted

core/src/androidTest/java/org/hisp/dhis/android/testapp/trackedentity/search/TrackedEntityInstanceQueryCollectionRepositoryMockIntegrationShould.kt, core/src/androidTest/java/org/hisp/dhis/android/testapp/trackedentity/search/TrackedEntitySearchCollectionRepositoryMockIntegrationShould.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryCollectionRepository.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntitySearchCollectionRepository.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntitySearchOperators.kt
Solves [ANDROSDK-1782](https://dhis2.atlassian.net/browse/ANDROSDK-1782).
Adds support to filter by trackedEntity uid in TEI search. It improves the performance of `.uid()` method. This method evaluated all the TEIs before filtering by uid. Now, it filters by uid in first place and then evaluates the TEI (header, attributes, etc)
[ANDROSDK-1782]: https://dhis2.atlassian.net/browse/ANDROSDK-1782?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [ANDROSDK-1782] Support search by trackedEntity in TEI search

core/src/androidTest/java/org/hisp/dhis/android/testapp/dataset/DataSetInstanceServiceMockIntegrationShould.kt, core/src/androidTest/java/org/hisp/dhis/android/testapp/organisationunit/OrganisationUnitCollectionRepositoryMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/dataset/internal/DataSetInstanceServiceImpl.kt, core/src/sharedTest/resources/category/category_options.json, core/src/sharedTest/resources/organisationunit/organisation_units.json
fix:
- DataSetInstanceServiceImpl `blockingGetEditableStatus` expired and closed checks
test:
- New `DataSetInstanceServiceMockIntegrationShould` for `DataSetInstanceServiceImpl`: `blockingGetEditableStatus` expired and closed checks
=> fix: [ANDROSDK-1787] Expired and closed editable status

core/build.gradle.kts, core/src/main/java/org/hisp/dhis/android/core/arch/db/access/internal/DatabaseAdapterFactory.java, core/src/main/java/org/hisp/dhis/android/core/arch/db/access/internal/DatabaseExport.java, core/src/main/java/org/hisp/dhis/android/core/arch/db/access/internal/EncryptedDatabaseAdapter.java, core/src/main/java/org/hisp/dhis/android/core/arch/db/access/internal/EncryptedDatabaseOpenHelper.java, core/src/main/java/org/hisp/dhis/android/core/arch/db/access/internal/EncryptedStatementWrapper.java, core/src/main/java/org/hisp/dhis/android/core/arch/helpers/FileResourceDirectoryHelper.kt, core/src/main/java/org/hisp/dhis/android/core/common/internal/NativeLibraryLoader.kt, core/src/main/java/org/hisp/dhis/android/core/user/internal/UserCall.kt
fix:
- Update SQLCipher to 4.5.5 in order to allow parallel operations on a database
=> fix: [ANDROSDK-1784] Database access is locked when transaction opened in encrypted DB

core/gradle.properties, core/src/main/java/org/hisp/dhis/android/core/systeminfo/DHISVersion.kt, core/src/test/java/org/hisp/dhis/android/core/systeminfo/internal/DHISVersionShould.kt
This PR changes the version to 1.10.0-SNAPSHOT and enables connections to DHIS2 v41. This PR makes "develop" branch ready for 1.10.0 development.
A new branch `1.9.1-rc` has been created for the patch release.
=> [BUMP-1.10.0] Bump to 1.10.0-SNAPSHOT; enable v41

core/src/main/java/org/hisp/dhis/android/core/arch/api/payload/internal/TrackerPager.kt, core/src/main/java/org/hisp/dhis/android/core/arch/api/payload/internal/TrackerPayload.kt, core/src/main/java/org/hisp/dhis/android/core/event/internal/NewEventEndpointCallFactory.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/NewTrackedEntityEndpointCallFactory.kt, core/src/main/java/org/hisp/dhis/android/core/tracker/exporter/TrackerExporterService.kt, core/src/sharedTest/resources/event/new_tracker_importer_events_greater_equal_v41.json, core/src/sharedTest/resources/event/new_tracker_importer_events_lower_v41.json, core/src/sharedTest/resources/trackedentity/new_tracker_importer_tracked_entities_greater_equal_v41.json, core/src/sharedTest/resources/trackedentity/new_tracker_importer_tracked_entities_lower_v41.json, core/src/test/java/org/hisp/dhis/android/core/event/NewTrackerImporterEventPayloadGreaterEqualV41Should.kt, core/src/test/java/org/hisp/dhis/android/core/event/NewTrackerImporterEventPayloadLowerV41Should.kt, core/src/test/java/org/hisp/dhis/android/core/trackedentity/NewTrackerImporterTrackedEntityPayloadGreaterEqualV41Should.kt, core/src/test/java/org/hisp/dhis/android/core/trackedentity/NewTrackerImporterTrackedEntityPayloadLowerV41Should.kt
Solves [ANDROSDK-1805](https://dhis2.atlassian.net/browse/ANDROSDK-1805)
New `TrackerPayload` class to accommodate both kinds of payload (<41 and >= 41). It uses the annotation @JsonAnyGetter to deserialize the item list, no matter the property name (in the same way it is done for metadata). Changes in pager are managed as well.
[ANDROSDK-1805]: https://dhis2.atlassian.net/browse/ANDROSDK-1805?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: [ANDROSDK-1805] Adapt to changes in tracker payload (v41)

Jenkinsfile
Abort previous builds for the same pipeline. This configuration is already set in the Android Capture App
=> fix: [DISABLE-CONCURRENT-BUILDS] Disable concurrent builds

core/src/main/java/org/hisp/dhis/android/core/event/internal/EventDateUtils.kt
Solves [ANDROSDK-1825](https://dhis2.atlassian.net/browse/ANDROSDK-1825).
[ANDROSDK-1825]: https://dhis2.atlassian.net/browse/ANDROSDK-1825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [ANDOSDK-1825] Prevent isEventExpired failure on null eventDate

core/src/main/java/org/hisp/dhis/android/core/event/internal/EventDateUtils.kt, core/src/test/java/org/hisp/dhis/android/core/event/internal/EventDateUtilsShould.kt
Solves [ANDROSDK-1835](https://dhis2.atlassian.net/browse/ANDROSDK-1835).
[ANDROSDK-1835]: https://dhis2.atlassian.net/browse/ANDROSDK-1835?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ANDROSDK-1835] Fix crash on event expired method when event and due dates are null

Jenkinsfile, build.gradle.kts, runChecks.sh, scripts/hooks/pre-commit, scripts/hooks/prepare-commit-msg, tasks.gradle.kts
To add the `pre-commit` and `prepare-commit-msg` script to your `.git/hooks` directory just run the gradle task `installGitHooks` with gradlew.
The pre-commit script runs kotlintFormat and detekt before commiting.
To avoid run the pre-commit if you don't need it you can add `--no-verify` at the end of your commit:
`git commit -m "Your commit message" --no-verify
`
This script ensures that Git commit messages include the current branch name (in uppercase) at the beginning, unless the branch is excluded (e.g., `master` or `develop`) or already mentioned in the commit message.
The gradle tasks are refactored outside the `build.gradle.kts` to `tasks.gradle.kts` and the `runChecks.sh` have been refactored to a gradle task.
=> feat: [ANDROSDK-1859] Add gradle task to install pre-commit and prepare-commit-msg scripts

core/src/androidTest/java/org/hisp/dhis/android/core/event/internal/EventPostNewMockIntegrationShould.kt, core/src/main/java/org/hisp/dhis/android/core/tracker/importer/internal/JobQueryCall.kt, core/src/main/java/org/hisp/dhis/android/core/tracker/importer/internal/JobReport.kt, core/src/main/java/org/hisp/dhis/android/core/tracker/importer/internal/TrackerImporterService.kt, core/src/sharedTest/resources/imports/tracker-importer/job_response_completed.json
Solves [ANDROSDK-1885](https://dhis2.atlassian.net/browse/ANDROSDK-1885).
This PR changes the behavior of the importer. Now, the importer checks the job status instead of the job report. Once the job status tells the job is complete, it fetches the job report. If the job report does not exist (as in the reported issue), it finishes the execution.
Previously, the job status changed to complete with an error and the job report was never available. That is the reason why fetching the job report never succeeded and had to wait for ~3minutes to finish.
[ANDROSDK-1885]: https://dhis2.atlassian.net/browse/ANDROSDK-1885?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [ANDROSDK-1885] Handle failed tracker job reports

core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackerQueryFactoryCommonHelper.kt, core/src/test/java/org/hisp/dhis/android/core/event/internal/EventQueryBundleFactoryShould.kt
Solves [ANDROSDK-1893](https://dhis2.atlassian.net/browse/ANDROSDK-1893)
This PR fixes the priority to determine the value of limitByOrgunit. The specific settings for a particular program was not respected when the application provided an explicit value for limitByOrgunit. The specific setting must be respected unless the application provides a explicit program id as well (check jira issue description).
[ANDROSDK-1893]: https://dhis2.atlassian.net/browse/ANDROSDK-1893?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [ANDROSDK-1893] Apply right priority in the evaluation of limitByOrgunit 

core/src/androidTest/java/org/hisp/dhis/android/testapp/maintenance/D2ErrorCollectionRepositoryMockIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/testapp/maintenance/MaintenanceMockIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/testapp/trackedentity/TrackedEntityAttributeValueCollectionRepositoryMockIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/testapp/trackedentity/TrackedEntityInstanceCollectionRepositoryMockIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/testapp/trackedentity/search/TrackedEntitySearchCollectionRepositoryMockIntegrationShould.kt, core/src/main/java/org/hisp/dhis/android/core/fileresource/internal/FileResourceDownloadCall.kt, core/src/sharedTest/resources/trackedentity/new_tracker_importer_tracked_entities.json, core/src/sharedTest/resources/trackedentity/tracked_entity_instances.json
Solves [ANDROSDK-1906](https://dhis2.atlassian.net/browse/ANDROSDK-1906).
FileResource download was stopping if a file resource didn't exist in the server. This is something likely to happen in demo instances, it should happen in production instances.
[ANDROSDK-1906]: https://dhis2.atlassian.net/browse/ANDROSDK-1906?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [ANDROSDK-1906] Continue fileResource download when error 

core/src/main/java/org/hisp/dhis/android/core/arch/api/HttpServiceClient.kt, core/src/main/java/org/hisp/dhis/android/core/arch/api/executors/internal/APIErrorMapper.kt
Solves [ANDROSDK-1930](https://dhis2.atlassian.net/browse/ANDROSDK-1930)
Removes the explicit http header `Connection: close`. As of HTTP1.1, the default value is `keep-alive`, so the header has simply been removed.
The error mapper has been modified to catch the EOF exception as a SERVER_CONNECTION_ERROR, which is considered as an offline error and allows the use of login offline. This is a workaround for an unexpected behavior in the combination of the mockserver and ktor.
[ANDROSDK-1930]: https://dhis2.atlassian.net/browse/ANDROSDK-1930?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [ANDROSDK-1930] Remove header with Connection: close

core/api/core.api, core/src/androidTest/java/org/hisp/dhis/android/core/relationship/RelationshipCollectionRepositoryMockIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/relationship/RelationshipServiceIntegrationShould.kt, core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipCollectionRepository.kt, core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipService.kt, core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipServiceImpl.kt, core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipTypeWithEntitySide.kt, core/src/sharedTest/resources/relationship/relationship_types.json, core/src/test/java/org/hisp/dhis/android/core/relationship/RelationshipServiceShould.kt
Solves [ANDROSDK-1954](https://dhis2.atlassian.net/browse/ANDROSDK-1954)
[ANDROSDK-1954]: https://dhis2.atlassian.net/browse/ANDROSDK-1954?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: [ANDROSDK-1954] Implement methods to get relevant relationshipTypes

core/src/androidTest/java/org/hisp/dhis/android/core/analytics/aggregated/internal/evaluator/DataElementSQLEvaluatorIntegrationShould.kt, core/src/androidTest/java/org/hisp/dhis/android/core/analytics/aggregated/internal/evaluator/EventDataItemSQLEvaluatorIntegrationShould.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/aggregated/internal/evaluator/DataElementSQLEvaluator.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/aggregated/internal/evaluator/EventDataItemSQLEvaluator.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/aggregated/internal/evaluator/ValuePosition.kt, core/src/main/java/org/hisp/dhis/android/core/util/SqlUtils.kt, docs/content/developer/analytics.md
Add support for:
- FIRST_FIRST_ORG_UNIT
- LAST_LAST_ORG_UNIT
- MAX_SUM_ORG_UNIT
- MIN_SUM_ORG_UNIT
Solves [ANDROSDK-1669](https://dhis2.atlassian.net/browse/ANDROSDK-1669)
[ANDROSDK-1669]: https://dhis2.atlassian.net/browse/ANDROSDK-1669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [ANDROSDK-1669] Add support for missing aggregation types

docs/content/developer/public-api.md
This header is currently breaking developer portal from building, as the formatting is currently incorrect.
=> docs(fix): fix broken header

.github/workflows/dokka.yml, README.md
This PR replaces the Dokka publication workflow with a reusable workflow in the "dhis2/workflows" repository. This is just to verify that it works fine before applying this workflow to other repositories.
This PR targets "master" branch, but it won't generate a release.
=> chore: [DOKKA-GRADLE-WORKFLOW] Add reusable workflow

core/src/main/java/org/hisp/dhis/android/network/datavalue/DataValueDTO.kt
Fix a defect in ANDROSDK-1983. The serialization of dates must be done using the method `DateUtils.DATE_FORMAT.parse()` (the opposite to the method used in deserialization). The method `toString()` prints the date in a friendly format, such as:
=> chore: [ANDROSDK-1983-2] Fix date format in DataValueDTO

core/src/main/java/org/hisp/dhis/android/core/arch/api/authentication/internal/CookieAuthenticatorHelper.kt, core/src/test/java/org/hisp/dhis/android/core/arch/api/authentication/internal/CookieAuthenticatorShould.kt
Related issue [ANDROSDK-2053](https://dhis2.atlassian.net/browse/ANDROSDK-2053).
Fix contributed as part of [this PR](https://github.com/dhis2/dhis2-android-sdk/pull/2311) by EyeSeeTea.
There are two main changes:
1. The Cookie header only includes the cookie name and its value, the rest of attributes are ignored (domain, expiration, etc).
2. If multiple cookies are defined, they are all included separated by ";".
[ANDROSDK-2053]: https://dhis2.atlassian.net/browse/ANDROSDK-2053?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [ANDROSDK-2053] Support multiple cookies

core/src/main/java/org/hisp/dhis/android/core/parser/internal/service/dataitem/DimensionalItem.kt, core/src/test/java/org/hisp/dhis/android/core/parser/internal/expression/ExpressionServiceShould.kt, docs/content/developer/getting-started.md, gradle/libs.versions.toml
Increases the version number to 1.12.1, which will generate the first snapshot release for this version.
Solves [ANDROSDK-2068](https://dhis2.atlassian.net/browse/ANDROSDK-2068). There was an unnecessary `!!` operator which throw a null pointer when a dataElement value was used inside a function and its value was null (check the added unit test, which was throwing a NullPointerException before).
[ANDROSDK-2068]: https://dhis2.atlassian.net/browse/ANDROSDK-2068?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [ANDROSDK-2068] Accept null values in Validation Rules functions 

core/src/main/java/org/hisp/dhis/android/core/arch/db/stores/internal/ObjectStoreImpl.kt, core/src/main/java/org/hisp/dhis/android/core/arch/db/stores/internal/ObjectWithoutUidStoreImpl.kt
Fixes these two bugs:
- https://dhis2.atlassian.net/browse/ANDROSDK-2107 
- https://dhis2.atlassian.net/browse/ANDROSDK-2108
Two parallel calls of the `updateWhere` or `insert` methods could generate these sequence:
1. (call 1) bindStatament
2. (call 1) executeStatement
3. (call 2) bindStatement
4. (call 1) clearBindings
5. (call 2) executeStatement -> error
As both calls share the same statement, the step 4 will clear the bindings made in step 3 (call 2), so the step 5 will fail because the bindings for the statement were cleared [ANDROSDK-2107](https://dhis2.atlassian.net/browse/ANDROSDK-2107). The same could happen for inserts [ANDROSDK-2108](https://dhis2.atlassian.net/browse/ANDROSDK-2108).
[ANDROSDK-2107]: https://dhis2.atlassian.net/browse/ANDROSDK-2107?atlOrigin=eyJpIjoiNWRkNTljNzY …
=> fix: [ANDROSDK-2107] Mark update and insert methods as Synchronized

core/api/core.api, core/src/main/java/org/hisp/dhis/android/core/arch/db/access/internal/DatabaseAdapterFactory.java, core/src/main/java/org/hisp/dhis/android/core/configuration/internal/MultiUserDatabaseManagerForD2Manager.kt, core/src/main/java/org/hisp/dhis/android/core/user/internal/AccountManagerImpl.kt
This change should only affect the testing flow. It forces the recreation of the openHelper when the database is opened again. It should solved the scenario when the database file is directly copied in the filesystem and there was a previous openHelper pointing to the same dbname.
=> chore: [ANDROSDK-2117] Force adapter recreation on testing db

core/api/core.api, processor/src/main/java/org/hisp/dhis/android/processor/EntityProcessor.kt
Adds the property "all()" to the generated TableInfo classes.
=> chore: [ANDROSDK-2116] Add 'all()' property to generated TableInfo
