dhis2/dhis2-android-sdk

- build.gradle
- core/src/main/java/org/hisp/dhis/android/core/common/ValueType.java
- gradle.properties
Added AGE and URL to ValueType.
> Hotfix/ ValueType fix

- core/src/androidTest/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitCallIntegrationTests.java
- core/src/androidTest/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitProgramLinkStoreTests.java
- core/src/androidTest/java/org/hisp/dhis/android/core/user/UserCallIntegrationTest.java
- core/src/main/java/org/hisp/dhis/android/core/D2.java
- core/src/main/java/org/hisp/dhis/android/core/common/MetadataCall.java
- core/src/main/java/org/hisp/dhis/android/core/data/database/DbOpenHelper.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitCall.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitHandler.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitProgramLinkModel.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitProgramLinkStoreImpl.java
- core/src/test/java/org/hisp/dhis/android/core/common/MetadataCallTests.java
- core/src/test/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitCallUnitTests.java
- core/src/test/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitHandlerTests.java
Hotfix for creating links between orgunit and programs
> Hotfix for creating links between orgunit and programs

- .travis.yml
- build.gradle
- build.sh
- core-rules/src/main/java/org/hisp/dhis/rules/RuleVariableValue.java
- core-rules/src/main/java/org/hisp/dhis/rules/functions/RuleFunction.java
- core-rules/src/main/java/org/hisp/dhis/rules/functions/RuleFunctionCeil.java
- core-rules/src/main/java/org/hisp/dhis/rules/functions/RuleFunctionConcatenate.java
- core-rules/src/main/java/org/hisp/dhis/rules/functions/RuleFunctionCount.java
- core-rules/src/main/java/org/hisp/dhis/rules/functions/RuleFunctionCountIfValue.java
- core-rules/src/main/java/org/hisp/dhis/rules/functions/RuleFunctionCountIfZeroPos.java
- core-rules/src/main/java/org/hisp/dhis/rules/functions/RuleFunctionFloor.java
- core-rules/src/main/java/org/hisp/dhis/rules/functions/RuleFunctionHasValue.java
- core-rules/src/main/java/org/hisp/dhis/rules/functions/RuleFunctionLeft.java
- core-rules/src/main/java/org/hisp/dhis/rules/functions/RuleFunctionLength.java
- core-rules/src/main/java/org/hisp/dhis/rules/functions/RuleFunctionOizp.java
- core-rules/src/main/java/org/hisp/dhis/rules/functions/RuleFunctionRight.java
- core-rules/src/main/java/org/hisp/dhis/rules/functions/RuleFunctionSplit.java
- core-rules/src/main/java/org/hisp/dhis/rules/functions/RuleFunctionSubString.java
- core-rules/src/main/java/org/hisp/dhis/rules/functions/RuleFunctionValidatePattern.java
- core-rules/src/main/java/org/hisp/dhis/rules/functions/RuleFunctionZpvc.java
- core/build.gradle
- core/src/androidTest/java/org/hisp/dhis/android/core/event/EventEndPointCallRealIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/data/database/CustomSQLBriteOpenHelper.java
- gradle.properties
Commenting javadocs in the CustomSQLBriteOpenHelper class
> javadoc comments for OpenHelpder, checkingstyle rules, and passing pendding tests

- build.gradle
- core/src/main/java/org/hisp/dhis/android/core/data/database/DbOpenHelper.java
- gradle.properties
> Removing the constrain between dataelement and trackedentitydatavalue

- core/src/androidTest/assets/admin/organisation_units.json
- core/src/androidTest/assets/organisationUnits.json
- core/src/main/java/org/hisp/dhis/android/core/calls/MetadataCall.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetParentCall.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetParentLinkManager.java
- core/src/main/java/org/hisp/dhis/android/core/indicator/IndicatorHandler.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitCall.java
- core/src/test/java/org/hisp/dhis/android/core/common/MetadataCallShould.java
- core/src/test/java/org/hisp/dhis/android/core/dataset/DataSetParentLinkManagerShould.java
- core/src/test/java/org/hisp/dhis/android/core/indicator/IndicatorTypeHandlerShould.java
These PR links all DataSets to their OrganisationUnits and fix Indicator and IndicatorType handler tests.
> DataSet OrgUnit link

- core/src/main/java/org/hisp/dhis/android/core/calls/TrackerEntitiesDataCall.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TeisEndPointCall.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstance.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceService.java
It downloads several TEIs at the same time
> TrackedEntityInstances endpoint

- core/src/main/java/org/hisp/dhis/android/core/period/BiWeeklyPeriodGenerator.java
- core/src/main/java/org/hisp/dhis/android/core/period/NMonthlyPeriodGenerators.java
- core/src/main/java/org/hisp/dhis/android/core/period/ParentPeriodGeneratorImpl.java
- core/src/main/java/org/hisp/dhis/android/core/period/PeriodType.java
- core/src/main/java/org/hisp/dhis/android/core/period/WeeklyPeriodGenerators.java
- core/src/main/java/org/hisp/dhis/android/core/period/YearlyPeriodGenerators.java
- core/src/test/java/org/hisp/dhis/android/core/period/BiWeeklyPeriodGeneratorShould.java
- core/src/test/java/org/hisp/dhis/android/core/period/ParentPeriodGeneratorImplShould.java
Solves [ANDROSDK-149](https://jira.dhis2.org/browse/ANDROSDK-149) bug.
> Bi weekly period

- core/src/main/java/org/hisp/dhis/android/core/relationship/Relationship.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TeisEndPointCall.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceEndPointCall.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceHandler.java
- core/src/test/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceHandlerShould.java
- core/src/test/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceShould.java
Solves https://jira.dhis2.org/browse/ANDROSDK-144.
> Download relationships

- core/src/main/java/org/hisp/dhis/android/core/user/LogOutUserCallable.java
Adds missing stores to be wiped.
> wipe-db-missing-0.6.1: add missing stores to be wiped

- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancePostCallRealIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/D2.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceEndPointCall.java
Solves [ANDROSDK-155](https://jira.dhis2.org/browse/ANDROSDK-155).
> Tei upload bug

- core/src/main/java/org/hisp/dhis/android/core/enrollment/note/NoteModel.java
Adds `toContentValues` to `NoteModel`
> note-model-content-values: add content values to note model

- core-rules/src/main/java/org/hisp/dhis/rules/models/RuleActionHideProgramStage.java
Solves [ANDROSDK-154](https://jira.dhis2.org/browse/ANDROSDK-154).
> rule-action-hide-program-stage

- core/src/main/java/org/hisp/dhis/android/core/calls/TrackerEntitiesDataCall.java
- core/src/main/java/org/hisp/dhis/android/core/user/UserOrganisationUnitLinkModel.java
Solves [ANDROSDK-189](https://jira.dhis2.org/browse/ANDROSDK-189).
> Tei capture scope

- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueManagerShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueStoreIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/common/BaseModel.java
- core/src/main/java/org/hisp/dhis/android/core/common/ObjectStore.java
- core/src/main/java/org/hisp/dhis/android/core/common/ObjectStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/common/ObjectWithoutUidStore.java
- core/src/main/java/org/hisp/dhis/android/core/common/ObjectWithoutUidStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/common/SQLStatementBuilder.java
- core/src/main/java/org/hisp/dhis/android/core/common/StoreFactory.java
- core/src/main/java/org/hisp/dhis/android/core/common/WhereStatementBinder.java
- core/src/main/java/org/hisp/dhis/android/core/data/database/DatabaseAdapter.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueManager.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueModel.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueStore.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueStoreInterface.java
- core/src/sharedTest/java/org/hisp/dhis/android/core/data/utils/FillPropertiesTestUtils.java
- core/src/test/java/org/hisp/dhis/android/core/common/SQLStatementBuilderShould.java
Creates a store extending generic stores with custom queries for reserved values. Store is used in reserved values manager making database access much more efficient. Solves [ANDROSDK-179](https://jira.dhis2.org/browse/ANDROSDK-179).
> Reserved values store

- core/src/androidTest/java/org/hisp/dhis/android/core/TeisCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancePostCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/user/UserOrganisationUnitLinkModelsShould.java
- core/src/main/assets/migrations/3.yaml
- core/src/main/java/org/hisp/dhis/android/core/D2.java
- core/src/main/java/org/hisp/dhis/android/core/calls/TrackedEntityInstanceWithLimitEndpointCall.java
- core/src/main/java/org/hisp/dhis/android/core/calls/TrackerEntitiesDataCall.java
- core/src/main/java/org/hisp/dhis/android/core/common/IdentifiableObjectStore.java
- core/src/main/java/org/hisp/dhis/android/core/common/IdentifiableObjectStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/common/ObjectStore.java
- core/src/main/java/org/hisp/dhis/android/core/common/ObjectStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/common/SQLStatementBuilder.java
- core/src/main/java/org/hisp/dhis/android/core/data/database/DbOpenHelper.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TeiQuery.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TeisEndPointCall.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceHandler.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceService.java
- core/src/main/java/org/hisp/dhis/android/core/user/UserOrganisationUnitLinkModel.java
- core/src/main/java/org/hisp/dhis/android/core/user/UserOrganisationUnitLinkModelBuilder.java
- core/src/main/java/org/hisp/dhis/android/core/user/UserOrganisationUnitLinkStore.java
- core/src/main/java/org/hisp/dhis/android/core/user/UserOrganisationUnitLinkStoreInterface.java
- core/src/main/java/org/hisp/dhis/android/core/utils/Utils.java
Solves [ANDROSDK-167](https://jira.dhis2.org/browse/ANDROSDK-167).
> TEIs call with limit

- core/src/main/java/org/hisp/dhis/android/core/calls/TrackedEntityInstanceWithLimitEndpointCall.java
Mark TEI transaction as successful
> Transaction succes fix

- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueManagerRealIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/enrollment/note/NoteModel.java
Solves [ANDROSDK-157](https://jira.dhis2.org/browse/ANDROSDK-157).
> note-model-public-create: make create method public

- core/src/main/java/org/hisp/dhis/android/core/program/ProgramEndpointCall.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramService.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageEndpointCall.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageService.java
- core/src/test/java/org/hisp/dhis/android/core/program/ProgramEndpointCallShould.java
Solves [ANDROSDK-142](https://jira.dhis2.org/browse/ANDROSDK-142).
> Program no last update

- core/src/main/java/org/hisp/dhis/android/core/category/CategoryComboHandler.java
- core/src/main/java/org/hisp/dhis/android/core/category/CategoryHandler.java
Solves [ANDROSDK-140](https://jira.dhis2.org/browse/ANDROSDK-140).
> Category option update

- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueManagerRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueModelShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueStoreIntegrationShould.java
- core/src/main/assets/migrations/4.yaml
- core/src/main/java/org/hisp/dhis/android/core/data/database/DbOpenHelper.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueEndpointCall.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueModel.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueModelBuilder.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueStore.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueValidatorHelper.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeStore.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeStoreImpl.java
- core/src/test/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueModelBuilderShould.java
- core/src/test/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueValidatorHelperShould.java
Solves [ANDROSDK-181](https://jira.dhis2.org/browse/ANDROSDK-181).
On top of #234, #235 and #236.
> Reserved value temporal validity

- core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipTypeModel.java
Solves [ANDROSDK-216](https://jira.dhis2.org/browse/ANDROSDK-216).
> relationship-type-a-to-b: fix duplicate b-to-a

- core/src/androidTest/java/org/hisp/dhis/android/core/event/EventPostCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancePostCallRealIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/D2.java
- core/src/main/java/org/hisp/dhis/android/core/calls/TrackedEntityInstancePostCall.java
- core/src/main/java/org/hisp/dhis/android/core/calls/TrackerDataCall.java
- core/src/main/java/org/hisp/dhis/android/core/category/CategoryEndpointCall.java
- core/src/main/java/org/hisp/dhis/android/core/common/AbstractEndpointListCall.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventEndpointCall.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventPersistenceCall.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventPostCall.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventWithLimitCall.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitCall.java
- core/src/main/java/org/hisp/dhis/android/core/systeminfo/SystemInfoCall.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceDownloadByUidEndPointCall.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceListDownloadAndPersistCall.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancePersistenceCall.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceWithLimitCall.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancesEndpointCall.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityTypeCall.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryCall.java
- core/src/main/java/org/hisp/dhis/android/core/user/UserCall.java
Solves [ANDROSDK-186](https://jira.dhis2.org/browse/ANDROSDK-186).
> D2 calls errors 2

- core/src/androidTest/java/org/hisp/dhis/android/core/common/ForeignKeyCleanerShould.java
- core/src/main/java/org/hisp/dhis/android/core/calls/MetadataCall.java
- core/src/main/java/org/hisp/dhis/android/core/common/ForeignKeyCleaner.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventPersistenceCall.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancePersistenceCall.java
- core/src/test/java/org/hisp/dhis/android/core/common/MetadataCallShould.java
Solves [ANDROSDK-205](https://jira.dhis2.org/browse/ANDROSDK-205).
> Foreign key cleaner

- core/src/main/java/org/hisp/dhis/android/core/common/LinkModelHandler.java
- core/src/main/java/org/hisp/dhis/android/core/common/LinkModelHandlerImpl.java
- core/src/main/java/org/hisp/dhis/android/core/common/LinkModelStore.java
- core/src/main/java/org/hisp/dhis/android/core/common/LinkModelStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/common/ObjectWithoutUidStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/common/StoreFactory.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramSectionHandler.java
- core/src/test/java/org/hisp/dhis/android/core/program/ProgramSectionHandlerShould.java
Solves [ANDROSDK-207](https://jira.dhis2.org/browse/ANDROSDK-207).
> Link model handler (ProgramSection - Attributes clear)

- core/src/main/java/org/hisp/dhis/android/core/utils/services/ProgramIndicatorEngine.java
- core/src/test/java/org/hisp/dhis/android/core/utils/services/ProgramIndicatorEngineShould.java
- core/src/test/java/org/hisp/dhis/android/core/utils/support/ExpressionUtilsShould.java
Solves [ANDROSDK-218](https://jira.dhis2.org/browse/ANDROSDK-218)
> Indicator engine zero value

- build.gradle
- core/build.gradle
- core/src/androidTest/java/org/hisp/dhis/android/core/common/D2Factory.java
- core/src/main/java/org/hisp/dhis/android/core/D2.java
- core/src/main/java/org/hisp/dhis/android/core/common/SSLContextInitializer.java
- core/src/test/java/org/hisp/dhis/android/core/D2Tests.java
Solves [ANDROSDK-217](https://jira.dhis2.org/browse/ANDROSDK-217).
> Ssl login bug

- core/src/main/java/org/hisp/dhis/android/core/legendset/ProgramIndicatorLegendSetLinkStore.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramIndicatorHandler.java
- core/src/test/java/org/hisp/dhis/android/core/program/ProgramIndicatorHandlerShould.java
Solves [ANDROSDK-211](https://jira.dhis2.org/browse/ANDROSDK-211).
> Indicator legend set link handler

- core/src/main/java/org/hisp/dhis/android/core/common/D2CallExecutor.java
- core/src/main/java/org/hisp/dhis/android/core/option/UidCallSplitter.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramParentCall.java
- core/src/main/java/org/hisp/dhis/android/core/utils/Utils.java
- core/src/sharedTest/java/org/hisp/dhis/android/core/data/server/Dhis2MockServer.java
- core/src/test/java/org/hisp/dhis/android/core/program/ProgramParentCallShould.java
Solves [ANDROSDK-177](https://jira.dhis2.org/browse/ANDROSDK-177) in a generic way and applies it to OptionSets.
> Uids call spliter

- core-rules/src/main/java/org/hisp/dhis/rules/RuleVariableValue.java
Makes "create" method in RuleVariableValue public
> rule-variable-value: make create method public

- core/src/main/java/org/hisp/dhis/android/core/common/ObjectWithUid.java
- core/src/main/java/org/hisp/dhis/android/core/common/ObjectWithUidInterface.java
- core/src/main/java/org/hisp/dhis/android/core/common/OrphanCleaner.java
- core/src/main/java/org/hisp/dhis/android/core/common/OrphanCleanerImpl.java
- core/src/main/java/org/hisp/dhis/android/core/common/UidsHelper.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramOrphanCleaner.java
Solves [ANDROSDK-239](https://jira.dhis2.org/browse/ANDROSDK-239)
> program-stage-orphan-cleaner

- core/src/main/java/org/hisp/dhis/android/core/common/CollectionCleaner.java
- core/src/main/java/org/hisp/dhis/android/core/common/CollectionCleanerImpl.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramHandler.java
- core/src/test/java/org/hisp/dhis/android/core/program/ProgramHandlerShould.java
Solves [ANDROSDK-220](https://jira.dhis2.org/browse/ANDROSDK-220)
> Collection cleaner

- core/src/main/java/org/hisp/dhis/android/core/data/database/DbOpenHelper.java
Solves [ANDROSDK-221](https://jira.dhis2.org/browse/ANDROSDK-221).
> Do not block db

- core/src/main/java/org/hisp/dhis/android/core/common/GenericCallData.java
- core/src/main/java/org/hisp/dhis/android/core/common/TransactionalListPersistor.java
- core/src/main/java/org/hisp/dhis/android/core/dataelement/DataElementEndpointCall.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetEndpointCall.java
- core/src/main/java/org/hisp/dhis/android/core/datavalue/DataValueEndpointCall.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventPersistenceCall.java
- core/src/main/java/org/hisp/dhis/android/core/indicator/IndicatorEndpointCall.java
- core/src/main/java/org/hisp/dhis/android/core/indicator/IndicatorTypeEndpointCall.java
- core/src/main/java/org/hisp/dhis/android/core/option/OptionSetCall.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/SearchOrganisationUnitCall.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramEndpointCall.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageEndpointCall.java
- core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipTypeEndpointCall.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueEndpointCall.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancePersistenceCall.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityTypeCall.java
Solves [ANDROSDK-240](https://jira.dhis2.org/browse/ANDROSDK-240).
> Search org unit call split

- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageHandler.java
- core/src/test/java/org/hisp/dhis/android/core/program/ProgramStageHandlerShould.java
Solves [ANDROSDK-224](https://jira.dhis2.org/browse/ANDROSDK-224) and [ANDROSDK-225](https://jira.dhis2.org/browse/ANDROSDK-225).
> program-stage-section-and-data-element-orphan-cleaner: clean orphans

- core/src/main/java/org/hisp/dhis/android/core/program/ProgramRuleHandler.java
- core/src/test/java/org/hisp/dhis/android/core/program/ProgramRuleHandlerShould.java
Solves [ANDROSDK-229](https://jira.dhis2.org/browse/ANDROSDK-229).
> Program rule action orphan cleaner

- core/src/main/java/org/hisp/dhis/android/core/category/CategoryComboHandler.java
- core/src/test/java/org/hisp/dhis/android/core/category/CategoryComboHandlerShould.java
Solves [ANDROSDK-231](https://jira.dhis2.org/browse/ANDROSDK-231).
> Category orphan cleaner

- core/src/main/java/org/hisp/dhis/android/core/legendset/LegendSetHandler.java
- core/src/test/java/org/hisp/dhis/android/core/legendset/LegendSetHandlerShould.java
Solves [ANDROSDK-232](https://jira.dhis2.org/browse/ANDROSDK-232).
> Legend orphan cleaner

- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageEndpointCall.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageHandler.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageService.java
- core/src/test/java/org/hisp/dhis/android/core/program/ProgramStageHandlerShould.java
Solves [ANDROSDK-245](https://jira.dhis2.org/browse/ANDROSDK-245).
> Program stage not readable

- core/src/androidTest/assets/data_elements.json
- core/src/androidTest/assets/program_stages.json
- core/src/androidTest/java/org/hisp/dhis/android/core/category/CategoryEndpointCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/common/IdentifiableObjectStoreIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/common/IdentifiableObjectStore.java
- core/src/main/java/org/hisp/dhis/android/core/common/IdentifiableObjectStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/common/ObjectStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/dataelement/DataElement.java
- core/src/main/java/org/hisp/dhis/android/core/dataelement/DataElementEndpointCall.java
- core/src/main/java/org/hisp/dhis/android/core/dataelement/DataElementService.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageDataElementHandler.java
- core/src/test/java/org/hisp/dhis/android/core/dataelement/DataElementShould.java
- core/src/test/java/org/hisp/dhis/android/core/program/ProgramStageDataElementHandlerShould.java
- core/src/test/resources/data_elements.json
- core/src/test/resources/dataelement/data_element.json
Solves [ANDROSDK-251](https://jira.dhis2.org/browse/ANDROSDK-251).
> Data elements share update

- core/src/androidTest/assets/programs_complete.json
- core/src/main/java/org/hisp/dhis/android/core/common/IdentifiableHandlerImpl.java
- core/src/main/java/org/hisp/dhis/android/core/common/ValueTypeRendering.java
- core/src/main/java/org/hisp/dhis/android/core/data/api/FieldsConverter.java
- core/src/main/java/org/hisp/dhis/android/core/dataelement/DataElement.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageSection.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageSectionRendering.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramTrackedEntityAttributeHandler.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttribute.java
- core/src/test/java/org/hisp/dhis/android/core/common/IdentifiableHandlerShould.java
- core/src/test/java/org/hisp/dhis/android/core/data/api/FieldsConverterShould.java
- core/src/test/java/org/hisp/dhis/android/core/program/ProgramIndicatorHandlerShould.java
- core/src/test/java/org/hisp/dhis/android/core/program/ProgramTrackedEntityAttributeHandlerShould.java
- core/src/test/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeShould.java
Solves [ANDROSDK-252](https://jira.dhis2.org/browse/ANDROSDK-252).
> Tracked entity attribute share update

- core/src/main/java/org/hisp/dhis/android/core/common/State.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceHandler.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceStore.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceStoreImpl.java
- core/src/test/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceHandlerShould.java
Solves [ANDROSDK-156](https://jira.dhis2.org/browse/ANDROSDK-156).
> Relationship state

- core-rules-android/src/androidTest/java/org/hisp/dhis/rules/android/DuktapeEvaluatorShould.java
- core-rules-android/src/main/java/org/hisp/dhis/rules/android/DuktapeEvaluator.java
Solves [ANDROSDK-265](https://jira.dhis2.org/browse/ANDROSDK-265)
> duktape-evaluate-string: catch Duktape exception and return expression

- core/src/androidTest/java/org/hisp/dhis/android/core/event/EventStoreShould.java
- core/src/main/java/org/hisp/dhis/android/core/common/Coordinates.java
- core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentHandler.java
- core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventHandler.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventStoreImpl.java
Solves [ANDROSDK-272](https://jira.dhis2.org/browse/ANDROSDK-272).
> Coordinates fix

- core/src/androidTest/java/org/hisp/dhis/android/core/event/EventPostCallRealIntegrationShould.java
Add a new event post test and some fixes.
> event-post-two-events-test: add second test, fix old one

- core/src/androidTest/java/org/hisp/dhis/android/core/common/D2Factory.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TeiQuery.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceWithLimitCall.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancesEndpointCall.java
- core/src/main/java/org/hisp/dhis/android/core/utils/services/ApiPagingEngine.java
- core/src/main/java/org/hisp/dhis/android/core/utils/services/Paging.java
- core/src/test/java/org/hisp/dhis/android/core/utils/services/ApiPagingEngineShould.java
Solves [ANDROSDK-270](https://jira.dhis2.org/browse/ANDROSDK-270).
> Tei last paging download

- core/src/main/java/org/hisp/dhis/android/core/dataelement/DataElement.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageSection.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageSectionRendering.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttribute.java
Fix to properly sync renderType on DataElement, ProgramStageSection and TrackedEntityAttribute.
> Render type fix

- core/src/main/java/org/hisp/dhis/android/core/dataset/SectionDataElementLinkStore.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/SectionHandler.java
- core/src/test/java/org/hisp/dhis/android/core/dataset/SectionHandlerShould.java
[ANDROSDK-249](https://jira.dhis2.org/browse/ANDROSDK-249)
> androsdk-249: Clean link table before update: Section - DataElement

- core/src/androidTest/java/org/hisp/dhis/android/core/MetadataCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/TeisCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/TrackedEntityInstanceQueryAndDownloadRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/TrackedEntityInstanceQueryCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/UserAuthenticateCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/datavalue/AggregatedDataCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/event/EventWithLimitCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancePostCallRealIntegrationShould.java
Deletes not necessary D2 logout calls on integration test initializations.
> Real integration test logout

- core/src/androidTest/java/org/hisp/dhis/android/core/common/EventCallFactory.java
- core/src/androidTest/java/org/hisp/dhis/android/core/event/EventEndpointCallMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventEndpointCall.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventQuery.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventWithLimitCall.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceWithLimitCall.java
- core/src/test/java/org/hisp/dhis/android/core/event/EventEndpointCallShould.java
- core/src/test/java/org/hisp/dhis/android/core/event/EventQueryShould.java
Solves [ANDROSDK-277](https://jira.dhis2.org/browse/ANDROSDK-277).
> Events api paging engine

- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetEndpointCall.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetService.java
[ANDROSDK-281](https://jira.dhis2.org/browse/ANDROSDK-281)
> Dataset: nested fields are not updated when dataset is not updated

- core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryCall.java
Solves [ANDROSDK-280](https://jira.dhis2.org/browse/ANDROSDK-280).
> Tei query call null pointer exception

- core/src/androidTest/java/org/hisp/dhis/android/core/program/ProgramStageModelShould.java
- core/src/main/assets/migrations/12.yaml
- core/src/main/java/org/hisp/dhis/android/core/data/database/DbOpenHelper.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStage.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageModel.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageModelBuilder.java
- core/src/test/java/org/hisp/dhis/android/core/program/ProgramStageShould.java
- core/src/test/resources/program/program_stage.json
Solves [ANDROSDK-293](https://jira.dhis2.org/browse/ANDROSDK-293).
> Program stage description

- core/src/androidTest/assets/tracked_entity_types.json
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityType.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityTypeHandler.java
- core/src/sharedTest/java/org/hisp/dhis/android/core/data/utils/FillPropertiesTestUtils.java
- core/src/test/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityTypeModelBuilderShould.java
Solves [ANDROSDK-292](https://jira.dhis2.org/browse/ANDROSDK-292).
> Tracked entity type style

- core/src/main/java/org/hisp/dhis/android/core/calls/WipeDBCallable.java
- core/src/test/java/org/hisp/dhis/android/core/calls/WipeDBCallableShould.java
Solves [ANDROSDK-300](https://jira.dhis2.org/browse/ANDROSDK-300).
> Transactional wipe db

- core/src/main/java/org/hisp/dhis/android/core/common/DataOrphanCleanerImpl.java
- core/src/main/java/org/hisp/dhis/android/core/enrollment/Enrollment.java
- core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentHandler.java
- core/src/main/java/org/hisp/dhis/android/core/event/Event.java
- core/src/test/java/org/hisp/dhis/android/core/enrollment/EnrollmentHandlerShould.java
Solves [ANDROSDK-294](https://jira.dhis2.org/browse/ANDROSDK-294).
> Sync down deleted events

- core/src/androidTest/java/org/hisp/dhis/android/core/data/server/RealServerMother.java
- core/src/main/java/org/hisp/dhis/android/core/systeminfo/DHISVersion.java
> enable-30: enable version 2.30

- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancePostCallRealIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/calls/TrackedEntityInstancePostCall.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceService.java
Solves [ANDROSDK-299](https://jira.dhis2.org/browse/ANDROSDK-299).
> Sync up deleted events

- core-rules/src/main/java/org/hisp/dhis/rules/RuleEngineExecution.java
Solves [ANDROSDK-297](https://jira.dhis2.org/browse/ANDROSDK-297).
> null-rule-variable-value-bug: fix bug

- core-rules/src/main/java/org/hisp/dhis/rules/RuleEngineExecution.java
- core-rules/src/test/java/org/hisp/dhis/rules/RuleEngineExecutionShould.java
Solves [ANDROSDK-295](https://jira.dhis2.org/browse/ANDROSDK-295)
> androsdk-295: break loop if same processed expression

- core/src/androidTest/java/org/hisp/dhis/android/core/program/ProgramStageDataElementStoreShould.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageDataElementHandler.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageDataElementStore.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageDataElementStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageSectionHandler.java
- core/src/test/java/org/hisp/dhis/android/core/program/ProgramStageSectionHandlerShould.java
[ANDROSDK-296](https://jira.dhis2.org/browse/ANDROSDK-296)
> DataElements not saved in Database for program stage section

- core/src/androidTest/java/org/hisp/dhis/android/core/calls/WipeDBCallMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/calls/WipeDBCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/category/CategoryComboEndpointCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/category/CategoryEndpointCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/category/CategoryEndpointCallShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/common/EventCallFactory.java
- core/src/androidTest/java/org/hisp/dhis/android/core/data/database/AbsStoreTestCase.java
- core/src/androidTest/java/org/hisp/dhis/android/core/dataelement/DataElementEndpointCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/dataset/DataSetEndpointCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/datavalue/DataValueEndpointCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/event/EventEndpointCallMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/event/EventEndpointCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/event/EventPostCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/option/OptionSetCallShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitCallMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/program/ProgramEndpointCallMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueEndpointCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityTypeCallMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/user/LogoutCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/user/UserCallMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/calls/AggregatedDataCall.java
- core/src/main/java/org/hisp/dhis/android/core/calls/MetadataCall.java
- core/src/main/java/org/hisp/dhis/android/core/common/GenericCallData.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueManager.java
- core/src/main/java/org/hisp/dhis/android/core/user/UserAuthenticateCall.java
- core/src/test/java/org/hisp/dhis/android/core/common/MetadataCallShould.java
- core/src/test/java/org/hisp/dhis/android/core/user/UserAuthenticateCallUnitShould.java
Refactorizations to ease [ANDROSDK-301](https://jira.dhis2.org/browse/ANDROSDK-301).
- Adds the version manager to the generic call data class.
> Generic call data version manager

- core/src/androidTest/java/org/hisp/dhis/android/core/program/ProgramStageModelShould.java
- core/src/main/assets/migrations/15.yaml
- core/src/main/java/org/hisp/dhis/android/core/arch/handlers/SyncHandlerBaseImpl.java
- core/src/main/java/org/hisp/dhis/android/core/common/GenericHandlerBaseImpl.java
- core/src/main/java/org/hisp/dhis/android/core/data/database/DbOpenHelper.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStage.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageEndpointCall.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageFields.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageHandler.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageModel.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageModelBuilder.java
- core/src/test/java/org/hisp/dhis/android/core/program/ProgramStageHandlerShould.java
- core/src/test/java/org/hisp/dhis/android/core/program/ProgramStageShould.java
- core/src/test/resources/program/program_stage.json
Solves [ANDROSDK-301](https://jira.dhis2.org/browse/ANDROSDK-301).
On top of #338.
> Program stage feature type

- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitCall.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitService.java
- core/src/test/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitCallUnitShould.java
Solves [ANDROSDK-289](https://jira.dhis2.org/browse/ANDROSDK-289).
> Organisation unit program link update

- core/src/androidTest/java/org/hisp/dhis/android/core/TrackedEntityInstanceSyncDownCallMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceSyncDownCallRealIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/D2.java
- core/src/main/java/org/hisp/dhis/android/core/calls/TrackedEntityInstanceSyncDownCall.java
Solves [ANDROSDK-312](https://jira.dhis2.org/browse/ANDROSDK-312).
> Teis sync down call

- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitHandler.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitProgramLinkModel.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitProgramLinkStore.java
- core/src/test/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitHandlerShould.java
Solves [ANDROSDK-314](https://jira.dhis2.org/browse/ANDROSDK-314).
On top of #345.
> Organisation unit program link handler

- core/src/androidTest/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitCallMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/calls/MetadataCall.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetHandler.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetOrganisationUnitLinkModelBuilder.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetOrganisationUnitLinkStore.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetParentCall.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetParentLinkManager.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitCall.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitHandler.java
- core/src/sharedTest/java/org/hisp/dhis/android/core/data/server/Dhis2MockServer.java
- core/src/test/java/org/hisp/dhis/android/core/common/MetadataCallShould.java
- core/src/test/java/org/hisp/dhis/android/core/dataset/DataSetHandlerShould.java
- core/src/test/java/org/hisp/dhis/android/core/dataset/DataSetParentLinkManagerShould.java
- core/src/test/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitHandlerShould.java
Solves [ANDROSDK-210](https://jira.dhis2.org/browse/ANDROSDK-210) and [ANDROSDK-303](https://jira.dhis2.org/browse/ANDROSDK-303).
> Organisation unit data set link handler

- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitHandler.java
- core/src/test/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitHandlerShould.java
Solves [ANDROSDK-321](https://jira.dhis2.org/browse/ANDROSDK-321).
On top of #348.
> Program data set not org unit linked

- core-rules/src/main/java/org/hisp/dhis/rules/RuleExpression.java
- core-rules/src/test/java/org/hisp/dhis/rules/RuleExpressionShould.java
Solves [ANDROSDK-318](https://jira.dhis2.org/browse/ANDROSDK-318)
> spaces-variable-name: support spaces in variable name

- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancePostCallRealIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/calls/TrackedEntityInstancePostCall.java
- core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityDataValueStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceService.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceStoreImpl.java
Solves [ANDROSDK-313](https://jira.dhis2.org/browse/ANDROSDK-313).
> Tei enrollment 2 30 upload

- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceService.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancesEndpointCall.java
Solves [ANDROSDK-331](https://jira.dhis2.org/browse/ANDROSDK-331)
> androsdk-331: add include all attributes

- core/src/main/java/org/hisp/dhis/android/core/common/APICallExecutor.java
Log and add to exception message returned by server
> api-call-error-message: log and add to exception message returned by server

- core/src/main/java/org/hisp/dhis/android/core/event/EventEndpointCall.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventService.java
We remove the following parameter: filter=event:in:[]
> Removing filter in /events endpoit

- core/src/main/java/org/hisp/dhis/android/core/relationship/BaseRelationship.java
- core/src/main/java/org/hisp/dhis/android/core/relationship/Relationship.java
- core/src/main/java/org/hisp/dhis/android/core/relationship/Relationship229Compatible.java
- core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipItem.java
- core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipItemTrackedEntityInstance.java
- core/src/sharedTest/java/org/hisp/dhis/android/core/data/relationship/RelationshipSamples.java
- core/src/test/java/org/hisp/dhis/android/core/common/BaseObjectShould.java
- core/src/test/java/org/hisp/dhis/android/core/relationship/Relationship29Should.java
- core/src/test/java/org/hisp/dhis/android/core/relationship/Relationship30Should.java
Include missing JsonProperty to upload relationships
> relationship-upload-bug: include missing JsonProperty. Tests

- core/src/main/java/org/hisp/dhis/android/core/calls/WipeDBCallable.java
Add missing CategoryOptionComboStore table in WipeDB
> wipe-db-fix: add missing table in wipedb

- core/src/main/java/org/hisp/dhis/android/core/enrollment/Enrollment.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstance.java
Add ignore null values in Enrollment and TrackedEntityInstance
> jackson-ignore-null: add ignore null annotation in enrollment and TEI

- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitHandler.java
- core/src/test/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitHandlerShould.java
Comment method that removes unassigned programs and orgunits
> multiple-root-bug: comment bug lines

- core/src/androidTest/java/org/hisp/dhis/android/core/systeminfo/SystemInfoCallMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/systeminfo/SystemInfoDatabaseMappingShould.java
- core/src/main/assets/migrations/17.yaml
- core/src/main/java/org/hisp/dhis/android/core/data/database/DbOpenHelper.java
- core/src/main/java/org/hisp/dhis/android/core/systeminfo/SystemInfo.java
- core/src/main/java/org/hisp/dhis/android/core/systeminfo/SystemInfoFields.java
- core/src/main/java/org/hisp/dhis/android/core/systeminfo/SystemInfoStore.java
- core/src/main/java/org/hisp/dhis/android/core/systeminfo/SystemInfoTableInfo.java
- core/src/sharedTest/java/org/hisp/dhis/android/core/data/systeminfo/SystemInfoSamples.java
[ANDROSDK-328](https://jira.dhis2.org/browse/ANDROSDK-328)
> ANDROSDK-328: Download Server Name

- core/src/androidTest/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitCallMockIntegrationShould.java
- core/src/main/assets/migrations/17.yaml
- core/src/main/assets/migrations/18.yaml
- core/src/main/java/org/hisp/dhis/android/core/calls/WipeDBCallable.java
- core/src/main/java/org/hisp/dhis/android/core/data/database/DbOpenHelper.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnit.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitGroup.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitGroupHandler.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitGroupModel.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitGroupModelBuilder.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitGroupStore.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitHandler.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitOrganisationUnitGroupLinkModel.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitOrganisationUnitGroupLinkModelBuilder.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitOrganisationUnitGroupLinkStore.java
- core/src/test/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitGroupHandlerShould.java
- core/src/test/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitGroupModelBuilderShould.java
- core/src/test/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitGroupShould.java
- core/src/test/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitHandlerShould.java
- core/src/test/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitModelBuilderShould.java
- core/src/test/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitOrganisationUnitGroupLinkModelBuilderShould.java
- core/src/test/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitTreeShould.java
- core/src/test/resources/organisationunit/organisation_unit_group.json
[ANDROSDK-20](https://jira.dhis2.org/browse/ANDROSDK-20)
> ANDROSDK-20: Include Object Organisation Unit Groups

- core/src/main/java/org/hisp/dhis/android/core/D2.java
- core/src/main/java/org/hisp/dhis/android/core/enrollment/Enrollment.java
- core/src/main/java/org/hisp/dhis/android/core/event/Event.java
- core/src/main/java/org/hisp/dhis/android/core/relationship/Relationship.java
- core/src/main/java/org/hisp/dhis/android/core/relationship/Relationship229Compatible.java
- core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipItem.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstance.java
Solves [ANDROSDK-325](https://jira.dhis2.org/browse/ANDROSDK-325).
> Global serialization inclusion

- core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipDHISVersionManager.java
Solves [ANDROSDK-339](https://jira.dhis2.org/browse/ANDROSDK-339).
> 2-30-relationship-upload: not upload relationship if tei has type to

- core/src/main/java/org/hisp/dhis/android/core/D2.java
- core/src/main/java/org/hisp/dhis/android/core/calls/AggregatedDataCall.java
- core/src/main/java/org/hisp/dhis/android/core/calls/TrackedEntityInstancePostCall.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetCompleteRegistrationPostCall.java
- core/src/main/java/org/hisp/dhis/android/core/datavalue/DataValuePostCall.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventPostCall.java
- core/src/main/java/org/hisp/dhis/android/core/imports/ImportCount.java
- core/src/main/java/org/hisp/dhis/android/core/imports/ImportSummaries.java
- core/src/main/java/org/hisp/dhis/android/core/imports/ImportSummary.java
- core/src/main/java/org/hisp/dhis/android/core/imports/WebResponse.java
Solves [ANDROSDK-342](https://jira.dhis2.org/browse/ANDROSDK-342)
> Return non null

- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancePostCallRealIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/ReadOnlyCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/ReadOnlyCollectionRepositoryImpl.java
- core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipModule.java
- core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipTypeRepository.java
Renames:
ReadOnlyListRepository -> ReadOnlyCollectionRepository
getAll() -> getSet()
To match SDK Architecture 1.0 document.
> Rename collection repository

- core/src/main/java/org/hisp/dhis/android/core/datavalue/DataValue.java
- core/src/main/java/org/hisp/dhis/android/core/datavalue/DataValueModel.java
- core/src/test/resources/datavalue/data_value.json
[ANDROSDK-94](https://jira.dhis2.org/browse/ANDROSDK-94)
> ANDROSDK-94: Aggregated - Add support to Data value pop-up: mark value for follow-up

- core/src/main/java/org/hisp/dhis/android/core/common/ObjectStore.java
- core/src/main/java/org/hisp/dhis/android/core/common/ObjectStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetCompleteRegistrationStore.java
Solves [ANDROSDK-341](https://jira.dhis2.org/browse/ANDROSDK-341)
> Select where

- core/src/main/java/org/hisp/dhis/android/core/calls/AggregatedDataCall.java
- core/src/main/java/org/hisp/dhis/android/core/datavalue/DataValueEndpointCall.java
- core/src/main/java/org/hisp/dhis/android/core/datavalue/DataValueService.java
[ANDROSDK-332](https://jira.dhis2.org/browse/ANDROSDK-332)
> ANDROSDK-332: Use only root organization units when requesting Data Values

- build.gradle
- core/src/main/java/org/hisp/dhis/android/core/data/database/DbOpenHelper.java
Solves [ANDROSDK-350](https://jira.dhis2.org/browse/ANDROSDK-350)
> enable-fk: use built-in method. Ugrade to minsdkversion = 19

- core-rules/src/main/java/org/hisp/dhis/rules/models/RuleEvent.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventStatus.java
Solves [ANDROSDK-362](https://jira.dhis2.org/browse/ANDROSDK-362)
> missing-event-status: add missing event states

- core/src/androidTest/java/org/hisp/dhis/android/core/program/ProgramIndicatorModelShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/utils/services/ProgramIndicatorEngineIntegrationShould.java
- core/src/main/assets/migrations/21.yaml
- core/src/main/java/org/hisp/dhis/android/core/common/AggregationType.java
- core/src/main/java/org/hisp/dhis/android/core/common/AggregationTypeColumnAdapter.java
- core/src/main/java/org/hisp/dhis/android/core/data/database/DbOpenHelper.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventStore.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramIndicator.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramIndicatorModel.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramIndicatorStore.java
- core/src/main/java/org/hisp/dhis/android/core/utils/services/ProgramIndicatorEngine.java
- core/src/test/java/org/hisp/dhis/android/core/program/ProgramIndicatorModelBuilderShould.java
- core/src/test/java/org/hisp/dhis/android/core/program/ProgramIndicatorShould.java
- core/src/test/java/org/hisp/dhis/android/core/utils/services/ProgramIndicatorEngineShould.java
Solves ([ANDROSDK-359](https://jira.dhis2.org/browse/ANDROSDK-359))
> Last value indicator

- core/src/main/java/org/hisp/dhis/android/core/common/OrderedLinkModelHandlerImpl.java
Solves [ANDROSDK-369](https://jira.dhis2.org/browse/ANDROSDK-369).
> sort-order-start-1: start sort order in 1 like server

- build.gradle
- core/src/main/java/org/hisp/dhis/android/core/data/database/DbOpenHelper.java
- gradle.properties
Disable FK constraint temporally to avoid issues in 4.4
> Hotbugfixing

- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceHandler.java
- core/src/test/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceHandlerShould.java
Solves [ANDROSDK-363](https://jira.dhis2.org/browse/ANDROSDK-363).
> Deleted enrollments sync

- core/src/main/assets/migrations/23.yaml
- core/src/main/java/org/hisp/dhis/android/core/category/CategoryCategoryOptionLinkModel.java
- core/src/main/java/org/hisp/dhis/android/core/category/CategoryCategoryOptionLinkModelBuilder.java
- core/src/main/java/org/hisp/dhis/android/core/category/CategoryCategoryOptionLinkStore.java
- core/src/main/java/org/hisp/dhis/android/core/category/CategoryHandler.java
- core/src/main/java/org/hisp/dhis/android/core/data/database/DbOpenHelper.java
- core/src/test/java/org/hisp/dhis/android/core/category/CategoryHandlerShould.java
Solves [ANDROSDK-354](https://jira.dhis2.org/browse/ANDROSDK-354)
> Category options order

- build.gradle
- core/src/main/java/org/hisp/dhis/android/core/data/database/DbOpenHelper.java
Solves [ANDROSDK-370](https://jira.dhis2.org/browse/ANDROSDK-370).
> 4.4-foreign-keys: set FKs only on android 4.4

- core/src/androidTest/java/org/hisp/dhis/android/core/category/CategoryCategoryComboLinkStoreShould.java
- core/src/main/assets/migrations/24.yaml
- core/src/main/java/org/hisp/dhis/android/core/category/CategoryCategoryComboLinkModel.java
- core/src/main/java/org/hisp/dhis/android/core/category/CategoryCategoryComboLinkModelBuilder.java
- core/src/main/java/org/hisp/dhis/android/core/category/CategoryCategoryComboLinkStore.java
- core/src/main/java/org/hisp/dhis/android/core/category/CategoryComboHandler.java
- core/src/main/java/org/hisp/dhis/android/core/data/database/DbOpenHelper.java
- core/src/test/java/org/hisp/dhis/android/core/category/CategoryComboHandlerShould.java
Solves [ANDROSDK-355](https://jira.dhis2.org/browse/ANDROSDK-355).
> category-category-combos-order: add sort order

- core/src/androidTest/java/org/hisp/dhis/android/core/dataset/SectionDataElementLinkModelShould.java
- core/src/main/assets/migrations/25.yaml
- core/src/main/java/org/hisp/dhis/android/core/data/database/DbOpenHelper.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/SectionDataElementLinkModel.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/SectionDataElementLinkModelBuilder.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/SectionDataElementLinkStore.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/SectionHandler.java
- core/src/test/java/org/hisp/dhis/android/core/dataset/SectionDataElementLinkModelBuilderShould.java
- core/src/test/java/org/hisp/dhis/android/core/dataset/SectionHandlerShould.java
Solves [ANDROSDK-364](https://jira.dhis2.org/browse/ANDROSDK-364).
> Data elements data set sections order

- core/src/main/java/org/hisp/dhis/android/core/relationship/Relationship229Compatible.java
- core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipType.java
- core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipTypeModel.java
[ANDROSDK-311](https://jira.dhis2.org/browse/ANDROSDK-311)
> deprecated-29: deprecated items in relationships

- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/api/TrackedEntityInstanceAPI29Should.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/api/TrackedEntityInstanceAPI30Should.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/api/TrackedEntityInstanceAPIShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/api/TrackedEntityInstanceUtils.java
- core/src/main/java/org/hisp/dhis/android/core/D2.java
- core/src/main/java/org/hisp/dhis/android/core/ObjectMapperFactory.java
- core/src/main/java/org/hisp/dhis/android/core/calls/TrackedEntityInstancePostCall.java
- core/src/main/java/org/hisp/dhis/android/core/common/APICallExecutor.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstance.java
Solves [ANDROSDK-373](https://jira.dhis2.org/browse/ANDROSDK-373).
> Tei error management

- core/src/main/java/org/hisp/dhis/android/core/data/database/IgnoreOptionAdapter.java
- core/src/main/java/org/hisp/dhis/android/core/data/database/IgnoreOptionListAdapter.java
- core/src/main/java/org/hisp/dhis/android/core/data/database/OptionSetWithUidColumnAdapter.java
- core/src/main/java/org/hisp/dhis/android/core/option/Option.java
- core/src/main/java/org/hisp/dhis/android/core/option/OptionFields.java
- core/src/main/java/org/hisp/dhis/android/core/option/OptionHandler.java
- core/src/main/java/org/hisp/dhis/android/core/option/OptionSet.java
- core/src/main/java/org/hisp/dhis/android/core/option/OptionSetCall.java
- core/src/main/java/org/hisp/dhis/android/core/option/OptionSetHandler.java
- core/src/main/java/org/hisp/dhis/android/core/option/OptionStore.java
- core/src/main/java/org/hisp/dhis/android/core/option/OptionTableInfo.java
- core/src/test/java/org/hisp/dhis/android/core/option/OptionSetHandlerShould.java
Solves [ANDROSDK-375](https://jira.dhis2.org/browse/ANDROSDK-375).
> Option unified

- core/src/main/java/org/hisp/dhis/android/core/D2.java
- core/src/main/java/org/hisp/dhis/android/core/D2InternalModules.java
- core/src/main/java/org/hisp/dhis/android/core/datavalue/DataValueCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/datavalue/DataValueEndpointCall.java
- core/src/main/java/org/hisp/dhis/android/core/datavalue/DataValueHandlerImpl.java
- core/src/main/java/org/hisp/dhis/android/core/datavalue/DataValueInternalModule.java
- core/src/main/java/org/hisp/dhis/android/core/datavalue/DataValueModule.java
- core/src/main/java/org/hisp/dhis/android/core/datavalue/DataValueStore.java
[ANDROSDK-346](https://jira.dhis2.org/browse/ANDROSDK-346)
> ANDROSDK-346: Create "datavalue" module

- core/src/main/java/org/hisp/dhis/android/core/datavalue/DataValueStore.java
- core/src/main/java/org/hisp/dhis/android/core/datavalue/DataValueTableInfo.java
Solves [ANDROSDK-387](https://jira.dhis2.org/browse/ANDROSDK-387)
> [ANDROSDK-387] Rewrite exists in DataValueStore

- core/src/androidTest/java/org/hisp/dhis/android/core/utils/services/ProgramIndicatorEngineIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventStoreImpl.java
Solves [ANDROSDK-388](https://jira.dhis2.org/browse/ANDROSDK-388)
> [ANDROSDK-388] Add failing test, add lastUpdated check

- core/src/main/java/org/hisp/dhis/android/core/arch/handlers/SyncHandlerBaseImpl.java
- core/src/main/java/org/hisp/dhis/android/core/arch/handlers/SyncHandlerWithTransformer.java
- core/src/main/java/org/hisp/dhis/android/core/category/CategoryComboHandler.java
- core/src/main/java/org/hisp/dhis/android/core/category/CategoryOptionComboHandler.java
- core/src/test/java/org/hisp/dhis/android/core/category/CategoryComboHandlerShould.java
Solves [ANDROSDK-381](https://jira.dhis2.org/browse/ANDROSDK-381).
> Androsdk 381

- core/src/androidTest/assets/data_sets.json
- core/src/main/java/org/hisp/dhis/android/core/arch/handlers/LinkSyncHandler.java
- core/src/main/java/org/hisp/dhis/android/core/arch/handlers/LinkSyncHandlerImpl.java
- core/src/main/java/org/hisp/dhis/android/core/arch/handlers/ObjectWithoutUidSyncHandlerImpl.java
- core/src/main/java/org/hisp/dhis/android/core/common/LinkModelStore.java
- core/src/main/java/org/hisp/dhis/android/core/common/LinkModelStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/common/ObjectWithoutUidStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/common/StoreFactory.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSet.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetDataElementLinkStore.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetElement.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetElementFields.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetElementLinkTableInfo.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetHandler.java
- core/src/test/java/org/hisp/dhis/android/core/dataset/DataSetHandlerShould.java
- core/src/test/resources/data_sets.json
- core/src/test/resources/dataset/data_set.json
Solves [ANDROSDK-367](https://jira.dhis2.org/browse/ANDROSDK-367).
> Androsdk 367

- core/src/main/java/org/hisp/dhis/android/core/arch/db/WhereClauseBuilder.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetCompleteRegistrationStore.java
- core/src/main/java/org/hisp/dhis/android/core/datavalue/DataValueStore.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStore.java
- core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipItemStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueStore.java
- core/src/test/java/org/hisp/dhis/android/core/arch/db/WhereClauseBuilderShould.java
Extracts and test whereClause building.
> [ANDROSDK-399] Add and use WhereClauseBuilder

- core/src/androidTest/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitCallMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/children/ChildrenAppender.java
- core/src/main/java/org/hisp/dhis/android/core/common/ObjectStyleChildrenAppender.java
- core/src/main/java/org/hisp/dhis/android/core/common/ObjectStyleStore.java
- core/src/main/java/org/hisp/dhis/android/core/common/ObjectStyleStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/common/ObjectStyleTableInfo.java
- core/src/main/java/org/hisp/dhis/android/core/common/ObjectWithStyle.java
- core/src/main/java/org/hisp/dhis/android/core/dataelement/DataElement.java
- core/src/main/java/org/hisp/dhis/android/core/dataelement/DataElementCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/program/Program.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStage.java
- core/src/main/java/org/hisp/dhis/android/core/wipe/WipeModuleImpl.java
Solves [ANDROSDK-360](https://jira.dhis2.org/browse/ANDROSDK-360).
> [ANDROSDK-360] ObjectStyle child appender in DataElement repository

- core/src/androidTest/java/org/hisp/dhis/android/core/data/database/DatabaseAdapterFactory.java
- core/src/androidTest/java/org/hisp/dhis/android/core/data/database/IdentifiableObjectStoreAbstractIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/data/database/ObjectStoreAbstractIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/indicator/IndicatorStoreIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/common/BaseIdentifiableObject.java
- core/src/main/java/org/hisp/dhis/android/core/common/BaseNameableObject.java
- core/src/sharedTest/java/org/hisp/dhis/android/core/data/indicator/IndicatorSamples.java
- core/src/sharedTest/java/org/hisp/dhis/android/core/data/utils/FillPropertiesTestUtils.java
Solves [ANDROSDK-401](https://jira.dhis2.org/browse/ANDROSDK-401).
> [ANDROSDK-401] Store tests

- core/src/main/java/org/hisp/dhis/android/core/event/EventPersistenceCall.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/SearchOrganisationUnitOnDemandCall.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancePersistenceCall.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceRelationshipPersistenceCall.java
[ANDROSDK-395](https://jira.dhis2.org/browse/ANDROSDK-395)
> [ANDROSDK-395] Refactor OldSearchOrganisationUnitCall

- core/src/androidTest/java/org/hisp/dhis/android/core/data/database/ObjectStoreAbstractIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/data/database/ObjectWithoutUidStoreAbstractIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/relationship/RelationshipConstraintStoreIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/systeminfo/SystemInfoStoreIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/systeminfo/SystemInfo.java
- core/src/sharedTest/java/org/hisp/dhis/android/core/data/relationship/RelationshipConstraintSamples.java
Solves [ANDROSDK-410](https://jira.dhis2.org/browse/ANDROSDK-410).
> [ANDROSDK-410] Add generic tests for ObjectWithoutUidStore

- core/src/main/java/org/hisp/dhis/android/core/common/StoreWithStateImpl.java
Solves [ANDROSDK-407](https://jira.dhis2.org/browse/ANDROSDK-407)
> [ANDROSDK-407] Fix not closed cursor

- core/src/androidTest/java/org/hisp/dhis/android/core/data/database/LinkModelStoreAbstractIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/dataset/DataInputPeriodLinkStoreIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/dataset/DataSetDataElementLinkStoreIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataInputPeriod.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataInputPeriodLinkStore.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetHandler.java
- core/src/main/java/org/hisp/dhis/android/core/wipe/WipeModuleImpl.java
- core/src/sharedTest/java/org/hisp/dhis/android/core/data/dataset/DataInputPeriodSamples.java
- core/src/sharedTest/java/org/hisp/dhis/android/core/data/dataset/DataSetElementSamples.java
- core/src/test/java/org/hisp/dhis/android/core/dataset/DataInputPeriodShould.java
Solves [ANDROSDK-411](https://jira.dhis2.org/browse/ANDROSDK-411).
On top of #448.
>  [ANDROSDK-411] Add generic tests for LinkStore

- core/src/androidTest/java/org/hisp/dhis/android/core/category/CategoryModuleMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/arch/db/TableInfo.java
- core/src/main/java/org/hisp/dhis/android/core/common/SQLStatementBuilder.java
- core/src/test/java/org/hisp/dhis/android/core/common/SQLStatementBuilderShould.java
Solves [ANDROSDK-420](https://jira.dhis2.org/browse/ANDROSDK-420).
> [ANDROSDK-420] Return category objects using sortOrder in repositories

- core/src/androidTest/java/org/hisp/dhis/android/core/event/api/EventAPI29Should.java
- core/src/androidTest/java/org/hisp/dhis/android/core/event/api/EventAPI30Should.java
- core/src/androidTest/java/org/hisp/dhis/android/core/event/api/EventAPIShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/event/api/EventUtils.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventService.java
Creates some tests to show behavior in [ANDROSDK-347](https://jira.dhis2.org/browse/ANDROSDK-347)
> [ANDROSDK-347] Add EventAPI tests

- core/src/androidTest/java/org/hisp/dhis/android/core/category/CategoryModuleMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/children/ChildrenAppenderExecutor.java
- core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipObjectRepository.java
Solves [ANDROSDK-372](https://jira.dhis2.org/browse/ANDROSDK-372).
> [ANDROSDK-372] Ensure not adding children to null objects, fix code

- core/src/androidTest/assets/categories.json
- core/src/main/assets/migrations/29.yaml
- core/src/main/java/org/hisp/dhis/android/core/category/CategoryHandler.java
- core/src/main/java/org/hisp/dhis/android/core/category/CategoryOption.java
- core/src/main/java/org/hisp/dhis/android/core/category/CategoryOptionFields.java
- core/src/main/java/org/hisp/dhis/android/core/category/CategoryOptionModel.java
- core/src/main/java/org/hisp/dhis/android/core/category/CategoryOptionStore.java
- core/src/main/java/org/hisp/dhis/android/core/category/CategoryOptionTableInfo.java
- core/src/main/java/org/hisp/dhis/android/core/data/database/DbOpenHelper.java
- core/src/test/java/org/hisp/dhis/android/core/category/CategoryHandlerShould.java
Solves [ANDROSDK-418](https://jira.dhis2.org/browse/ANDROSDK-418).
> [ANDROSDK-418] Data access in category options

- core/src/androidTest/java/org/hisp/dhis/android/core/category/CategoryComboEndpointCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/category/CategoryComboUidsSeekerMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/category/CategoryEndpointCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/category/CategoryEndpointCallShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/data/database/MockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/dataelement/CreateDataElementUtils.java
- core/src/androidTest/java/org/hisp/dhis/android/core/program/ProgramRuleActionStoreShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/program/ProgramRuleVariableStoreShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/program/ProgramStageDataElementStoreShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/utils/services/ProgramIndicatorEngineIntegrationShould.java
- core/src/main/assets/migrations/30.yaml
- core/src/main/java/org/hisp/dhis/android/core/arch/db/MultipleTableQueryBuilder.java
- core/src/main/java/org/hisp/dhis/android/core/calls/MetadataCall.java
- core/src/main/java/org/hisp/dhis/android/core/category/CategoryComboEndpointCall.java
- core/src/main/java/org/hisp/dhis/android/core/category/CategoryComboFields.java
- core/src/main/java/org/hisp/dhis/android/core/category/CategoryComboService.java
- core/src/main/java/org/hisp/dhis/android/core/category/CategoryComboUidsSeeker.java
- core/src/main/java/org/hisp/dhis/android/core/category/CategoryEndpointCall.java
- core/src/main/java/org/hisp/dhis/android/core/category/CategoryParentUidsHelper.java
- core/src/main/java/org/hisp/dhis/android/core/category/CategoryService.java
- core/src/main/java/org/hisp/dhis/android/core/data/database/DbOpenHelper.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetFields.java
- core/src/sharedTest/java/org/hisp/dhis/android/core/data/server/Dhis2MockServer.java
- core/src/test/java/org/hisp/dhis/android/core/arch/db/MultipleTableQueryBuilderShould.java
- core/src/test/java/org/hisp/dhis/android/core/common/MetadataCallShould.java
Solves [ANDROSDK-379](https://jira.dhis2.org/browse/ANDROSDK-379).
> [ANDROSDK-379] Download only necessary Categories and CategoryCombos

- core/src/androidTest/java/org/hisp/dhis/android/core/legendset/LegendSetStoreIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/legendset/LegendStoreIntegrationShould.java
- core/src/sharedTest/java/org/hisp/dhis/android/core/data/legend/LegendSamples.java
- core/src/sharedTest/java/org/hisp/dhis/android/core/data/legend/LegendSetSamples.java
Solves [ANDROSDK-435](https://jira.dhis2.org/browse/ANDROSDK-435).
>  [ANDROSDK-435] Add Legend set and Legend store tests.

- build.gradle
- core/src/main/java/org/hisp/dhis/android/core/event/EventHandler.java
- gradle.properties
Solves [ANDROSDK-440](https://jira.dhis2.org/browse/ANDROSDK-440)
> Do not remove events without eventDate

- core/src/androidTest/java/org/hisp/dhis/android/core/user/UserCallMockIntegrationShould.java
Solves (ANDROSDK-438)[https://jira.dhis2.org/browse/ANDROSDK-438].
> [ANDROSDK-438] Remove hardcoded JSON from Java instrumentation tests

- core/src/main/java/org/hisp/dhis/android/core/category/Category.java
- core/src/main/java/org/hisp/dhis/android/core/category/CategoryCombo.java
- core/src/main/java/org/hisp/dhis/android/core/category/CategoryOption.java
- core/src/main/java/org/hisp/dhis/android/core/category/CategoryOptionCombo.java
- core/src/main/java/org/hisp/dhis/android/core/common/BaseModel.java
- core/src/main/java/org/hisp/dhis/android/core/common/Model.java
- core/src/main/java/org/hisp/dhis/android/core/dataelement/DataElement.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSet.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetElement.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/Section.java
- core/src/main/java/org/hisp/dhis/android/core/enrollment/note/Note.java
- core/src/main/java/org/hisp/dhis/android/core/indicator/Indicator.java
- core/src/main/java/org/hisp/dhis/android/core/indicator/IndicatorType.java
- core/src/main/java/org/hisp/dhis/android/core/legendset/Legend.java
- core/src/main/java/org/hisp/dhis/android/core/legendset/LegendSet.java
- core/src/main/java/org/hisp/dhis/android/core/option/Option.java
- core/src/main/java/org/hisp/dhis/android/core/option/OptionSet.java
- core/src/main/java/org/hisp/dhis/android/core/program/Program.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramIndicator.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageSection.java
- core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipType.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityType.java
- core/src/main/java/org/hisp/dhis/android/core/user/User.java
- core/src/main/java/org/hisp/dhis/android/core/user/UserCredentials.java
Solves [ANDROSDK-443](https://jira.dhis2.org/browse/ANDROSDK-443).
> [ANDROSDK-443] Move toContentValues from BaseModel to Model

- core/src/main/java/org/hisp/dhis/android/core/data/database/CategoryComboWithUidColumnAdapter.java
- core/src/main/java/org/hisp/dhis/android/core/data/database/IdentifiableObjectColumnAdapter.java
- core/src/main/java/org/hisp/dhis/android/core/data/database/ObjectWithUidColumnAdapter.java
- core/src/main/java/org/hisp/dhis/android/core/data/database/OptionSetWithUidColumnAdapter.java
- core/src/main/java/org/hisp/dhis/android/core/data/database/OrganisationUnitWithUidColumnAdapter.java
- core/src/main/java/org/hisp/dhis/android/core/data/database/ProgramStageWithUidColumnAdapter.java
- core/src/main/java/org/hisp/dhis/android/core/data/database/ProgramWithUidColumnAdapter.java
- core/src/main/java/org/hisp/dhis/android/core/data/database/RelationshipTypeWithUidColumnAdapter.java
- core/src/main/java/org/hisp/dhis/android/core/data/database/TrackedEntityInstanceWithUidColumnAdapter.java
- core/src/main/java/org/hisp/dhis/android/core/data/database/TrackedEntityTypeWithUidColumnAdapter.java
- core/src/main/java/org/hisp/dhis/android/core/data/database/UserWithUidColumnAdapter.java
Solves [ANDROSDK-448](https://jira.dhis2.org/browse/ANDROSDK-448).
> [ANDROSDK-448]  Ensure IdAdapters don't try to create objects with null uid

- core/src/androidTest/java/org/hisp/dhis/android/core/systeminfo/SystemInfoModuleMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/common/ObjectStore.java
- core/src/main/java/org/hisp/dhis/android/core/common/ObjectStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/common/SQLStatementBuilder.java
- core/src/main/java/org/hisp/dhis/android/core/common/UidsHelper.java
- core/src/main/java/org/hisp/dhis/android/core/systeminfo/PerformanceHintsService.java
- core/src/main/java/org/hisp/dhis/android/core/systeminfo/SystemInfoModule.java
- core/src/test/java/org/hisp/dhis/android/core/common/SQLStatementBuilderShould.java
- core/src/test/java/org/hisp/dhis/android/core/systeminfo/PerformanceHintsServiceShould.java
Solves [ANDROSDK-446](https://jira.dhis2.org/browse/ANDROSDK-446)
> [ANDROSDK-446] Metadata performance evaluation

- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueEndpointCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueManagerRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueStoreIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValue.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueEndpointCall.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueHandler.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueManager.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueModelBuilder.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueStore.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueStoreInterface.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueTableInfo.java
- core/src/test/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueHandlerShould.java
- core/src/test/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueModelBuilderShould.java
Solves [ANDROSDK-433](https://jira.dhis2.org/browse/ANDROSDK-433).
> [ANDROSDK-433] Unified classTreackedEntityAttributeReservedValue

- core/src/main/java/org/hisp/dhis/android/core/common/ValueTypeRenderingType.java
Solves [ANDROSDK-467](https://jira.dhis2.org/browse/ANDROSDK-467)
> [ANDROSDK-467] Add AUTOCOMPLETE renderType

- core/src/main/assets/migrations/34.yaml
- core/src/main/java/org/hisp/dhis/android/core/data/database/DbOpenHelper.java
- core/src/main/java/org/hisp/dhis/android/core/maintenance/D2Error.java
- core/src/main/java/org/hisp/dhis/android/core/maintenance/D2ErrorStore.java
- core/src/main/java/org/hisp/dhis/android/core/maintenance/D2ErrorTableInfo.java
Solves [ANDROSDK-469](https://jira.dhis2.org/browse/ANDROSDK-469).
> [ANDROSDK-469] Add created Column to D2Error

- core/src/androidTest/java/org/hisp/dhis/android/core/TeisCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancePostCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceSyncDownCallRealIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/D2.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceWithLimitCall.java
Solves [ANDROSDK-464](https://jira.dhis2.org/browse/ANDROSDK-464).
> [ANDROSDK-464] Persist teis after each call

- build.gradle
- core/build.gradle
- core/src/androidTest/java/org/hisp/dhis/android/core/systeminfo/SystemInfoCallMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/D2.java
- core/src/main/java/org/hisp/dhis/android/core/D2DIComponent.java
- core/src/main/java/org/hisp/dhis/android/core/D2InternalModules.java
- core/src/main/java/org/hisp/dhis/android/core/D2InternalModulesDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/arch/api/retrofit/RetrofitDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/category/CategoryDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/category/CategoryInternalModule.java
- core/src/main/java/org/hisp/dhis/android/core/category/CategoryModule.java
- core/src/main/java/org/hisp/dhis/android/core/data/database/DatabaseDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/dataelement/DataElementDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/dataelement/DataElementInternalModule.java
- core/src/main/java/org/hisp/dhis/android/core/dataelement/DataElementModule.java
- core/src/main/java/org/hisp/dhis/android/core/datavalue/DataValueDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/datavalue/DataValueInternalModule.java
- core/src/main/java/org/hisp/dhis/android/core/datavalue/DataValueModule.java
- core/src/main/java/org/hisp/dhis/android/core/maintenance/MaintenanceDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/maintenance/MaintenanceInternalModule.java
- core/src/main/java/org/hisp/dhis/android/core/maintenance/MaintenanceModule.java
- core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipCollectionRepositoryImpl.java
- core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipInternalModule.java
- core/src/main/java/org/hisp/dhis/android/core/systeminfo/DHISVersionManager.java
- core/src/main/java/org/hisp/dhis/android/core/systeminfo/SystemInfoDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/systeminfo/SystemInfoInternalModule.java
- core/src/main/java/org/hisp/dhis/android/core/systeminfo/SystemInfoModule.java
Solves [ANDROSDK-461](https://jira.dhis2.org/browse/ANDROSDK-461).
> [ANDROSDK-461] Introduce Dagger and bind SDK modules

- core/src/main/java/org/hisp/dhis/android/core/calls/AggregatedDataCall.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventWithLimitCall.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceWithLimitCall.java
- core/src/main/java/org/hisp/dhis/android/core/user/UserOrganisationUnitLinkStore.java
- core/src/main/java/org/hisp/dhis/android/core/user/UserOrganisationUnitLinkStoreInterface.java
Solves [ANDROSDK-480](https://jira.dhis2.org/browse/ANDROSDK-480).
> [ANDROSDK-480] Fix event with limit call

- core/src/androidTest/java/org/hisp/dhis/android/core/data/database/AbsStoreTestCase.java
- core/src/androidTest/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitCallMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/D2.java
- core/src/main/java/org/hisp/dhis/android/core/D2DIComponent.java
- core/src/main/java/org/hisp/dhis/android/core/calls/AggregatedDataCall.java
- core/src/main/java/org/hisp/dhis/android/core/calls/MetadataCall.java
- core/src/main/java/org/hisp/dhis/android/core/common/GenericCallData.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitCall.java
- core/src/main/java/org/hisp/dhis/android/core/resource/ResourceHandler.java
- core/src/main/java/org/hisp/dhis/android/core/systeminfo/SystemInfoCall.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueManager.java
- core/src/main/java/org/hisp/dhis/android/core/user/UserAuthenticateCall.java
- core/src/main/java/org/hisp/dhis/android/core/user/UserCall.java
- core/src/test/java/org/hisp/dhis/android/core/common/BaseCallShould.java
- core/src/test/java/org/hisp/dhis/android/core/common/MetadataCallShould.java
- core/src/test/java/org/hisp/dhis/android/core/resource/ResourceHandlerShould.java
- core/src/test/java/org/hisp/dhis/android/core/systeminfo/SystemInfoCallShould.java
- core/src/test/java/org/hisp/dhis/android/core/user/UserAuthenticateCallUnitShould.java
- core/src/test/java/org/hisp/dhis/android/core/user/UserCallShould.java
Solves [ANDROSDK-477](https://jira.dhis2.org/browse/ANDROSDK-477).
> [ANDROSDK-477] Handle server date inside resource handler

- core/src/main/java/org/hisp/dhis/android/core/user/AuthorityCallProcessor.java
- core/src/main/java/org/hisp/dhis/android/core/user/AuthorityEndpointCall.java
- core/src/test/java/org/hisp/dhis/android/core/user/AuthorityEndpointCallShould.java
Solves [ANDROSDK-478](https://jira.dhis2.org/browse/ANDROSDK-478).
> [ANDROSDK-478] Clean authorities table before each authorities update

- core/src/androidTest/java/org/hisp/dhis/android/core/option/OptionSetCallShould.java
- core/src/main/java/org/hisp/dhis/android/core/calls/AggregatedDataCall.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetParentCall.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventPersistenceCall.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramParentCall.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancePersistenceCall.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceRelationshipPersistenceCall.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceWithLimitCall.java
Solves [ANDROSDK-483](https://jira.dhis2.org/browse/ANDROSDK-483).
>  [ANDROSDK-483] Remove unnecessary calls to d2Executor

- core/src/androidTest/java/org/hisp/dhis/android/core/EventWithLimitCallMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/common/EventCallFactory.java
- core/src/main/java/org/hisp/dhis/android/core/D2.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventEndpointCall.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventQuery.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventService.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventWithLimitCall.java
- core/src/test/java/org/hisp/dhis/android/core/event/EventEndpointCallShould.java
- core/src/test/java/org/hisp/dhis/android/core/event/EventQueryShould.java
Solves [ANDROSDK-486](https://jira.dhis2.org/browse/ANDROSDK-486)
> Androsdk 486 - LastUpdatedStartDate in single events

- core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityDataValueStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceStoreImpl.java
Solves [ANDROSDK-473](https://jira.dhis2.org/browse/ANDROSDK-473).
> [ANDROSDK-473] Post only modified elements on tei sync up.

- build.gradle
- core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityDataValueStoreImpl.java
- gradle.properties
Revert ANDROSDK-473.
Version 0.13.0
> Academy znz

- core/src/main/java/org/hisp/dhis/android/core/D2DIComponent.java
- core/src/main/java/org/hisp/dhis/android/core/arch/di/IdentifiableEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/arch/di/IdentifiableEntityFromDatabaseAdapterDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/arch/di/IdentifiableStoreProvider.java
- core/src/main/java/org/hisp/dhis/android/core/arch/di/ObjectWithoutUidEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/arch/di/ObjectWithoutUidStoreProvider.java
- core/src/main/java/org/hisp/dhis/android/core/arch/di/SyncHandlerFromDatabaseAdapterProvider.java
- core/src/main/java/org/hisp/dhis/android/core/category/CategoryPackageDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/common/CommonPackageDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/dataelement/DataElementEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/indicator/IndicatorEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/indicator/IndicatorTypeEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/maintenance/MaintenancePackageDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/option/OptionSetEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/period/PeriodEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/period/PeriodPackageDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipPackageDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/resource/ResourceEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/resource/ResourcePackageDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/settings/SystemSettingEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/settings/SystemSettingPackageDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/systeminfo/SystemInfoEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/systeminfo/SystemInfoPackageDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/user/AuthenticatedUserEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/user/AuthorityEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/user/UserCredentialsEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/user/UserEntityDIModule.java
Solves [ANDROSDK-516](https://jira.dhis2.org/browse/ANDROSDK-516).
> [ANDROSDK-516] Restructure DIModules in PackageDIModule and EntityDIModule

- core/src/androidTest/java/org/hisp/dhis/android/core/user/UserCallMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/calls/MetadataCall.java
- core/src/main/java/org/hisp/dhis/android/core/user/UserCall.java
- core/src/main/java/org/hisp/dhis/android/core/user/UserDownloadModule.java
- core/src/main/java/org/hisp/dhis/android/core/user/UserInternalModule.java
- core/src/main/java/org/hisp/dhis/android/core/user/UserPackageDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/user/UserParentCall.java
- core/src/test/java/org/hisp/dhis/android/core/common/MetadataCallShould.java
- core/src/test/java/org/hisp/dhis/android/core/user/AuthorityEndpointCallShould.java
- core/src/test/java/org/hisp/dhis/android/core/user/UserCallShould.java
Solves [ANDROSDK-522](https://jira.dhis2.org/browse/ANDROSDK-522).
> [ANDROSDK-522] UserParentCall downloading user and authorities

- core/src/androidTest/java/org/hisp/dhis/android/core/systeminfo/SystemInfoCallMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/user/UserCallMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/arch/modules/MetadataModuleDownloader.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadOnlyWithDownloadObjectRepository.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/object/ReadOnlyFirstObjectWithDownloadRepositoryImpl.java
- core/src/main/java/org/hisp/dhis/android/core/calls/MetadataCall.java
- core/src/main/java/org/hisp/dhis/android/core/domain/aggregated/data/AggregatedDataCall.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventWithLimitCall.java
- core/src/main/java/org/hisp/dhis/android/core/maintenance/ForeignKeyCleanerImpl.java
- core/src/main/java/org/hisp/dhis/android/core/maintenance/MaintenancePackageDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/systeminfo/SystemInfoCall.java
- core/src/main/java/org/hisp/dhis/android/core/systeminfo/SystemInfoInternalModule.java
- core/src/main/java/org/hisp/dhis/android/core/systeminfo/SystemInfoModuleDownloader.java
- core/src/main/java/org/hisp/dhis/android/core/systeminfo/SystemInfoPackageDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueManager.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceWithLimitCall.java
- core/src/main/java/org/hisp/dhis/android/core/user/UserAuthenticateCallFactory.java
- core/src/main/java/org/hisp/dhis/android/core/user/UserCall.java
- core/src/main/java/org/hisp/dhis/android/core/user/UserDownloadModule.java
- core/src/main/java/org/hisp/dhis/android/core/user/UserInternalModule.java
- core/src/main/java/org/hisp/dhis/android/core/user/UserModuleDownloader.java
- core/src/main/java/org/hisp/dhis/android/core/user/UserPackageDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/user/UserParentCall.java
- core/src/test/java/org/hisp/dhis/android/core/common/MetadataCallShould.java
- core/src/test/java/org/hisp/dhis/android/core/systeminfo/SystemInfoCallShould.java
- core/src/test/java/org/hisp/dhis/android/core/user/AuthorityEndpointCallShould.java
- core/src/test/java/org/hisp/dhis/android/core/user/UserAuthenticateCallUnitShould.java
- core/src/test/java/org/hisp/dhis/android/core/user/UserCallShould.java
Solves [ANDROSDK-523](https://jira.dhis2.org/browse/ANDROSDK-523).
> [ANDROSDK-523] SystemInfo download in repository

- core/src/androidTest/java/org/hisp/dhis/android/core/dataset/DataSetStoreIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/common/Access.java
- core/src/main/java/org/hisp/dhis/android/core/dataelement/DataElementEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/dataelement/DataElementModule.java
- core/src/main/java/org/hisp/dhis/android/core/dataelement/DataElementPackageDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetModule.java
- core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipModule.java
- core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipPackageDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipTypeEntityDIModule.java
- core/src/sharedTest/java/org/hisp/dhis/android/core/data/dataset/DataSetSamples.java
Solves [ANDROSDK-525](https://jira.dhis2.org/browse/ANDROSDK-525).
> [ANDROSDK-525] Add DataSet repository to DataSetModule

- core/src/main/java/org/hisp/dhis/android/core/dataset/DataInputPeriodLinkStore.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetCompulsoryDataElementOperandLinkStore.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetDataElementLinkStore.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetElementFields.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetHandler.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetService.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetStore.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/SectionDataElementLinkStore.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/SectionGreyedFieldsLinkStore.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/SectionHandler.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/SectionStore.java
Solves [ANDROSDK-530](https://jira.dhis2.org/browse/ANDROSDK-530).
> [ANDROSDK-530] Reduce DataSet package class visibilty

- core/src/androidTest/java/org/hisp/dhis/android/core/program/ProgramModuleMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/D2.java
- core/src/main/java/org/hisp/dhis/android/core/D2Modules.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramModule.java
Solves [ANDROSDK-531](https://jira.dhis2.org/browse/ANDROSDK-531).
> [ANDROSDK-531] Create ProgramModule with ProgramCollectionRepository

- core/src/main/java/org/hisp/dhis/android/core/calls/TrackedEntityInstanceSyncDownCall.java
- core/src/main/java/org/hisp/dhis/android/core/calls/fetchers/PayloadNoResourceCallFetcher.java
- core/src/main/java/org/hisp/dhis/android/core/calls/fetchers/PayloadResourceCallFetcher.java
- core/src/main/java/org/hisp/dhis/android/core/calls/fetchers/UidsNoResourceCallFetcher.java
- core/src/main/java/org/hisp/dhis/android/core/calls/processors/TransactionalNoResourceCallProcessor.java
- core/src/main/java/org/hisp/dhis/android/core/calls/processors/TransactionalNoResourceSyncCallProcessor.java
- core/src/main/java/org/hisp/dhis/android/core/calls/processors/TransactionalNoResourceSyncCallWithTransformerProcessor.java
- core/src/main/java/org/hisp/dhis/android/core/calls/processors/TransactionalResourceSyncCallProcessor.java
- core/src/main/java/org/hisp/dhis/android/core/common/LinkModelStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/common/ObjectWithStyle.java
- core/src/main/java/org/hisp/dhis/android/core/configuration/ConfigurationStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetCompleteRegistrationCallFetcher.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitHandlerImpl.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/SearchOrganisationUnitHandlerImpl.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/UserOrganisationUnitEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramRuleActionStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramRuleVariableStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageDataElementStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipObjectRepository.java
- core/src/main/java/org/hisp/dhis/android/core/resource/ResourceStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceDownloadByUidEndPointCall.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceListDownloadAndPersistCall.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancesEndpointCall.java
- core/src/main/java/org/hisp/dhis/android/core/user/UserOrganisationUnitLinkStore.java
- core/src/main/java/org/hisp/dhis/android/core/user/UserOrganisationUnitLinkStoreInterface.java
- core/src/main/java/org/hisp/dhis/android/core/user/UserRoleStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/wipe/WipeModule.java
- core/src/test/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitHandlerShould.java
- core/src/test/java/org/hisp/dhis/android/core/organisationunit/SearchOrganisationUnitHandlerShould.java
[ANDROSDK-398](https://jira.dhis2.org/browse/ANDROSDK-398)
> [ANDROSDK-398] Manage updates in UserOrganisationUnit

- core/src/androidTest/java/org/hisp/dhis/android/core/data/database/MockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/event/EventModuleMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/D2.java
- core/src/main/java/org/hisp/dhis/android/core/D2DIComponent.java
- core/src/main/java/org/hisp/dhis/android/core/D2Modules.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventModule.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventPackageDIModule.java
- core/src/sharedTest/java/org/hisp/dhis/android/core/data/server/Dhis2MockServer.java
Solves [ANDROSDK-536](https://jira.dhis2.org/browse/ANDROSDK-536).
> [ANDROSDK-536] Create EventModule with EventCollectionRepository

- core/src/androidTest/java/org/hisp/dhis/android/core/data/database/MockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/data/server/RealServerMother.java
- core/src/androidTest/java/org/hisp/dhis/android/core/event/EventModuleMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/systeminfo/DHISVersionsManagerRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityModuleMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/D2.java
- core/src/main/java/org/hisp/dhis/android/core/D2DIComponent.java
- core/src/main/java/org/hisp/dhis/android/core/D2Modules.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventModule.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventPackageDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/systeminfo/DHISVersion.java
- core/src/main/java/org/hisp/dhis/android/core/systeminfo/DHISVersionManager.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityModule.java
- core/src/sharedTest/java/org/hisp/dhis/android/core/data/server/Dhis2MockServer.java
- core/src/sharedTest/resources/trackedentity/tracked_entity_instances.json
Solves [ANDROSDK-537](https://jira.dhis2.org/browse/ANDROSDK-537)
>  [ANDROSDK-537] Create TrackedEntityModule

- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceWithLimitCall.java
Solves [ANDROSDK-538](https://jira.dhis2.org/browse/ANDROSDK-538).
> [ANDROSDK-538] Prevent multiple systemInfo calls in TEIs download

- core/src/androidTest/java/org/hisp/dhis/android/core/data/database/MockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/data/server/RealServerMother.java
- core/src/androidTest/java/org/hisp/dhis/android/core/enrollment/EnrollmentModuleMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/event/EventModuleMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/systeminfo/DHISVersionsManagerRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityModuleMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/D2.java
- core/src/main/java/org/hisp/dhis/android/core/D2DIComponent.java
- core/src/main/java/org/hisp/dhis/android/core/D2Modules.java
- core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentModule.java
- core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentPackageDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventModule.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventPackageDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/systeminfo/DHISVersion.java
- core/src/main/java/org/hisp/dhis/android/core/systeminfo/DHISVersionManager.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityModule.java
- core/src/sharedTest/java/org/hisp/dhis/android/core/data/server/Dhis2MockServer.java
- core/src/sharedTest/resources/trackedentity/tracked_entity_instances.json
Solves [ANDROSDK-535](https://jira.dhis2.org/browse/ANDROSDK-537).
>  [ANDROSDK-535] Create EnrollmentModule with EnrollmentCollectionRepository

- core/src/androidTest/java/org/hisp/dhis/android/core/data/database/MockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/systeminfo/SystemInfoModuleMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/user/UserModuleMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/object/ReadOnlyFirstObjectRepositoryImpl.java
- core/src/main/java/org/hisp/dhis/android/core/user/AuthenticatedUserEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/user/UserModule.java
Solves [ANDROSDK-539](https://jira.dhis2.org/browse/ANDROSDK-539).
> [ANDROSDK-539] Create AuthenticatedUserRepository

- core/src/androidTest/java/org/hisp/dhis/android/core/user/UserModuleMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/user/UserCredentialsEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/user/UserModule.java
Solves [ANDROSDK-540](https://jira.dhis2.org/browse/ANDROSDK-540).
>  [ANDROSDK-540] Create UserCredentialsRepository

- core/src/androidTest/java/org/hisp/dhis/android/core/user/UserModuleMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/user/UserEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/user/UserModule.java
Solves [ANDROSDK-541](https://jira.dhis2.org/browse/ANDROSDK-541).
> [ANDROSDK-541] Create UserRepository

- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueEndpointCallRealIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/D2.java
- core/src/main/java/org/hisp/dhis/android/core/D2DIComponent.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueEndpointCallFactory.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueManager.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityModule.java
Solves [ANDROSDK-545](https://jira.dhis2.org/browse/ANDROSDK-545).
> [ANDROSDK-545] Let client access directly ReservedValuesManager and remove d2 methods

- core/src/androidTest/java/org/hisp/dhis/android/core/event/EventEndpointCallMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceCallMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentHandler.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventHandler.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventPersistenceCall.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceHandler.java
- core/src/test/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceHandlerShould.java
Solves [ANDROSDK-527](https://jira.dhis2.org/browse/ANDROSDK-527).
> [ANDROSDK-527] Enrollments and TEIs have null state

- core/src/androidTest/java/org/hisp/dhis/android/core/EventWithLimitCallMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/data/database/MockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/event/EventEndpointCallMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/event/EventPostCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/event/EventWithLimitCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceCallMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/D2.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadOnlyWithUploadCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentHandler.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventHandler.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventModule.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventPersistenceCall.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventPostCall.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventWithLimitCallFactory.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityDataValueEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityDataValueHandler.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceHandler.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityPackageDIModule.java
- core/src/test/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceHandlerShould.java
Solves [ANDROSDK-543](https://jira.dhis2.org/browse/ANDROSDK-543).
> [ANDROSDK-543] Move syncSingleEvents to EventModule

- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceHandler.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceWithLimitCall.java
Solves [ANDROSDK-533](https://jira.dhis2.org/browse/ANDROSDK-533).
> [ANDROSDK-533] Prevent overwrite already downloaded teis

- core/src/main/java/org/hisp/dhis/android/core/event/EventWithLimitCallFactory.java
Solves [ANDROSDK-547](https://jira.dhis2.org/browse/ANDROSDK-547).
> [ANDROSDK-547] Download event with limit call last page properly

- core/src/androidTest/java/org/hisp/dhis/android/core/utils/services/ProgramIndicatorEngineIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/D2.java
- core/src/main/java/org/hisp/dhis/android/core/D2DIComponent.java
- core/src/main/java/org/hisp/dhis/android/core/constant/ConstantPackageDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramIndicatorEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramPackageDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeValueEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeValueHandler.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityPackageDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/utils/services/ProgramIndicatorEngine.java
Solves [ANDROSDK-546](https://jira.dhis2.org/browse/ANDROSDK-546).
> [ANDROSDK-546] Move programIndicatorEngine methods from D2 to ProgramIndicatorEngine

- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceCallMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentHandler.java
- core/src/sharedTest/resources/trackedentity/tracked_entity_instances.json
- core/src/test/java/org/hisp/dhis/android/core/enrollment/EnrollmentHandlerShould.java
Solves [ANDROSDK-527B](https://jira.dhis2.org/browse/ANDROSDK-527).
> [ANDROSDK-527B] Add state sync in events inside enrollments

- core/src/androidTest/java/org/hisp/dhis/android/core/arch/repositories/collection/IdentifiableCollectionFiltersMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/arch/db/WhereClauseBuilder.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadOnlyIdentifiableCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadOnlyIdentifiableCollectionRepositoryImpl.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/BaseFilterConnector.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/DateFilterConnector.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/StringFilterConnector.java
- core/src/test/java/org/hisp/dhis/android/core/arch/repositories/scope/WhereClauseFromScopeBuilderShould.java
Solves [ANDROSDK-558](https://jira.dhis2.org/browse/ANDROSDK-558).
> [ANDROSDK-558] Implement date filters

- core/src/androidTest/java/org/hisp/dhis/android/core/common/D2Factory.java
- core/src/androidTest/java/org/hisp/dhis/android/core/configuration/ConfigurationStoreIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/configuration/ConfigurationStoreShould.java
- core/src/main/java/org/hisp/dhis/android/core/D2.java
- core/src/main/java/org/hisp/dhis/android/core/common/ObjectStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/configuration/Configuration.java
- core/src/main/java/org/hisp/dhis/android/core/configuration/ConfigurationHelper.java
- core/src/main/java/org/hisp/dhis/android/core/configuration/ConfigurationManager.java
- core/src/main/java/org/hisp/dhis/android/core/configuration/ConfigurationManagerFactory.java
- core/src/main/java/org/hisp/dhis/android/core/configuration/ConfigurationManagerImpl.java
- core/src/main/java/org/hisp/dhis/android/core/configuration/ConfigurationModel.java
- core/src/main/java/org/hisp/dhis/android/core/configuration/ConfigurationStore.java
- core/src/main/java/org/hisp/dhis/android/core/configuration/ConfigurationStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/configuration/ConfigurationTableInfo.java
- core/src/sharedTest/java/org/hisp/dhis/android/core/data/configuration/ConfigurationSamples.java
- core/src/test/java/org/hisp/dhis/android/core/D2Tests.java
- core/src/test/java/org/hisp/dhis/android/core/configuration/ConfigurationManagerShould.java
- core/src/test/java/org/hisp/dhis/android/core/configuration/ConfigurationShould.java
Solves [ANDROSDK-554](https://jira.dhis2.org/browse/ANDROSDK-554).
> [ANDROSDK-554] Unify Configuration

- core/src/androidTest/java/org/hisp/dhis/android/core/arch/repositories/collection/IdentifiableCollectionFiltersMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/arch/repositories/collection/NameableCollectionFiltersMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/CollectionRepositoryFactory.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadOnlyCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadOnlyCollectionRepositoryImpl.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadOnlyIdentifiableCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadOnlyIdentifiableCollectionRepositoryImpl.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadOnlyNameableCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadOnlyNameableCollectionRepositoryImpl.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadOnlyWithUidCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadOnlyWithUidCollectionRepositoryImpl.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadOnlyWithUploadWithUidCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/BaseFilterConnector.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/DateFilterConnector.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/FilterConnectorFactory.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/IdentifiableFilters.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/NameableFilters.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/StringFilterConnector.java
- core/src/main/java/org/hisp/dhis/android/core/category/CategoryModule.java
- core/src/main/java/org/hisp/dhis/android/core/category/CategoryOptionEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentModule.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventModule.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityModule.java
- core/src/sharedTest/resources/category/categories.json
Solves [ANDROSDK-566](https://jira.dhis2.org/browse/ANDROSDK-566).
> [ANDROSDK-566] Implement nameable filters

- core/src/main/java/org/hisp/dhis/android/core/domain/aggregated/data/AggregatedDataCall.java
Solves [ANDROSDK-548](https://jira.dhis2.org/browse/ANDROSDK-548).
> [ANDROSDK-548] Add foreign key cleaner to aggregated data call

- core/src/androidTest/java/org/hisp/dhis/android/core/arch/repositories/collection/IdentifiableCollectionFiltersMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadOnlyWithUidCollectionRepositoryImpl.java
- core/src/main/java/org/hisp/dhis/android/core/category/CategoryComboCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/category/CategoryComboEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/category/CategoryModule.java
Solves [ANDROSDK-560](https://jira.dhis2.org/browse/ANDROSDK-560).
IsDefault filter will be implemented as part of https://jira.dhis2.org/browse/ANDROSDK-559
> [ANDROSDK-560] Implement specific CategoryComboCollectionRepository

- core/src/androidTest/java/org/hisp/dhis/android/core/arch/repositories/collection/IdentifiableCollectionFiltersMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/category/CategoryComboCollectionRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadOnlyWithUidCollectionRepositoryImpl.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/BooleanFilterConnector.java
- core/src/main/java/org/hisp/dhis/android/core/category/CategoryComboCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/category/CategoryComboEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/category/CategoryModule.java
Solves  [ANDROSDK-559](https://jira.dhis2.org/browse/ANDROSDK-559).
>  [ANDROSDK-559] Implement boolean filter, apply to CategoryCombo isDefault

- core/src/androidTest/java/org/hisp/dhis/android/core/category/CategoryCollectionRepositoryMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/category/CategoryOptionComboCollectionRepositoryMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/category/CategoryOptionRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/category/CategoryCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/category/CategoryComboCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/category/CategoryOptionCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/category/CategoryOptionComboCollectionRepository.java
- core/src/sharedTest/resources/category/categories.json
Solves [ANDROSDK-575](https://jira.dhis2.org/browse/ANDROSDK-575).
> [ANDROSDK-575] Implement Category module filters

- core/src/androidTest/java/org/hisp/dhis/android/core/dataelement/DataElementCollectionRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/EnumFilterConnector.java
- core/src/main/java/org/hisp/dhis/android/core/dataelement/DataElementCollectionRepository.java
- core/src/sharedTest/resources/dataelement/data_elements.json
Solves [ANDROSDK-577](https://jira.dhis2.org/browse/ANDROSDK-577).
> [ANDROSDK-577] Implement DataElement filters

- core/src/main/java/org/hisp/dhis/android/core/D2DIComponent.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadOnlyCollectionRepositoryImpl.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadOnlyIdentifiableCollectionRepositoryImpl.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadOnlyWithUidCollectionRepositoryImpl.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/scope/RepositoryScopeDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetCompleteRegistrationCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetCompleteRegistrationEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/datavalue/DataValueCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/datavalue/DataValueEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/datavalue/DataValueModule.java
- core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentModule.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventModule.java
- core/src/main/java/org/hisp/dhis/android/core/maintenance/ForeignKeyViolationCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/maintenance/ForeignKeyViolationEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/maintenance/MaintenanceModule.java
- core/src/main/java/org/hisp/dhis/android/core/maintenance/MaintenancePackageDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipCollectionRepositoryImpl.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityModule.java
Solves [ANDROSDK-591](https://jira.dhis2.org/browse/ANDROSDK-591).
>  [ANDROSDK-591] Enable filters in non identifiable collection repositories

- core/src/androidTest/java/org/hisp/dhis/android/core/program/ProgramEndpointCallMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/D2DIComponent.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventHandler.java
- core/src/main/java/org/hisp/dhis/android/core/legendset/LegendEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/legendset/LegendPackageDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/legendset/LegendSetEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/legendset/LegendSetHandler.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramHandler.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramIndicatorHandler.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramIndicatorLegendSetEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramPackageDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramRuleActionEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramRuleEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramRuleHandler.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramRuleVariableEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramSectionAttributeEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramSectionEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramSectionHandler.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageDataElementEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageDataElementHandler.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageHandler.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageSectionDataElementEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageSectionEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageSectionHandler.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageSectionProgramIndicatorEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramTrackedEntityAttributeEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramTrackedEntityAttributeHandler.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeEntityDIModule.java
- core/src/test/java/org/hisp/dhis/android/core/program/ProgramHandlerShould.java
Solves [ANDROSDK-597](https://jira.dhis2.org/browse/ANDROSDK-597).
>  [ANDROSDK-597] Improve Program Package DI

- core/src/androidTest/java/org/hisp/dhis/android/core/dataset/DataSetEndpointCallRealIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/D2DIComponent.java
- core/src/main/java/org/hisp/dhis/android/core/dataelement/DataElementOperandEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/dataelement/DataElementPackageDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataInputPeriodEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetCompulsoryDataElementOperandEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetElementEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetHandler.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetPackageDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/SectionDataElementEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/SectionEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/SectionGreyedFieldsEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/SectionHandler.java
- core/src/main/java/org/hisp/dhis/android/core/indicator/DataSetIndicatorEntityDIModule.java
Solves [ANDROSDK-602](https://jira.dhis2.org/browse/ANDROSDK-602).
>  [ANDROSDK-602] Improve DataSet package DI

- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueManagerRealIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitProgramLinkStore.java
[ANDROSDK-468](https://jira.dhis2.org/browse/ANDROSDK-468)
> [ANDROSDK-468] Fix TrackedEntityAttributeReservedValueManager android tests

- core/src/androidTest/java/org/hisp/dhis/android/core/relationship/RelationshipStoreIntegrationShould.java
- core/src/main/assets/migrations/37.yaml
- core/src/main/java/org/hisp/dhis/android/core/common/StoreFactory.java
- core/src/main/java/org/hisp/dhis/android/core/data/database/DbOpenHelper.java
- core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipModel.java
- core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipModuleWiper.java
- core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipStore.java
- core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipTableInfo.java
- core/src/sharedTest/java/org/hisp/dhis/android/core/data/relationship/RelationshipSamples.java
Solves [ANDROSDK-605](https://jira.dhis2.org/browse/ANDROSDK-605).
> [ANDROSDK-605] Unify Relationship

- core/src/main/java/org/hisp/dhis/android/core/systeminfo/DHISVersion.java
Solves [ANDROSDK-607](https://jira.dhis2.org/browse/ANDROSDK-607).
Metadata sync tested against: 
- https://play.dhis2.org/android-current/api/
- https://play.dhis2.org/2.31.0/api/
- https://play.dhis2.org/2.31.1/api/
> [ANDROSDK-607] Review 2.31 coding for version manager

- core/src/androidTest/java/org/hisp/dhis/android/core/arch/repositories/collection/CollectionRepositoryOneMethodMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/arch/repositories/collection/IdentifiableCollectionFiltersMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/data/database/ObjectStoreAbstractIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceCallMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancePostCallRealIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadOnlyCollectionRepositoryImpl.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/object/ReadOnlyOneObjectRepositoryImpl.java
- core/src/main/java/org/hisp/dhis/android/core/category/CategoryOptionComboStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/common/ObjectStore.java
- core/src/main/java/org/hisp/dhis/android/core/common/ObjectStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetCompleteRegistrationStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/datavalue/DataValueStore.java
- core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentImportHandler.java
- core/src/main/java/org/hisp/dhis/android/core/enrollment/note/NoteUniquenessManager.java
- core/src/main/java/org/hisp/dhis/android/core/resource/ResourceStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeValueStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityDataValueStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancePostCall.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceStoreImpl.java
Solves [ANDROSDK-576](https://jira.dhis2.org/browse/ANDROSDK-576).
> [ANDROSDK-576] Implement the one() method in collection repositories

- core/src/androidTest/java/org/hisp/dhis/android/core/data/database/MockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/dataset/DataSetCompleteRegistrationCollectionRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetCompleteRegistrationCollectionRepository.java
- core/src/sharedTest/java/org/hisp/dhis/android/core/data/server/Dhis2MockServer.java
- core/src/sharedTest/resources/dataset/data_set_complete_registrations.json
- core/src/sharedTest/resources/dataset/data_sets.json
- core/src/sharedTest/resources/datavalue/data_values.json
[ANDROSDK-586](https://jira.dhis2.org/browse/ANDROSDK-586)
> [ANDROSDK-586] Implement DataSetCompleteRegistration filters

- core/src/androidTest/java/org/hisp/dhis/android/core/datavalue/DataValueCollectionRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/datavalue/DataValueCollectionRepository.java
- core/src/sharedTest/resources/datavalue/data_values.json
[ANDROSDK-585](https://jira.dhis2.org/browse/ANDROSDK-585)
> [ANDROSDK-585] Implement DataValue filters

- core/src/androidTest/java/org/hisp/dhis/android/core/dataset/SectionCollectionRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/SectionCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/SectionEntityDIModule.java
- core/src/sharedTest/resources/dataset/data_sets.json
Solves [ANDROSDK-611](https://jira.dhis2.org/browse/ANDROSDK-611). Solves [ANDROSDK-614](https://jira.dhis2.org/browse/ANDROSDK-614).
> [ANDROSDK-611] [ANDROSDK-614] Add section repository with filters

- core/src/androidTest/java/org/hisp/dhis/android/core/dataset/SectionCollectionRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/dataelement/DataElementStore.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetModuleWiper.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/Section.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/SectionDataElementChildrenAppender.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/SectionDataElementEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/SectionDataElementLinkModelBuilder.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/SectionDataElementLinkTableInfo.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/SectionEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/SectionGreyedFieldsChildrenAppender.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/SectionGreyedFieldsLinkStore.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/SectionGreyedFieldsLinkTableInfo.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/SectionHandler.java
- core/src/sharedTest/resources/dataset/data_sets.json
- core/src/test/java/org/hisp/dhis/android/core/dataset/SectionDataElementLinkModelBuilderShould.java
- core/src/test/java/org/hisp/dhis/android/core/dataset/SectionHandlerShould.java
Solves [ANDROSDK-613](https://jira.dhis2.org/browse/ANDROSDK-613).
> [ANDROSDK-613] Create Section children appenders

- core/src/androidTest/java/org/hisp/dhis/android/core/period/PeriodStoreIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/domain/aggregated/data/AggregatedDataCall.java
- core/src/main/java/org/hisp/dhis/android/core/period/AbstractPeriodGenerator.java
- core/src/main/java/org/hisp/dhis/android/core/period/ParentPeriodGenerator.java
- core/src/main/java/org/hisp/dhis/android/core/period/ParentPeriodGeneratorImpl.java
- core/src/main/java/org/hisp/dhis/android/core/period/Period.java
- core/src/main/java/org/hisp/dhis/android/core/period/PeriodEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/period/PeriodGenerator.java
- core/src/main/java/org/hisp/dhis/android/core/period/PeriodHandler.java
- core/src/main/java/org/hisp/dhis/android/core/period/PeriodModel.java
- core/src/main/java/org/hisp/dhis/android/core/period/PeriodModuleWiper.java
- core/src/main/java/org/hisp/dhis/android/core/period/PeriodStore.java
- core/src/main/java/org/hisp/dhis/android/core/period/PeriodTableInfo.java
- core/src/sharedTest/java/org/hisp/dhis/android/core/data/period/PeriodSamples.java
- core/src/test/java/org/hisp/dhis/android/core/period/AbstractPeriodGeneratorShould.java
- core/src/test/java/org/hisp/dhis/android/core/period/BiWeeklyPeriodGeneratorShould.java
- core/src/test/java/org/hisp/dhis/android/core/period/DailyPeriodGeneratorShould.java
- core/src/test/java/org/hisp/dhis/android/core/period/FinancialOctPeriodGeneratorShould.java
- core/src/test/java/org/hisp/dhis/android/core/period/MonthlyPeriodGeneratorShould.java
- core/src/test/java/org/hisp/dhis/android/core/period/ParentPeriodGeneratorImplShould.java
- core/src/test/java/org/hisp/dhis/android/core/period/PeriodGeneratorBaseShould.java
- core/src/test/java/org/hisp/dhis/android/core/period/PeriodHandlerShould.java
- core/src/test/java/org/hisp/dhis/android/core/period/QuarterPeriodGeneratorShould.java
- core/src/test/java/org/hisp/dhis/android/core/period/SixMonthlyPeriodGeneratorShould.java
- core/src/test/java/org/hisp/dhis/android/core/period/WeeklyPeriodGeneratorShould.java
Solves [ANDROSDK-617](https://jira.dhis2.org/browse/ANDROSDK-617).
> [ANDROSDK-617] Unify Period

- core/src/androidTest/java/org/hisp/dhis/android/core/maintenance/ForeignKeyCleanerShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/user/UserObjectRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/object/ReadOnlyFirstObjectRepositoryImpl.java
- core/src/main/java/org/hisp/dhis/android/core/user/User.java
- core/src/main/java/org/hisp/dhis/android/core/user/UserCredentialsChildrenAppender.java
- core/src/main/java/org/hisp/dhis/android/core/user/UserCredentialsStore.java
- core/src/main/java/org/hisp/dhis/android/core/user/UserCredentialsStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/user/UserEntityDIModule.java
Solves [ANDROSDK-618](https://jira.dhis2.org/browse/ANDROSDK-618).
> [ANDROSDK-618] Add UserCredentialsChildrenAppender

- core/src/androidTest/java/org/hisp/dhis/android/core/user/UserCredentialsObjectRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/user/UserRoleChildrenAppender.java
Solves [ANDROSDK-619](https://jira.dhis2.org/browse/ANDROSDK-619).
> [ANDROSDK-619] Add UserRoleChildrenAppender

- core/src/main/java/org/hisp/dhis/android/core/common/StoreFactory.java
Solves [ANDROSDK-621](https://jira.dhis2.org/browse/ANDROSDK-621).
> [ANDROSDK-621] Remove old method for objectWithoutUidStore creation

- core/src/androidTest/java/org/hisp/dhis/android/core/user/UserObjectRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/arch/db/stores/LinkModelChildStore.java
- core/src/main/java/org/hisp/dhis/android/core/arch/db/stores/LinkModelChildStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/common/SQLStatementBuilder.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitStore.java
- core/src/main/java/org/hisp/dhis/android/core/user/UserEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/user/UserOrganisationUnitChildrenAppender.java
- core/src/main/java/org/hisp/dhis/android/core/user/UserOrganisationUnitLinkTableInfo.java
- core/src/test/java/org/hisp/dhis/android/core/common/SQLStatementBuilderShould.java
Solves [ANDROSDK-622](https://jira.dhis2.org/browse/ANDROSDK-622).
> [ANDROSDK-622] Add UserOrganisationUnitChildrenAppender

- core/src/androidTest/java/org/hisp/dhis/android/core/indicator/DataSetIndicatorLinkStoreIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetHandler.java
- core/src/main/java/org/hisp/dhis/android/core/indicator/DataSetIndicatorEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/indicator/DataSetIndicatorLink.java
- core/src/main/java/org/hisp/dhis/android/core/indicator/DataSetIndicatorLinkModel.java
- core/src/main/java/org/hisp/dhis/android/core/indicator/DataSetIndicatorLinkStore.java
- core/src/main/java/org/hisp/dhis/android/core/indicator/DataSetIndicatorLinkTableInfo.java
- core/src/main/java/org/hisp/dhis/android/core/indicator/IndicatorModuleWiper.java
- core/src/sharedTest/java/org/hisp/dhis/android/core/data/indicator/DataSetIndicatorLinkSamples.java
- core/src/test/java/org/hisp/dhis/android/core/dataset/DataSetHandlerShould.java
Solves [ANDROSDK-620](https://jira.dhis2.org/browse/ANDROSDK-620).
> [ANDROSDK-620] Unify DataSetIndicatorLink

- core/src/androidTest/java/org/hisp/dhis/android/core/data/database/MockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/event/EventCollectionRepositoryMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/event/EventModuleMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventCollectionRepository.java
- core/src/sharedTest/resources/event/events.json
[ANDROSDK-588](https://jira.dhis2.org/browse/ANDROSDK-588)
> [ANDROSDK-588] Implement Event filters

- core/src/androidTest/java/org/hisp/dhis/android/core/legendset/LegendSetStoreIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/legendset/LegendStoreIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/legendset/ProgramIndicatorLegendSetLinkStoreIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/legendset/LegendSetModuleWiper.java
- core/src/main/java/org/hisp/dhis/android/core/legendset/ProgramIndicatorLegendSetLink.java
- core/src/main/java/org/hisp/dhis/android/core/legendset/ProgramIndicatorLegendSetLinkModel.java
- core/src/main/java/org/hisp/dhis/android/core/legendset/ProgramIndicatorLegendSetLinkStore.java
- core/src/main/java/org/hisp/dhis/android/core/legendset/ProgramIndicatorLegendSetLinkTableInfo.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramIndicatorHandler.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramIndicatorLegendSetEntityDIModule.java
- core/src/sharedTest/java/org/hisp/dhis/android/core/data/legendset/LegendSamples.java
- core/src/sharedTest/java/org/hisp/dhis/android/core/data/legendset/LegendSetSamples.java
- core/src/sharedTest/java/org/hisp/dhis/android/core/data/legendset/ProgramIndicatorLegendSetLinkSamples.java
- core/src/test/java/org/hisp/dhis/android/core/program/ProgramIndicatorHandlerShould.java
Solves [ANDROSDK-624](https://jira.dhis2.org/browse/ANDROSDK-624).
> [ANDROSDK-624] Unify ProgramIndicatorLegendSetLink

- core/src/androidTest/java/org/hisp/dhis/android/core/event/EventCallFactory.java
- core/src/androidTest/java/org/hisp/dhis/android/core/event/EventPostCallRealIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventEndpointCallFactory.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventQuery.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventService.java
Solves [ANDROSDK-616](https://jira.dhis2.org/browse/ANDROSDK-616)
> [ANDROSDK-616] Remove event get call by categoryCombo

- core/src/main/java/org/hisp/dhis/android/core/category/CategoryComboHandler.java
- core/src/main/java/org/hisp/dhis/android/core/category/CategoryOptionComboCategoryOptionLinkModelBuilder.java
- core/src/main/java/org/hisp/dhis/android/core/common/ModelBuilder.java
- core/src/main/java/org/hisp/dhis/android/core/common/ObjectStyleModelBuilder.java
- core/src/main/java/org/hisp/dhis/android/core/common/ValueTypeRenderingHandler.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetCompulsoryDataElementOperandLinkModelBuilder.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetHandler.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetOrganisationUnitLinkModelBuilder.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/SectionGreyedFieldsLinkModelBuilder.java
- core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentHandler.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventHandler.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventPersistenceCallFactory.java
- core/src/main/java/org/hisp/dhis/android/core/legendset/LegendSetHandler.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitDisplayPathTransformer.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitOrganisationUnitGroupLinkModelBuilder.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitProgramLinkModelBuilder.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramSectionAttributeLinkModelBuilder.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageHandler.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageSectionProgramIndicatorLinkModelBuilder.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueModelBuilder.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceHandler.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceModelBuilder.java
- core/src/main/java/org/hisp/dhis/android/core/user/UserModelBuilder.java
- core/src/main/java/org/hisp/dhis/android/core/user/UserOrganisationUnitLinkModelBuilder.java
Solves [ANDROSDK-629](https://jira.dhis2.org/browse/ANDROSDK-629).
> [ANDROSDK-629] Make ModelBuilder a functional interface so instances can be lambda

- core/src/main/java/org/hisp/dhis/android/core/dataelement/DataElement.java
- core/src/main/java/org/hisp/dhis/android/core/dataelement/DataElementFields.java
- core/src/main/java/org/hisp/dhis/android/core/dataelement/DataElementHandler.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageDataElement.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageDataElementFields.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageDataElementHandler.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramTrackedEntityAttribute.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramTrackedEntityAttributeFields.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramTrackedEntityAttributeHandler.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttribute.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeFields.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeHandler.java
- core/src/sharedTest/resources/dataelement/data_element.json
- core/src/sharedTest/resources/program/program_stage_data_element.json
- core/src/sharedTest/resources/program/program_tracked_entity_attribute.json
- core/src/test/java/org/hisp/dhis/android/core/dataelement/DataElementShould.java
- core/src/test/java/org/hisp/dhis/android/core/program/ProgramStageDataElementHandlerShould.java
- core/src/test/java/org/hisp/dhis/android/core/program/ProgramStageDataElementShould.java
- core/src/test/java/org/hisp/dhis/android/core/program/ProgramTrackedEntityAttributeHandlerShould.java
- core/src/test/java/org/hisp/dhis/android/core/program/ProgramTrackedEntityAttributeShould.java
- core/src/test/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeHandlerShould.java
Solves [ANDROSDK-626](https://jira.dhis2.org/browse/ANDROSDK-626)
> [ANDROSDK-626] Persist ValueTypeDeviceRendering

- core/src/androidTest/java/org/hisp/dhis/android/core/data/database/MockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/enrollment/EnrollmentModuleMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityModuleMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/testapp/event/EventCollectionRepositoryMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/testapp/trackedentity/TrackedEntityCollectionRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceCollectionRepository.java
- core/src/sharedTest/resources/trackedentity/tracked_entity_instances.json
[ANDROSDK-589](https://jira.dhis2.org/browse/ANDROSDK-589)
> [ANDROSDK-589] Implement TrackedEntityInstance filters

- core/src/androidTest/java/org/hisp/dhis/android/testapp/dataelement/DataElementCollectionRepositoryMockIntegrationShould.java
- core/src/main/assets/migrations/38.yaml
- core/src/main/java/org/hisp/dhis/android/core/data/database/DbOpenHelper.java
- core/src/main/java/org/hisp/dhis/android/core/dataelement/DataElement.java
- core/src/main/java/org/hisp/dhis/android/core/dataelement/DataElementCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/dataelement/DataElementFields.java
- core/src/main/java/org/hisp/dhis/android/core/dataelement/DataElementStore.java
- core/src/main/java/org/hisp/dhis/android/core/dataelement/DataElementTableInfo.java
[ANDROSDK-357](https://jira.dhis2.org/browse/ANDROSDK-357)
> [ANDROSDK-357] Remove deprecated fields in dataelement (numberType and dimension)

- core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramCollectionRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/data/database/IgnoreProgramStageListColumnAdapter.java
- core/src/main/java/org/hisp/dhis/android/core/program/Program.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramCategoryComboChildrenAppender.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramIndicatorChildrenAppender.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramIndicatorStore.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramModuleWiper.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramOrphanCleaner.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramParentUidsHelper.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramRuleChildrenAppender.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramRuleStore.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramRuleVariableChildrenAppender.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramRuleVariableStore.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramSectionChildrenAppender.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramSectionStore.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageChildrenAppender.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageStore.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramTrackedEntityAttributeChildrenAppender.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramTrackedEntityAttributeStore.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramTrackedEntityTypeChildrenAppender.java
- core/src/main/java/org/hisp/dhis/android/core/program/RelatedProgramChildrenAppender.java
- core/src/sharedTest/resources/program/programs.json
- core/src/test/java/org/hisp/dhis/android/core/payload/ProgramModelPayloadShould.java
- core/src/test/java/org/hisp/dhis/android/core/program/ProgramHandlerShould.java
- core/src/test/java/org/hisp/dhis/android/core/program/ProgramModuleDownloaderShould.java
Solves [ANDROSDK-636](https://jira.dhis2.org/browse/ANDROSDK-636).
> [ANDROSDK-636] Add program children appenders

- core/src/androidTest/java/org/hisp/dhis/android/core/user/AuthenticatedUserStoreIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/user/LogoutCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/user/UserAuthenticateCallMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/user/UserModuleMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/testapp/user/AuthenticatedUserPublicAccessShould.java
- core/src/main/java/org/hisp/dhis/android/core/data/api/BasicAuthenticator.java
- core/src/main/java/org/hisp/dhis/android/core/data/api/BasicAuthenticatorFactory.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventPersistenceCallFactory.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancePersistenceCallFactory.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceRelationshipPersistenceCallFactory.java
- core/src/main/java/org/hisp/dhis/android/core/user/AuthenticatedUser.java
- core/src/main/java/org/hisp/dhis/android/core/user/AuthenticatedUserEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/user/AuthenticatedUserModel.java
- core/src/main/java/org/hisp/dhis/android/core/user/AuthenticatedUserStore.java
- core/src/main/java/org/hisp/dhis/android/core/user/IsUserLoggedInCallable.java
- core/src/main/java/org/hisp/dhis/android/core/user/LogOutUserCallable.java
- core/src/main/java/org/hisp/dhis/android/core/user/UserAuthenticateCallFactory.java
- core/src/main/java/org/hisp/dhis/android/core/user/UserModule.java
- core/src/sharedTest/java/org/hisp/dhis/android/core/data/user/AuthenticatedUserSamples.java
- core/src/test/java/org/hisp/dhis/android/core/data/api/BasicAuthenticatorShould.java
- core/src/test/java/org/hisp/dhis/android/core/user/AuthenticatedUserShould.java
- core/src/test/java/org/hisp/dhis/android/core/user/IsUserLoggedInCallableShould.java
- core/src/test/java/org/hisp/dhis/android/core/user/LogOutUserCallableShould.java
- core/src/test/java/org/hisp/dhis/android/core/user/UserAuthenticateCallUnitShould.java
Solves [ANDROSDK-638](https://jira.dhis2.org/browse/ANDROSDK-638).
> [ANDROSDK-638] Unify AuthenticatedUser

- core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramIndicatorCollectionRepositoryMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramRuleActionCollectionRepositoryMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramRuleCollectionRepositoryMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramRuleVariableCollectionRepositoryMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramSectionCollectionRepositoryMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramStageCollectionRepositoryMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramStageSectionCollectionRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/data/database/ProgramStageSectionRenderingColumnAdapter.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramIndicatorCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramModule.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramRuleActionCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramRuleCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramRuleVariableCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramRuleVariableEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramSectionCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageSectionsCollectionRepository.java
- core/src/sharedTest/resources/program/program_stages.json
- Solves [ANDROSDK-635](https://jira.dhis2.org/browse/ANDROSDK-635).
- Fixes ProgramStageSectionRenderingColumnAdapter for null values.
> [ANDROSDK-635] Add program package repositories

- core/src/androidTest/java/org/hisp/dhis/android/core/relationship/RelationshipCollectionRepositoryMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/systeminfo/SystemInfoModuleMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipTableInfo.java
- core/src/sharedTest/java/org/hisp/dhis/android/core/data/systeminfo/SystemInfoSamples.java
- core/src/sharedTest/resources/systeminfo/system_info.json
- core/src/sharedTest/resources/trackedentity/tracked_entity_instances.json
[ANDROSDK-587](https://jira.dhis2.org/browse/ANDROSDK-587)
> [ANDROSDK-587] Implement Relationship filters

- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancePostCallMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/D2DIComponent.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancePostCall.java
Solves [ANDROSDK-654](https://jira.dhis2.org/browse/ANDROSDK-654)
> [ANDROSDK-654] Bugfix TEIPostCall; add test showing the bug

- core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramRuleCollectionRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramRuleActionChildrenAppender.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramRuleActionStore.java
Solves [ANDROSDK-656](https://jira.dhis2.org/browse/ANDROSDK-656).
> [ANDROSDK-656] Add ProgramRuleAction children appender

- core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramIndicatorCollectionRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/legendset/ProgramIndicatorLegendSetLinkTableInfo.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramIndicatorLegendSetChildrenAppender.java
- core/src/sharedTest/resources/program/programs.json
Solves [ANDROSDK-657](https://jira.dhis2.org/browse/ANDROSDK-657).
> [ANDROSDK-657] Add ProgramIndicatorLegendSet children appender

- core/src/androidTest/java/org/hisp/dhis/android/core/data/database/MockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramStageCollectionRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/data/database/ProgramStageSectionRenderingColumnAdapter.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageDataElementChildrenAppender.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageHandler.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageSection.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageSectionChildrenAppender.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageSectionRenderingHelper.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageSectionStore.java
- core/src/sharedTest/java/org/hisp/dhis/android/core/data/program/ProgramStageSectionSamples.java
- core/src/sharedTest/resources/program/program_stages.json
- core/src/test/java/org/hisp/dhis/android/core/program/ProgramStageHandlerShould.java
Solves [ANDROSDK-653](https://jira.dhis2.org/browse/ANDROSDK-653).
> [ANDROSDK-653] Add ProgramStage children appenders

- core/src/main/java/org/hisp/dhis/android/core/user/AuthorityCallFetcher.java
Solves [ANDROSDK-661](https://jira.dhis2.org/browse/ANDROSDK-661).
> [ANDROSDK-661] Save all the authorities

- core/src/androidTest/java/org/hisp/dhis/android/core/utils/services/ProgramIndicatorEngineIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventStore.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/utils/services/ProgramIndicatorEngine.java
- core/src/main/java/org/hisp/dhis/android/core/utils/support/ExpressionUtils.java
- core/src/test/java/org/hisp/dhis/android/core/utils/services/ProgramIndicatorEngineShould.java
- core/src/test/java/org/hisp/dhis/android/core/utils/support/ExpressionUtilsShould.java
Solves [ANDROSDK-608](https://jira.dhis2.org/browse/ANDROSDK-608)
Also add support for due_date, event_count and enrollment_status variables.
> [ANDROSDK-608] Return strings in ProgramIndicatorEngine

- core/src/androidTest/java/org/hisp/dhis/android/testapp/trackedentity/TrackedEntityCollectionRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/AppContextDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/imports/BaseImportSummaries.java
- core/src/main/java/org/hisp/dhis/android/core/imports/BaseImportSummary.java
- core/src/main/java/org/hisp/dhis/android/core/imports/EnrollmentImportSummaries.java
- core/src/main/java/org/hisp/dhis/android/core/imports/EnrollmentImportSummary.java
- core/src/main/java/org/hisp/dhis/android/core/imports/EventImportSummaries.java
- core/src/main/java/org/hisp/dhis/android/core/imports/EventImportSummary.java
- core/src/main/java/org/hisp/dhis/android/core/imports/ImportSummaries.java
- core/src/main/java/org/hisp/dhis/android/core/imports/ImportSummary.java
- core/src/main/java/org/hisp/dhis/android/core/imports/TEIImportSummaries.java
- core/src/main/java/org/hisp/dhis/android/core/imports/TEIImportSummary.java
- core/src/main/java/org/hisp/dhis/android/core/maintenance/ForeignKeyViolationCollectionRepository.java
- core/src/test/java/org/hisp/dhis/android/core/sms/InitTest.java
- core/src/test/java/org/hisp/dhis/android/core/sms/TestRepositories.java
[ANDROSDK-667](https://jira.dhis2.org/browse/ANDROSDK-667)
> [ANDROSDK-667] Add missing copyright notices to Java files

- core/src/androidTest/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitLevelStoreIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/testapp/organisationunit/OrganisationUnitLevelPublicAccessShould.java
- core/src/main/assets/migrations/41.yaml
- core/src/main/java/org/hisp/dhis/android/core/data/database/DbOpenHelper.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitLevel.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitLevelEndpointCallFactory.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitLevelEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitLevelFields.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitLevelService.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitLevelStore.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitLevelTableInfo.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitModuleDownloader.java
- core/src/sharedTest/java/org/hisp/dhis/android/core/data/organisationunit/OrganisationUnitLevelSamples.java
- core/src/sharedTest/java/org/hisp/dhis/android/core/data/server/Dhis2MockServer.java
- core/src/sharedTest/resources/organisationunit/organisation_unit_level.json
- core/src/sharedTest/resources/organisationunit/organisation_unit_levels.json
- core/src/test/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitLevelShould.java
Solves [ANDROSDK-639](https://jira.dhis2.org/browse/ANDROSDK-639).
> [ANDROSDK-639] Download Hierarchy level name

- core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramCollectionRepositoryMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramIndicatorCollectionRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramIndicatorCollectionRepository.java
- core/src/sharedTest/resources/program/programs.json
[ANDROSDK-645](https://jira.dhis2.org/browse/ANDROSDK-645)
> [ANDROSDK-645] Implement ProgramIndicator filters

- core/src/main/assets/migrations/42.yaml
- core/src/main/java/org/hisp/dhis/android/core/data/database/DbOpenHelper.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttribute.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeFields.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeHandler.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeModel.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeStore.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeTableInfo.java
- core/src/sharedTest/java/org/hisp/dhis/android/core/data/trackedentity/TrackedEntityAttributeSamples.java
- core/src/test/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeHandlerShould.java
Solves [ANDROSDK-662](https://jira.dhis2.org/browse/ANDROSDK-662).
> [ANDROSDK-662] Add formName property to TrackedEntityAttribute

- core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramCollectionRepositoryMockIntegrationShould.java
- core/src/main/assets/migrations/42.yaml
- core/src/main/java/org/hisp/dhis/android/core/data/database/DbOpenHelper.java
- core/src/main/java/org/hisp/dhis/android/core/program/Program.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramDHISVersionManager.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramFields.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramHandler.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStore.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramTableInfo.java
- core/src/test/java/org/hisp/dhis/android/core/program/ProgramHandlerShould.java
Solves [ANDROSDK-665](https://jira.dhis2.org/browse/ANDROSDK-665).
> [ANDROSDK-665] Add featureType to Program

- core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramRuleCollectionRepositoryMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramRuleVariableCollectionRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramRuleVariableCollectionRepository.java
- core/src/sharedTest/resources/program/programs.json
[ANDROSDK-648](https://jira.dhis2.org/browse/ANDROSDK-648)
> [ANDROSDK-648] Implement ProgramRuleVariable filters

- core/src/androidTest/java/org/hisp/dhis/android/core/event/EventPostCallMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancePostCallMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventPostCall.java
- core/src/main/java/org/hisp/dhis/android/core/imports/EventWebResponse.java
- core/src/main/java/org/hisp/dhis/android/core/imports/TEIWebResponse.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancePostCall.java
Solves [ANDROSDK-676](https://jira.dhis2.org/browse/ANDROSDK-676)
> [ANDROSDK-676] Return non-empty response

- core/src/main/java/org/hisp/dhis/android/core/calls/MetadataCall.java
- core/src/main/java/org/hisp/dhis/android/core/constant/Constant.java
- core/src/main/java/org/hisp/dhis/android/core/constant/ConstantCallFactory.java
- core/src/main/java/org/hisp/dhis/android/core/constant/ConstantFields.java
- core/src/main/java/org/hisp/dhis/android/core/constant/ConstantHandler.java
- core/src/main/java/org/hisp/dhis/android/core/constant/ConstantModuleDownloader.java
- core/src/main/java/org/hisp/dhis/android/core/constant/ConstantModuleWiper.java
- core/src/main/java/org/hisp/dhis/android/core/constant/ConstantService.java
- core/src/main/java/org/hisp/dhis/android/core/constant/ConstantTableInfo.java
- core/src/main/java/org/hisp/dhis/android/core/wipe/D2ModuleWipers.java
- core/src/sharedTest/java/org/hisp/dhis/android/core/data/server/Dhis2MockServer.java
- core/src/sharedTest/resources/constant/constants.json
- core/src/test/java/org/hisp/dhis/android/core/common/MetadataCallShould.java
Solves [ANDROSDK-599](https://jira.dhis2.org/browse/ANDROSDK-599)
> [ANDROSDK-599] Persist constants

- core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramCollectionRepositoryMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramIndicatorCollectionRepositoryMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramStageSectionCollectionRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramModuleWiper.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageSectionDataElementChildrenAppender.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageSectionDataElementLinkTableInfo.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageSectionEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageSectionProgramIndicatorChildrenAppender.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageSectionProgramIndicatorLinkTableInfo.java
- core/src/sharedTest/resources/program/program_stages.json
Solves [ANDROSDK-658](https://jira.dhis2.org/browse/ANDROSDK-658).
> [ANDROSDK-658] Add ProgramStageSection children appenders

- core/src/androidTest/java/org/hisp/dhis/android/testapp/event/EventCollectionRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityDataValueChildrenAppender.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityDataValueStoreImpl.java
Solves [ANDROSDK-670](https://jira.dhis2.org/browse/ANDROSDK-670).
> [ANDROSDK-670] Add Event children appenders

- core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramCollectionRepositoryMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramRuleActionCollectionRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramRuleActionCollectionRepository.java
- core/src/sharedTest/resources/program/program_rules.json
- core/src/sharedTest/resources/program/programs.json
[ANDROSDK-647](https://jira.dhis2.org/browse/ANDROSDK-647)
> [ANDROSDK-647] Implement ProgramRuleAction filters

- build.gradle
- core/src/main/java/org/hisp/dhis/android/core/common/LinkModelStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/common/ObjectStore.java
- core/src/main/java/org/hisp/dhis/android/core/common/ObjectStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/enrollment/note/NoteUniquenessManager.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueStore.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeValueStoreImpl.java
- gradle.properties
Solves [ANDROSDK-678](https://jira.dhis2.org/browse/ANDROSDK-678).
> [HOT-BUG-FIXING] [ANDROSDK-678] Delete only own element notes

- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetDataElementLinkTableInfo.java
- core/src/main/java/org/hisp/dhis/android/core/wipe/TableWiper.java
Solves [ANDROSDK-689](https://jira.dhis2.org/browse/ANDROSDK-689).
> [ANDROSDK-689] Wipe all tables passing TableInfo classes

- core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramSectionCollectionRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramSectionCollectionRepository.java
[ANDROSDK-649](https://jira.dhis2.org/browse/ANDROSDK-649)
> [ANDROSDK-649] Implement ProgramSection filters

- core/src/androidTest/java/org/hisp/dhis/android/testapp/dataelement/DataElementCollectionRepositoryMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramCollectionRepositoryMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramIndicatorCollectionRepositoryMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramSectionCollectionRepositoryMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramStageCollectionRepositoryMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramStageSectionCollectionRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramSectionCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageTableInfo.java
- core/src/sharedTest/resources/program/program_stages.json
[ANDROSDK-650](https://jira.dhis2.org/browse/ANDROSDK-650)
> [ANDROSDK-650] Implement ProgramStage filters

- core/src/sharedTest/resources/dataset/data_set_complete_registrations.json
[ANDROSDK-697](https://jira.dhis2.org/browse/ANDROSDK-697)
> [ANDROSDK-697] Update DataSetCompleteRegistration sample data periods

- core/src/main/java/org/hisp/dhis/android/core/category/CategoryCategoryComboEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/category/CategoryCategoryOptionEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/category/CategoryComboHandler.java
- core/src/main/java/org/hisp/dhis/android/core/category/CategoryHandler.java
- core/src/main/java/org/hisp/dhis/android/core/common/OrderedLinkSyncHandler.java
- core/src/main/java/org/hisp/dhis/android/core/common/OrderedLinkSyncHandlerImpl.java
- core/src/main/java/org/hisp/dhis/android/core/common/OrderedLinkTransformer.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/SectionDataElementEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/SectionHandler.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageSectionDataElementEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageSectionHandler.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityTypeAttributeEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityTypeHandler.java
- core/src/sharedTest/resources/dataset/data_set_complete_registrations.json
- core/src/test/java/org/hisp/dhis/android/core/category/CategoryComboHandlerShould.java
- core/src/test/java/org/hisp/dhis/android/core/category/CategoryHandlerShould.java
- core/src/test/java/org/hisp/dhis/android/core/dataset/SectionHandlerShould.java
- core/src/test/java/org/hisp/dhis/android/core/program/ProgramStageSectionHandlerShould.java
Solves [ANDROSDK-698](https://jira.dhis2.org/browse/ANDROSDK-698).
> [ANDROSDK-698] Refactor OrderedLinks

- build.gradle
- core/src/androidTest/java/org/hisp/dhis/android/core/relationship/RelationshipCollectionRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipCollectionRepository.java
- gradle.properties
Solves [ANDROSDK-700](https://jira.dhis2.org/browse/ANDROSDK-700).
> Release 0.14.5

- core/src/androidTest/java/org/hisp/dhis/android/core/arch/repositories/collection/EqualityFiltersMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/BooleanFilterConnector.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/DateFilterConnector.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/EnumFilterConnector.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/IntegerFilterConnector.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/StringFilterConnector.java
- core/src/sharedTest/resources/program/program_stages.json
Solves [ANDROSDK-693](https://jira.dhis2.org/browse/ANDROSDK-693).
> [ANDROSDK-693] Add ne filter for all types

- core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramStageSectionCollectionRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageSectionTableInfo.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageSectionsCollectionRepository.java
- core/src/sharedTest/resources/program/program_stages.json
[ANDROSDK-651](https://jira.dhis2.org/browse/ANDROSDK-651)
> [ANDROSDK-651] Implement ProgramStage filters

- build.gradle
- core/src/androidTest/java/org/hisp/dhis/android/core/relationship/RelationshipCollectionRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipCollectionRepository.java
- gradle.properties
Solves [ANDROSDK-700](https://jira.dhis2.org/browse/ANDROSDK-700).
> [ANDROSDK-700-BUGFIX] Fix relationship return by TEI

- core/src/androidTest/java/org/hisp/dhis/android/core/arch/repositories/collection/FiltersOperatorsMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/BaseFilterConnector.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/BooleanFilterConnector.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/DateFilterConnector.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/EnumFilterConnector.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/IntegerFilterConnector.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/StringFilterConnector.java
- core/src/main/java/org/hisp/dhis/android/core/utils/Utils.java
Solves [ANDROSDK-694](https://jira.dhis2.org/browse/ANDROSDK-694).
> [ANDROSDK-694] Add in filter in repositories

- core/src/main/assets/migrations/44.yaml
- core/src/main/java/org/hisp/dhis/android/core/data/database/DbOpenHelper.java
Solves [ANDROSDK-641](https://jira.dhis2.org/browse/ANDROSDK-641).
> [ANDROSDK-641] Add program foreign key to ProgramSection program column

- core/src/androidTest/java/org/hisp/dhis/android/core/period/PeriodMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/period/PeriodStoreIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/D2.java
- core/src/main/java/org/hisp/dhis/android/core/D2Modules.java
- core/src/main/java/org/hisp/dhis/android/core/arch/db/WhereClauseBuilder.java
- core/src/main/java/org/hisp/dhis/android/core/domain/aggregated/data/AggregatedDataCall.java
- core/src/main/java/org/hisp/dhis/android/core/period/PeriodEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/period/PeriodHandler.java
- core/src/main/java/org/hisp/dhis/android/core/period/PeriodHelper.java
- core/src/main/java/org/hisp/dhis/android/core/period/PeriodModule.java
- core/src/main/java/org/hisp/dhis/android/core/period/PeriodStore.java
- core/src/main/java/org/hisp/dhis/android/core/period/PeriodStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/systeminfo/DHISVersionManager.java
- core/src/main/java/org/hisp/dhis/android/core/systeminfo/SystemInfoPackageDIModule.java
- core/src/test/java/org/hisp/dhis/android/core/arch/db/WhereClauseBuilderShould.java
- core/src/test/java/org/hisp/dhis/android/core/period/PeriodHandlerShould.java
Solves [ANDROSDK-680](https://jira.dhis2.org/browse/ANDROSDK-680).
> [ANDROSDK-680] Add public method to get period from date and periodType

- build.gradle
- build.sh
- core/src/main/java/org/hisp/dhis/android/core/arch/handlers/SyncHandlerBaseImpl.java
- core/src/main/java/org/hisp/dhis/android/core/category/CategoryComboUidsSeeker.java
- core/src/main/java/org/hisp/dhis/android/core/common/IdentifiableObjectStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/common/SafeDateFormat.java
- core/src/main/java/org/hisp/dhis/android/core/configuration/ConfigurationManagerImpl.java
- core/src/main/java/org/hisp/dhis/android/core/data/database/SqliteCheckerUtility.java
- core/src/main/java/org/hisp/dhis/android/core/option/OptionGroupCallFactory.java
- core/src/main/java/org/hisp/dhis/android/core/option/OptionSetCallFactory.java
- core/src/main/java/org/hisp/dhis/android/core/sms/data/smsrepository/SendingStateReceiver.java
- core/src/main/java/org/hisp/dhis/android/core/utils/UserUtils.java
- core/src/main/java/org/hisp/dhis/android/core/utils/Utils.java
- core/src/main/java/org/hisp/dhis/android/core/utils/services/ProgramIndicatorEngine.java
- core/src/main/java/org/hisp/dhis/android/core/utils/support/math/ExpressionFunctions.java
- core/src/main/java/org/hisp/dhis/android/core/wipe/TableWiper.java
- plugins/android-checkstyle.gradle
- plugins/android-findbugs.gradle
- plugins/android-pmd.gradle
[ANDROSDK-707](https://jira.dhis2.org/browse/ANDROSDK-707)
> [ANDROSDK-707] Build checks not working with Gradle 5

- core/src/main/java/org/hisp/dhis/android/core/data/database/IgnoreTrackedEntityAttributeListColumnAdapter.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramSection.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramSectionAttributeChildrenAppender.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramSectionAttributeEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramSectionHandler.java
- core/src/test/java/org/hisp/dhis/android/core/program/ProgramSectionHandlerShould.java
Solves [ANDROSDK-664](https://jira.dhis2.org/browse/ANDROSDK-664).
> [ANDROSDK-664] ProgramSection with TrackedEntityAttributes

- core/src/main/java/org/hisp/dhis/android/core/D2.java
- core/src/main/java/org/hisp/dhis/android/core/period/PeriodHelper.java
Solves [ANDROSDK-709](https://jira.dhis2.org/browse/ANDROSDK-709).
> [ANDROSDK-709] Fix PMD warnings

- core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramCollectionRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/children/ChildrenAppenderExecutor.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadOnlyCollectionRepositoryImpl.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/FilterConnectorFactory.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/object/ReadOnlyObjectRepositoryImpl.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/scope/RepositoryScopeHelper.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramCollectionRepository.java
Solves [ANDROSDK-711](https://jira.dhis2.org/browse/ANDROSDK-711).
> [ANDROSDK-711] Implement children selection in program

- core/src/androidTest/java/org/hisp/dhis/android/core/enrollment/EnrollmentCollectionRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/DoubleFilterConnector.java
- core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentFields.java
- core/src/sharedTest/resources/trackedentity/tracked_entity_instances.json
Solves [ANDROSDK-717](https://jira.dhis2.org/browse/ANDROSDK-717).
> [ANDROSDK-717] Add enrollment filters

- core/src/androidTest/java/org/hisp/dhis/android/core/arch/repositories/collection/IdentifiableCollectionFiltersMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/arch/db/WhereClauseBuilder.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadOnlyCollectionRepositoryImpl.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/di/RepositoriesDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/BaseFilterConnector.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/DateFilterConnector.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/object/ReadOnlyOneObjectRepositoryImpl.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/scope/RepositoryScope.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/scope/RepositoryScopeComplexFilterItem.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/scope/RepositoryScopeHelper.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/scope/WhereClauseFromScopeBuilder.java
- core/src/main/java/org/hisp/dhis/android/core/period/DatePeriod.java
- core/src/main/java/org/hisp/dhis/android/core/period/InPeriodQueryHelper.java
- core/src/test/java/org/hisp/dhis/android/core/arch/db/WhereClauseBuilderShould.java
- core/src/test/java/org/hisp/dhis/android/core/arch/repositories/scope/WhereClauseFromScopeBuilderShould.java
- core/src/test/java/org/hisp/dhis/android/core/period/InPeriodQueryHelperShould.java
Solves [ANDROSDK-743](https://jira.dhis2.org/browse/ANDROSDK-743).
> [ANDROSDK-743] Add an inPeriod method as complex filters on DateFilterConnector

- core/src/androidTest/java/org/hisp/dhis/android/core/d2manager/D2ManagerRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/settings/SettingsModuleMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/D2.java
- core/src/main/java/org/hisp/dhis/android/core/D2Modules.java
- core/src/main/java/org/hisp/dhis/android/core/data/database/DbSystemSettingKeyColumnAdapter.java
- core/src/main/java/org/hisp/dhis/android/core/settings/SystemSetting.java
- core/src/main/java/org/hisp/dhis/android/core/settings/SystemSettingCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/settings/SystemSettingEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/settings/SystemSettingModule.java
- core/src/main/java/org/hisp/dhis/android/core/settings/SystemSettingsSplitter.java
- core/src/sharedTest/java/org/hisp/dhis/android/core/data/settings/SystemSettingSamples.java
- core/src/test/java/org/hisp/dhis/android/core/settings/SystemSettingSplitterShould.java
Solves [ANDROSDK-732](https://jira.dhis2.org/browse/ANDROSDK-732).
> [ANDROSDK-732] SystemSettings repository & filters

- core/src/androidTest/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadOnlyCollectionRepositoryImplIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/testapp/event/EventCollectionRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadOnlyCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadOnlyCollectionRepositoryImpl.java
- core/src/main/java/org/hisp/dhis/android/core/common/ObjectStore.java
- core/src/main/java/org/hisp/dhis/android/core/common/ObjectStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventStore.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventStoreImpl.java
Solves [ANDROSDK-750](https://jira.dhis2.org/browse/ANDROSDK-750) and [ANDROSDK-745](https://jira.dhis2.org/browse/ANDROSDK-745)
>  [ANDROSDK-745] Add count TEIs method in EventRepository

- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityDataValueCollectionRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityDataValueCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityDataValueEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityModule.java
- core/src/sharedTest/resources/event/events.json
Solves [ANDROSDK-738](https://jira.dhis2.org/browse/ANDROSDK-738).
> [ANDROSDK-738] Add TrackedEntityDataValue repository and filters

- core/src/androidTest/java/org/hisp/dhis/android/core/data/database/SyncedDatabaseMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/maintenance/MaintenanceMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/maintenance/D2ErrorCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/maintenance/D2ErrorEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/maintenance/D2ErrorTableInfo.java
- core/src/main/java/org/hisp/dhis/android/core/maintenance/MaintenanceModule.java
- core/src/main/java/org/hisp/dhis/android/core/maintenance/MaintenanceModuleWiper.java
Solves [ANDROSDK-722](https://jira.dhis2.org/browse/ANDROSDK-722).
> [ANDROSDK-722] Add D2ErrorCollectionRepository

- core/src/androidTest/java/org/hisp/dhis/android/testapp/organisationunit/OrganisationUnitCollectionRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/D2.java
- core/src/main/java/org/hisp/dhis/android/core/D2Modules.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitDataSetChildrenAppender.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitFields.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitModule.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitOrganisationUnitGroupProgramChildrenAppender.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitProgramChildrenAppender.java
- core/src/main/java/org/hisp/dhis/android/core/user/UserOrganisationUnitLinkTableInfo.java
- core/src/sharedTest/resources/organisationunit/organisation_units.json
Solves [ANDROSDK-726](https://jira.dhis2.org/browse/ANDROSDK-726).
> [ANDROSDK-726] Add OrganisationUnitCollectionRepository

- core/build.gradle
- core/src/androidTest/java/org/hisp/dhis/android/core/arch/repositories/collection/PagingMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/data/database/SyncedDatabaseMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/D2DIComponent.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadOnlyCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadOnlyCollectionRepositoryImpl.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/object/ReadOnlyOneObjectRepositoryImpl.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/paging/RepositoryDataSource.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/scope/RepositoryScope.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/scope/WhereClauseFromScopeBuilder.java
- core/src/main/java/org/hisp/dhis/android/core/common/ObjectStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/common/SQLStatementBuilder.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventCollectionRepository.java
Solves [ANDROSDK-749](https://jira.dhis2.org/browse/ANDROSDK-749).
> [ANDROSDK-749] Repository paging

- core/src/androidTest/java/org/hisp/dhis/android/core/resource/ResourceStoreIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/data/database/ResourceTypeColumnAdapter.java
- core/src/main/java/org/hisp/dhis/android/core/resource/Resource.java
- core/src/main/java/org/hisp/dhis/android/core/resource/ResourceHandler.java
- core/src/main/java/org/hisp/dhis/android/core/resource/ResourceModuleWiper.java
- core/src/main/java/org/hisp/dhis/android/core/resource/ResourceStore.java
- core/src/main/java/org/hisp/dhis/android/core/resource/ResourceStoreImpl.java
Solves [ANDROSDK-751](https://jira.dhis2.org/browse/ANDROSDK-751)
> [ANDROSDK-751] Wipe data resources on data wipe

- core/src/androidTest/java/org/hisp/dhis/android/core/period/PeriodStoreIntegrationShould.java
Solves [ANDROSDK-756](https://jira.dhis2.org/browse/ANDROSDK-756).
> [ANDROSDK-756] Fix PeriodStoreIntegrationShould

- core/src/androidTest/java/org/hisp/dhis/android/testapp/maintenance/D2ErrorCollectionRepositoryMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/testapp/maintenance/ForeignKeyViolationCollectionRepositoryMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/testapp/maintenance/MaintenanceMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/maintenance/ForeignKeyViolationCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/maintenance/ForeignKeyViolationTableInfo.java
Solves [ANDROSDK-723](https://jira.dhis2.org/browse/ANDROSDK-723).
> [ANDROSDK-723] Add ForeignKeyViolationCollectionRepository filters

- core/src/androidTest/java/org/hisp/dhis/android/testapp/constant/ConstantCollectionRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/D2.java
- core/src/main/java/org/hisp/dhis/android/core/D2Modules.java
- core/src/main/java/org/hisp/dhis/android/core/constant/ConstantCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/constant/ConstantModule.java
Solves [ANDROSDK-716](https://jira.dhis2.org/browse/ANDROSDK-716)
> [ANDROSDK-716] Add Constant repository

- core/src/androidTest/java/org/hisp/dhis/android/core/period/PeriodStoreIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeValueCollectionRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeValueCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeValueEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityModule.java
Solves [ANDROSDK-737](https://jira.dhis2.org/browse/ANDROSDK-737).
> [ANDROSDK-737] Add TrackedEntityAttributeValue repository and filters

- core/src/androidTest/java/org/hisp/dhis/android/testapp/option/OptionSetCollectionRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/D2.java
- core/src/main/java/org/hisp/dhis/android/core/D2Modules.java
- core/src/main/java/org/hisp/dhis/android/core/option/OptionModule.java
- core/src/main/java/org/hisp/dhis/android/core/option/OptionSetCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/option/OptionSetEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/option/OptionSetOptionChildrenAppender.java
- core/src/main/java/org/hisp/dhis/android/core/option/OptionStore.java
Solves [ANDROSDK-725](https://jira.dhis2.org/browse/ANDROSDK-725).
> [ANDROSDK-725] Add OptionSet repository and filters

- core/src/androidTest/java/org/hisp/dhis/android/testapp/user/AuthorityCollectionRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/user/AuthorityCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/user/AuthorityEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/user/UserModule.java
Solves [ANDROSDK-733](https://jira.dhis2.org/browse/ANDROSDK-733).
> [ANDROSDK-733] Add Authority repository

- core/src/androidTest/java/org/hisp/dhis/android/testapp/option/OptionGroupCollectionRepositoryMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/testapp/option/OptionSetCollectionRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/D2.java
- core/src/main/java/org/hisp/dhis/android/core/D2Modules.java
- core/src/main/java/org/hisp/dhis/android/core/arch/db/stores/ObjectWithUidChildStore.java
- core/src/main/java/org/hisp/dhis/android/core/arch/db/stores/ObjectWithUidChildStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/common/StoreFactory.java
- core/src/main/java/org/hisp/dhis/android/core/option/OptionGroup.java
- core/src/main/java/org/hisp/dhis/android/core/option/OptionGroupCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/option/OptionGroupFields.java
- core/src/main/java/org/hisp/dhis/android/core/option/OptionGroupHandler.java
- core/src/main/java/org/hisp/dhis/android/core/option/OptionGroupOptionChildrenAppender.java
- core/src/main/java/org/hisp/dhis/android/core/option/OptionGroupOptionEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/option/OptionGroupOptionLinkTableInfo.java
- core/src/main/java/org/hisp/dhis/android/core/option/OptionModule.java
- core/src/main/java/org/hisp/dhis/android/core/option/OptionSetCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/option/OptionSetEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/option/OptionSetOptionChildrenAppender.java
- core/src/main/java/org/hisp/dhis/android/core/option/OptionStore.java
- core/src/sharedTest/java/org/hisp/dhis/android/core/data/option/OptionGroupSamples.java
Solves [ANDROSDK-724](https://jira.dhis2.org/browse/ANDROSDK-724).
> [ANDROSDK-724] Add OptionGroup repository

- core/src/androidTest/java/org/hisp/dhis/android/testapp/category/CategoryOptionComboCollectionRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/category/CategoryOptionComboCollectionRepository.java
Solves [ANDROSDK-759](https://jira.dhis2.org/browse/ANDROSDK-759).
> [ANDROSDK-759] Add CategoryOptions as CategoryOptionCombo children

- core/src/androidTest/java/org/hisp/dhis/android/core/arch/repositories/collection/PagingMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/testapp/event/EventCollectionRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/D2DIComponent.java
- core/src/main/java/org/hisp/dhis/android/core/arch/db/OrderByClauseBuilder.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadOnlyCollectionRepositoryImpl.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadOnlyIdentifiableCollectionRepositoryImpl.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadOnlyNameableCollectionRepositoryImpl.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/di/RepositoriesDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/FilterConnectorFactory.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/object/ReadOnlyOneObjectRepositoryImpl.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/paging/RepositoryDataSource.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/paging/RepositoryPagingConfig.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/scope/RepositoryScope.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/scope/RepositoryScopeHelper.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/scope/RepositoryScopeOrderByItem.java
- core/src/main/java/org/hisp/dhis/android/core/common/ObjectStore.java
- core/src/main/java/org/hisp/dhis/android/core/common/ObjectStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/common/SQLStatementBuilder.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventCollectionRepository.java
- core/src/sharedTest/java/org/hisp/dhis/android/core/data/category/CategoryOptionSamples.java
- core/src/sharedTest/resources/category/categories.json
- core/src/sharedTest/resources/event/events.json
- core/src/sharedTest/resources/trackedentity/tracked_entity_instances.json
- core/src/test/java/org/hisp/dhis/android/core/arch/repositories/collection/RepositoryPagingShould.java
- core/src/test/java/org/hisp/dhis/android/core/arch/repositories/scope/WhereClauseFromScopeBuilderShould.java
- core/src/test/java/org/hisp/dhis/android/core/common/SQLStatementBuilderShould.java
Solves [ANDROSDK-754](https://jira.dhis2.org/browse/ANDROSDK-754).
> [ANDROSDK-754] Implement orderBy in repositories

- core/src/androidTest/java/org/hisp/dhis/android/testapp/indicator/IndicatorCollectionRepositoryMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/testapp/indicator/IndicatorTypeCollectionRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/D2.java
- core/src/main/java/org/hisp/dhis/android/core/D2Modules.java
- core/src/main/java/org/hisp/dhis/android/core/indicator/IndicatorCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/indicator/IndicatorModule.java
- core/src/main/java/org/hisp/dhis/android/core/indicator/IndicatorTypeCollectionRepository.java
- core/src/sharedTest/resources/indicators/indicators.json
Solves [ANDROSDK-718](https://jira.dhis2.org/browse/ANDROSDK-718) and [ANDROSDK-719](https://jira.dhis2.org/browse/ANDROSDK-719).
> [ANDROSDK-718] [ANDROSDK-719] Indicator and indicator type repositories 

- core/src/androidTest/java/org/hisp/dhis/android/testapp/indicator/IndicatorCollectionRepositoryMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/testapp/indicator/IndicatorTypeCollectionRepositoryMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/testapp/legendset/LegendSetCollectionRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/D2.java
- core/src/main/java/org/hisp/dhis/android/core/D2Modules.java
- core/src/main/java/org/hisp/dhis/android/core/indicator/IndicatorCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/indicator/IndicatorModule.java
- core/src/main/java/org/hisp/dhis/android/core/indicator/IndicatorTypeCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/legendset/LegendChildrenAppender.java
- core/src/main/java/org/hisp/dhis/android/core/legendset/LegendSetCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/legendset/LegendSetEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/legendset/LegendSetModule.java
- core/src/main/java/org/hisp/dhis/android/core/legendset/LegendStore.java
- core/src/sharedTest/resources/indicators/indicators.json
Solves [ANDROSDK-720](https://jira.dhis2.org/browse/ANDROSDK-720) and [ANDROSDK-721](https://jira.dhis2.org/browse/ANDROSDK-721).
> [ANDROSDK-720] [ANDROSDK-721] Legend set repo, children appenders and filters

- core/src/androidTest/java/org/hisp/dhis/android/testapp/dataset/DataSetCompleteRegistrationCollectionRepositoryMockIntegrationShould.java
- core/src/sharedTest/resources/dataset/data_set_complete_registrations.json
[ANDROSDK-761](https://jira.dhis2.org/browse/ANDROSDK-761)
> [ANDROSDK-761] Fix DataSetCompletion test data periods

- core/src/main/java/org/hisp/dhis/android/core/arch/db/OrderByClauseBuilder.java
Solves [ANDROSDK-766](https://jira.dhis2.org/browse/ANDROSDK-766).
> [ANDROSDK-766] Fix paging second page with orderBy date

- core/src/androidTest/java/org/hisp/dhis/android/core/arch/repositories/collection/CollectionRepositoryOneMethodMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/category/CategoryModuleMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/testapp/category/CategoryComboCollectionRepositoryMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/testapp/category/CategoryOptionComboCollectionRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/BaseFilterConnector.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/SubQueryFilterConnector.java
- core/src/main/java/org/hisp/dhis/android/core/category/CategoryOptionComboCollectionRepository.java
- core/src/sharedTest/resources/category/category_combos.json
Solves [ANDROSDK-760](https://jira.dhis2.org/browse/ANDROSDK-760).
> [ANDROSDK-760] Add byCategoryOptions filter on CategoryOptionCombo repository

- core/src/main/java/org/hisp/dhis/android/core/arch/handlers/SyncHandlerBaseImpl.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramHandler.java
- core/src/test/java/org/hisp/dhis/android/core/option/OptionSetHandlerShould.java
- core/src/test/java/org/hisp/dhis/android/core/program/ProgramHandlerShould.java
Solves [ANDROSDK-491](https://jira.dhis2.org/browse/ANDROSDK-491).
> [ANDROSDK-491] Check tracker programs have tracked entity type

- core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipObjectRepository.java
Solves [ANDROSDK-764](https://jira.dhis2.org/browse/ANDROSDK-764)
> [ANDROSDK-764] Append all children to relationship

- core/src/androidTest/java/org/hisp/dhis/android/testapp/user/UserCredentialsObjectRepositoryMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/testapp/user/UserObjectRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/object/ReadOnlyObjectRepositoryImpl.java
- core/src/main/java/org/hisp/dhis/android/core/user/UserCredentialsObjectRepository.java
- core/src/main/java/org/hisp/dhis/android/core/user/UserObjectRepository.java
Solves [ANDROSDK-763](https://jira.dhis2.org/browse/ANDROSDK-763).
> [ANDROSDK-763] Add children selection in User and UserCredentials

- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadOnlyCollectionRepositoryImpl.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/paging/RepositoryDataSource.java
- core/src/test/java/org/hisp/dhis/android/core/arch/repositories/collection/RepositoryPagingShould.java
Solves [ANDROSDK-767](https://jira.dhis2.org/browse/ANDROSDK-767).
> [ANDROSDK-767] Append children in paging

- core/src/main/java/org/hisp/dhis/android/core/enrollment/Enrollment.java
- core/src/sharedTest/resources/enrollment/enrollment.json
- core/src/test/java/org/hisp/dhis/android/core/enrollment/EnrollmentShould.java
Solves [ANDROSDK-765](https://jira.dhis2.org/browse/ANDROSDK-765).
> [ANDROSDK-765] Send enrollment coordinates to server

- core/src/androidTest/java/org/hisp/dhis/android/core/dataset/DataSetCompleteRegistrationPostCallRealIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/arch/api/executors/APICallExecutor.java
- core/src/main/java/org/hisp/dhis/android/core/arch/api/executors/APICallExecutorImpl.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetCompleteRegistrationImportHandler.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetCompleteRegistrationPostCall.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetCompleteRegistrationService.java
- core/src/main/java/org/hisp/dhis/android/core/imports/ImportCount.java
- core/src/test/java/org/hisp/dhis/android/core/dataset/DataSetCompleteRegistrationImportHandlerShould.java
Solves [ANDROSDK-769](https://jira.dhis2.org/browse/ANDROSDK-769).
> [ANDROSDK-769] DataSetCompleteRegistrations deletion

- core/src/androidTest/java/org/hisp/dhis/android/testapp/period/PeriodCollectionRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/period/PeriodCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/period/PeriodModule.java
Solves [ANDROSDK-774](https://jira.dhis2.org/browse/ANDROSDK-774).
> [ANDROSDK-774] Add PeriodCollectionRepository

- core/src/main/java/org/hisp/dhis/android/core/arch/db/OrderByClauseBuilder.java
- core/src/main/java/org/hisp/dhis/android/core/arch/db/WhereClauseBuilder.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/scope/WhereClauseFromScopeBuilder.java
- core/src/test/java/org/hisp/dhis/android/core/arch/db/WhereClauseBuilderShould.java
- core/src/test/java/org/hisp/dhis/android/core/arch/repositories/collection/RepositoryPagingShould.java
- core/src/test/java/org/hisp/dhis/android/core/arch/repositories/scope/WhereClauseFromScopeBuilderShould.java
Solves [ANDROSDK-773](https://jira.dhis2.org/browse/ANDROSDK-773)
>  [ANDROSDK-773] OrderByWhereClauseBuilder for paging

- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceCallMockIntegrationShould.java
- core/src/main/assets/migrations/48.yaml
- core/src/main/java/org/hisp/dhis/android/core/data/database/DbOpenHelper.java
Solves [ANDROSDK-775](https://jira.dhis2.org/browse/ANDROSDK-775)
> [ANDROSDK-775] Add unique constraint to TrackedEntityInstanceAttributeValue

- core/build.gradle
- core/src/androidTest/java/org/hisp/dhis/android/core/common/D2Factory.java
- core/src/main/java/org/hisp/dhis/android/core/arch/api/executors/APICallExecutorImpl.java
- core/src/main/java/org/hisp/dhis/android/core/arch/api/retrofit/PreventURLDecodeInterceptor.java
- core/src/main/java/org/hisp/dhis/android/core/d2manager/D2Manager.java
- core/src/main/java/org/hisp/dhis/android/core/d2manager/OkHttpClientFactory.java
- core/src/main/java/org/hisp/dhis/android/core/dataapproval/DataApprovalService.java
- core/src/main/java/org/hisp/dhis/android/core/dataelement/DataElementService.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetCompleteRegistrationService.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetService.java
- core/src/main/java/org/hisp/dhis/android/core/datavalue/DataValueService.java
- core/src/main/java/org/hisp/dhis/android/core/option/OptionGroupService.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramRuleService.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramService.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageService.java
- core/src/test/java/org/hisp/dhis/android/core/data/api/FieldsConverterShould.java
- core/src/test/java/org/hisp/dhis/android/core/data/api/FilterConverterShould.java
- core/src/test/java/org/hisp/dhis/android/core/data/api/RetrofitFactory.java
Solves [ANDROSDK-776](https://jira.dhis2.org/browse/ANDROSDK-776).
> [ANDROSDK-776] Upgrade Retrofit to latest version

- core/src/androidTest/java/org/hisp/dhis/android/core/option/OptionSetCallShould.java
- core/src/androidTest/java/org/hisp/dhis/android/testapp/option/OptionCollectionRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/option/Option.java
- core/src/main/java/org/hisp/dhis/android/core/option/OptionCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/option/OptionEntityDIModule.java
- core/src/sharedTest/resources/option/option_sets.json
Solves [ANDROSDK-777](https://jira.dhis2.org/browse/ANDROSDK-777)
> [ANDROSDK-777] Option collection repository

- core/build.gradle
- core/src/main/java/org/hisp/dhis/android/core/D2.java
- core/src/main/java/org/hisp/dhis/android/core/arch/api/executors/APICallExecutorImpl.java
- core/src/main/java/org/hisp/dhis/android/core/arch/api/executors/APIErrorMapper.java
- core/src/main/java/org/hisp/dhis/android/core/arch/api/executors/APIExecutorsDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/arch/api/executors/CallableObservableTransformer.java
- core/src/main/java/org/hisp/dhis/android/core/arch/api/executors/RxAPICallExecutor.java
- core/src/main/java/org/hisp/dhis/android/core/arch/api/executors/RxAPICallExecutorImpl.java
- core/src/main/java/org/hisp/dhis/android/core/systeminfo/SystemInfoCall.java
- core/src/main/java/org/hisp/dhis/android/core/systeminfo/SystemInfoObjectRepository.java
- core/src/main/java/org/hisp/dhis/android/core/systeminfo/SystemInfoService.java
- core/src/test/java/org/hisp/dhis/android/core/systeminfo/SystemInfoCallShould.java
Solves [ANDROSDK-779](https://jira.dhis2.org/browse/ANDROSDK-779).
> [ANDROSDK-779] Download and handle resource using RxJava

- core/src/androidTest/java/org/hisp/dhis/android/core/enrollment/EnrollmentCollectionRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentFields.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventChildrenAppender.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventStoreImpl.java
Solves [ANDROSDK-781](https://jira.dhis2.org/browse/ANDROSDK-781).
> [ANDROSDK-781] Adds the children appender for events of enrollments

- core/src/androidTest/java/org/hisp/dhis/android/core/data/server/RealServerMother.java
Solves [ANDROSDK-787](https://jira.dhis2.org/browse/ANDROSDK-787).
> [ANDROSDK-787] Update 2.31.0 url to 2.31.3 in RealServerMother

- core/src/main/java/org/hisp/dhis/android/core/common/ObjectStore.java
- core/src/main/java/org/hisp/dhis/android/core/common/ObjectStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/common/ObjectStyle.java
- core/src/main/java/org/hisp/dhis/android/core/common/ObjectStyleEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/common/ObjectStyleHandler.java
- core/src/main/java/org/hisp/dhis/android/core/common/ObjectStyleHandlerImpl.java
- core/src/main/java/org/hisp/dhis/android/core/dataelement/DataElementHandler.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetHandler.java
- core/src/main/java/org/hisp/dhis/android/core/option/OptionHandler.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramHandler.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramSectionHandler.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageHandler.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeHandler.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityTypeHandler.java
- core/src/test/java/org/hisp/dhis/android/core/common/ObjectStyleHandlerShould.java
- core/src/test/java/org/hisp/dhis/android/core/dataelement/DataElementHandlerShould.java
- core/src/test/java/org/hisp/dhis/android/core/dataset/DataSetHandlerShould.java
- core/src/test/java/org/hisp/dhis/android/core/program/ProgramHandlerShould.java
- core/src/test/java/org/hisp/dhis/android/core/program/ProgramSectionHandlerShould.java
- core/src/test/java/org/hisp/dhis/android/core/program/ProgramStageHandlerShould.java
- core/src/test/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeHandlerShould.java
Solves [ANDROSDK-397](https://jira.dhis2.org/browse/ANDROSDK-397).
> [ANDROSDK-397] Remove object style from db when is removed from server

- core/src/androidTest/java/org/hisp/dhis/android/core/systeminfo/SystemInfoCallMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/arch/api/executors/RxAPICallExecutor.java
- core/src/main/java/org/hisp/dhis/android/core/arch/api/executors/RxAPICallExecutorImpl.java
- core/src/main/java/org/hisp/dhis/android/core/arch/call/CompletableProvider.java
- core/src/main/java/org/hisp/dhis/android/core/arch/modules/RxMetadataModuleDownloader.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadOnlyWithDownloadObjectRepository.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/object/ReadOnlyFirstObjectWithDownloadRepositoryImpl.java
- core/src/main/java/org/hisp/dhis/android/core/calls/MetadataCall.java
- core/src/main/java/org/hisp/dhis/android/core/domain/aggregated/data/AggregatedDataCall.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventWithLimitCallFactory.java
- core/src/main/java/org/hisp/dhis/android/core/systeminfo/SystemInfoCall.java
- core/src/main/java/org/hisp/dhis/android/core/systeminfo/SystemInfoObjectRepository.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueManager.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceWithLimitCallFactory.java
- core/src/main/java/org/hisp/dhis/android/core/user/UserAuthenticateCallFactory.java
- core/src/test/java/org/hisp/dhis/android/core/common/MetadataCallShould.java
- core/src/test/java/org/hisp/dhis/android/core/systeminfo/SystemInfoCallShould.java
- core/src/test/java/org/hisp/dhis/android/core/user/UserAuthenticateCallUnitShould.java
Solves [ANDROSDK-784](https://jira.dhis2.org/browse/ANDROSDK-784).
> [ANDROSDK-784] Use completable in SystemInfo download

- core/src/androidTest/java/org/hisp/dhis/android/core/event/EventEndpointCallMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/arch/handlers/IdentifiableDataSyncHandlerImpl.java
- core/src/main/java/org/hisp/dhis/android/core/arch/handlers/IdentifiableSyncHandlerImpl.java
- core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentHandler.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventHandler.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceHandler.java
- core/src/test/java/org/hisp/dhis/android/core/enrollment/EnrollmentHandlerShould.java
Solves [ANDROSDK-408](https://jira.dhis2.org/browse/ANDROSDK-408).
> [ANDROSDK-408] Do not overwrite non-synchronized data

- core/src/androidTest/java/org/hisp/dhis/android/core/data/database/SyncedDatabaseMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/dataset/DataSetCompleteRegistrationPostCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/datavalue/AggregatedDataCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/datavalue/DataValuePostCallRealIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/arch/api/executors/RxAPICallExecutor.java
- core/src/main/java/org/hisp/dhis/android/core/arch/api/executors/RxAPICallExecutorImpl.java
- core/src/main/java/org/hisp/dhis/android/core/arch/call/D2Completable.java
- core/src/main/java/org/hisp/dhis/android/core/arch/call/D2CompletableImpl.java
- core/src/main/java/org/hisp/dhis/android/core/domain/aggregated/data/AggregatedDataCall.java
- core/src/main/java/org/hisp/dhis/android/core/domain/aggregated/data/AggregatedDataModule.java
Solves [ANDROSDK-783](https://jira.dhis2.org/browse/ANDROSDK-783).
> [ANDROSDK-783] Download aggregated data using RxJava

- core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentImportHandler.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventImportHandler.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventPostCall.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceImportHandler.java
- core/src/test/java/org/hisp/dhis/android/core/enrollment/EnrollmentImportHandlerShould.java
- core/src/test/java/org/hisp/dhis/android/core/event/EventImportHandlerShould.java
- core/src/test/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceImportHandlerShould.java
Solves [ANDROSDK-790](https://jira.dhis2.org/browse/ANDROSDK-790).
> [ANDROSDK-790] Propagate states on tracker import handlers

- core/src/androidTest/java/org/hisp/dhis/android/core/data/database/SyncedDatabaseMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/dataset/DataSetCompleteRegistrationPostCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/datavalue/AggregatedDataCallMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/datavalue/AggregatedDataCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/datavalue/DataValuePostCallRealIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/arch/api/executors/RxAPICallExecutor.java
- core/src/main/java/org/hisp/dhis/android/core/arch/api/executors/RxAPICallExecutorImpl.java
- core/src/main/java/org/hisp/dhis/android/core/arch/call/D2CallWithProgress.java
- core/src/main/java/org/hisp/dhis/android/core/arch/call/D2CallWithProgressImpl.java
- core/src/main/java/org/hisp/dhis/android/core/arch/call/D2Progress.java
- core/src/main/java/org/hisp/dhis/android/core/arch/call/D2ProgressManager.java
- core/src/main/java/org/hisp/dhis/android/core/domain/aggregated/data/AggregatedDataCall.java
Solves [ANDROSDK-791](https://jira.dhis2.org/browse/ANDROSDK-791).
> [ANDROSDK-791] Notify progess in aggregated data call

- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancePostCallMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/arch/db/WhereClauseBuilder.java
- core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityDataValueStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceStoreImpl.java
- core/src/test/java/org/hisp/dhis/android/core/arch/db/WhereClauseBuilderShould.java
Solves [ANDROSDK-794](https://jira.dhis2.org/browse/ANDROSDK-794).
> [ANDROSDK-794] Selective tracker data upload

- doc/content/androsdk/synchronization.md
Solves [ANDROSDK-793](https://jira.dhis2.org/browse/ANDROSDK-793).
> [ANDROSDK-793] Add sync documentation for the SDK

- core/src/androidTest/java/org/hisp/dhis/android/core/maintenance/ForeignKeyCleanerShould.java
- core/src/main/java/org/hisp/dhis/android/core/maintenance/ForeignKeyCleanerImpl.java
Solves [ANDROSDK-795](https://jira.dhis2.org/browse/ANDROSDK-795).
> [ANDROSDK-795] Don't let ForeignKeyCleaner store null violations

- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancePostCallMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/common/IdentifiableObjectWithStateStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/common/StoreWithState.java
- core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentImportHandler.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventImportHandler.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceImportHandler.java
- core/src/test/java/org/hisp/dhis/android/core/enrollment/EnrollmentImportHandlerShould.java
- core/src/test/java/org/hisp/dhis/android/core/event/EventImportHandlerShould.java
- core/src/test/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceImportHandlerShould.java
Solves [ANDROSDK-800](https://jira.dhis2.org/browse/ANDROSDK-800).
> [ANDROSDK-800] Handle success responses for server deletions

- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/api/TrackedEntityInstanceAPIShould.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceListDownloadAndPersistCallFactory.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceRelationshipDownloadAndPersistCallFactory.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceService.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancesEndpointCallFactory.java
Solves [ANDROSDK-801](https://jira.dhis2.org/browse/ANDROSDK-801).
> [ANDROSDK-801] Include deleted on TEI services

- core/build.gradle
- core/gradle.properties
- core/src/main/java/org/hisp/dhis/android/core/arch/db/OrderByClauseBuilder.java
- core/src/test/java/org/hisp/dhis/android/core/arch/repositories/collection/RepositoryPagingShould.java
Solves [ANDROSDK-804](https://jira.dhis2.org/browse/ANDROSDK-804)
> Hotbugfixing 0.15.5

- core/src/main/java/org/hisp/dhis/android/core/event/EventEndpointCallFactory.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventService.java
Solves [ANDROSDK-803](https://jira.dhis2.org/browse/ANDROSDK-803)
> [ANDROSDK-803] Add includeDeleted in EventService

- core/src/androidTest/java/org/hisp/dhis/android/core/EventWithLimitCallMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/category/CategoryEndpointCallShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/data/database/SyncedDatabaseMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/datavalue/AggregatedDataCallMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/event/EventEndpointCallMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/maintenance/ForeignKeyCleanerShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/option/OptionSetCallShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitCallMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/program/ProgramEndpointCallMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/systeminfo/SystemInfoCallMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceCallMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancePostCallMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/user/UserAuthenticateCallMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/user/UserCallMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/wipe/WipeDBCallMockIntegrationShould.java
- core/src/sharedTest/java/org/hisp/dhis/android/core/data/server/Dhis2MockServer.java
- core/src/test/java/org/hisp/dhis/android/core/common/BaseCallShould.java
Solves [ANDROSDK-786](https://jira.dhis2.org/browse/ANDROSDK-786).
> [ANDROSDK-786] Instantiate FileReader inside Dhis2MockServer

- core/src/androidTest/java/org/hisp/dhis/android/core/TeisCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/data/database/SyncedDatabaseMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancePostCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/wipe/WipeDBCallRealIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/arch/call/D2Progress.java
- core/src/main/java/org/hisp/dhis/android/core/arch/call/D2ProgressManager.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceListDownloadAndPersistCallFactory.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceRelationshipDownloadAndPersistCallFactory.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceWithLimitCallFactory.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityModule.java
Solves [ANDROSDK-771](https://jira.dhis2.org/browse/ANDROSDK-771).
> [ANDROSDK-771] Download TEIs by orgunit in parallel

- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancePostCallMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancePostCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceStoreShould.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadOnlyCollectionRepositoryImpl.java
- core/src/main/java/org/hisp/dhis/android/core/common/UidsHelper.java
- core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipItemStore.java
- core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipItemStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancePostCall.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceStore.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceStoreImpl.java
- core/src/sharedTest/java/org/hisp/dhis/android/core/data/relationship/RelationshipSamples.java
- core/src/sharedTest/java/org/hisp/dhis/android/core/data/trackedentity/TrackedEntityInstanceSamples.java
Solves [ANDROSDK-802](https://jira.dhis2.org/browse/ANDROSDK-802).
> [ANDROSDK-802] Granular TrackedEntityInstance sync

- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancePostCallMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancePostCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceStoreShould.java
- core/src/androidTest/java/org/hisp/dhis/android/testapp/trackedentity/TrackedEntityCollectionRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadOnlyCollectionRepositoryImpl.java
- core/src/main/java/org/hisp/dhis/android/core/common/UidsHelper.java
- core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentFields.java
- core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipItemStore.java
- core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipItemStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancePostCall.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceStore.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceStoreImpl.java
- core/src/sharedTest/java/org/hisp/dhis/android/core/data/relationship/RelationshipSamples.java
- core/src/sharedTest/java/org/hisp/dhis/android/core/data/trackedentity/TrackedEntityInstanceSamples.java
Solves [ANDROSDK-807](https://jira.dhis2.org/browse/ANDROSDK-807).
> [ANDROSDK-807] Adds byProgram filter on TEICollectionRepository

- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancePostCallMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/common/ObjectStore.java
- core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentImportHandler.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventImportHandler.java
- core/src/main/java/org/hisp/dhis/android/core/imports/TrackerImportConflictTableInfo.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceImportHandler.java
- core/src/sharedTest/resources/imports/web_response_with_import_conflicts_3.json
Solves [ANDROSDK-798](https://jira.dhis2.org/browse/ANDROSDK-798).
> [ANDROSDK-798] Delete old import conflicts after sync.

- core/src/main/java/org/hisp/dhis/android/core/arch/api/executors/APICallExecutorImpl.java
- core/src/test/java/org/hisp/dhis/android/core/arch/api/executors/APICallExecutorShould.java
Solves [ANDROSDK-808](https://jira.dhis2.org/browse/ANDROSDK-808)
> [ANDROSDK-808] Do not catch already catched exceptions

- core/src/androidTest/java/org/hisp/dhis/android/core/event/EventPostCallMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/D2DIComponent.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventPostCall.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventStoreImpl.java
- core/src/sharedTest/resources/imports/web_response_with_event_import_conflicts.json
- core/src/sharedTest/resources/imports/web_response_with_event_import_conflicts2.json
Solves [ANDROSDK-806](https://jira.dhis2.org/browse/ANDROSDK-806).
> [ANDROSDK-806] Granular event upload sync

- core/src/androidTest/java/org/hisp/dhis/android/core/event/EventPostCallMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/D2DIComponent.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventPostCall.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventStoreImpl.java
- core/src/sharedTest/resources/imports/web_response_with_event_import_conflicts.json
- core/src/sharedTest/resources/imports/web_response_with_event_import_conflicts2.json
Solves [ANDROSDK-809](https://jira.dhis2.org/browse/ANDROSDK-809).
> [ANDROSDK-809] Use sync strategy when 2.30 or later version

- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceCallMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/arch/handlers/IdentifiableDataSyncHandlerImpl.java
Solves [ANDROSDK-810](https://jira.dhis2.org/browse/ANDROSDK-810).
> [ANDROSDK-810] Do not ignore data objects deleted on server if not synced

- core/src/main/java/org/hisp/dhis/android/core/arch/handlers/IdentifiableDataSyncHandlerImpl.java
Solves [ANDROSDK-818](https://jira.dhis2.org/browse/ANDROSDK-818).
> [ANDROSDK-818] Overwirtte TEIs with relationship state when syncing

- core/src/androidTest/java/org/hisp/dhis/android/core/d2manager/D2ManagerRealIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/d2manager/D2Configuration.java
- core/src/main/java/org/hisp/dhis/android/core/d2manager/D2Manager.java
- core/src/main/java/org/hisp/dhis/android/core/d2manager/OkHttpClientFactory.java
- Makes constructor public, so it can be instantiated outside of the package
- Lets configure interceptors
> [D2-MANAGER-IMPROVE] Improve D2Manager

- core/src/androidTest/java/org/hisp/dhis/android/core/relationship/RelationshipStoreIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceCollectionRepositoryMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancePostCallMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipChildrenAppender.java
- core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipHandlerImpl.java
- core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipItem.java
- core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipObjectRepository.java
- core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipStore.java
- core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceFields.java
- core/src/test/java/org/hisp/dhis/android/core/relationship/RelationshipHandlerShould.java
Solves [ANDROSDK-672](https://jira.dhis2.org/browse/ANDROSDK-672).
> [ANDROSDK-672] Relationships and relationship items as tei children

- core/src/androidTest/java/org/hisp/dhis/android/core/TeisCallRealIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceService.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceWithLimitCallFactory.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancesEndpointCallFactory.java
Solves [ANDROSDK-811](https://jira.dhis2.org/browse/ANDROSDK-811).
> [ANDROSDK-811] Improve TEI download with Rx to enable parallel

- core/src/androidTest/java/org/hisp/dhis/android/core/maintenance/ForeignKeyCleanerShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/option/OptionSetCallShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancePostCallMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/calls/processors/TransactionalNoResourceSyncCallProcessor.java
- core/src/main/java/org/hisp/dhis/android/core/calls/processors/TransactionalResourceSyncCallProcessor.java
- core/src/main/java/org/hisp/dhis/android/core/common/D2CallExecutor.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueCallProcessor.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueManager.java
- core/src/main/java/org/hisp/dhis/android/core/user/AuthorityCallProcessor.java
- core/src/test/java/org/hisp/dhis/android/core/common/MetadataCallShould.java
- core/src/test/java/org/hisp/dhis/android/core/wipe/WipeModuleShould.java
Solves [ANDROSDK-823](https://jira.dhis2.org/browse/ANDROSDK-823)
> [ANDROSDK-823] Persist d2Errors in d2callexecutor

- core/src/androidTest/java/org/hisp/dhis/android/core/TeisCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/data/database/SyncedDatabaseMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancePostCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/wipe/WipeDBCallRealIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitPackageDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitProgramLinkEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceService.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceWithLimitCallFactory.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancesEndpointCallFactory.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityModule.java
Solves [ANDROSDK-805](https://jira.dhis2.org/browse/ANDROSDK-805).
> [ANDROSDK-805] Download TEIs: limit by program

- core/src/androidTest/java/org/hisp/dhis/android/core/TeisCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/data/database/SyncedDatabaseMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancePostCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/wipe/WipeDBCallRealIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitPackageDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitProgramLinkEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceService.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceWithLimitCallFactory.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancesEndpointCallFactory.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityModule.java
Solves [ANDROSDK-821](https://jira.dhis2.org/browse/ANDROSDK-821).
> [ANDROSDK-821] TEI download: check that ou list is not empty

- core/src/main/java/org/hisp/dhis/android/core/arch/fields/FieldsHelper.java
- core/src/main/java/org/hisp/dhis/android/core/data/api/Fields.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceFields.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceHandler.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceRelationshipDownloadAndPersistCallFactory.java
Solves ([ANDROSDK-826](https://jira.dhis2.org/browse/ANDROSDK-826))
>  [ANDROSDK-826] Use relationship fields in tei call

- core/src/androidTest/java/org/hisp/dhis/android/core/EventWithLimitCallMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/data/database/SyncedDatabaseMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/event/EventWithLimitCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/wipe/WipeDBCallMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventModule.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventWithLimitCallFactory.java
Solves [ANDROSDK-830](https://jira.dhis2.org/browse/ANDROSDK-830).
> [ANDROSDK-830] Download events limit by program

- core/src/androidTest/java/org/hisp/dhis/android/core/d2manager/D2ManagerRealIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/d2manager/D2Configuration.java
- core/src/main/java/org/hisp/dhis/android/core/d2manager/OkHttpClientFactory.java
Solves [ANDROSDK-822](https://jira.dhis2.org/browse/ANDROSDK-822).
> [ANDROSDK-822] Make interceptors optional in D2Manager

- core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceLocalQueryHelper.java
Solves [ANDROSDK-829](https://jira.dhis2.org/browse/ANDROSDK-829)
> [ANDROSDK-829] Add distinct results in tei search

- core/src/androidTest/java/org/hisp/dhis/android/core/arch/repositories/collection/FiltersOperatorsMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/BaseFilterConnector.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventStoreImpl.java
- core/src/sharedTest/resources/program/program_stages.json
Solves [ANDROSDK-832](https://jira.dhis2.org/browse/ANDROSDK-832)
> [ANDROSDK-832] Filter event post call

- core/src/main/java/org/hisp/dhis/android/core/enrollment/Enrollment.java
Solves [ANDROSDK-833](https://jira.dhis2.org/browse/ANDROSDK-833)
> [ANDROSDK-833] Send enrollment status

- core/src/androidTest/java/org/hisp/dhis/android/core/common/DataStatePropagatorIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/enrollment/EnrollmentCollectionRepositoryMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/enrollment/EnrollmentObjectRepositoryMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/testapp/trackedentity/TrackedEntityCollectionRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/object/ReadWriteWithUidDataObjectRepositoryImpl.java
- core/src/main/java/org/hisp/dhis/android/core/common/DataStatePropagator.java
- core/src/main/java/org/hisp/dhis/android/core/common/IdentifiableObjectWithStateStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/common/StoreWithState.java
- core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentCreateProjection.java
- core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentObjectRepository.java
- core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentProjectionTransformer.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceObjectRepository.java
Solves [ANDROSDK-813](https://jira.dhis2.org/browse/ANDROSDK-813).
> [ANDROSDK-813] Support for Enrollment creation

- core/src/androidTest/java/org/hisp/dhis/android/core/common/DataStatePropagatorIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/testapp/enrollment/EnrollmentCollectionRepositoryMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/testapp/enrollment/EnrollmentObjectRepositoryMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/testapp/event/EventCollectionRepositoryMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/testapp/event/EventObjectRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/common/DataStatePropagator.java
- core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentObjectRepository.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventCreateProjection.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventObjectRepository.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventProjectionTransformer.java
Solves [ANDROSDK-814](https://jira.dhis2.org/browse/ANDROSDK-814).
> [ANDROSDK-814] Support for Event creation

- core/src/androidTest/java/org/hisp/dhis/android/core/common/D2Factory.java
- core/src/androidTest/java/org/hisp/dhis/android/core/d2manager/D2ManagerRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/data/server/RealServerMother.java
- core/src/main/java/org/hisp/dhis/android/core/D2.java
- core/src/main/java/org/hisp/dhis/android/core/configuration/Configuration.java
- core/src/main/java/org/hisp/dhis/android/core/configuration/ConfigurationManager.java
- core/src/main/java/org/hisp/dhis/android/core/configuration/ConfigurationManagerImpl.java
- core/src/main/java/org/hisp/dhis/android/core/d2manager/D2Manager.java
- core/src/sharedTest/java/org/hisp/dhis/android/core/data/server/Dhis2MockServer.java
- core/src/test/java/org/hisp/dhis/android/core/configuration/ConfigurationManagerShould.java
Solves [ANDROSDK-834](https://jira.dhis2.org/browse/ANDROSDK-834).
> [ANDROSDK-834] Apply app feedback in D2Manager

- core/src/androidTest/java/org/hisp/dhis/android/core/common/DataStatePropagatorIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/testapp/trackedentity/TrackedEntityDataValueCollectionRepositoryMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/testapp/trackedentity/TrackedEntityDataValueObjectRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadWriteWithValueCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadWriteWithValueCollectionRepositoryImpl.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/object/ReadWriteValueObjectRepository.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/object/ReadWriteWithValueObjectRepositoryImpl.java
- core/src/main/java/org/hisp/dhis/android/core/common/DataStatePropagator.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityDataValueCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityDataValueCreateProjection.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityDataValueEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityDataValueObjectRepository.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityDataValueProjectionTransformer.java
Solves [ANDROSDK-816](https://jira.dhis2.org/browse/ANDROSDK-816).
> [ANDROSDK-816] Support for TrackedEntityDataValue creation

- core/src/androidTest/java/org/hisp/dhis/android/core/common/DataStatePropagatorIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/testapp/trackedentity/TrackedEntityAttributeValueCollectionRepositoryMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/testapp/trackedentity/TrackedEntityAttributeValueObjectRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/common/DataStatePropagator.java
- core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentObjectRepository.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventCreateProjection.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventObjectRepository.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeValueCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeValueCreateProjection.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeValueObjectRepository.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeValueProjectionTransformer.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityDataValueCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityDataValueObjectRepository.java
Solves [ANDROSDK-815](https://jira.dhis2.org/browse/ANDROSDK-815).
> [ANDROSDK-815] Support for TrackedEntityAttributeValue creation

- core/src/androidTest/java/org/hisp/dhis/android/testapp/datavalue/DataValueCollectionRepositoryMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/testapp/enrollment/EnrollmentCollectionRepositoryMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/testapp/event/EventCollectionRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/datavalue/DataValueCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentCollectionRepository.java
Solves [ANDROSDK-842](https://jira.dhis2.org/browse/ANDROSDK-842)
> [ANDROSDK-842] Add byState in DataValueRepository, EnrollmentRepository

- core/src/androidTest/java/org/hisp/dhis/android/core/common/D2Factory.java
- core/src/androidTest/java/org/hisp/dhis/android/core/configuration/ConfigurationStoreIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/configuration/ConfigurationStoreShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/d2manager/D2ManagerRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceCallMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/utils/integration/mock/MockIntegrationTestObjects.java
- core/src/androidTest/java/org/hisp/dhis/android/core/utils/integration/real/BaseRealIntegrationTest.java
- core/src/androidTest/java/org/hisp/dhis/android/core/wipe/WipeDBCallMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/D2.java
- core/src/main/java/org/hisp/dhis/android/core/D2DIComponent.java
- core/src/main/java/org/hisp/dhis/android/core/configuration/Configuration.java
- core/src/main/java/org/hisp/dhis/android/core/configuration/ConfigurationHelper.java
- core/src/main/java/org/hisp/dhis/android/core/configuration/ConfigurationStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/d2manager/D2Configuration.java
- core/src/main/java/org/hisp/dhis/android/core/d2manager/D2Manager.java
- core/src/sharedTest/java/org/hisp/dhis/android/core/data/configuration/ConfigurationSamples.java
- core/src/test/java/org/hisp/dhis/android/core/configuration/ConfigurationHelperShould.java
- Makes mock integration shoulds that use D2 get the instance through D2Manager.
- Ensures no api/api/ is stored in configuration.
- Enables reconfiguration of D2.
> [ANDROSDK-824] [ANDROSDK-841] D2Manager final improvements

- core/src/androidTest/java/org/hisp/dhis/android/core/data/database/ObjectWithoutUidStoreAbstractIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/testapp/datavalue/DataValueObjectRepositoryMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/testapp/trackedentity/TrackedEntityAttributeValueObjectRepositoryMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/testapp/trackedentity/TrackedEntityDataValueObjectRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/arch/db/binders/WhereStatementBinder.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/object/ReadWriteWithValueObjectRepositoryImpl.java
- core/src/main/java/org/hisp/dhis/android/core/common/ObjectStyleStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/common/ObjectWithoutUidStore.java
- core/src/main/java/org/hisp/dhis/android/core/common/ObjectWithoutUidStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/common/SQLStatementBuilder.java
- core/src/main/java/org/hisp/dhis/android/core/common/StoreFactory.java
- core/src/main/java/org/hisp/dhis/android/core/common/ValueTypeDeviceRenderingStore.java
- core/src/main/java/org/hisp/dhis/android/core/dataapproval/DataApprovalStore.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetCompleteRegistrationStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/datavalue/DataValueObjectRepository.java
- core/src/main/java/org/hisp/dhis/android/core/datavalue/DataValueStore.java
- core/src/main/java/org/hisp/dhis/android/core/enrollment/note/NoteStore.java
- core/src/main/java/org/hisp/dhis/android/core/period/PeriodStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipConstraintStore.java
- core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipItemStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/resource/ResourceStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/settings/SystemSettingStore.java
- core/src/main/java/org/hisp/dhis/android/core/systeminfo/SystemInfoStore.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueStore.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeValueStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityDataValueStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/user/AuthenticatedUserStore.java
- core/src/main/java/org/hisp/dhis/android/core/user/AuthorityStore.java
Solves [ANDROSDK-838](https://jira.dhis2.org/browse/ANDROSDK-838).
> [ANDROSDK-838] Add delete method on value object repositories

- core/src/androidTest/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadOnlyCollectionRepositoryImplIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/period/PeriodMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadOnlyCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/internal/ReadOnlyCollectionRepositoryImpl.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/object/ReadOnlyObjectRepository.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/object/internal/ReadOnlyObjectRepositoryImpl.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryCollectionRepository.java
Solves [ANDROSDK-862](https://jira.dhis2.org/browse/ANDROSDK-862).
> [ANDROSDK-862] Implement getAsync returning Single

- core/src/androidTest/java/org/hisp/dhis/android/core/d2manager/D2Factory.java
- core/src/androidTest/java/org/hisp/dhis/android/core/d2manager/D2ManagerRealIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/d2manager/D2Configuration.java
- core/src/main/java/org/hisp/dhis/android/core/d2manager/D2Manager.java
Solves [ANDROSDK-863](https://jira.dhis2.org/browse/ANDROSDK-863).
> [ANDROSDK-863] Configure database name internally in SDK

- core/src/androidTest/java/org/hisp/dhis/android/core/d2manager/D2Factory.java
- core/src/main/java/org/hisp/dhis/android/core/configuration/Configuration.java
- core/src/main/java/org/hisp/dhis/android/core/configuration/ServerUrlParser.java
- core/src/main/java/org/hisp/dhis/android/core/d2manager/D2Manager.java
- core/src/test/java/org/hisp/dhis/android/core/configuration/ConfigurationManagerShould.java
- core/src/test/java/org/hisp/dhis/android/core/configuration/ServerUrlParserShould.java
Solves [ANDROSDK-861](https://jira.dhis2.org/browse/ANDROSDK-861).
> [ANDROSDK-861] Move server URL parse to SDK

- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceWithLimitCallFactory.java
Solves [ANDROSDK-867](https://jira.dhis2.org/browse/ANDROSDK-861).
> fix: [ANDROSDK-867] Prevent database call in main thread in teis download

- core/src/androidTest/java/org/hisp/dhis/android/core/d2manager/D2Factory.java
- core/src/androidTest/java/org/hisp/dhis/android/core/d2manager/D2ManagerRealIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/d2manager/D2Manager.java
Solves [ANDROSDK-868](https://jira.dhis2.org/browse/ANDROSDK-868).
> feat: [ANDROSDK-868] Add RxJava to D2Manager

- core/src/main/java/org/hisp/dhis/android/core/program/ProgramIndicator.java
- core/src/main/java/org/hisp/dhis/android/core/utils/services/ProgramIndicatorEngine.java
- core/src/test/java/org/hisp/dhis/android/core/utils/services/ProgramIndicatorEngineShould.java
Solves [ANDROSDK-856](https://jira.dhis2.org/browse/ANDROSDK-856)
> fix: [ANDROSDK-856] Handle empty AggregationType on ProgramIndicator

- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceWithLimitCallFactory.java
- core/src/main/java/org/hisp/dhis/android/core/user/UserOrganisationUnitLinkStore.java
- core/src/main/java/org/hisp/dhis/android/core/user/UserOrganisationUnitLinkStoreImpl.java
Solves [ANDROSDK-855](https://jira.dhis2.org/browse/ANDROSDK-855)
> fix: [ANDROSDK-855] Use only capture orgunits in TEI download

- core/src/androidTest/java/org/hisp/dhis/android/core/utils/services/ProgramIndicatorEngineIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/utils/services/ProgramIndicatorEngine.java
- core/src/test/java/org/hisp/dhis/android/core/utils/services/ProgramIndicatorEngineShould.java
[ANDROSDK-872](https://jira.dhis2.org/browse/ANDROSDK-872)
> fix: [ANDROSDK-872] Program indicator engine: integer division is giving wrong results

- core/src/main/java/org/hisp/dhis/android/core/data/api/Field.java
- core/src/main/java/org/hisp/dhis/android/core/data/api/SingleValueFilter.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitCallFactory.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitFields.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitQuery.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitService.java
- core/src/test/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitCallUnitShould.java
Solves [ANDROSDK-869](https://jira.dhis2.org/browse/ANDROSDK-869)
> feat: [ANDROSDK-869] Use paging in OrganisationUnitService

- core/src/androidTest/java/org/hisp/dhis/android/core/common/internal/DataStatePropagatorIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/common/internal/DataStatePropagator.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventCreateProjection.java
Solves [ANDROSDK-875](https://jira.dhis2.org/browse/ANDROSDK-875)
> fix: [ANDROSDK-875] Enrollment as nullable in EventCreation

- core/src/main/java/org/hisp/dhis/android/core/enrollment/internal/EnrollmentProjectionTransformer.java
- core/src/main/java/org/hisp/dhis/android/core/event/internal/EventProjectionTransformer.java
Solves [ANDROSDK-871](https://jira.dhis2.org/browse/ANDROSDK-871)
> fix: [ANDROSDK-871] Default to status ACTIVE in Events and Enrollments

- core/src/main/java/org/hisp/dhis/android/core/datavalue/DataSetReport.java
- core/src/main/java/org/hisp/dhis/android/core/datavalue/internal/DataSetReportSQLStatementBuilder.java
Solves [ANDROSDK-878](https://jira.dhis2.org/browse/ANDROSDK-878)
> fix: [ANDROSDK-878] Fix paging key in DataSetReports

- core/src/androidTest/java/org/hisp/dhis/android/core/MetadataCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/TeisCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/UserAuthenticateCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/dataset/internal/DataSetCompleteRegistrationPostCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/datavalue/internal/DataValuePostCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/domain/aggregated/data/AggregatedDataCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/enrollment/note/NotePostCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/event/internal/EventEndpointCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/event/internal/EventPostCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/event/internal/EventWithLimitCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/maintenance/internal/ForeignKeyCleanerShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueManagerRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancePostCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryAndDownloadRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/user/internal/LogoutCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/utils/integration/mock/BaseMockIntegrationTestFullDispatcher.java
- core/src/androidTest/java/org/hisp/dhis/android/core/utils/integration/mock/BaseMockIntegrationTestMetadataDispatcher.java
- core/src/androidTest/java/org/hisp/dhis/android/core/utils/integration/mock/BaseMockIntegrationTestMetadataEnqueable.java
- core/src/androidTest/java/org/hisp/dhis/android/core/wipe/WipeDBCallMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/wipe/WipeDBCallRealIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/D2.java
- core/src/main/java/org/hisp/dhis/android/core/arch/api/executors/internal/RxAPICallExecutorImpl.java
- core/src/main/java/org/hisp/dhis/android/core/domain/metadata/MetadataCall.java
- core/src/test/java/org/hisp/dhis/android/core/common/MetadataCallShould.java
Solves [ANDROSDK-877](https://jira.dhis2.org/browse/ANDROSDK-877).
> feat: [ANDROSDK-877] Make metadataSync return Observable<D2Progress>

- core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramCollectionRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramCollectionRepository.java
Fix unknown Jira issue (Jira is down).
> feat: [PROGRA-BY-ORGANISATION-UNIT] Add filter program by organisation unit

- core/src/main/java/org/hisp/dhis/android/core/domain/metadata/MetadataCall.java
- core/src/test/java/org/hisp/dhis/android/core/common/MetadataCallShould.java
Solves [ANDROSDK-879](https://jira.dhis2.org/browse/ANDROSDK-879).
> fix: [ANDROSDK-879] Fix Metadata system info D2Error

- core/src/androidTest/java/org/hisp/dhis/android/core/dataset/internal/DataSetCompleteRegistrationPostCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/datavalue/internal/DataValuePostCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/enrollment/note/NotePostCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/event/internal/EventPostCallMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/event/internal/EventPostCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancePostCallMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancePostCallRealIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadOnlyWithUploadCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadWriteWithUploadWithUidCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetCompleteRegistrationCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/internal/DataSetCompleteRegistrationPostCall.java
- core/src/main/java/org/hisp/dhis/android/core/datavalue/DataValueCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/datavalue/internal/DataValuePostCall.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/event/internal/EventPostCall.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancePostCall.java
Solves [ANDROSDK-886](https://jira.dhis2.org/browse/ANDROSDK-886).
> feat: [ANDROSDK-886] Make upload calls return observable

- core/src/androidTest/java/org/hisp/dhis/android/core/EventWithLimitCallMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/enrollment/note/NotePostCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/event/internal/EventWithLimitCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceCallMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancePostCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryAndDownloadRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/utils/integration/mock/BaseMockIntegrationTestFullDispatcher.java
- core/src/androidTest/java/org/hisp/dhis/android/core/wipe/WipeDBCallMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventModule.java
- core/src/main/java/org/hisp/dhis/android/core/event/internal/EventWithLimitCallFactory.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceListDownloadAndPersistCallFactory.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityModule.java
Solves [ANDROSDK-887](https://jira.dhis2.org/browse/ANDROSDK-887).
> feat: [ANDROSDK-887] Make remaining download methods return observable

- core/src/androidTest/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadOnlyCollectionRepositoryImplIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadOnlyCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/internal/ReadOnlyCollectionRepositoryImpl.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryCollectionRepository.java
Solves [ANDROSDK-890](https://jira.dhis2.org/browse/ANDROSDK-890).
> feat: [ANDROSDK-890] Add isEmpty method to collection repositories

- core/src/main/java/org/hisp/dhis/android/core/program/programindicatorengine/ProgramIndicatorEngine.java
- core/src/test/java/org/hisp/dhis/android/core/program/programindicatorengine/ProgramIndicatorEngineShould.java
Solves [ANDROSDK-895](https://jira.dhis2.org/browse/ANDROSDK-895)
> fix: [ANDROSDK-895] ProgramIndicatorEngine: fix division by zero

- core/src/androidTest/java/org/hisp/dhis/android/testapp/dataapproval/DataApprovalCollectionRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/dataapproval/DataApprovalCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/dataapproval/internal/DataApprovalEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetModule.java
[ANDROSDK-858](https://jira.dhis2.org/browse/ANDROSDK-858)
> feat: [ANDROSDK-858] Add DataApproval repository

- core/src/androidTest/java/org/hisp/dhis/android/testapp/dataset/DataSetCompleteRegistrationCollectionRepositoryMockIntegrationShould.java
- core/src/sharedTest/resources/dataset/data_set_complete_registrations.json
[ANDROSDK-714](https://jira.dhis2.org/browse/ANDROSDK-714)
> fix: [ANDROSDK-714] DataSetCompleteteRegistration tests failing depending on current date

- core/src/androidTest/java/org/hisp/dhis/android/testapp/dataapproval/DataApprovalCollectionRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/dataapproval/DataApprovalCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/dataapproval/DataApprovalTableInfo.java
[ANDROSDK-896](https://jira.dhis2.org/browse/ANDROSDK-896)
> feat: [ANDROSDK-896] Add state filter to approval repository

- core/src/androidTest/java/org/hisp/dhis/android/core/organisationunit/internal/OrganisationUnitCallMockIntegrationShould.java
- core/src/main/assets/migrations/51.yaml
- core/src/main/java/org/hisp/dhis/android/core/arch/db/stores/internal/LinkModelStore.java
- core/src/main/java/org/hisp/dhis/android/core/arch/db/stores/internal/LinkModelStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/arch/handlers/internal/LinkHandler.java
- core/src/main/java/org/hisp/dhis/android/core/arch/handlers/internal/LinkHandlerImpl.java
- core/src/main/java/org/hisp/dhis/android/core/data/database/DbOpenHelper.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/internal/OrganisationUnitCallFactory.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/internal/OrganisationUnitHandler.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/internal/OrganisationUnitHandlerImpl.java
- core/src/test/java/org/hisp/dhis/android/core/organisationunit/internal/OrganisationUnitCallUnitShould.java
Solves [ANDROSDK-898](https://jira.dhis2.org/browse/ANDROSDK-898)
> feat: [ANDROSDK-898] Persist orgunit in every page; improve indexes

- core/src/main/java/org/hisp/dhis/android/core/datavalue/DataSetReportCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/datavalue/internal/DataSetReportEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/datavalue/internal/DataSetReportSQLStatementBuilder.java
Solves [ANDROSDK-889](https://jira.dhis2.org/browse/ANDROSDK-889)
> fix: [ANDROSDK-889] Fix paging in DataSetReports

- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceFields.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceService.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceLocalQueryHelper.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQuery.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryCallFactory.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryOnline.java
- core/src/test/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryCallShould.java
Solves [ANDROSDK-899](https://jira.dhis2.org/browse/ANDROSDK-899)
> feat: [ANDROSDK-899] Add TrackedEntityType filter in tei search

- core/src/androidTest/java/org/hisp/dhis/android/testapp/datavalue/DataSetReportCollectionRepositoryMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/testapp/datavalue/DataValueCollectionRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/data/database/IsColumnNotNullColumnAdapter.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetCompleteRegistrationTableInfo.java
- core/src/main/java/org/hisp/dhis/android/core/datavalue/DataSetReport.java
- core/src/main/java/org/hisp/dhis/android/core/datavalue/internal/DataSetReportSQLStatementBuilder.java
- core/src/sharedTest/resources/datavalue/data_values.json
Solves [ANDROSDK-884](https://jira.dhis2.org/browse/ANDROSDK-884)
> feat: [ANDROSDK-884] Add complete and completionDate properties in DataSetReport

- core/src/androidTest/java/org/hisp/dhis/android/testapp/dataset/DataSetInstanceCollectionRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetInstance.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetInstanceCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetModule.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/internal/DataSetInstanceEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/internal/DataSetInstanceSQLStatementBuilder.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/internal/DataSetInstanceStore.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/internal/DataSetPackageDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/datavalue/DataValue.java
- core/src/main/java/org/hisp/dhis/android/core/datavalue/DataValueModule.java
- core/src/main/java/org/hisp/dhis/android/core/datavalue/internal/DataValuePackageDIModule.java
Solves [ANDROSDK-901](https://jira.dhis2.org/browse/ANDROSDK-901)
> feat: [ANDROSDK-901] Refactor DataSetReport -> DataSetInstance

- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueEndpointCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueManagerRealIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueManager.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceWithLimitCallFactory.java
- core/src/main/java/org/hisp/dhis/android/core/utils/internal/BooleanWrapper.java
Solves [ANDROSDK-891](https://jira.dhis2.org/browse/ANDROSDK-891)
> feat: [ANDROSDK-891] Make reserved values manager return observables 

- core/src/androidTest/java/org/hisp/dhis/android/core/MetadataCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/UserAuthenticateCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/dataset/internal/DataSetCompleteRegistrationPostCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/datavalue/internal/DataValuePostCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/domain/aggregated/data/AggregatedDataCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/enrollment/note/NotePostCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/event/internal/EventEndpointCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/event/internal/EventPostCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/event/internal/EventWithLimitCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/maintenance/internal/ForeignKeyCleanerShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueManagerRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancePostCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryAndDownloadRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/user/internal/LogoutCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/utils/integration/mock/BaseMockIntegrationTestFullDispatcher.java
- core/src/androidTest/java/org/hisp/dhis/android/core/utils/integration/mock/BaseMockIntegrationTestMetadataDispatcher.java
- core/src/androidTest/java/org/hisp/dhis/android/core/utils/integration/mock/BaseMockIntegrationTestMetadataEnqueable.java
- core/src/androidTest/java/org/hisp/dhis/android/core/wipe/WipeDBCallMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/wipe/WipeDBCallRealIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/D2.java
- core/src/main/java/org/hisp/dhis/android/core/D2DIComponent.java
- core/src/main/java/org/hisp/dhis/android/core/domain/metadata/MetadataCall.java
- core/src/main/java/org/hisp/dhis/android/core/domain/metadata/MetadataModule.java
Solves [ANDROSDK-900](https://jira.dhis2.org/browse/ANDROSDK-900).
> feat: [ANDROSDK-900] Move metadata download to module and rename method

- core/src/androidTest/java/org/hisp/dhis/android/core/relationship/CreateRelationshipTypeUtils.java
- core/src/androidTest/java/org/hisp/dhis/android/core/relationship/RelationshipTypeModelShould.java
- core/src/main/assets/migrations/52.yaml
- core/src/main/java/org/hisp/dhis/android/core/data/database/DbOpenHelper.java
- core/src/main/java/org/hisp/dhis/android/core/data/database/IgnoreStringColumnAdapter.java
- core/src/main/java/org/hisp/dhis/android/core/program/Program.java
- core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipType.java
- core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipTypeTableInfo.java
- core/src/main/java/org/hisp/dhis/android/core/relationship/internal/RelationshipTypeEndpointCallFactory.java
- core/src/main/java/org/hisp/dhis/android/core/relationship/internal/RelationshipTypeFields.java
- core/src/main/java/org/hisp/dhis/android/core/relationship/internal/RelationshipTypeService.java
- core/src/main/java/org/hisp/dhis/android/core/relationship/internal/RelationshipTypeStore.java
- core/src/sharedTest/resources/relationship/relationship_type_30.json
- core/src/sharedTest/resources/relationship/relationship_type_32.json
- core/src/test/java/org/hisp/dhis/android/core/relationship/RelationshipType29Should.java
- core/src/test/java/org/hisp/dhis/android/core/relationship/RelationshipType30Should.java
- core/src/test/java/org/hisp/dhis/android/core/relationship/RelationshipType32Should.java
Solves [ANDROSDK-883](https://jira.dhis2.org/browse/ANDROSDK-883)
> feat: [ANDROSDK-883] RelationshipType model to 2.32

- core/src/main/java/org/hisp/dhis/android/core/program/programindicatorengine/ProgramIndicatorEngine.java
[ANDROSDK-859](https://jira.dhis2.org/browse/ANDROSDK-859)
> fix: [ANDROSDK-859] ProgramIndicatorEngine parse exception

- core/src/main/java/org/hisp/dhis/android/core/dataset/DataInputPeriodTableInfo.java
[ANDROSDK-413](https://jira.dhis2.org/browse/ANDROSDK-413)
> fix: [ANDROSDK-413] Remove "where" columns in DataInputPeriodTableInfo

- core/src/main/java/org/hisp/dhis/android/core/category/CategoryComboCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/category/CategoryComboTableInfo.java
- core/src/main/java/org/hisp/dhis/android/core/category/internal/CategoryComboFields.java
Solves [ANDROSDK-907](https://jira.dhis2.org/browse/ANDROSDK-907).
> feat: [ANDROSDK-907] TableInfo prototype for 1.0

- core/src/androidTest/java/org/hisp/dhis/android/testapp/event/EventObjectRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/category/internal/CategoryOptionComboStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventObjectRepository.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventTableInfo.java
- core/src/main/java/org/hisp/dhis/android/core/event/internal/EventFields.java
Solves [ANDROSDK-911](https://jira.dhis2.org/browse/ANDROSDK-911)
> feat: [ANDROSDK-911] Edit attributeOptionCombo in Events

- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/object/internal/ReadWriteWithValueObjectRepositoryImpl.java
- core/src/main/java/org/hisp/dhis/android/core/datavalue/DataValueObjectRepository.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeValueObjectRepository.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityDataValueObjectRepository.java
Solves [ANDROSDK-874](https://jira.dhis2.org/browse/ANDROSDK-874)
> fix: [ANDROSDK-874] Propagate status on deletion

- core/src/main/java/org/hisp/dhis/android/core/category/internal/CategoryComboUidsSeeker.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetTableInfo.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/internal/DataSetFields.java
- core/src/main/java/org/hisp/dhis/android/core/dataset/internal/DataSetInstanceSQLStatementBuilder.java
- core/src/main/java/org/hisp/dhis/android/core/datavalue/DataValueCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/datavalue/DataValueTableInfo.java
- core/src/main/java/org/hisp/dhis/android/core/datavalue/internal/DataValueFields.java
- core/src/main/java/org/hisp/dhis/android/core/datavalue/internal/DataValueStore.java
- core/src/main/java/org/hisp/dhis/android/core/domain/aggregated/data/AggregatedDataCall.java
Partially solves [ANDROSDK-910](https://jira.dhis2.org/browse/ANDROSDK-910)
> feat: [ANDROSDK-910] Harmonize DataValueTableInfo, DataValueTableInfo

- core/src/main/java/org/hisp/dhis/android/core/arch/helpers/GeometryHelper.java
- core/src/test/java/org/hisp/dhis/android/core/arch/helpers/GeometryHelperShould.java
Solves [ANDROSDK-915](https://jira.dhis2.org/browse/ANDROSDK-915).
> feat: [androsdk-915] Add a method to create geometry from longitude and latitude

- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceStoreShould.java
- core/src/main/java/org/hisp/dhis/android/core/enrollment/Enrollment.java
- core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentObjectRepository.java
- core/src/main/java/org/hisp/dhis/android/core/enrollment/internal/EnrollmentProjectionTransformer.java
- core/src/main/java/org/hisp/dhis/android/core/event/Event.java
- core/src/main/java/org/hisp/dhis/android/core/event/EventObjectRepository.java
- core/src/main/java/org/hisp/dhis/android/core/event/internal/EventProjectionTransformer.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstance.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceObjectRepository.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceProjectionTransformer.java
- core/src/sharedTest/java/org/hisp/dhis/android/core/data/enrollment/EnrollmentSamples.java
- core/src/sharedTest/java/org/hisp/dhis/android/core/data/trackedentity/EventSamples.java
- core/src/sharedTest/java/org/hisp/dhis/android/core/data/trackedentity/TrackedEntityInstanceSamples.java
[ANDROSDK-819](https://jira.dhis2.org/browse/ANDROSDK-819)
> fix: [ANDROSDK-819] Review type of createdAtClient and lastUpdatedAtClient fields

- core/src/main/java/org/hisp/dhis/android/core/arch/db/querybuilders/internal/WhereClauseBuilder.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceLocalQueryHelper.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQuery.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryRepositoryScope.java
- core/src/test/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceLocalQueryHelperShould.java
Solves [ANDROSDK-918](https://jira.dhis2.org/browse/ANDROSDK-918)
> feat: [ANDROSDK-918] Add state filter in TrackedEntityInstanceQuery

- core/src/androidTest/java/org/hisp/dhis/android/core/data/server/RealServerMother.java
- core/src/main/java/org/hisp/dhis/android/core/systeminfo/DHISVersion.java
- core/src/main/java/org/hisp/dhis/android/core/systeminfo/DHISVersionManager.java
Solves [ANDROSDK-923](https://jira.dhis2.org/browse/ANDROSDK-923)
> feat: [ANDROSDK-923] Support 2.33 login

- core/src/main/java/org/hisp/dhis/android/core/arch/api/payload/internal/Payload.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceRelationshipDownloadAndPersistCallFactory.java
Solves [ANDROSDK-828](https://jira.dhis2.org/browse/ANDROSDK-828)
> fix: [ANDROSDK-828] Clean relationships for failed teis

- core/build.gradle
- core/gradle.properties
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancePostCallMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/arch/helpers/UidsHelper.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancePostCall.java
Solves [ANDROSDK-920](https://jira.dhis2.org/browse/ANDROSDK-920)
> feat: [ANDROSDK-920] Page trackedEntityInstance upload

- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueEndpointCallRealIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueManagerRealIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueManager.java
Solves [ANDROSDK-905](https://jira.dhis2.org/browse/ANDROSDK-905)
> feat: [ANDROSDK-905] Refactor reserved values methods

- core/src/androidTest/java/org/hisp/dhis/android/core/program/internal/ProgramEndpointCallMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueManagerRealIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramTrackedEntityAttribute.java
- core/src/main/java/org/hisp/dhis/android/core/program/internal/ProgramModuleDownloader.java
- core/src/main/java/org/hisp/dhis/android/core/program/internal/ProgramParentUidsHelper.java
- core/src/main/java/org/hisp/dhis/android/core/program/internal/ProgramTrackedEntityAttributeFields.java
- core/src/main/java/org/hisp/dhis/android/core/program/internal/ProgramTrackedEntityAttributeHandler.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeCallFactory.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeFields.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeService.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityPackageDIModule.java
- core/src/sharedTest/java/org/hisp/dhis/android/core/data/program/ProgramTrackedEntityAttributeSamples.java
- core/src/sharedTest/java/org/hisp/dhis/android/core/data/server/Dhis2MockServer.java
- core/src/sharedTest/resources/program/programs.json
- core/src/sharedTest/resources/program/programs_complete.json
- core/src/sharedTest/resources/trackedentity/tracked_entity_attributes.json
- core/src/test/java/org/hisp/dhis/android/core/program/internal/ProgramModuleDownloaderShould.java
- core/src/test/java/org/hisp/dhis/android/core/program/internal/ProgramTrackedEntityAttributeHandlerShould.java
- core/src/test/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeHandlerShould.java
Solves [ANDROSDK-730](https://jira.dhis2.org/browse/ANDROSDK-730)
> feat: [ANDROSDK-730] TrackedEntityAttributes in separate call

- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceListDownloadAndPersistCallFactory.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityModule.java
Clean [ANDROSDK-916](https://jira.dhis2.org/browse/ANDROSDK-916)
> feat: [ANDROSDK-916-2] Clean androsdk-916

- core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramCollectionRepositoryMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramIndicatorCollectionRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageSection.java
- core/src/main/java/org/hisp/dhis/android/core/program/internal/ProgramIndicatorFields.java
- core/src/main/java/org/hisp/dhis/android/core/program/internal/ProgramStageSectionFields.java
- core/src/main/java/org/hisp/dhis/android/core/program/internal/ProgramStageSectionHandler.java
- core/src/sharedTest/resources/program/program_stages.json
- core/src/test/java/org/hisp/dhis/android/core/program/internal/ProgramStageSectionHandlerShould.java
Solves [ANDROSDK-673](https://jira.dhis2.org/browse/ANDROSDK-673)
> fix: [ANDROSDK-673] Prevent erase programIndicators in programStageSection

- core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramStageCollectionRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageCollectionRepository.java
Solves [ANDROSDK-925](https://jira.dhis2.org/browse/ANDROSDK-925)
> feat: [ANDROSDK-925] Add sortBySortOrder in programStages

- core/src/androidTest/java/org/hisp/dhis/android/core/d2manager/D2Factory.java
- core/src/main/java/org/hisp/dhis/android/core/arch/api/internal/ServerUrlInterceptor.java
- core/src/main/java/org/hisp/dhis/android/core/d2manager/D2Manager.java
- core/src/main/java/org/hisp/dhis/android/core/d2manager/OkHttpClientFactory.java
Solves [ANDROSDK-866](https://jira.dhis2.org/browse/ANDROSDK-866).
> fix: [ANDROSDK-866] Fix server URL redirection

- core/src/androidTest/java/org/hisp/dhis/android/core/dataelement/internal/DataElementStoreIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/testapp/dataelement/DataElementCollectionRepositoryMockIntegrationShould.java
- core/src/androidTest/java/org/hisp/dhis/android/testapp/trackedentity/TrackedEntityAttributeCollectionRepositoryMockIntegrationShould.java
- core/src/main/assets/migrations/59.yaml
- core/src/main/java/org/hisp/dhis/android/core/arch/db/access/DbOpenHelper.java
- core/src/main/java/org/hisp/dhis/android/core/dataelement/DataElement.java
- core/src/main/java/org/hisp/dhis/android/core/dataelement/DataElementCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/dataelement/internal/DataElementFields.java
- core/src/main/java/org/hisp/dhis/android/core/dataelement/internal/DataElementStore.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttribute.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeTableInfo.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityAttributeFields.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityAttributeStore.java
- core/src/sharedTest/java/org/hisp/dhis/android/core/data/dataelement/DataElementSamples.java
- core/src/sharedTest/java/org/hisp/dhis/android/core/data/trackedentity/TrackedEntityAttributeSamples.java
- core/src/sharedTest/resources/dataelement/data_element.json
- core/src/sharedTest/resources/dataelement/data_elements.json
- core/src/sharedTest/resources/trackedentity/tracked_entity_attribute.json
- core/src/sharedTest/resources/trackedentity/tracked_entity_attributes.json
- core/src/test/java/org/hisp/dhis/android/core/dataelement/DataElementShould.java
- core/src/test/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeShould.java
Solves [ANDROSDK-929](https://jira.dhis2.org/browse/ANDROSDK-929)
> feat: [ANDROSDK-929] FieldMask in DataElement and TrackedEntityAttribute

- core/src/androidTest/java/org/hisp/dhis/android/core/d2manager/D2ManagerRealIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/d2manager/D2Configuration.java
- core/src/main/java/org/hisp/dhis/android/core/d2manager/OkHttpClientFactory.java
Solves [ANDROSDK-926](https://jira.dhis2.org/browse/ANDROSDK-926).
> feat: [ANDROSDK-926] Add D2Configuration default values

- core/src/androidTest/java/org/hisp/dhis/android/testapp/organisationunit/OrganisationUnitCollectionRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitCollectionRepository.java
Solves [ANDROSDK-935](https://jira.dhis2.org/browse/ANDROSDK-935).
> feat: [ANDROSDK-935] Filter organisationUnits by programUids

- core/src/androidTest/java/org/hisp/dhis/android/core/fileresource/internal/FileResourceCallRealIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/fileresource/FileResourceCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/fileresource/FileResourceObjectRepository.java
- core/src/main/java/org/hisp/dhis/android/core/fileresource/internal/FileResourceEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/fileresource/internal/FileResourceModuleDownloader.java
- core/src/main/java/org/hisp/dhis/android/core/fileresource/internal/FileResourceModuleWiper.java
- core/src/main/java/org/hisp/dhis/android/core/fileresource/internal/FileResourcePostCall.java
- core/src/main/java/org/hisp/dhis/android/core/fileresource/internal/FileResourceStoreImpl.java
- core/src/main/java/org/hisp/dhis/android/core/wipe/internal/D2ModuleWipers.java
Solves [ANDROSDK-932](https://jira.dhis2.org/browse/ANDROSDK-932).
> feat: [androsdk-932] Avoid download existing files

- core/src/androidTest/java/org/hisp/dhis/android/core/systeminfo/SystemInfoCallMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/arch/api/executors/internal/RxAPICallExecutor.java
- core/src/main/java/org/hisp/dhis/android/core/arch/api/executors/internal/RxAPICallExecutorImpl.java
- core/src/main/java/org/hisp/dhis/android/core/arch/call/internal/CompletableProvider.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadOnlyWithDownloadObjectRepository.java
- core/src/main/java/org/hisp/dhis/android/core/arch/repositories/object/internal/ReadOnlyFirstObjectWithDownloadRepositoryImpl.java
- core/src/main/java/org/hisp/dhis/android/core/domain/aggregated/data/AggregatedDataCall.java
- core/src/main/java/org/hisp/dhis/android/core/event/internal/EventWithLimitCallFactory.java
- core/src/main/java/org/hisp/dhis/android/core/systeminfo/SystemInfoCall.java
- core/src/main/java/org/hisp/dhis/android/core/systeminfo/internal/SystemInfoModuleDownloader.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueManager.java
- core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceWithLimitCallFactory.java
- core/src/main/java/org/hisp/dhis/android/core/user/internal/UserAuthenticateCallFactory.java
- core/src/test/java/org/hisp/dhis/android/core/systeminfo/SystemInfoCallShould.java
- core/src/test/java/org/hisp/dhis/android/core/user/internal/UserAuthenticateCallUnitShould.java
Solves [ANDROSDK-906](https://jira.dhis2.org/browse/ANDROSDK-906).
> fix: [ANDROSDK-906] Reserved values .getValue() don't log offline

- core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramStageDataElementCollectionRepositoryMockIntegrationShould.java
- core/src/main/java/org/hisp/dhis/android/core/common/ValueTypeDeviceRenderingTableInfo.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramModule.java
- core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageDataElementCollectionRepository.java
- core/src/main/java/org/hisp/dhis/android/core/program/internal/ProgramStageDataElementEntityDIModule.java
- core/src/main/java/org/hisp/dhis/android/core/program/internal/ValueTypeRenderingChildrenAppender.java
- core/src/sharedTest/resources/program/program_stages.json
Solves [ANDROSDK-930](https://jira.dhis2.org/browse/ANDROSDK-930).
> feat: [androsdk-930] Add ProgramStageDataElement repository

- core/src/main/java/org/hisp/dhis/android/core/event/EventCreateProjection.java
Solves [ANDROSDK-937](https://jira.dhis2.org/browse/ANDROSDK-937)
> fix: [ANDROSDK-937] Nullable AOC in Event projection
