dhis2/dhis2-android-sdk

core/src/main/java/org/hisp/dhis/android/core/fileresource/internal/FileResourceCallFactory.java
Solves [ANDROSDK-933](https://jira.dhis2.org/browse/ANDROSDK-933).
=> fix: [androsdk-933] Avoid to fail download if a file call fails

core/src/androidTest/java/org/hisp/dhis/android/core/fileresource/internal/FileResourceCallRealIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/testapp/fileresource/FileResourceCollectionRepositoryMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/fileresource/internal/FileResourcePostCall.java, core/src/main/java/org/hisp/dhis/android/core/fileresource/internal/FileResourceUtil.java
Solves [ANDROSDK-938](https://jira.dhis2.org/browse/ANDROSDK-938).
=> fix: [androsdk-938] Add content types to file resources

core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramTrackedEntityAttributeCollectionRepositoryMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/program/ProgramModule.java, core/src/main/java/org/hisp/dhis/android/core/program/ProgramTrackedEntityAttributeCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/program/internal/DataElementValueTypeRenderingChildrenAppender.java, core/src/main/java/org/hisp/dhis/android/core/program/internal/ProgramStageDataElementEntityDIModule.java, core/src/main/java/org/hisp/dhis/android/core/program/internal/ProgramTrackedEntityAttributeEntityDIModule.java, core/src/main/java/org/hisp/dhis/android/core/program/internal/ProgramTrackedEntityAttributeFields.java, core/src/main/java/org/hisp/dhis/android/core/program/internal/ProgramTrackedEntityAttributeValueTypeRenderingChildrenAppender.java, core/src/sharedTest/resources/program/programs.json
Solves [ANDROSDK-931](https://jira.dhis2.org/browse/ANDROSDK-931).
=> feat: [androsdk-931] Add ProgramTrackedEntityAttribute collection repository

core/src/androidTest/java/org/hisp/dhis/android/testapp/organisationunit/OrganisationUnitCollectionRepositoryMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitCollectionRepository.java
Solves [ANDROSDK-939](https://jira.dhis2.org/browse/ANDROSDK-939).
=> feat: [androsdk-939] Add filter by dataSets on OrganisationUnit repository

core/src/androidTest/java/org/hisp/dhis/android/core/fileresource/internal/FileResourceCallRealIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/testapp/fileresource/FileResourceCollectionRepositoryMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/fileresource/internal/FileResourceCallFactory.java, core/src/main/java/org/hisp/dhis/android/core/fileresource/internal/FileResourcePostCall.java, core/src/main/java/org/hisp/dhis/android/core/fileresource/internal/FileResourceProjectionTransformer.java, core/src/main/java/org/hisp/dhis/android/core/fileresource/internal/FileResourceUtil.java
Solves [ANDROSDK-941](https://jira.dhis2.org/browse/ANDROSDK-941).
=> feat: [androsdk-941] Add complete path on file resources

core/src/androidTest/java/org/hisp/dhis/android/core/arch/repositories/collection/CollectionRepositoryOneMethodMockIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/arch/repositories/collection/IdentifiableCollectionFiltersMockIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadOnlyCollectionRepositoryImplIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadOnlyIdentifiableCollectionRepositoryImplIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/testapp/category/CategoryComboCollectionRepositoryMockIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/testapp/category/CategoryModuleMockIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/testapp/category/CategoryOptionComboCollectionRepositoryMockIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/testapp/dataset/DataSetModuleMockIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/testapp/maintenance/MaintenanceMockIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/testapp/option/OptionSetCollectionRepositoryMockIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/testapp/organisationunit/OrganisationUnitCollectionRepositoryMockIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramCollectionRepositoryMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/children/internal/ChildrenAppenderExecutor.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/children/internal/ChildrenSelection.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/internal/ReadOnlyCollectionRepositoryImpl.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/object/internal/ReadOnlyObjectRepositoryImpl.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/object/internal/ReadWriteWithUidDataObjectRepositoryImpl.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/scope/internal/RepositoryScopeHelper.java, core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipObjectRepository.java, core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipTypeCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/relationship/internal/RelationshipTypeFields.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryDataSource.java
Solves [ANDROSDK-940](https://jira.dhis2.org/browse/ANDROSDK-940).
=> feat: [ANDROSDK-940] Remove withAllChildren() methods

core/src/main/java/org/hisp/dhis/android/core/dataset/internal/DataSetCompleteRegistrationImportHandler.java
Solves [ANDROSDK-945](https://jira.dhis2.org/browse/ANDROSDK-945).
=> fix: [ANDROSDK-945] Fix DataSetCompleteRegistrationImportHandler

core/src/main/java/org/hisp/dhis/android/core/dataelement/DataElement.java, core/src/test/java/org/hisp/dhis/android/core/dataelement/DataElementShould.java
Partially [ANDROSDK-942](https://jira.dhis2.org/browse/ANDROSDK-942)
=> feat: [ANDROSDK-942] Remove access from DataElement

core/build.gradle, core/gradle.properties, core/src/main/java/org/hisp/dhis/android/core/event/internal/EventEndpointCallFactory.java, core/src/main/java/org/hisp/dhis/android/core/event/internal/EventService.java, core/src/test/java/org/hisp/dhis/android/core/event/internal/EventEndpointCallShould.java
Solves [ANDROSDK-946](https://jira.dhis2.org/browse/ANDROSDK-946)
=> fix: [HOTBUGFIXING] Release 0.17.4

core/src/main/java/org/hisp/dhis/android/core/domain/metadata/MetadataCall.java, core/src/test/java/org/hisp/dhis/android/core/domain/metadata/MetadataCallShould.java
Solves [ANDROSDK-453](https://jira.dhis2.org/browse/ANDROSDK-453).
=> feat: [androsdk-453] Delete foreign key violation records before each metadata download

core/src/main/java/org/hisp/dhis/android/core/event/internal/EventHandler.java, core/src/test/java/org/hisp/dhis/android/core/event/internal/EventHandlerShould.java
Solves [ANDROSDK-947](https://jira.dhis2.org/browse/ANDROSDK-947)
=> fix: [ANDROSDK-947] Do not persist datavalues on deleted events

core/src/androidTest/java/org/hisp/dhis/android/core/datavalue/internal/DataValuePostCallRealIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/event/internal/EventPostCallMockIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstancePostCallMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/dataset/internal/DataSetCompleteRegistrationPostCall.java, core/src/main/java/org/hisp/dhis/android/core/datavalue/internal/DataValuePostCall.java, core/src/main/java/org/hisp/dhis/android/core/event/internal/EventPostCall.java, core/src/main/java/org/hisp/dhis/android/core/fileresource/internal/FileResourceCall.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstancePostCall.java
Solves [ANDROSDK-903](https://jira.dhis2.org/browse/ANDROSDK-903).
=> feat: [ANDROSDK-903] Download system info before post

core/src/androidTest/java/org/hisp/dhis/android/core/enrollment/note/NotePostCallRealIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/fileresource/internal/FileResourcePostCall.java
Solves [ANDROSDK-934](https://jira.dhis2.org/browse/ANDROSDK-934).
=> fix: [ANDROSDK-934] FileResourceCall: call SystemInfo only if some resource to download

core/src/androidTest/java/org/hisp/dhis/android/testapp/maintenance/ForeignKeyViolationCollectionRepositoryMockIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/testapp/maintenance/MaintenanceMockIntegrationShould.java, core/src/main/assets/migrations/61.yaml, core/src/main/java/org/hisp/dhis/android/core/arch/db/access/DbOpenHelper.java, core/src/sharedTest/resources/dataset/data_set_complete_registrations.json
Solves [ANDROSDK-864](https://jira.dhis2.org/browse/ANDROSDK-864).
=> fix: [androsdk-864] Fix the DataSetCompleteRegistration table period foreign key

core/plugins/gradle-mvn-push.gradle, core/src/main/java/org/hisp/dhis/android/core/dataapproval/DataApprovalTableInfo.java, core/src/main/java/org/hisp/dhis/android/core/dataapproval/internal/DataApprovalFields.java, core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipTypeTableInfo.java, core/src/main/java/org/hisp/dhis/android/core/relationship/internal/RelationshipTypeFields.java
Solves [ANDROSDK-944](https://jira.dhis2.org/browse/ANDROSDK-944).
=> feat: [androsdk-944] Exclude internal packages from javadoc generation task

core/src/main/java/org/hisp/dhis/android/core/datavalue/DataValueObjectRepository.java, core/src/main/java/org/hisp/dhis/android/core/enrollment/internal/EnrollmentProjectionTransformer.java, core/src/main/java/org/hisp/dhis/android/core/event/internal/EventProjectionTransformer.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceProjectionTransformer.java
Solves [ANDROSDK-955](https://jira.dhis2.org/browse/ANDROSDK-955)
=> fix: [ANDROSDK-955] Default to deleted=false on data creation

core/src/androidTest/java/org/hisp/dhis/android/core/domain/aggregated/data/AggregatedDataCallMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/arch/api/payload/internal/Payload.java, core/src/main/java/org/hisp/dhis/android/core/domain/aggregated/data/AggregatedDataCall.java, core/src/sharedTest/resources/dataset/data_sets.json
Solves [ANDROSDK-949](https://jira.dhis2.org/browse/ANDROSDK-949).
=> feat: [ANDROSDK-949] Download aggregated data by periodType

core/src/androidTest/java/org/hisp/dhis/android/testapp/dataset/DataSetInstanceCollectionRepositoryMockIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/testapp/datavalue/DataValueCollectionRepositoryMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/dataset/internal/DataSetInstanceSQLStatementBuilder.java, core/src/sharedTest/resources/datavalue/data_values.json
Solves [ANDROSDK-956](https://jira.dhis2.org/browse/ANDROSDK-956)
=> fix: [ANDROSDK-956] Fix wrong coc in DataSetInstances

core/src/main/java/org/hisp/dhis/android/core/datavalue/DataValueCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/datavalue/internal/DataValueImportHandler.java, core/src/main/java/org/hisp/dhis/android/core/datavalue/internal/DataValuePostCall.java
Solves [ANDROSDK-953](https://jira.dhis2.org/browse/ANDROSDK-953).
=> fix: [ANDROSDK-953] Apply filters in DataValuePostCall

doc/dhis2_android_sdk_user_guide_INDEX.md
Solves [ANDROSDK-950](https://jira.dhis2.org/browse/ANDROSDK-950).
=> feat: [androsdk-950] Add File resources documentation

core/src/androidTest/java/org/hisp/dhis/android/core/period/PeriodMockIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/testapp/dataset/DataSetCollectionRepositoryMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/domain/aggregated/data/AggregatedDataCall.java, core/src/main/java/org/hisp/dhis/android/core/period/internal/AbstractPeriodGenerator.java, core/src/main/java/org/hisp/dhis/android/core/period/internal/PeriodForDataSetManager.java, core/src/main/java/org/hisp/dhis/android/core/period/internal/PeriodHandler.java, core/src/sharedTest/resources/dataset/data_sets.json
Solves [ANDROSDK-957](https://jira.dhis2.org/browse/ANDROSDK-957).
=> feat: [ANDROSDK-957] Download aggregated data for open future periods

core/src/androidTest/java/org/hisp/dhis/android/core/organisationunit/internal/OrganisationUnitCallMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitInternalAccessor.java, core/src/main/java/org/hisp/dhis/android/core/organisationunit/internal/OrganisationUnitDisplayPathGenerator.java, core/src/main/java/org/hisp/dhis/android/core/organisationunit/internal/OrganisationUnitEntityDIModule.java, core/src/test/java/org/hisp/dhis/android/core/organisationunit/internal/OrganisationUnitDisplayPathGeneratorShould.java
Solves [ANDROSDK-966](https://jira.dhis2.org/browse/ANDROSDK-966).
=> refactor: [androsdk-966] Rename OrganisationUnitAncestorAccessor to OrganisationUnitInternalAccessor

core/src/androidTest/java/org/hisp/dhis/android/core/utils/integration/mock/BaseMockIntegrationTestFullDispatcher.java, core/src/androidTest/java/org/hisp/dhis/android/testapp/maintenance/D2ErrorCollectionRepositoryMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/arch/api/executors/internal/APIErrorMapper.java, core/src/main/java/org/hisp/dhis/android/core/maintenance/D2Error.java, core/src/main/java/org/hisp/dhis/android/core/maintenance/D2ErrorCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/maintenance/D2ErrorTableInfo.java, core/src/main/java/org/hisp/dhis/android/core/maintenance/internal/D2ErrorStore.java, core/src/sharedTest/java/org/hisp/dhis/android/core/data/maintenance/D2ErrorSamples.java
Solves [ANDROSDK-967](https://jira.dhis2.org/browse/ANDROSDK-967).
=> feat: [ANDROSDK-967] Remove uid and resourceType fields from D2Error

core/src/main/java/org/hisp/dhis/android/core/dataset/internal/DataSetCompleteRegistrationPostCall.java, core/src/main/java/org/hisp/dhis/android/core/datavalue/internal/DataValuePostCall.java, core/src/main/java/org/hisp/dhis/android/core/domain/metadata/MetadataCall.java, core/src/main/java/org/hisp/dhis/android/core/event/internal/EventPostCall.java, core/src/main/java/org/hisp/dhis/android/core/fileresource/internal/FileResourceCall.java, core/src/main/java/org/hisp/dhis/android/core/fileresource/internal/FileResourcePostCall.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstancePostCall.java
Solves [ANDROSDK-968](https://jira.dhis2.org/browse/ANDROSDK-968).
=> fix: [ANDROSDK-968] Sync error: Sequence contains more than one element

core/src/androidTest/java/org/hisp/dhis/android/core/option/OptionCallShould.java, core/src/main/java/org/hisp/dhis/android/core/arch/d2/internal/D2DIComponent.java, core/src/main/java/org/hisp/dhis/android/core/option/OptionSet.java, core/src/main/java/org/hisp/dhis/android/core/option/OptionSetCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/option/internal/OptionEndpointCallFactory.java, core/src/main/java/org/hisp/dhis/android/core/option/internal/OptionEntityDIModule.java, core/src/main/java/org/hisp/dhis/android/core/option/internal/OptionHandler.java, core/src/main/java/org/hisp/dhis/android/core/option/internal/OptionPackageDIModule.java, core/src/main/java/org/hisp/dhis/android/core/option/internal/OptionService.java, core/src/main/java/org/hisp/dhis/android/core/option/internal/OptionSetCallFactory.java, core/src/main/java/org/hisp/dhis/android/core/option/internal/OptionSetEntityDIModule.java, core/src/main/java/org/hisp/dhis/android/core/option/internal/OptionSetHandler.java, core/src/main/java/org/hisp/dhis/android/core/option/internal/OptionSetService.java, core/src/main/java/org/hisp/dhis/android/core/program/internal/ProgramModuleDownloader.java, core/src/sharedTest/java/org/hisp/dhis/android/core/data/server/Dhis2MockServer.java, core/src/sharedTest/resources/option/option_sets.json, core/src/sharedTest/resources/option/options.json, core/src/test/java/org/hisp/dhis/android/core/option/internal/OptionHandlerShould.java, core/src/test/java/org/hisp/dhis/android/core/program/internal/ProgramModuleDownloaderShould.java
Solves [ANDROSDK-959](https://jira.dhis2.org/browse/ANDROSDK-959).
=> refactor: [androsdk-959] Deprecate options in optionSet and split options and optionSets in two calls

core/src/main/java/org/hisp/dhis/android/core/arch/repositories/object/ReadWriteObjectRepository.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/object/internal/ReadWriteWithUidDataObjectRepositoryImpl.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/object/internal/ReadWriteWithValueObjectRepositoryImpl.java, core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentObjectRepository.java, core/src/main/java/org/hisp/dhis/android/core/event/EventObjectRepository.java, core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipObjectRepository.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceObjectRepository.java
Solves [ANDROSDK-912](https://jira.dhis2.org/browse/ANDROSDK-912).
=> feat: [androsdk-912] Add deleteIfExist and blockingDeleteIfExist methods to read-write object repositories

core/src/main/java/org/hisp/dhis/android/core/arch/db/stores/internal/IdentifiableDataObjectStoreImpl.java
Solves [ANDROSDK-979](https://jira.dhis2.org/browse/ANDROSDK-979)
=> fix: [ANDROSDK-979] Modifications in data synced by sms

core/src/androidTest/java/org/hisp/dhis/android/core/utils/integration/mock/BaseMockIntegrationTestFullDispatcher.java, core/src/main/java/org/hisp/dhis/android/core/user/UserModule.java
Solves [ANDROSDK-969](https://jira.dhis2.org/browse/ANDROSDK-969).
=> feat: [ANDROSDK-969] Add blocking methods to UserModule

core/src/androidTest/java/org/hisp/dhis/android/testapp/legendset/LegendCollectionRepositoryMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/legendset/LegendCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/legendset/LegendSetModule.java, core/src/main/java/org/hisp/dhis/android/core/legendset/LegendTableInfo.java, core/src/main/java/org/hisp/dhis/android/core/legendset/internal/LegendFields.java, core/src/sharedTest/resources/program/programs.json
Solves [ANDROSDK-975](https://jira.dhis2.org/browse/ANDROSDK-975)
=> feat: [ANDROSDK-975] Add LegendCollectionRepository

core/src/androidTest/java/org/hisp/dhis/android/testapp/dataset/DataSetCollectionRepositoryMockIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/testapp/dataset/DataSetModuleMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/dataset/DataSet.java, core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetInternalAccessor.java, core/src/main/java/org/hisp/dhis/android/core/dataset/internal/DataSetEntityDIModule.java, core/src/main/java/org/hisp/dhis/android/core/dataset/internal/DataSetHandler.java, core/src/test/java/org/hisp/dhis/android/core/dataset/internal/DataSetHandlerShould.java
Solves [ANDROSDK-972](https://jira.dhis2.org/browse/ANDROSDK-972)
=> feat: [ANDROSDK-972] Package-private sections in DataSet

core/src/androidTest/java/org/hisp/dhis/android/testapp/dataset/DataSetCollectionRepositoryMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetCollectionRepository.java
Solves [ANDROSDK-976](https://jira.dhis2.org/browse/ANDROSDK-976).
=> feat: [androsdk-976] Add by organisation unit uid methods on DataSetCollectionRepository

core/src/androidTest/java/org/hisp/dhis/android/core/arch/repositories/collection/CollectionRepositoryOneMethodMockIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/testapp/category/CategoryComboCollectionRepositoryMockIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/testapp/category/CategoryModuleMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/category/CategoryCombo.java, core/src/main/java/org/hisp/dhis/android/core/category/CategoryComboInternalAccessor.java, core/src/main/java/org/hisp/dhis/android/core/category/internal/CategoryComboEntityDIModule.java, core/src/main/java/org/hisp/dhis/android/core/category/internal/CategoryComboHandler.java, core/src/test/java/org/hisp/dhis/android/core/category/internal/CategoryComboHandlerShould.java
Solves [ANDROSDK-973](https://jira.dhis2.org/browse/ANDROSDK-973).
=> refactor: [androsdk-973] Hide category option combos access from category combo

core/src/androidTest/java/org/hisp/dhis/android/testapp/organisationunit/OrganisationUnitCollectionRepositoryMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnit.java, core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/organisationunit/internal/OrganisationUnitDataSetChildrenAppender.java, core/src/main/java/org/hisp/dhis/android/core/organisationunit/internal/OrganisationUnitHandlerImpl.java, core/src/main/java/org/hisp/dhis/android/core/organisationunit/internal/OrganisationUnitProgramChildrenAppender.java, core/src/test/java/org/hisp/dhis/android/core/organisationunit/internal/OrganisationUnitHandlerShould.java
Solves [ANDROSDK-977](https://jira.dhis2.org/browse/ANDROSDK-977).
=> refactor: [androsdk-977] Use ObjectWithUids instead Program and DataSet on OrganisationUnit

core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/api/BreakTheGlassAPIShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/api/TrackedEntityInstanceAPIShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/api/TrackedEntityInstanceUtils.java, core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceCallMockIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstancePostCallMockIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/testapp/enrollment/EnrollmentCollectionRepositoryMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/enrollment/Enrollment.java, core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentInternalAccessor.java, core/src/main/java/org/hisp/dhis/android/core/enrollment/internal/EnrollmentEntityDIModule.java, core/src/main/java/org/hisp/dhis/android/core/enrollment/internal/EnrollmentFields.java, core/src/main/java/org/hisp/dhis/android/core/enrollment/internal/EnrollmentHandler.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstancePostCall.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceUidHelperImpl.java, core/src/test/java/org/hisp/dhis/android/core/enrollment/internal/EnrollmentHandlerShould.java, core/src/test/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceUidHelperShould.java
Solves [ANDROSDK-982](https://jira.dhis2.org/browse/ANDROSDK-982).
=> refactor: [androsdk-982] Hide events on enrollment

core/src/main/java/org/hisp/dhis/android/core/arch/helpers/UidsHelper.java
Solves [ANDROSDK-985](https://jira.dhis2.org/browse/ANDROSDK-985)
=> refactor: [ANDROSDK-985] Make uidHelper generic to UidInterface

core/src/main/java/org/hisp/dhis/android/core/arch/helpers/CollectionsHelper.java, core/src/main/java/org/hisp/dhis/android/core/dataset/internal/DataSetCompleteRegistrationPostCall.java, core/src/main/java/org/hisp/dhis/android/core/dataset/internal/DataSetCompleteRegistrationService.java
Solves [ANDROSDK-991](https://jira.dhis2.org/browse/ANDROSDK-991)
=> fix: [ANDROSDK-991] Add missing parameters to CompleteRegistration post call

core/src/main/java/org/hisp/dhis/android/core/user/internal/UserAuthenticateCallFactory.java, core/src/test/java/org/hisp/dhis/android/core/user/internal/UserAuthenticateCallUnitShould.java
Solves [ANDROSDK-993](https://jira.dhis2.org/browse/ANDROSDK-993)
=> fix: [ANDROSDK-993] Fix login offline (remove api suffix)

core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramStageCollectionRepositoryMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/program/ProgramStage.java, core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageInternalAccessor.java, core/src/main/java/org/hisp/dhis/android/core/program/internal/ProgramParentUidsHelper.java, core/src/main/java/org/hisp/dhis/android/core/program/internal/ProgramStageDataElementChildrenAppender.java, core/src/main/java/org/hisp/dhis/android/core/program/internal/ProgramStageEndpointCallFactory.java, core/src/main/java/org/hisp/dhis/android/core/program/internal/ProgramStageHandler.java, core/src/main/java/org/hisp/dhis/android/core/program/internal/ProgramStageSectionChildrenAppender.java, core/src/test/java/org/hisp/dhis/android/core/program/ProgramStageShould.java, core/src/test/java/org/hisp/dhis/android/core/program/internal/ProgramStageHandlerShould.java
Solves [ANDROSDK-990](https://jira.dhis2.org/browse/ANDROSDK-990).
=> refactor: [androsdk-990] Deprecate ProgramStageSections and ProgramStageDataElements in ProgramStage

core/src/androidTest/java/org/hisp/dhis/android/core/arch/repositories/collection/IdentifiableCollectionFiltersMockIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/testapp/category/CategoryComboCollectionRepositoryMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/internal/BaseAbstractFilterConnector.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/internal/BaseStringFilterConnector.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/internal/StringFilterConnector.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceLocalQueryHelper.java, core/src/sharedTest/resources/category/category_combos.json
Solves [ANDROSDK-997](https://jira.dhis2.org/browse/ANDROSDK-997).
=> fix: [androsdk-997] Escape single quotes on Strings filter connectors

core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityAttributeReservedValueEndpointCallRealIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueManager.java
Solves [ANDROSDK-998](https://jira.dhis2.org/browse/ANDROSDK-998).
=> feat: [androsdk-998] Add count methods to the TEAReservedValueManager

core/src/androidTest/java/org/hisp/dhis/android/testapp/dataset/DataSetCompleteRegistrationObjectRepositoryMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetCompleteRegistrationCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetCompleteRegistrationObjectRepository.java
[ANDROSDK-964](https://jira.dhis2.org/browse/ANDROSDK-964)
=> feat: [ANDROSDK-964] Create DataSetCompleteRegistrations ojbect repository

core/src/main/java/org/hisp/dhis/android/core/user/internal/IsUserLoggedInCallableFactory.java, core/src/main/java/org/hisp/dhis/android/core/user/internal/UserAuthenticateCallFactory.java, core/src/main/java/org/hisp/dhis/android/core/wipe/internal/WipeDIModule.java, core/src/main/java/org/hisp/dhis/android/core/wipe/internal/WipeModuleImpl.java, core/src/test/java/org/hisp/dhis/android/core/user/internal/IsUserLoggedInCallableShould.java, core/src/test/java/org/hisp/dhis/android/core/user/internal/UserAuthenticateCallUnitShould.java, core/src/test/java/org/hisp/dhis/android/core/wipe/internal/WipeModuleShould.java
Solves [ANDROSDK-1003](https://jira.dhis2.org/browse/ANDROSDK-1003)
=> fix: [ANDROSDK-1003] Wipe credentials when wipe metadata

core/src/main/java/org/hisp/dhis/android/core/datavalue/DataValueCollectionRepository.java
Solves [ANDROSDK-954](https://jira.dhis2.org/browse/ANDROSDK-954)
=> fix: [ANDROSDK-954] Include error and warning states in aggregated

doc/content/user/modules-and-repositories.md
Solves [ANDROSDK-1011](https://jira.dhis2.org/browse/ANDROSDK-1011).
=> feat: [ANDROSDK-1011] Update module list

core/src/main/java/org/hisp/dhis/android/core/common/State.java, doc/content/user/workflow.md
Solves [ANDROSDK-1013](https://jira.dhis2.org/browse/ANDROSDK-1013)
=> feat: [ANDROSDK-1013] Update metadata sync and state doc

doc/content/user/workflow.md
Solves [ANDROSDK-1014](https://jira.dhis2.org/browse/ANDROSDK-1014).
=> feat: [androsdk-1014] Update tracker data download documentation

core/src/main/java/org/hisp/dhis/android/core/D2Manager.java
Solves [ANDROSDK-961](https://jira.dhis2.org/browse/ANDROSDK-961).
=> feat: [ANDROSDK-961-2] Add D2Manager Javadoc

doc/content/user/workflow.md
Solves [ANDROSDK-1015](https://jira.dhis2.org/browse/ANDROSDK-1015).
=> feat: [androsdk-1015] Update aggregated download documentation

doc/content/user/workflow.md
Solves [ANDROSDK-1016](https://jira.dhis2.org/browse/ANDROSDK-1016)
=> feat: [androsdk-1016] Update aggregated data creation documentation

doc/content/user/workflow.md
Solves [ANDROSDK-1017](https://jira.dhis2.org/browse/ANDROSDK-1017)
=> feat: [ANDROSDK-1017] Update datasetinstance section

core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/internal/BaseAbstractFilterConnector.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/internal/BooleanFilterConnector.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/internal/DateFilterConnector.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/internal/DoubleFilterConnector.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/internal/IntegerFilterConnector.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/internal/LongFilterConnector.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/internal/StringFilterConnector.java
Solves partially [ANDROSDK-1021](https://jira.dhis2.org/browse/ANDROSDK-1021).
=> feat: [ANDROSDK-1021] Add Javadoc to filter connectors

doc/content/user/overview.md
Solves [ANDROSDK-1010](https://jira.dhis2.org/browse/ANDROSDK-1010)
=> feat: [ANDROSDK-1010] SDK overview

doc/content/user/compatibility-strategy.md, doc/content/user/workflow.md
Solves [ANDROSDK-1012](https://jira.dhis2.org/browse/ANDROSDK-1012)
=> feat: [ANDROSDK-1012] Update workflow overview

core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/CollectionRepositoryUpload.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadOnlyCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadOnlyWithDownloadObjectRepository.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadOnlyWithUidCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadOnlyWithUploadCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadWriteCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadWriteWithUidCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadWriteWithUploadWithUidCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/internal/ReadOnlyCollectionRepositoryImpl.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/internal/ReadOnlyWithUidCollectionRepositoryImpl.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/internal/ReadWriteWithUidCollectionRepositoryImpl.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/object/ReadOnlyObjectRepository.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/object/ReadWriteObjectRepository.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/object/internal/ReadOnlyFirstObjectWithDownloadRepositoryImpl.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/object/internal/ReadOnlyObjectRepositoryImpl.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/object/internal/ReadWriteWithUidDataObjectRepositoryImpl.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/object/internal/ReadWriteWithValueObjectRepositoryImpl.java
Solves [ANDROSDK-1021](https://jira.dhis2.org/browse/ANDROSDK-1021).
=> feat: [ANDROSDK-1021] Add Javadoc to repository methods

core/src/androidTest/java/org/hisp/dhis/android/core/systeminfo/SystemInfoCallMockIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/systeminfo/internal/SystemInfoStoreIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/arch/d2/internal/D2DIComponent.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadOnlyWithDownloadObjectRepository.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/object/internal/ReadOnlyFirstObjectWithDownloadRepositoryImpl.java, core/src/main/java/org/hisp/dhis/android/core/domain/aggregated/data/internal/AggregatedDataCall.java, core/src/main/java/org/hisp/dhis/android/core/event/internal/EventWithLimitCallFactory.java, core/src/main/java/org/hisp/dhis/android/core/systeminfo/DHISVersionManager.java, core/src/main/java/org/hisp/dhis/android/core/systeminfo/SystemInfoTableInfo.java, core/src/main/java/org/hisp/dhis/android/core/systeminfo/internal/DHISVersionManagerImpl.java, core/src/main/java/org/hisp/dhis/android/core/systeminfo/internal/SystemInfoCall.java, core/src/main/java/org/hisp/dhis/android/core/systeminfo/internal/SystemInfoEntityDIModule.java, core/src/main/java/org/hisp/dhis/android/core/systeminfo/internal/SystemInfoFields.java, core/src/main/java/org/hisp/dhis/android/core/systeminfo/internal/SystemInfoModuleDownloader.java, core/src/main/java/org/hisp/dhis/android/core/systeminfo/internal/SystemInfoPackageDIModule.java, core/src/main/java/org/hisp/dhis/android/core/systeminfo/internal/SystemInfoService.java, core/src/main/java/org/hisp/dhis/android/core/systeminfo/internal/SystemInfoStore.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueManager.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceWithLimitCallFactory.java, core/src/main/java/org/hisp/dhis/android/core/user/internal/UserAuthenticateCallFactory.java, core/src/test/java/org/hisp/dhis/android/core/systeminfo/internal/SystemInfoCallShould.java, core/src/test/java/org/hisp/dhis/android/core/user/internal/UserAuthenticateCallUnitShould.java
Solves [CNR-1027](https://jira.dhis2.org/browse/ANDROSDK-1027).
=> refactor: [CNR-1027] Hide boolean storeErrors in repositories

core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/internal/ReadOnlyCollectionRepositoryImpl.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/object/internal/ReadOnlyObjectRepositoryImpl.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/object/internal/ReadOnlyOneObjectRepositoryImpl.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/object/internal/ReadWriteWithValueObjectRepositoryImpl.java, core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetCompleteRegistrationCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetCompleteRegistrationObjectRepository.java, core/src/main/java/org/hisp/dhis/android/core/datavalue/DataValueCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/datavalue/DataValueObjectRepository.java, core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentObjectRepository.java, core/src/main/java/org/hisp/dhis/android/core/event/EventCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/event/EventObjectRepository.java, core/src/main/java/org/hisp/dhis/android/core/fileresource/FileResourceCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeValueObjectRepository.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityDataValueObjectRepository.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceObjectRepository.java
Solves [ANDROSDK-1031](https://jira.dhis2.org/browse/ANDROSDK-1031).
=> refactor: [ANDROSDK-1031] Rename getWithoutChildren method and make protected

core/src/main/java/org/hisp/dhis/android/core/arch/helpers/AccessHelper.java, core/src/main/java/org/hisp/dhis/android/core/arch/helpers/CollectionsHelper.java, core/src/main/java/org/hisp/dhis/android/core/arch/helpers/CoordinateHelper.java, core/src/main/java/org/hisp/dhis/android/core/arch/helpers/FileResizerHelper.java, core/src/main/java/org/hisp/dhis/android/core/arch/helpers/FileResourceDirectoryHelper.java, core/src/main/java/org/hisp/dhis/android/core/arch/helpers/GeometryHelper.java, core/src/main/java/org/hisp/dhis/android/core/arch/helpers/UidsHelper.java, core/src/main/java/org/hisp/dhis/android/core/arch/helpers/UserHelper.java
Solves [ANDROSDK-1022](https://jira.dhis2.org/browse/ANDROSDK-1022).
Also renames a `GeometryHelper` method from `containtsAMultiPolygon()` to `containsAMultiPolygon()`.
=> feat: [androsdk-1022] Add Javadoc to helper classes

doc/content/user/error-management.md
Solves [ANDROSDK-1029](https://jira.dhis2.org/browse/ANDROSDK-1029).
=> feat: [androsdk-1029] Update error management documentation.

doc/content/dev/architecture.md, doc/content/dev/development.md, doc/content/user/compatibility-strategy.md, doc/content/user/workflow.md
Solves [ANDROSDK-1028](https://jira.dhis2.org/browse/ANDROSDK-1028).
=> feat: [ANDROSDK-1028] Improve arch and dev documentation

core/src/main/java/org/hisp/dhis/android/core/sms/domain/interactor/ConfigCase.java, core/src/main/java/org/hisp/dhis/android/core/sms/domain/interactor/QrCodeCase.java, core/src/main/java/org/hisp/dhis/android/core/sms/domain/interactor/SmsSubmitCase.java, doc/content/user/sms.md
Solves [ANDROSDK-1018](https://jira.dhis2.org/browse/ANDROSDK-1018).
=> feat: [androsdk-1018] Update the SMS documentation.

README.md
Solves [ANDROSDK-1026](https://jira.dhis2.org/browse/ANDROSDK-1026)
=> feat: [ANDROSDK-1026] Basic readme skeleton

doc/content/user/compatibility-strategy.md, doc/content/user/modules-and-repositories.md, doc/content/user/object-style.md, doc/dhis2_android_sdk_user_guide_INDEX.md
Solves [ANDROSDK-1019](https://jira.dhis2.org/browse/ANDROSDK-1019), [ANDROSDK-1033](https://jira.dhis2.org/browse/ANDROSDK-1033) and [ANDROSDK-1034](https://jira.dhis2.org/browse/ANDROSDK-1034)
=> feat: [ANDROSDK-1034] Helpers, style and compatibility doc

core/src/androidTest/java/org/hisp/dhis/android/core/event/internal/EventPostCallRealIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/event/internal/EventUtils.java, core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/api/BreakTheGlassAPIShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/api/TrackedEntityInstanceUtils.java, core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstancePostCallRealIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/arch/helpers/UidGenerator.java, core/src/main/java/org/hisp/dhis/android/core/arch/helpers/UidGeneratorImpl.java, core/src/main/java/org/hisp/dhis/android/core/enrollment/internal/EnrollmentProjectionTransformer.java, core/src/main/java/org/hisp/dhis/android/core/event/internal/EventProjectionTransformer.java, core/src/main/java/org/hisp/dhis/android/core/fileresource/FileResourceCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/note/internal/NoteDHISVersionManager.java, core/src/main/java/org/hisp/dhis/android/core/note/internal/NoteProjectionTransformer.java, core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipHelper.java, core/src/main/java/org/hisp/dhis/android/core/relationship/internal/RelationshipDHISVersionManager.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceProjectionTransformer.java
Solves [ANDROSDK-1035](https://jira.dhis2.org/browse/ANDROSDK-1035)
=> refactor: [ANDROSDK-1035] Refactor CodeGenerator

core/src/main/java/org/hisp/dhis/android/core/arch/cleaners/internal/DataOrphanCleanerImpl.java, core/src/main/java/org/hisp/dhis/android/core/arch/handlers/internal/HandlerBaseImpl.java, core/src/main/java/org/hisp/dhis/android/core/arch/handlers/internal/IdentifiableDataHandlerImpl.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceHandler.java
Solves [ANDROSDK-1039](https://jira.dhis2.org/browse/ANDROSDK-1039)
=> fix: [ANDROSDK-1039] Do not remove errored TEIs on sync

core/src/androidTest/java/org/hisp/dhis/android/core/D2Factory.java, core/src/androidTest/java/org/hisp/dhis/android/core/maintenance/internal/ForeignKeyCleanerShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/utils/integration/mock/BaseMockIntegrationTest.java, core/src/main/java/org/hisp/dhis/android/core/D2Manager.java, core/src/main/java/org/hisp/dhis/android/core/OkHttpClientFactory.java, core/src/main/java/org/hisp/dhis/android/core/arch/api/internal/DynamicServerURLInterceptor.java, core/src/main/java/org/hisp/dhis/android/core/arch/api/internal/ServerURLVersionRedirectionInterceptor.java, core/src/main/java/org/hisp/dhis/android/core/arch/api/internal/ServerURLWrapper.java, core/src/main/java/org/hisp/dhis/android/core/user/internal/UserAuthenticateCallFactory.java
Solves [ANDROSDK-1041](https://jira.dhis2.org/browse/ANDROSDK-1041).
=> fix: [ANDROSDK-1041] Fix DHIS server URL redirection

core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetCompleteRegistrationObjectRepository.java
Solves [ANDROSDK-1047](https://jira.dhis2.org/browse/ANDROSDK-1047).
=> fix: [androsdk-1047] Switch orgunit and dataset on DataSetCompleteRegistrationObjectRepository

core/src/androidTest/java/org/hisp/dhis/android/core/event/internal/EventPostCallMockIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstancePostCallMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/arch/helpers/internal/EnumHelper.java, core/src/main/java/org/hisp/dhis/android/core/common/State.java, core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetCompleteRegistrationCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/datavalue/DataValueCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/enrollment/internal/EnrollmentStoreImpl.java, core/src/main/java/org/hisp/dhis/android/core/event/EventCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/event/internal/EventStoreImpl.java, core/src/main/java/org/hisp/dhis/android/core/fileresource/FileResourceCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/sms/data/localdbrepository/internal/DataSetsStore.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityAttributeValueStoreImpl.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityDataValueStoreImpl.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceStoreImpl.java
Solves [ANDROSDK-1048](https://jira.dhis2.org/browse/ANDROSDK-1048).
=> feat: [ANDROSDK-1048] Consider SMS statuses as uploadable statuses

core/src/main/java/org/hisp/dhis/android/core/sms/data/localdbrepository/internal/LocalDbRepositoryImpl.java
Solves [ANDROSDK-1049](https://jira.dhis2.org/browse/ANDROSDK-1049).
=> fix: [ANDROSDK-1049] Propagate TEI status in Enrollment sync by SMS

core/src/androidTest/java/org/hisp/dhis/android/core/period/PeriodMockIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/utils/integration/mock/BaseMockIntegrationTestMetadataDispatcher.java, core/src/androidTest/java/org/hisp/dhis/android/core/utils/integration/mock/MockIntegrationTestObjects.java
Solves [ANDROSDK-1059](https://jira.dhis2.org/browse/ANDROSDK-1059).
=> fix: [ANDROSDK-1059] Fix tests failing in Travis

core/build.gradle, core/src/androidTest/java/org/hisp/dhis/android/core/utils/integration/real/BaseRealIntegrationTest.java, core/src/main/java/org/hisp/dhis/android/core/arch/db/access/DatabaseAdapter.java, core/src/main/java/org/hisp/dhis/android/core/arch/db/access/internal/BaseDatabaseOpenHelper.java, core/src/main/java/org/hisp/dhis/android/core/arch/db/access/internal/EncryptedDatabaseAdapter.java, core/src/main/java/org/hisp/dhis/android/core/arch/db/access/internal/EncryptedDatabaseOpenHelper.java, core/src/main/java/org/hisp/dhis/android/core/arch/db/access/internal/EncryptedStatementWrapper.java, core/src/main/java/org/hisp/dhis/android/core/arch/db/access/internal/UnencryptedDatabaseOpenHelper.java
Solves [ANDROSDK-1057](https://jira.dhis2.org/browse/ANDROSDK-1057).
=> feat: [ANDROSDK-1057] Add SQL cipher with switch to encrypt

core/src/androidTest/java/org/hisp/dhis/android/testapp/option/OptionCollectionRepositoryMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/option/OptionCollectionRepository.java
Solves [ANDROSDK-1053](https://jira.dhis2.org/browse/ANDROSDK-1053)
=> feat: [ANDROSDK-1053] Add sortOrderBySortOrder in option repository

core/src/androidTest/java/org/hisp/dhis/android/core/data/server/RealServerMother.java, core/src/main/java/org/hisp/dhis/android/core/systeminfo/DHISVersion.java
Sovles [ANDROSDK-1066](https://jira.dhis2.org/browse/ANDROSDK-1066)
=> feat: [ANDROSDK-1066] Accept connection to version 2.34

core/src/main/java/org/hisp/dhis/android/core/common/AssignedUserMode.java, core/src/main/java/org/hisp/dhis/android/core/systeminfo/DHISVersionManager.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceService.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceLocalQueryHelper.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryCallFactory.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryOnline.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryRepositoryScope.java, core/src/test/java/org/hisp/dhis/android/core/systeminfo/internal/DHISVersionManagerShould.java, core/src/test/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceLocalQueryHelperShould.java, core/src/test/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryCallShould.java
Solves [ANDROSDK-1050](https://jira.dhis2.org/browse/ANDROSDK-1050)
=> feat: [ANDROSDK-1050] Add byAssignedUserMode to search repository

core/src/main/java/org/hisp/dhis/android/core/common/ValueTypeRenderingType.java
Solves [ANDROSDK-1071](https://jira.dhis2.org/browse/ANDROSDK-1071)
=> feat: [ANDROSDK-1071] Update ValueTypeRenderingType

core/src/androidTest/java/org/hisp/dhis/android/core/period/PeriodMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/configuration/ServerUrlParser.java, core/src/main/java/org/hisp/dhis/android/core/user/internal/UserAuthenticateCallFactory.java, core/src/test/java/org/hisp/dhis/android/core/configuration/ServerUrlParserShould.java, core/src/test/java/org/hisp/dhis/android/core/user/internal/UserAuthenticateCallUnitShould.java
Solves [ANDROSDK-1052](https://jira.dhis2.org/browse/ANDROSDK-1052)
=> fix: [ANDROSDK-1052] Fix login offline with trailing slash in server url

core/src/androidTest/java/org/hisp/dhis/android/core/period/PeriodMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/period/PeriodType.java, core/src/main/java/org/hisp/dhis/android/core/period/internal/AbstractPeriodGenerator.java, core/src/main/java/org/hisp/dhis/android/core/period/internal/ParentPeriodGenerator.java, core/src/main/java/org/hisp/dhis/android/core/period/internal/ParentPeriodGeneratorImpl.java, core/src/main/java/org/hisp/dhis/android/core/period/internal/PeriodGenerator.java, core/src/main/java/org/hisp/dhis/android/core/period/internal/PeriodHelper.java, core/src/test/java/org/hisp/dhis/android/core/period/internal/BiWeeklyPeriodGeneratorShould.java, core/src/test/java/org/hisp/dhis/android/core/period/internal/DailyPeriodGeneratorShould.java, core/src/test/java/org/hisp/dhis/android/core/period/internal/FinancialOctPeriodGeneratorShould.java, core/src/test/java/org/hisp/dhis/android/core/period/internal/MonthlyPeriodGeneratorShould.java, core/src/test/java/org/hisp/dhis/android/core/period/internal/ParentPeriodGeneratorImplShould.java, core/src/test/java/org/hisp/dhis/android/core/period/internal/QuarterPeriodGeneratorShould.java, core/src/test/java/org/hisp/dhis/android/core/period/internal/SixMonthlyPeriodGeneratorShould.java, core/src/test/java/org/hisp/dhis/android/core/period/internal/WeeklyPeriodGeneratorShould.java
Solves [ANDROSDK-1067](https://jira.dhis2.org/browse/ANDROSDK-1067)
=> fix: [ANDROSDK-1067] Create period in database if it does not exist

core/src/androidTest/java/org/hisp/dhis/android/core/user/internal/UserAuthenticateWithEncryptionMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/user/internal/IsUserLoggedInCallableFactory.java, core/src/test/java/org/hisp/dhis/android/core/user/internal/IsUserLoggedInCallableShould.java
Solves [ANDROSDK-1083](https://jira.dhis2.org/browse/ANDROSDK-1083).
=> feat: [ANDROSDK-1083] Ensure isLogged method works when database not yet created

.buildscript/deploy.sh, core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstancePostCallMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstancePostCall.java
Solves [ANDROSDK-1072](https://jira.dhis2.org/browse/ANDROSDK-1072)
=> fix: [ANDROSDK-1072] Revert UPLOADING status if post fails

core/src/main/java/org/hisp/dhis/android/core/sms/data/localdbrepository/internal/LocalDbRepositoryImpl.java, core/src/main/java/org/hisp/dhis/android/core/sms/domain/converter/internal/DatasetConverter.java, core/src/main/java/org/hisp/dhis/android/core/sms/domain/model/internal/SMSDataValueSet.java, core/src/main/java/org/hisp/dhis/android/core/sms/domain/repository/internal/LocalDbRepository.java, core/src/test/java/org/hisp/dhis/android/core/sms/ConvertTest.java, core/src/test/java/org/hisp/dhis/android/core/sms/mockrepos/MockLocalDbRepository.java, core/src/test/java/org/hisp/dhis/android/core/sms/mockrepos/testobjects/MockMetadata.java, core/src/test/java/org/hisp/dhis/android/core/sms/mockrepos/testobjects/MockObjects.java
Solves [ANDROSDK-1080](https://jira.dhis2.org/browse/ANDROSDK-1080)
=> fix: [ANDROSDK-1080] Add completion information to dataValueSet

core/src/main/java/org/hisp/dhis/android/core/sms/data/localdbrepository/internal/LocalDbRepositoryImpl.java, core/src/main/java/org/hisp/dhis/android/core/sms/domain/converter/internal/DatasetConverter.java, core/src/main/java/org/hisp/dhis/android/core/sms/domain/model/internal/SMSDataValueSet.java, core/src/main/java/org/hisp/dhis/android/core/sms/domain/repository/internal/LocalDbRepository.java, core/src/test/java/org/hisp/dhis/android/core/sms/ConvertTest.java, core/src/test/java/org/hisp/dhis/android/core/sms/mockrepos/MockLocalDbRepository.java, core/src/test/java/org/hisp/dhis/android/core/sms/mockrepos/testobjects/MockMetadata.java, core/src/test/java/org/hisp/dhis/android/core/sms/mockrepos/testobjects/MockObjects.java
Solves [ANDROSDK-1080](https://jira.dhis2.org/browse/ANDROSDK-1080)
=> fix: [DEVELOP] [ANDROSDK-1080] Add completion information to dataValueSet

core/src/main/java/org/hisp/dhis/android/core/common/ValueTypeRenderingType.java
Solves [ANDROSDK-1071](https://jira.dhis2.org/browse/ANDROSDK-1071)
=> fix: [ANDROSDK-1071-B] Update ValueTypeRenderingType

core/src/main/java/org/hisp/dhis/android/core/common/ValueTypeRenderingType.java
Solves [ANDROSDK-1071](https://jira.dhis2.org/browse/ANDROSDK-1071)
=> fix: [DEVELOP] [ANDROSDK-1071-B] Update ValueTypeRenderingType

core/src/main/java/org/hisp/dhis/android/core/arch/db/stores/internal/IdentifiableObjectStoreImpl.java, core/src/main/java/org/hisp/dhis/android/core/arch/db/stores/internal/ObjectStoreImpl.java, core/src/main/java/org/hisp/dhis/android/core/arch/db/stores/internal/ObjectWithoutUidStoreImpl.java
Solves [ANDROSDK-1085](https://jira.dhis2.org/browse/ANDROSDK-1085).
=> fix: [ANDROSDK-1085] Fix cached database adapter issues in stores

core/src/main/java/org/hisp/dhis/android/core/D2Manager.java, core/src/main/java/org/hisp/dhis/android/core/arch/db/stores/internal/IdentifiableObjectStoreImpl.java, core/src/main/java/org/hisp/dhis/android/core/arch/db/stores/internal/ObjectStoreImpl.java, core/src/main/java/org/hisp/dhis/android/core/arch/db/stores/internal/ObjectWithoutUidStoreImpl.java
Solves [ANDROSDK-1086](https://jira.dhis2.org/browse/ANDROSDK-1086).
=> fix: [ANDROSDK-1086] Instantiate database if credentials in D2 initialization

core/src/androidTest/java/org/hisp/dhis/android/testapp/enrollment/EnrollmentCollectionRepositoryMockIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/testapp/event/EventCollectionRepositoryMockIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/testapp/trackedentity/TrackedEntityCollectionRepositoryMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/event/EventCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceCollectionRepository.java, core/src/sharedTest/resources/trackedentity/tracked_entity_instances.json
Solves [ANDROSDK-1082](https://jira.dhis2.org/browse/ANDROSDK-1082).
=> feat: [androsdk-1082] Add sort filters to the event, enrollment and tei collection repositories

core/build.gradle, core/src/androidTest/java/org/hisp/dhis/android/core/period/PeriodMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/period/PeriodType.java, core/src/main/java/org/hisp/dhis/android/core/period/internal/NMonthlyPeriodGenerator.java, core/src/main/java/org/hisp/dhis/android/core/period/internal/NMonthlyPeriodGeneratorFactory.java, core/src/main/java/org/hisp/dhis/android/core/period/internal/NMonthlyPeriodGenerators.java, core/src/main/java/org/hisp/dhis/android/core/period/internal/ParentPeriodGeneratorImpl.java, core/src/main/java/org/hisp/dhis/android/core/period/internal/YearlyPeriodGeneratorFactory.java, core/src/main/java/org/hisp/dhis/android/core/period/internal/YearlyPeriodGenerators.java, core/src/test/java/org/hisp/dhis/android/core/period/internal/ParentPeriodGeneratorImplShould.java, core/src/test/java/org/hisp/dhis/android/core/period/internal/SixMonthlyPeriodGeneratorShould.java
Solves [ANDROSDK-1079](https://jira.dhis2.org/browse/ANDROSDK-1079)
=> fix: [ANDROSDK-1079] New period types and fix n monthly

core/src/androidTest/java/org/hisp/dhis/android/core/arch/db/access/internal/DatabaseAdapterFactoryIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/utils/integration/mock/MockIntegrationTestObjects.java, core/src/main/java/org/hisp/dhis/android/core/arch/db/access/internal/DatabaseAdapterFactory.java
Solves [ANDROSDK-1090](https://jira.dhis2.org/browse/ANDROSDK-1090).
=> fix: [ANDROSDK-1090] Database is created without .db

core/src/main/java/org/hisp/dhis/android/core/program/ProgramSection.java, core/src/main/java/org/hisp/dhis/android/core/program/internal/ProgramSectionFields.java, core/src/sharedTest/resources/program/program_section_32_and_previous.json, core/src/test/java/org/hisp/dhis/android/core/program/ProgramSection32Should.java
Solves [ANDROSDK-1089](https://jira.dhis2.org/browse/ANDROSDK-1089)
=> fix: [ANDROSDK-1089] Accept alias for attributes in programSections

core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetCompleteRegistration.java, core/src/main/java/org/hisp/dhis/android/core/dataset/internal/DataSetCompleteRegistrationCallProcessor.java, core/src/main/java/org/hisp/dhis/android/core/dataset/internal/DataSetCompleteRegistrationFields.java, core/src/sharedTest/resources/dataset/data_set_complete_registration_with_completed.json, core/src/test/java/org/hisp/dhis/android/core/dataset/DataSetCompleteRegistrationWithCompletedShould.java
Solves [ANDROSDK-992](https://jira.dhis2.org/browse/ANDROSDK-992) for 2.32 and later
=> fix: [ANDROSDK-992-B] Read 'completed' property in DataSetCompleteRegistration

core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetCompleteRegistration.java, core/src/main/java/org/hisp/dhis/android/core/dataset/internal/DataSetCompleteRegistrationCallProcessor.java, core/src/main/java/org/hisp/dhis/android/core/dataset/internal/DataSetCompleteRegistrationFields.java, core/src/sharedTest/resources/dataset/data_set_complete_registration_with_completed.json, core/src/test/java/org/hisp/dhis/android/core/dataset/DataSetCompleteRegistrationWithCompletedShould.java
Solves [ANDROSDK-992](https://jira.dhis2.org/browse/ANDROSDK-992) for 2.32 and later
=> fix: [ANDROSDK-992-B] (develop) Read 'completed' property in DataSetCompleteRegistration

core/src/main/java/org/hisp/dhis/android/core/arch/handlers/internal/IdentifiableDataHandler.java, core/src/main/java/org/hisp/dhis/android/core/arch/handlers/internal/IdentifiableDataHandlerImpl.java, core/src/main/java/org/hisp/dhis/android/core/enrollment/internal/EnrollmentEntityDIModule.java, core/src/main/java/org/hisp/dhis/android/core/enrollment/internal/EnrollmentHandler.java, core/src/main/java/org/hisp/dhis/android/core/event/internal/EventHandler.java, core/src/main/java/org/hisp/dhis/android/core/event/internal/EventPersistenceCallFactory.java, core/src/main/java/org/hisp/dhis/android/core/program/internal/ProgramDataDownloadParams.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceDownloader.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceHandler.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceListDownloadAndPersistCallFactory.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstancePersistenceCallFactory.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceRelationshipPersistenceCallFactory.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceWithLimitCallFactory.java, core/src/test/java/org/hisp/dhis/android/core/enrollment/internal/EnrollmentHandlerShould.java, core/src/test/java/org/hisp/dhis/android/core/event/internal/EventHandlerShould.java, core/src/test/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceDownloaderShould.java, core/src/test/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceHandlerShould.java
Solves [ANDROSDK-1092](https://jira.dhis2.org/browse/ANDROSDK-1092)
=> fix: [ANDROSDK-1092] Overwrite TEI if download single TEI

core/src/main/java/org/hisp/dhis/android/core/arch/handlers/internal/IdentifiableDataHandler.java, core/src/main/java/org/hisp/dhis/android/core/arch/handlers/internal/IdentifiableDataHandlerImpl.java, core/src/main/java/org/hisp/dhis/android/core/enrollment/internal/EnrollmentEntityDIModule.java, core/src/main/java/org/hisp/dhis/android/core/enrollment/internal/EnrollmentHandler.java, core/src/main/java/org/hisp/dhis/android/core/event/internal/EventHandler.java, core/src/main/java/org/hisp/dhis/android/core/event/internal/EventPersistenceCallFactory.java, core/src/main/java/org/hisp/dhis/android/core/program/internal/ProgramDataDownloadParams.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceDownloader.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceHandler.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceListDownloadAndPersistCallFactory.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstancePersistenceCallFactory.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceRelationshipPersistenceCallFactory.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceWithLimitCallFactory.java, core/src/test/java/org/hisp/dhis/android/core/enrollment/internal/EnrollmentHandlerShould.java, core/src/test/java/org/hisp/dhis/android/core/event/internal/EventHandlerShould.java, core/src/test/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceDownloaderShould.java, core/src/test/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceHandlerShould.java
Solves [ANDROSDK-1092](https://jira.dhis2.org/browse/ANDROSDK-1092)
=> fix: [ANDROSDK-1092] (develop) Overwrite TEI if download single TEI

core/src/androidTest/java/org/hisp/dhis/android/core/utils/integration/mock/BaseMockIntegrationTestMetadataDispatcher.java, core/src/main/java/org/hisp/dhis/android/core/sms/data/localdbrepository/internal/DataSetsStore.java, core/src/test/java/org/hisp/dhis/android/core/sms/ConvertTest.java, core/src/test/java/org/hisp/dhis/android/core/sms/mockrepos/MockLocalDbRepository.java, core/src/test/java/org/hisp/dhis/android/core/sms/mockrepos/testobjects/MockObjects.java
Solves [ANDROSDK-1097](https://jira.dhis2.org/browse/ANDROSDK-1097)
=> fix: [ANDROSDK-1097] Avoid empty list in dataset submission

core/src/androidTest/java/org/hisp/dhis/android/core/user/internal/UserAuthenticateWithEncryptionMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/user/internal/IsUserLoggedInCallableFactory.java, core/src/test/java/org/hisp/dhis/android/core/user/internal/IsUserLoggedInCallableShould.java
Solves [ANDROSDK-1096](https://jira.dhis2.org/browse/ANDROSDK-1096).
=> feat: [ANDROSDK-1096] Simplify isLogged method

core/src/androidTest/java/org/hisp/dhis/android/core/BaseRealIntegrationTest.java, core/src/androidTest/java/org/hisp/dhis/android/core/MetadataCallRealIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/arch/db/access/internal/DatabaseAdapterFactoryIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/configuration/internal/DatabaseConfigurationMigrationIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/data/database/migrations/DataBaseMigrationShould.java, core/src/main/java/org/hisp/dhis/android/core/D2Manager.java, core/src/main/java/org/hisp/dhis/android/core/arch/db/access/internal/DatabaseAdapterFactory.java, core/src/main/java/org/hisp/dhis/android/core/arch/db/access/internal/DatabaseCreator.java, core/src/main/java/org/hisp/dhis/android/core/configuration/internal/ConfigurationPackageDIModule.java, core/src/main/java/org/hisp/dhis/android/core/configuration/internal/DatabaseConfigurationHelper.java, core/src/main/java/org/hisp/dhis/android/core/configuration/internal/DatabaseConfigurationMigration.java, core/src/main/java/org/hisp/dhis/android/core/configuration/internal/DatabaseCopy.java, core/src/main/java/org/hisp/dhis/android/core/configuration/internal/DatabaseUserConfiguration.java, core/src/main/java/org/hisp/dhis/android/core/configuration/internal/MultiUserDatabaseManager.java, core/src/main/java/org/hisp/dhis/android/core/user/internal/UserAuthenticateCallFactory.java, core/src/test/java/org/hisp/dhis/android/core/configuration/internal/DatabasesConfigurationHelperShould.java, core/src/test/java/org/hisp/dhis/android/core/configuration/internal/MultiUserDatabaseManagerUnitShould.java, core/src/test/java/org/hisp/dhis/android/core/user/internal/UserAuthenticateCallUnitShould.java
Solves [ANDROSDK-1100](https://jira.dhis2.org/browse/ANDROSDK-1100)
=> feat: [ANDROSDK-1100] Prepare code for database copy when encryption changes

core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityAttributeReservedValueEndpointCallRealIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/ReservedValueSummary.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueManager.java
Solves [ANDROSDK-1075](https://jira.dhis2.org/browse/ANDROSDK-1075).
=> feat: [androsdk-1075] Add a method to retrieve a summary of the reserved values state

core/src/main/java/org/hisp/dhis/android/core/arch/db/stores/internal/ObjectWithoutUidStore.java, core/src/main/java/org/hisp/dhis/android/core/arch/db/stores/internal/ObjectWithoutUidStoreImpl.java, core/src/main/java/org/hisp/dhis/android/core/arch/handlers/internal/ObjectWithoutUidHandlerImpl.java, core/src/main/java/org/hisp/dhis/android/core/datavalue/internal/DataValueEndpointCallFactory.java, core/src/main/java/org/hisp/dhis/android/core/datavalue/internal/DataValueEntityDIModule.java, core/src/main/java/org/hisp/dhis/android/core/datavalue/internal/DataValueHandler.java, core/src/main/java/org/hisp/dhis/android/core/datavalue/internal/DataValueService.java
Solves [ANDROSDK-1105](https://jira.dhis2.org/browse/ANDROSDK-1105)
=> fix: [ANDROSDK-1105] React to datavalue deletions in the server

core/src/androidTest/java/org/hisp/dhis/android/core/maintenance/internal/ForeignKeyCleanerShould.java, core/src/main/java/org/hisp/dhis/android/core/configuration/internal/MultiUserDatabaseManager.java, core/src/main/java/org/hisp/dhis/android/core/domain/metadata/MetadataCall.java, core/src/main/java/org/hisp/dhis/android/core/mockwebserver/Dhis2MockServer.java, core/src/test/java/org/hisp/dhis/android/core/domain/metadata/MetadataCallShould.java
Solves [ANDROSDK-1102](https://jira.dhis2.org/browse/ANDROSDK-1102).
=> feat: [ANDROSDK-1102] Change encryption if required in metadata call

core/src/androidTest/java/org/hisp/dhis/android/core/BaseRealIntegrationTest.java, core/src/androidTest/java/org/hisp/dhis/android/core/D2Factory.java, core/src/androidTest/java/org/hisp/dhis/android/core/arch/db/access/internal/DatabaseAdapterFactoryIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/configuration/internal/DatabaseConfigurationMigrationIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/data/database/migrations/DataBaseMigrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/maintenance/internal/ForeignKeyCleanerShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/utils/integration/mock/TestDatabaseAdapterFactory.java, core/src/main/java/org/hisp/dhis/android/core/D2Manager.java, core/src/main/java/org/hisp/dhis/android/core/arch/db/access/internal/DatabaseAdapterFactory.java, core/src/main/java/org/hisp/dhis/android/core/arch/db/access/internal/DatabaseDIModule.java, core/src/main/java/org/hisp/dhis/android/core/arch/db/access/internal/DatabaseEncryptionPasswordGenerator.java, core/src/main/java/org/hisp/dhis/android/core/configuration/internal/ConfigurationPackageDIModule.java, core/src/main/java/org/hisp/dhis/android/core/configuration/internal/DatabaseConfigurationMigration.java, core/src/main/java/org/hisp/dhis/android/core/configuration/internal/DatabaseEncryptionPasswordsSecureStore.java, core/src/main/java/org/hisp/dhis/android/core/configuration/internal/DatabasesEncryptionPasswords.java, core/src/main/java/org/hisp/dhis/android/core/configuration/internal/MultiUserDatabaseManager.java, core/src/main/java/org/hisp/dhis/android/core/domain/metadata/MetadataCall.java, core/src/main/java/org/hisp/dhis/android/core/mockwebserver/Dhis2MockServer.java, core/src/main/java/org/hisp/dhis/android/core/user/internal/LogOutCallFactory.java, core/src/test/java/org/hisp/dhis/android/core/configuration/internal/MultiUserDatabaseManagerUnitShould.java, core/src/test/java/org/hisp/dhis/android/core/domain/metadata/MetadataCallShould.java, core/src/test/java/org/hisp/dhis/android/core/user/internal/LogOutCallFactoryShould.java
Solves [ANDROSDK-1103](https://jira.dhis2.org/browse/ANDROSDK-1103).
=> feat: [ANDROSDK-1103] Generate and save encryption passwords

core/src/androidTest/java/org/hisp/dhis/android/core/dataset/internal/DataSetEndpointCallRealIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/organisationunit/internal/OrganisationUnitCallMockIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/program/internal/ProgramEndpointCallMockIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/program/internal/ProgramEndpointCallRealIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/arch/d2/internal/D2DIComponent.java, core/src/main/java/org/hisp/dhis/android/core/arch/modules/internal/MetadataModuleByUidDownloader.java, core/src/main/java/org/hisp/dhis/android/core/dataset/internal/DataSetEndpointCallFactory.java, core/src/main/java/org/hisp/dhis/android/core/dataset/internal/DataSetModuleDownloader.java, core/src/main/java/org/hisp/dhis/android/core/dataset/internal/DataSetPackageDIModule.java, core/src/main/java/org/hisp/dhis/android/core/dataset/internal/DataSetService.java, core/src/main/java/org/hisp/dhis/android/core/domain/metadata/MetadataCall.java, core/src/main/java/org/hisp/dhis/android/core/domain/metadata/internal/MetadataHelper.java, core/src/main/java/org/hisp/dhis/android/core/mockwebserver/Dhis2MockServer.java, core/src/main/java/org/hisp/dhis/android/core/organisationunit/internal/OrganisationUnitCallFactory.java, core/src/main/java/org/hisp/dhis/android/core/organisationunit/internal/OrganisationUnitHandler.java, core/src/main/java/org/hisp/dhis/android/core/organisationunit/internal/OrganisationUnitHandlerImpl.java, core/src/main/java/org/hisp/dhis/android/core/organisationunit/internal/OrganisationUnitModuleDownloader.java, core/src/main/java/org/hisp/dhis/android/core/organisationunit/internal/SearchOrganisationUnitOnDemandCallFactory.java, core/src/main/java/org/hisp/dhis/android/core/program/internal/ProgramEndpointCallFactory.java, core/src/main/java/org/hisp/dhis/android/core/program/internal/ProgramFields.java, core/src/main/java/org/hisp/dhis/android/core/program/internal/ProgramModuleDownloader.java, core/src/main/java/org/hisp/dhis/android/core/program/internal/ProgramPackageDIModule.java, core/src/main/java/org/hisp/dhis/android/core/program/internal/ProgramService.java, core/src/test/java/org/hisp/dhis/android/core/domain/metadata/MetadataCallShould.java, core/src/test/java/org/hisp/dhis/android/core/organisationunit/internal/OrganisationUnitCallUnitShould.java, core/src/test/java/org/hisp/dhis/android/core/organisationunit/internal/OrganisationUnitHandlerShould.java, core/src/test/java/org/hisp/dhis/android/core/program/internal/ProgramEndpointCallShould.java, core/src/test/java/org/hisp/dhis/android/core/program/internal/ProgramModuleDownloaderShould.java
Solves [ANDROSDK-1093](https://jira.dhis2.org/browse/ANDROSDK-1093).
=> fix: [androsdk-1093] Avoid download programs and data sets not assigned to any user organisation unit

core/src/androidTest/java/org/hisp/dhis/android/core/MetadataCallRealIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/D2Manager.java, core/src/main/java/org/hisp/dhis/android/core/configuration/internal/ConfigurationPackageDIModule.java, core/src/main/java/org/hisp/dhis/android/core/configuration/internal/DatabaseCopy.java, core/src/main/java/org/hisp/dhis/android/core/configuration/internal/MultiUserDatabaseManager.java, core/src/main/java/org/hisp/dhis/android/core/configuration/internal/MultiUserDatabaseManagerForD2Manager.java, core/src/test/java/org/hisp/dhis/android/core/configuration/internal/MultiUserDatabaseManagerForD2ManagerUnitShould.java, core/src/test/java/org/hisp/dhis/android/core/configuration/internal/MultiUserDatabaseManagerUnitShould.java
Solves [ANDROSDK-1088](https://jira.dhis2.org/browse/ANDROSDK-1088)
=> feat: [ANDROSDK-1088] Copy database when changing encryption value

core/src/main/java/org/hisp/dhis/android/core/configuration/internal/MultiUserDatabaseManager.java, core/src/main/java/org/hisp/dhis/android/core/domain/metadata/MetadataCall.java, core/src/main/java/org/hisp/dhis/android/core/settings/internal/GeneralSettingCall.java, core/src/main/java/org/hisp/dhis/android/core/user/internal/UserAuthenticateCallFactory.java
Solves [ANDROSDK-1109](https://jira.dhis2.org/browse/ANDROSDK-1109).
=> fix: [ANDROSDK-1109] Fix general settings call error handling

core/src/androidTest/java/org/hisp/dhis/android/core/D2Factory.java, core/src/main/java/org/hisp/dhis/android/core/D2Manager.java, core/src/main/java/org/hisp/dhis/android/core/configuration/internal/MultiUserDatabaseManagerForD2Manager.java
Partially solves [ANDROSDK-445](https://jira.dhis2.org/browse/ANDROSDK-845).
=> feat: [ANDROSDK-445] D2Manager with testing infrastructure, wipe test copied database

core/src/androidTest/java/org/hisp/dhis/android/core/program/ProgramIndicatorEngineIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/arch/db/querybuilders/internal/WhereClauseBuilder.java, core/src/main/java/org/hisp/dhis/android/core/event/internal/EventStore.java, core/src/main/java/org/hisp/dhis/android/core/event/internal/EventStoreImpl.java, core/src/main/java/org/hisp/dhis/android/core/program/programindicatorengine/ProgramIndicatorEngine.java, core/src/test/java/org/hisp/dhis/android/core/arch/db/WhereClauseBuilderShould.java, core/src/test/java/org/hisp/dhis/android/core/program/programindicatorengine/ProgramIndicatorEngineShould.java
Solves [ANDROSDK-1114](https://jira.dhis2.org/browse/ANDROSDK-1114)
=> fix: [ANDROSDK-1114] Ignore deleted events in program indicator engine

core/src/main/java/org/hisp/dhis/android/core/arch/db/querybuilders/internal/WhereClauseBuilder.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceLocalQueryHelper.java, core/src/test/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceLocalQueryHelperShould.java
Solves [ANDROSDK-1111](https://jira.dhis2.org/browse/ANDROSDK-1111)
=> fix: [ANDROSDK-1111] Exclude relationships by default in Tracker query search

docs/content/developer/about-this-android-guide.md, docs/content/developer/database.md, docs/content/developer/getting-started.md, docs/content/developer/workflow.md, docs/dhis2_android_sdk_developer_guide_INDEX.md
Solves [ANDROSDK-1055](https://jira.dhis2.org/browse/ANDROSDK-1055).
=> feat: [ANDROSDK-1055] Add encryption documentation

core/src/main/java/org/hisp/dhis/android/core/arch/db/stores/internal/IdentifiableDataObjectStoreImpl.java
Solves [ANDROSDK-1117](https://jira.dhis2.org/browse/ANDROSDK-1117).
=> fix: [ANDROSDK-1117] Fix statement reset in IdentifiableDataObjectStoreImpl

core/src/main/java/org/hisp/dhis/android/core/sms/data/webapirepository/internal/WebApiRepositoryImpl.java
Solves [ANDROSDK-1120](https://jira.dhis2.org/browse/ANDROSDK-1120)
=> fix: [ANDROSDK-1120] Take local date as last sync date in metadata

core/src/androidTest/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadOnlyIdentifiableCollectionRepositoryImplIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/arch/d2/internal/D2DIComponent.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/internal/SubQueryFilterConnector.java, core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipTypeCollectionRepository.java, core/src/sharedTest/java/org/hisp/dhis/android/core/data/relationship/RelationshipTypeSamples.java
Solves [ANDROSDK-1069](https://jira.dhis2.org/browse/ANDROSDK-1069).
=> feat: [androsdk-1069] Add by constraint filters on relationship type repository

core/src/androidTest/java/org/hisp/dhis/android/core/event/internal/EventEndpointCallMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/arch/api/executors/internal/RxAPICallExecutor.java, core/src/main/java/org/hisp/dhis/android/core/arch/api/executors/internal/RxAPICallExecutorImpl.java, core/src/main/java/org/hisp/dhis/android/core/arch/modules/internal/MetadataModuleByUidDownloader.java, core/src/main/java/org/hisp/dhis/android/core/arch/modules/internal/TypedModuleDownloader.java, core/src/main/java/org/hisp/dhis/android/core/arch/modules/internal/UntypedModuleDownloader.java, core/src/main/java/org/hisp/dhis/android/core/category/internal/CategoryModuleDownloader.java, core/src/main/java/org/hisp/dhis/android/core/constant/internal/ConstantModuleDownloader.java, core/src/main/java/org/hisp/dhis/android/core/dataset/internal/DataSetModuleDownloader.java, core/src/main/java/org/hisp/dhis/android/core/domain/metadata/MetadataCall.java, core/src/main/java/org/hisp/dhis/android/core/event/internal/EventPersistenceCallFactory.java, core/src/main/java/org/hisp/dhis/android/core/event/internal/EventWithLimitCallFactory.java, core/src/main/java/org/hisp/dhis/android/core/mockwebserver/Dhis2MockServer.java, core/src/main/java/org/hisp/dhis/android/core/organisationunit/internal/OrganisationUnitModuleDownloader.java, core/src/main/java/org/hisp/dhis/android/core/program/internal/ProgramModuleDownloader.java, core/src/main/java/org/hisp/dhis/android/core/sms/domain/interactor/ConfigCase.java, core/src/main/java/org/hisp/dhis/android/core/systeminfo/internal/SystemInfoModuleDownloader.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceListDownloadAndPersistCallFactory.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstancePersistenceCallFactory.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceRelationshipPersistenceCallFactory.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceWithLimitCallFactory.java, core/src/main/java/org/hisp/dhis/android/core/user/internal/UserModuleDownloader.java, core/src/test/java/org/hisp/dhis/android/core/domain/metadata/MetadataCallShould.java, core/src/test/java/org/hisp/dhis/android/core/program/internal/ProgramModuleDownloaderShould.java
Solves [ANDROSDK-1122](https://jira.dhis2.org/browse/ANDROSDK-1122).
=> feat: [ANDROSDK-1122] Metadata call with RxJava

core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitTree.java, core/src/main/java/org/hisp/dhis/android/core/organisationunit/internal/OrganisationUnitCallFactory.java, core/src/main/java/org/hisp/dhis/android/core/organisationunit/internal/OrganisationUnitHandler.java, core/src/main/java/org/hisp/dhis/android/core/organisationunit/internal/OrganisationUnitHandlerImpl.java, core/src/main/java/org/hisp/dhis/android/core/user/internal/UserOrganisationUnitLinkHelper.java, core/src/test/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitTreeShould.java
Solves [ANDROSDK-1063](https://jira.dhis2.org/browse/ANDROSDK-1063).
=> fix: [androsdk-1063] Avoid download capture org units in search scope twice 

core/src/androidTest/java/org/hisp/dhis/android/core/option/OptionCallShould.java, core/src/main/java/org/hisp/dhis/android/core/arch/api/executors/internal/APIDownloader.java, core/src/main/java/org/hisp/dhis/android/core/arch/api/executors/internal/APIDownloaderImpl.java, core/src/main/java/org/hisp/dhis/android/core/arch/call/factories/internal/RxUidsCall.java, core/src/main/java/org/hisp/dhis/android/core/arch/d2/internal/D2DIComponent.java, core/src/main/java/org/hisp/dhis/android/core/dataset/internal/DataSetModuleDownloader.java, core/src/main/java/org/hisp/dhis/android/core/option/internal/OptionCall.java, core/src/main/java/org/hisp/dhis/android/core/option/internal/OptionPackageDIModule.java, core/src/main/java/org/hisp/dhis/android/core/option/internal/RxOptionCall.java, core/src/main/java/org/hisp/dhis/android/core/program/internal/ProgramModuleDownloader.java, core/src/test/java/org/hisp/dhis/android/core/program/internal/ProgramModuleDownloaderShould.java
Solves [ANDROSDK-1126](https://jira.dhis2.org/browse/ANDROSDK-1126).
=> refactor: [ANDROSDK-1126] OptionCall with RxJava

core/src/main/java/org/hisp/dhis/android/core/common/State.java, core/src/main/java/org/hisp/dhis/android/core/event/internal/EventStoreImpl.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityAttributeValueStoreImpl.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityDataValueStoreImpl.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceLocalQueryHelper.java
Solves [ANDROSDK-1129](https://jira.dhis2.org/browse/ANDROSDK-1129)
=> fix: [ANDROSDK-1129] Include UPLOADING state in the list of uploadable states

core/src/main/java/org/hisp/dhis/android/core/datavalue/internal/DataValueImportHandler.java, core/src/main/java/org/hisp/dhis/android/core/datavalue/internal/DataValuePostCall.java, core/src/main/java/org/hisp/dhis/android/core/datavalue/internal/DataValueStore.java, core/src/test/java/org/hisp/dhis/android/core/datavalue/internal/DataValueImportHandlerShould.java
Solves [ANDROSDK-1007](https://jira.dhis2.org/browse/ANDROSDK-1007).
=> feat: [androsdk-1007] Set data values state as uploading when syncing

core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetCompleteRegistrationCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/dataset/internal/DataSetCompleteRegistrationImportHandler.java, core/src/main/java/org/hisp/dhis/android/core/dataset/internal/DataSetCompleteRegistrationPostCall.java, core/src/main/java/org/hisp/dhis/android/core/dataset/internal/DataSetCompleteRegistrationStore.java, core/src/main/java/org/hisp/dhis/android/core/dataset/internal/DataSetCompleteRegistrationStoreImpl.java, core/src/test/java/org/hisp/dhis/android/core/dataset/internal/DataSetCompleteRegistrationImportHandlerShould.java
Solves [ANDROSDK-1008](https://jira.dhis2.org/browse/ANDROSDK-1008).
=> feat: [androsdk-1008] Set data set complete registration state as uploading when syncing

core/src/main/java/org/hisp/dhis/android/core/enrollment/internal/EnrollmentImportHandler.java, core/src/main/java/org/hisp/dhis/android/core/event/internal/EventImportHandler.java, core/src/main/java/org/hisp/dhis/android/core/event/internal/EventPostCall.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstancePostCall.java
Solves [ANDROSDK-1133](https://jira.dhis2.org/browse/ANDROSDK-1133)
=> fix: [ANDROSDK-1133] Upload single event notes

core/src/androidTest/java/org/hisp/dhis/android/core/option/OptionCallShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/option/OptionSetCallShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/program/internal/ProgramEndpointCallMockIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/program/internal/ProgramEndpointCallRealIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/arch/api/executors/internal/APIDownloader.java, core/src/main/java/org/hisp/dhis/android/core/arch/api/executors/internal/APIDownloaderImpl.java, core/src/main/java/org/hisp/dhis/android/core/arch/api/executors/internal/APIExecutorsDIModule.java, core/src/main/java/org/hisp/dhis/android/core/arch/call/factories/internal/ListCall.java, core/src/main/java/org/hisp/dhis/android/core/arch/call/factories/internal/UidsCall.java, core/src/main/java/org/hisp/dhis/android/core/mockwebserver/Dhis2MockServer.java, core/src/main/java/org/hisp/dhis/android/core/option/internal/OptionCall.java, core/src/main/java/org/hisp/dhis/android/core/option/internal/OptionGroupCall.java, core/src/main/java/org/hisp/dhis/android/core/option/internal/OptionSetCall.java, core/src/main/java/org/hisp/dhis/android/core/program/Program.java, core/src/main/java/org/hisp/dhis/android/core/program/internal/ProgramCall.java, core/src/main/java/org/hisp/dhis/android/core/program/internal/ProgramModuleDownloader.java, core/src/main/java/org/hisp/dhis/android/core/program/internal/ProgramRuleCall.java, core/src/main/java/org/hisp/dhis/android/core/program/internal/ProgramStageCall.java, core/src/main/java/org/hisp/dhis/android/core/relationship/internal/RelationshipTypeCall.java, core/src/main/java/org/hisp/dhis/android/core/relationship/internal/RelationshipTypeService.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityAttributeCall.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityTypeCall.java, core/src/test/java/org/hisp/dhis/android/core/program/internal/ProgramEndpointCallShould.java, core/src/test/java/org/hisp/dhis/android/core/program/internal/ProgramModuleDownloaderShould.java
Solves [ANDROSDK-1125](https://jira.dhis2.org/browse/ANDROSDK-1125).
=> refactor: [ANDROSDK-1125] ProgramModuleDownloader with RxJava

core/src/androidTest/java/org/hisp/dhis/android/core/category/internal/CategoryComboEndpointCallRealIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/category/internal/CategoryEndpointCallRealIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/category/internal/CategoryEndpointCallShould.java, core/src/main/java/org/hisp/dhis/android/core/category/internal/CategoryCall.java, core/src/main/java/org/hisp/dhis/android/core/category/internal/CategoryComboCall.java, core/src/main/java/org/hisp/dhis/android/core/category/internal/CategoryComboService.java, core/src/main/java/org/hisp/dhis/android/core/category/internal/CategoryInternalModule.java, core/src/main/java/org/hisp/dhis/android/core/category/internal/CategoryModuleDownloader.java, core/src/main/java/org/hisp/dhis/android/core/category/internal/CategoryPackageDIModule.java, core/src/main/java/org/hisp/dhis/android/core/category/internal/CategoryService.java
Solves [ANDROSDK-1146](https://jira.dhis2.org/browse/ANDROSDK-1146)
=> refactor: [ANDROSDK-1146] Category download with RxJava

core/src/main/java/org/hisp/dhis/android/core/program/internal/ProgramModuleDownloader.java
This simplifies slightly flatMap composition.
=> refactor: Program module downloader refactor

core/src/main/java/org/hisp/dhis/android/core/domain/aggregated/data/internal/AggregatedDataCallBundleFactory.java, core/src/main/java/org/hisp/dhis/android/core/period/internal/AbstractPeriodGenerator.java, core/src/test/java/org/hisp/dhis/android/core/domain/aggregated/data/internal/AggregatedDataCallBundleFactoryShould.java, core/src/test/java/org/hisp/dhis/android/core/period/internal/AbstractPeriodGeneratorShould.java
Solves [ANDROSDK-1152](https://jira.dhis2.org/browse/ANDROSDK-1152)
=> fix: [ANDROSDK-1152] Ignore aggregated data queries when 0 periods to download

core/src/main/java/org/hisp/dhis/android/core/organisationunit/internal/OrganisationUnitFields.java
Solves [ANDROSDK-1157](https://jira.dhis2.org/browse/ANDROSDK-1157)
=> fix: [ANDROSDK-1157] Do not download orgunit geometry value by default

docs/content/developer/workflow.md
Fix some spelling I could remember that I found while reading.
=> fix: Fix some spelling

core/src/main/java/org/hisp/dhis/android/core/validation/engine/internal/ValidationEngineImpl.java
=> fix: [ANDROSDK-99-B] Fix ValidationEngine params order

core/src/androidTest/java/org/hisp/dhis/android/core/utils/integration/mock/BaseMockIntegrationTestLocalAnalyticsDispatcher.kt, core/src/androidTest/java/org/hisp/dhis/android/localanalytics/LocalAnalyticsDataGenerator.kt, core/src/androidTest/java/org/hisp/dhis/android/localanalytics/LocalAnalyticsDatabaseFiller.kt, core/src/androidTest/java/org/hisp/dhis/android/localanalytics/LocalAnalyticsDatabaseMockIntegrationShould.kt, core/src/androidTest/java/org/hisp/dhis/android/localanalytics/LocalAnalyticsMetadataGenerator.kt, core/src/androidTest/java/org/hisp/dhis/android/localanalytics/LocalAnalyticsParams.kt, core/src/sharedTest/java/org/hisp/dhis/android/core/data/category/CategoryOptionComboSamples.java, core/src/sharedTest/java/org/hisp/dhis/android/core/data/datavalue/DataValueSamples.kt, core/src/sharedTest/java/org/hisp/dhis/android/core/data/enrollment/EnrollmentSamples.java, core/src/sharedTest/java/org/hisp/dhis/android/core/data/trackedentity/EventSamples.java, core/src/sharedTest/java/org/hisp/dhis/android/core/data/trackedentity/TrackedEntityAttributeValueSamples.java, core/src/sharedTest/java/org/hisp/dhis/android/core/data/trackedentity/TrackedEntityDataValueSamples.java, core/src/sharedTest/java/org/hisp/dhis/android/core/data/trackedentity/TrackedEntityInstanceSamples.java
Solves [ANDROSDK-1154](https://jira.dhis2.org/browse/ANDROSDK-1154)
=> feat: [ANDROSDK-1154] Local analytics: database for performance tests (data)

core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetInstance.java, core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetInstanceSummary.java, core/src/main/java/org/hisp/dhis/android/core/dataset/internal/DataSetInstanceSQLStatementBuilder.java, core/src/main/java/org/hisp/dhis/android/core/dataset/internal/DataSetInstanceSummarySQLStatementBuilder.java
Solves [ANDROSDK-1149](https://jira.dhis2.org/browse/ANDROSDK-1149)
=> feat: [ANDROSDK-1149] Add completedBy and lastUpdated to dataSetInstance

core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetElement.java, core/src/main/java/org/hisp/dhis/android/core/dataset/internal/DataSetHandler.java
Solves [ANDROSDK-1160](https://jira.dhis2.org/browse/ANDROSDK-1160).
=> feat: [androsdk-1160] Avoid crashes when API returns corrupted DataSetElements

core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceLocalQueryHelper.java
Solves [ANDROSDK-1161](https://jira.dhis2.org/browse/ANDROSDK-1161)
=> fix: [ANDROSDK-1161] Order TEI query by lastUpdated

core/src/androidTest/java/org/hisp/dhis/android/core/utils/integration/mock/BaseMockIntegrationTestLocalAnalyticsDispatcher.kt, core/src/androidTest/java/org/hisp/dhis/android/localanalytics/LocalAnalyticsDatabaseMockIntegrationShould.kt, core/src/androidTest/java/org/hisp/dhis/android/localanalytics/LocalAnalyticsParams.kt, core/src/androidTest/java/org/hisp/dhis/android/localanalytics/LocalAnalyticsTrackerEventsMockIntegrationShould.kt, core/src/androidTest/java/org/hisp/dhis/android/localanalytics/LocalAnalyticsTrackerMockIntegrationShould.kt
Solves [[ANDROSDK-1135]](https://jira.dhis2.org/browse/ANDROSDK-1135)
=> feat: [ANDROSDK-1135] Local analytics performance test (tracker)

core/src/main/java/org/hisp/dhis/android/core/relationship/internal/RelationshipHandlerImpl.java
Solves [ANDROSDK-1163](https://jira.dhis2.org/browse/ANDROSDK-1163)
=> fix: [ANDROSDK-1163] Do not crash if relationship is not tei-te

core/src/androidTest/java/org/hisp/dhis/android/localanalytics/LocalAnalyticsTrackerMockIntegrationShould.kt
Add sql query for Tracker local analytics
=> feat: [LOCAL-ANALYTICS-SQL] Add sql test for tracker analytics

core/build.gradle, core/src/androidTest/java/org/hisp/dhis/android/core/common/internal/DataStatePropagatorIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/testapp/trackedentity/TrackedEntityCollectionRepositoryMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/arch/db/stores/internal/IdentifiableDataObjectStoreImpl.java, core/src/main/java/org/hisp/dhis/android/core/arch/db/stores/internal/StoreWithState.java, core/src/main/java/org/hisp/dhis/android/core/common/internal/DataStatePropagator.java, core/src/main/java/org/hisp/dhis/android/core/common/internal/DataStatePropagatorImpl.java, core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipHelper.java, core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipObjectRepository.java, core/src/sharedTest/resources/trackedentity/tracked_entity_instances.json
Solves [ANDROSDK-1169](https://jira.dhis2.org/browse/ANDROSDK-1169)
=> fix: [ANDROSDK-1169] Update lastUpdated value in tracker data propagation

core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceService.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceLocalQueryHelper.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryCallFactory.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryOnline.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryRepositoryScope.java, core/src/test/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryCallShould.java
Solves [ANDROSDK-1173](https://jira.dhis2.org/browse/ANDROSDK-1173)
=> feat: [ANDROSDK-1173] Add byProgramStatus filter

core/src/androidTest/java/org/hisp/dhis/android/testapp/category/CategoryOptionRepositoryMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/category/CategoryOptionCollectionRepository.java
Solves [ANDROSDK-1176](https://jira.dhis2.org/browse/ANDROSDK-1176)
=> feat: [ANDROSDK-1176] Add byCategoryUid filter in categoryOption repository

core/src/androidTest/java/org/hisp/dhis/android/testapp/event/EventObjectRepositoryMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/event/EventObjectRepository.java
Solves [ANDROSDK-1172](https://jira.dhis2.org/browse/ANDROSDK-1172)
=> feat: [ANDROSDK-1172] Set completedDate when changing event status

core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstancePostCallMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/arch/api/internal/DynamicServerURLInterceptor.java, core/src/main/java/org/hisp/dhis/android/core/arch/api/internal/ServerURLVersionRedirectionInterceptor.java, core/src/main/java/org/hisp/dhis/android/core/maintenance/D2Error.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstancePostCall.java, core/src/main/java/org/hisp/dhis/android/core/user/internal/UserAuthenticateCallFactory.java, core/src/test/java/org/hisp/dhis/android/core/user/internal/UserAuthenticateCallUnitShould.java
Partially solves [ANDROSDK-1162-a](https://jira.dhis2.org/browse/ANDROSDK-1162)
=> feat: [ANDROSDK-1162-a] Remove system info call from TEI post call

core/src/main/java/org/hisp/dhis/android/core/datavalue/internal/DataValueImportHandler.java
Solves [ANDROSDK-1180](https://jira.dhis2.org/browse/ANDROSDK-1180).
=> feat: [androsdk-1180] Handle warnings on data value post

core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueManagerRealIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/fileresource/internal/FileResourceCall.java, core/src/main/java/org/hisp/dhis/android/core/fileresource/internal/FileResourcePostCall.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueManager.java
Solves [ANDROSDK-1162](https://jira.dhis2.org/browse/ANDROSDK-1162).
=> feat: [ANDROSDK-1162] Remove system info calls for reserved values and file resource calls

core/src/androidTest/java/org/hisp/dhis/android/core/BaseIntegrationTestWithDatabase.java, core/src/androidTest/java/org/hisp/dhis/android/core/BaseRealIntegrationTest.java, core/src/androidTest/java/org/hisp/dhis/android/core/TeisCallRealIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/category/internal/CategoryCategoryComboLinkStoreShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/category/internal/CategoryCategoryOptionLinkStoreShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/category/internal/CategoryComboEndpointCallRealIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/common/IdentifiableObjectStoreIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/dataset/internal/DataSetCompleteRegistrationPostCallRealIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/datavalue/internal/DataValueEndpointCallRealIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/event/internal/EventEndpointCallRealIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueManagerRealIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityAttributeReservedValueEndpointCallRealIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityAttributeReservedValueStoreIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityAttributeValueStoreShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityDataValueStoreShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstancePostCallRealIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceStoreShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/user/internal/LogoutCallRealIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/wipe/WipeDBCallRealIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/fileresource/internal/FileResourceCall.java, core/src/main/java/org/hisp/dhis/android/core/fileresource/internal/FileResourcePostCall.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueManager.java
Solves [ANDROSDK-1185](https://jira.dhis2.org/browse/ANDROSDK-1185)
=> feat: [ANDROSDK-1185] Split BaseRealIntegrationTest and BaseIntegrationTestWithDatabase

core/src/main/java/org/hisp/dhis/android/core/enrollment/internal/EnrollmentStoreImpl.java
Solves [ANDROSDK-1184](https://jira.dhis2.org/browse/ANDROSDK-1184)
=> fix: [ANDROSDK-1184] Post enrollments in ERROR/WARNING state

core/src/main/java/org/hisp/dhis/android/core/program/programindicatorengine/internal/dataitem/ProgramItemPsEventdate.java, core/src/main/java/org/hisp/dhis/android/core/program/programindicatorengine/internal/variable/ProgramVariableItem.java, core/src/main/java/org/hisp/dhis/android/core/program/programindicatorengine/internal/variable/VCompletedDate.java, core/src/test/java/org/hisp/dhis/android/core/parser/internal/expression/ExpressionServiceShould.java, core/src/test/java/org/hisp/dhis/android/core/program/programindicatorengine/internal/ProgramIndicatorExecutorShould.java, docs/content/developer/program-indicator-engine.md
Completes [ANDROSDK-529](https://jira.dhis2.org/browse/ANDROSDK-529)
=> feat: ANDROSDK-529-2] Add functions and missing variables to program indicator engine

core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueManager.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityAttributeReservedValueStore.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityAttributeReservedValueStoreInterface.java
Solves [ANDROSDK-1193](https://jira.dhis2.org/browse/ANDROSDK-1193).
=> feat: [androsdk-1193] Update unique values if the attribute pattern changes

core/src/main/java/org/hisp/dhis/android/core/arch/db/querybuilders/internal/OrderByClauseBuilder.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/internal/FilterConnectorFactory.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/scope/internal/RepositoryScopeKeyOrderExtractor.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/scope/internal/RepositoryScopeOrderByItem.java, core/src/main/java/org/hisp/dhis/android/core/event/EventCollectionRepository.java
Solves [ANDROSDK-1196](https://jira.dhis2.org/browse/ANDROSDK-1196)
=> fix: [ANDROSDK-1196] Fix paging in orderyBy organisationUnitName and timeline

core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceService.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceLocalQueryHelper.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryCallFactory.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryOnline.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryRepositoryScope.java, core/src/test/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryCallShould.java
Solves [ANDROSDK-1197](https://jira.dhis2.org/browse/ANDROSDK-1197)
=> feat: [ANDROSDK-1197] TEI query search: add byEventStatus; refactor byEnrollmentStatus

core/src/androidTest/java/org/hisp/dhis/android/core/data/server/RealServerMother.java, core/src/main/java/org/hisp/dhis/android/core/arch/db/querybuilders/internal/WhereClauseBuilder.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceService.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceLocalQueryHelper.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryCallFactory.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryOnline.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryRepositoryScope.java, core/src/test/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceLocalQueryHelperShould.java, core/src/test/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryCallShould.java
Solves [ANDROSDK-1203](https://jira.dhis2.org/browse/ANDROSDK-1203)
=> feat: [ANDROSDK-1203] Add eventDate filters in TEI query search

core/src/androidTest/java/org/hisp/dhis/android/core/event/internal/EventPostCallMockIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstancePostCallMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstancePostCall.java
Solves [ANDROSDK-1207](https://jira.dhis2.org/browse/ANDROSDK-1207)
=> fix: [ANDROSDK-1207] Fix: add tracker notes in sync

core/src/main/java/org/hisp/dhis/android/core/arch/helpers/GeometryHelper.java, core/src/test/java/org/hisp/dhis/android/core/arch/helpers/GeometryHelperShould.java
Solves [ANDROSDK-1208](https://jira.dhis2.org/browse/ANDROSDK-1208)
=> fix: [ANDROSDK-1208] Remove empty spaces in coordinates

README.md, core/build.gradle, core/gradle.properties, core/src/main/java/org/hisp/dhis/android/core/program/programindicatorengine/ProgramIndicatorEngine.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceService.java, core/src/main/java/org/hisp/dhis/android/core/validation/engine/ValidationEngine.java, docs/content/developer/compatibility.md, docs/content/developer/getting-started.md, docs/content/developer/modules-and-repositories.md, docs/content/developer/program-indicator-engine.md, docs/content/developer/settings-app.md, docs/content/developer/settings.md, docs/content/developer/sms.md, docs/content/developer/validation-rule-engine.md, docs/content/developer/workflow.md, docs/dhis2_android_sdk_developer_guide_INDEX.md
Solves [ANDROSDK-1201](https://jira.dhis2.org/browse/ANDROSDK-1201)
=> feat: [ANDROSDK-1201] Update documentation; Version 1.2.0

core/src/main/java/org/hisp/dhis/android/core/systeminfo/internal/DHISVersionManagerImpl.java
Solves [ANDROSDK-1217](https://jira.dhis2.org/browse/ANDROSDK-1217)
=> fix: [ANDROSDK-1217] Version manager: check version before evaluation

core/src/androidTest/java/org/hisp/dhis/android/core/data/server/RealServerMother.java, core/src/main/java/org/hisp/dhis/android/core/systeminfo/DHISPatchVersion.java, core/src/main/java/org/hisp/dhis/android/core/systeminfo/DHISVersion.java, core/src/main/java/org/hisp/dhis/android/core/systeminfo/DHISVersionManager.java, core/src/main/java/org/hisp/dhis/android/core/systeminfo/internal/DHISVersionManagerImpl.java
Solves [ANDROSDK-1228](https://jira.dhis2.org/browse/ANDROSDK-1228)
=> feat: [ANDROSDK-1228] Accept connections to 2.35 servers

core/build.gradle, core/src/main/java/org/hisp/dhis/android/core/parser/internal/expression/ParserUtils.java, core/src/main/java/org/hisp/dhis/android/core/parser/internal/expression/function/FunctionLog.java, core/src/main/java/org/hisp/dhis/android/core/parser/internal/expression/function/FunctionLog10.java, core/src/test/java/org/hisp/dhis/android/core/parser/internal/expression/ExpressionServiceShould.java
Solves [ANDROSDK-1230](https://jira.dhis2.org/browse/ANDROSDK-1230)
=> feat: [ANDROSDK-1230] Update parser library to 1.0.11

core/src/main/java/org/hisp/dhis/android/core/arch/json/internal/ObjectMapperFactory.java, core/src/main/java/org/hisp/dhis/android/core/settings/DataSyncPeriod.java, core/src/main/java/org/hisp/dhis/android/core/settings/MetadataSyncPeriod.java, core/src/sharedTest/resources/settings/general_settings.json, core/src/sharedTest/resources/settings/general_settings_with_unknown_options.json, core/src/test/java/org/hisp/dhis/android/core/settings/GeneralSettingsShould.java
Solves [ANDROSDK-1231](https://jira.dhis2.org/browse/ANDROSDK-1231)
=> feat: [ANDROSDK-1231] Add manual sync options in android settings

core/src/main/java/org/hisp/dhis/android/core/imports/internal/TrackerImportConflictParser.kt, core/src/main/java/org/hisp/dhis/android/core/imports/internal/conflicts/InvalidDataValueConflict.kt, core/src/main/java/org/hisp/dhis/android/core/imports/internal/conflicts/MissingAttributeConflict.kt, core/src/main/java/org/hisp/dhis/android/core/imports/internal/conflicts/TrackerImportConflictItem.kt, core/src/sharedTest/java/org/hisp/dhis/android/core/imports/internal/conflicts/TrackedImportConflictSamples.kt, core/src/test/java/org/hisp/dhis/android/core/imports/internal/conflicts/InvalidDataValueConflictShould.kt, core/src/test/java/org/hisp/dhis/android/core/imports/internal/conflicts/MissingAttributeConflictShould.kt
Add more conflicts. It belongs to [ANDROSDK-1229](https://jira.dhis2.org/browse/ANDROSDK-1229)
=> feat: [ANDROSDK-1229-2] Add InvalidDataValueConflict; persist value

core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentModule.java, core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentService.kt, core/src/main/java/org/hisp/dhis/android/core/enrollment/internal/EnrollmentModuleImpl.java, core/src/test/java/org/hisp/dhis/android/core/enrollment/EnrollmentServiceShould.kt
Solves [ANDROSDK-1221](https://jira.dhis2.org/browse/ANDROSDK-1221)
=> feat: [ANDROSDK-1221] Add EnrollmentService; is enrollment open method

core/src/main/java/org/hisp/dhis/android/core/event/EventService.kt, core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitService.kt, core/src/main/java/org/hisp/dhis/android/core/organisationunit/internal/OrganisationUnitModuleImpl.java, core/src/test/java/org/hisp/dhis/android/core/event/EventServiceShould.kt, core/src/test/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitServiceShould.kt
Solves [ANDROSDK-1225](https://jira.dhis2.org/browse/ANDROSDK-1225)
=> feat: [ANDROSDK-1225] Check orgunit range in eventService 

core/src/androidTest/java/org/hisp/dhis/android/testapp/category/CategoryOptionRepositoryMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/category/CategoryOptionCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/category/CategoryOptionComboService.kt, core/src/main/java/org/hisp/dhis/android/core/category/internal/CategoryModuleImpl.java, core/src/main/java/org/hisp/dhis/android/core/event/EventService.kt, core/src/test/java/org/hisp/dhis/android/core/category/CategoryOptionComboServiceShould.kt, core/src/test/java/org/hisp/dhis/android/core/event/EventServiceShould.kt
Solves [ANDROSDK-1223](https://jira.dhis2.org/browse/ANDROSDK-1223)
=> feat: [ANDROSDK-1223] Add CategoryOptionComboService 

core/src/main/java/org/hisp/dhis/android/core/imports/internal/TrackerImportConflictParser.kt, core/src/main/java/org/hisp/dhis/android/core/imports/internal/conflicts/BadAttributePatternConflict.kt, core/src/main/java/org/hisp/dhis/android/core/imports/internal/conflicts/MissingDataElementConflict.kt, core/src/main/java/org/hisp/dhis/android/core/imports/internal/conflicts/NonUniqueAttributeConflict.kt, core/src/sharedTest/java/org/hisp/dhis/android/core/imports/internal/conflicts/TrackedImportConflictSamples.kt, core/src/test/java/org/hisp/dhis/android/core/imports/internal/conflicts/BadAttributePatternConflictShould.kt, core/src/test/java/org/hisp/dhis/android/core/imports/internal/conflicts/MissingDataElementConflictShould.kt, core/src/test/java/org/hisp/dhis/android/core/imports/internal/conflicts/NonUniqueAttributeConflictShould.kt
Add more TrackerImportConflicts
=> feat: [ANDROSDK-1229-3] Add MissingDataElementConflict; BadAttributePatternConflict; NonUniqueAttributeConflict

core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryEntityDIModule.java
Solves [ANDROSDK-1220](https://jira.dhis2.org/browse/ANDROSDK-1220)
=> feat: [ANDROSDK-1220-2] Inject onlineCache to make it a singleton

core/src/main/java/org/hisp/dhis/android/core/imports/internal/TrackerImportConflictParser.kt, core/src/main/java/org/hisp/dhis/android/core/imports/internal/conflicts/InvalidAttributeValueTypeConflict.kt, core/src/sharedTest/java/org/hisp/dhis/android/core/imports/internal/conflicts/TrackedImportConflictSamples.kt, core/src/test/java/org/hisp/dhis/android/core/imports/internal/conflicts/BadAttributePatternConflictShould.kt, core/src/test/java/org/hisp/dhis/android/core/imports/internal/conflicts/BaseConflictShould.kt, core/src/test/java/org/hisp/dhis/android/core/imports/internal/conflicts/InvalidAttributeValueTypeConflictShould.kt, core/src/test/java/org/hisp/dhis/android/core/imports/internal/conflicts/InvalidDataValueConflictShould.kt, core/src/test/java/org/hisp/dhis/android/core/imports/internal/conflicts/MissingDataElementConflictShould.kt, core/src/test/java/org/hisp/dhis/android/core/imports/internal/conflicts/NonUniqueAttributeConflictShould.kt
Add Invalid attribute value type conflict
=> feat: [ANDROSDK-1229-4] Add invalid attribute value type 

core/src/main/java/org/hisp/dhis/android/core/event/EventService.kt, core/src/test/java/org/hisp/dhis/android/core/event/EventServiceShould.kt
Solves [ANDROSDK-1227](https://jira.dhis2.org/browse/ANDROSDK-1227)
=> feat: [ANDROSDK-1227] Add CanAddEventToEnrollment method

core/src/main/java/org/hisp/dhis/android/core/period/internal/PeriodHelper.java, core/src/main/java/org/hisp/dhis/android/core/period/internal/PeriodStore.java, core/src/main/java/org/hisp/dhis/android/core/period/internal/PeriodStoreImpl.java
Solves [ANDROSDK-1261](https://jira.dhis2.org/browse/ANDROSDK-1261)
=> fix: [ANDROSDK-1261] Fix period generation in period helper

core/src/main/java/org/hisp/dhis/android/core/arch/helpers/UidsHelper.kt, core/src/main/java/org/hisp/dhis/android/core/domain/metadata/MetadataCall.kt, core/src/main/java/org/hisp/dhis/android/core/domain/metadata/internal/MetadataHelper.kt
Solves [ANDROSDK-1247](https://jira.dhis2.org/browse/ANDROSDK-1247)
=> feat: [ANDROSDK-1247] Only persist DataSets linked to Capture scope

core/src/main/java/org/hisp/dhis/android/core/sms/data/localdbrepository/internal/LocalDbRepositoryImpl.java, core/src/main/java/org/hisp/dhis/android/core/sms/domain/interactor/ConfigCase.java, core/src/main/java/org/hisp/dhis/android/core/sms/domain/repository/internal/LocalDbRepository.java, core/src/test/java/org/hisp/dhis/android/core/sms/mockrepos/MockLocalDbRepository.java
Solves [ANDROSDK-1244](https://jira.dhis2.org/browse/ANDROSDK-1244).
=> feat: [ANDROSDK-1244] Method to remove SMS settings

core/src/androidTest/java/org/hisp/dhis/android/testapp/trackedentity/search/TrackedEntityInstanceQueryCollectionRepositoryMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceLocalQueryHelper.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryCollectionRepository.java
Solves [ANDROSDK-1263](https://jira.dhis2.org/browse/ANDROSDK-1263)
=> feat: [ANDROSDK-1263] Implement getUids in tei query repository

core/src/androidTest/java/org/hisp/dhis/android/testapp/datavalue/DataValueCollectionRepositoryMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/internal/SubQueryFilterConnector.java, core/src/main/java/org/hisp/dhis/android/core/datavalue/DataValueByDataSetQueryHelper.kt, core/src/main/java/org/hisp/dhis/android/core/datavalue/DataValueCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/sms/data/localdbrepository/internal/DataSetsStore.java, core/src/main/java/org/hisp/dhis/android/core/validation/engine/internal/ValidationEngineImpl.java
Solves [ANDROSDK-857](https://jira.dhis2.org/browse/ANDROSDK-857)
=> feat: [ANDROSDK-587] Filter by dataSetUid in DataValueCollectionRepository

core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/internal/EqFilterConnector.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/internal/ListFilterConnector.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/internal/ScopedFilterConnectorFactory.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/internal/ScopedRepositoryFilterFactory.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryCollectionRepository.java
Solves [ANDROSDK-1279](https://jira.dhis2.org/browse/ANDROSDK-1279)
=> feat: [ANDROSDK-1279] Remove scope dependency in scoped repositories 

core/src/main/java/org/hisp/dhis/android/core/period/internal/BiWeeklyPeriodGenerator.java, core/src/main/java/org/hisp/dhis/android/core/period/internal/CalendarUtils.kt, core/src/main/java/org/hisp/dhis/android/core/period/internal/PeriodParser.java, core/src/main/java/org/hisp/dhis/android/core/period/internal/WeeklyPeriodGenerator.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityAttributeReservedValueValidatorHelper.java, core/src/test/java/org/hisp/dhis/android/core/period/internal/BiWeeklyPeriodGeneratorShould.java, core/src/test/java/org/hisp/dhis/android/core/period/internal/WeeklyPeriodGeneratorShould.java, core/src/test/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityAttributeReservedValueValidatorHelperShould.java
Solves [ANDROSDK-1280](https://jira.dhis2.org/browse/ANDROSDK-1280)
=> fix: [ANDROSDK-1280-CALENDAR] Workaround for Calendar.set(DAY_OF_WEEK)

core/src/main/java/org/hisp/dhis/android/core/organisationunit/internal/OrganisationUnitCall.java, core/src/main/java/org/hisp/dhis/android/core/organisationunit/internal/OrganisationUnitFields.java, core/src/main/java/org/hisp/dhis/android/core/organisationunit/internal/OrganisationUnitService.java, core/src/main/java/org/hisp/dhis/android/core/organisationunit/internal/SearchOrganisationUnitOnDemandCall.java, core/src/test/java/org/hisp/dhis/android/core/organisationunit/internal/OrganisationUnitCallUnitShould.java
Solves [ANDROSDK-1284](https://jira.dhis2.org/browse/ANDROSDK-1284).
=> feat: [androsdk-1284] Download org units ordered by uid

core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceQueryBuilderFactory.java
Solves [ANDROSDK-1278](https://jira.dhis2.org/browse/ANDROSDK-1278)
=> fix: [ANDROSDK-1278] Set UIDs length as limit for TEIs download

core/src/androidTest/java/org/hisp/dhis/android/core/analytics/eventlinelist/EventLineListIntegrationShould.kt, core/src/androidTest/java/org/hisp/dhis/android/core/analytics/eventlinelist/EventLineListSamples.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/linelist/EventLineListServiceImpl.kt
Solves [ANDROSDK-1285](https://jira.dhis2.org/browse/ANDROSDK-1285)
=> fix: [ANDROSDK-1285] Include events with eventDate and dueDate; ignore others

core/src/main/java/org/hisp/dhis/android/core/arch/json/internal/DateMultiFormatDeserializer.kt, core/src/main/java/org/hisp/dhis/android/core/arch/json/internal/ObjectMapperFactory.kt
Solves [ANDROSDK-1289](https://jira.dhis2.org/browse/ANDROSDK-1289).
=> fix: [ANDROSDK-1289] Add date serializer for multiple date formats

core/src/main/java/org/hisp/dhis/android/core/arch/json/internal/ObjectMapperFactory.kt, core/src/test/java/org/hisp/dhis/android/core/arch/json/internal/ObjectMapperFactoryShould.kt
Solves [ANDROSDK-1299](https://jira.dhis2.org/browse/ANDROSDK-1299)
=> fix: [ANDROSDK-1299] Add default date format in ObjectMapper

core/src/main/java/org/hisp/dhis/android/core/event/search/EventQueryCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/event/search/EventQueryRepositoryScopeHelper.kt, core/src/main/java/org/hisp/dhis/android/core/event/search/EventQueryScopeOrderColumn.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryCollectionRepository.java, core/src/test/java/org/hisp/dhis/android/core/event/internal/EventQueryBundleFactoryShould.kt, core/src/test/java/org/hisp/dhis/android/core/event/search/EventQueryCollectionRepositoryShould.kt, core/src/test/java/org/hisp/dhis/android/core/event/search/EventQueryRepositoryScopeHelperShould.kt
Solves [ANDROSDK-1282](https://jira.dhis2.org/browse/ANDROSDK-1282)
=> feat: [ANDROSDK-1282] Add event working list support

core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/internal/PeriodFilterConnector.java, core/src/main/java/org/hisp/dhis/android/core/event/search/EventCollectionRepositoryAdapter.kt, core/src/main/java/org/hisp/dhis/android/core/event/search/EventQueryCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/event/search/EventQueryRepositoryScope.java, core/src/main/java/org/hisp/dhis/android/core/event/search/EventQueryRepositoryScopeHelper.kt, core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitMode.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceLocalQueryHelper.kt, core/src/test/java/org/hisp/dhis/android/core/event/search/EventCollectionRepositoryAdapterShould.kt, core/src/test/java/org/hisp/dhis/android/core/event/search/EventQueryCollectionRepositoryShould.kt
Solves defects in [ANDROSDK-1070](https://jira.dhis2.org/browse/ANDROSDK-1070)
=> feat: [ANDROSDK-1070-2] Add CAPTURE ouMode support; missing filters in Event query

core/src/main/java/org/hisp/dhis/android/core/event/search/EventCollectionRepositoryAdapter.kt, core/src/main/java/org/hisp/dhis/android/core/event/search/EventQueryCollectionRepository.java
Enable data source for EventQueryCollectionRepository for this issue: https://jira.dhis2.org/browse/ANDROAPP-3625
=> feat: [ANDROAPP-3625] Add workinglist in events

core/src/androidTest/java/org/hisp/dhis/android/testapp/event/EventCollectionRepositoryMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/internal/BaseSubQueryFilterConnector.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/internal/DateFilterConnector.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/internal/FilterConnectorFactory.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/internal/PeriodFilterConnector.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/internal/SubQueryFilterConnector.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/internal/ValueSubQueryFilterConnector.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/scope/internal/FilterItemOperator.java, core/src/main/java/org/hisp/dhis/android/core/common/DateFilterPeriodHelper.kt, core/src/main/java/org/hisp/dhis/android/core/event/EventCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/event/search/EventCollectionRepositoryAdapter.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryCollectionRepository.java, core/src/sharedTest/resources/event/events.json, core/src/test/java/org/hisp/dhis/android/core/event/search/EventQueryCollectionRepositoryShould.kt, core/src/test/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceLocalQueryHelperShould.java
Solves [ANDROSDK-1321](https://jira.dhis2.org/browse/ANDROSDK-1321)
=> feat: [ANDROSDK-1321] Include afterOrEqual and beforeOrEqual filters

core/src/main/java/org/hisp/dhis/android/core/event/EventEditableStatus.kt, core/src/main/java/org/hisp/dhis/android/core/event/EventNonEditableReason.kt, core/src/main/java/org/hisp/dhis/android/core/event/EventService.kt, core/src/test/java/org/hisp/dhis/android/core/event/EventServiceShould.kt
Solves [ANDROSDK-1288](https://jira.dhis2.org/browse/ANDROSDK-1288)
=> feat: [ANDROSDK-1288] Add reason for non editable events

core/src/main/java/org/hisp/dhis/android/core/settings/AppearanceSettingsObjectRepository.java
https://jira.dhis2.org/browse/ANDROSDK-1317
=> feat: [ANDROSDK-1317-EXISTS] Check is appearance setting is configured

core/src/main/assets/migrations/96.sql
=> fix: [FIX-MIGRATION-96] Fix typo in migration 96

core/src/main/java/org/hisp/dhis/android/core/sms/data/localdbrepository/internal/LocalDbRepositoryImpl.java, core/src/main/java/org/hisp/dhis/android/core/sms/domain/repository/internal/LocalDbRepository.java, core/src/main/java/org/hisp/dhis/android/core/sms/internal/SMSModuleWiper.java, core/src/main/java/org/hisp/dhis/android/core/wipe/internal/D2ModuleWipers.java, core/src/test/java/org/hisp/dhis/android/core/sms/mockrepos/MockLocalDbRepository.java
Partially solves [ANDROSDK-1322](https://jira.dhis2.org/browse/ANDROSDK-1322)
=> fix: [ANDROSDK-1322] Delete SMS shared preferences on delete metadata

core/src/main/java/org/hisp/dhis/android/core/D2.java, core/src/main/java/org/hisp/dhis/android/core/D2Manager.java, core/src/main/java/org/hisp/dhis/android/core/OkHttpClientFactory.java, core/src/main/java/org/hisp/dhis/android/core/arch/api/authentication/internal/BasicAuthenticator.kt, core/src/main/java/org/hisp/dhis/android/core/arch/d2/internal/D2DIComponent.java, core/src/main/java/org/hisp/dhis/android/core/arch/storage/internal/UserIdInMemoryStore.kt, core/src/main/java/org/hisp/dhis/android/core/user/internal/LogInCall.kt, core/src/main/java/org/hisp/dhis/android/core/user/internal/LogOutCall.kt, core/src/main/java/org/hisp/dhis/android/core/user/internal/UserStore.java, core/src/test/java/org/hisp/dhis/android/core/arch/api/authentication/internal/BasicAuthenticatorShould.java, core/src/test/java/org/hisp/dhis/android/core/user/internal/LogInCallUnitShould.java, core/src/test/java/org/hisp/dhis/android/core/user/internal/LogOutCallShould.java
Solves [ANDROSDK-1283](https://jira.dhis2.org/browse/ANDROSDK-1283)
=> feat: [ANDROSDK-1283-2] Add user id in custom header

core/src/androidTest/java/org/hisp/dhis/android/testapp/event/EventCollectionRepositoryMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/internal/FilterConnectorFactory.java, core/src/main/java/org/hisp/dhis/android/core/event/EventCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/event/search/EventCollectionRepositoryAdapter.kt, core/src/main/java/org/hisp/dhis/android/core/event/search/EventQueryCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/event/search/EventQueryRepositoryScopeHelper.kt, core/src/main/java/org/hisp/dhis/android/core/event/search/EventQueryScopeOrderColumn.java, core/src/test/java/org/hisp/dhis/android/core/event/search/EventQueryRepositoryScopeHelperShould.kt
Solves [ANDROSDK-1305](https://jira.dhis2.org/browse/ANDROSDK-1305)
=> feat: [ANDROSDK-1305] Add support for orderByDataElement in Events

core/src/androidTest/java/org/hisp/dhis/android/core/event/internal/EventCallFactory.kt, core/src/androidTest/java/org/hisp/dhis/android/core/event/internal/EventDownloadRealIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/event/internal/EventDownloadCall.kt, core/src/main/java/org/hisp/dhis/android/core/event/internal/EventEndpointCallFactory.kt, core/src/main/java/org/hisp/dhis/android/core/event/internal/EventQuery.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstancesEndpointCallFactory.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackerSyncLastUpdatedManager.kt, core/src/test/java/org/hisp/dhis/android/core/event/internal/EventEndpointCallShould.java
Solves [ANDROSDK-1331](https://jira.dhis2.org/browse/ANDROSDK-1331)
=> fix: [ANDROSDK-1331] Fix event download (missing programId)

core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryCallFactory.java
Solves [ANDROSDK-1339](https://jira.dhis2.org/browse/ANDROSDK-1339)
=> [ANDROSDK-1339] TEI query: do not append empty string if orgunit list is empty

core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceCallMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/event/internal/EventDownloadCall.kt, core/src/main/java/org/hisp/dhis/android/core/event/internal/EventQueryBundleInternalFactory.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceQueryInternalFactory.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackerQueryFactoryCommonHelper.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryCallFactory.java, docs/content/developer/compatibility.md, docs/content/developer/getting-started.md, docs/content/developer/known-issues.md, docs/dhis2_android_sdk_developer_guide_INDEX.md
=> fix: [MASTER-DEV] Version 1.3.2 

core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstancePostCallRealIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/arch/db/adapters/ignore/internal/IgnoreNewTrackerImporterEnrollmentListColumnAdapter.java, core/src/main/java/org/hisp/dhis/android/core/arch/db/adapters/ignore/internal/IgnoreNewTrackerImporterEventListColumnAdapter.java, core/src/main/java/org/hisp/dhis/android/core/arch/db/adapters/ignore/internal/IgnoreNewTrackerImporterTrackedEntityAttributeValueListColumnAdapter.java, core/src/main/java/org/hisp/dhis/android/core/enrollment/NewTrackerImporterEnrollment.java, core/src/main/java/org/hisp/dhis/android/core/enrollment/NewTrackerImporterEnrollmentTransformer.kt, core/src/main/java/org/hisp/dhis/android/core/event/internal/EventTrackerImporterPostCall.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/NewTrackerImporterTrackedEntity.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/NewTrackerImporterTrackedEntityAttributeValue.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/NewTrackerImporterTrackedEntityAttributeValueTransformer.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/NewTrackerImporterTrackedEntityInstance.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/NewTrackerImporterTranckedEntityTransformer.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/NewTrackerImporterTrackedEntityPayload.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/NewTrackerImporterTrackedEntityPostPayloadGenerator.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/NewTrackerImporterTrackedEntityPostStateManager.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/StatePersistorHelper.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstancePostStateManager.kt, core/src/main/java/org/hisp/dhis/android/core/tracker/importer/internal/TrackedEntityInstanceTrackerImporterPostCall.kt
Solves [ANDROSDK-1316](https://jira.dhis2.org/browse/ANDROSDK-1316)
=> feat: [ANDROSDK-1316] Tracker importer, tracked entities serialization

core/src/androidTest/java/org/hisp/dhis/android/core/event/internal/EventPostCallRealIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/wipe/WipeDBCallMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/arch/helpers/internal/DataStateHelper.kt, core/src/main/java/org/hisp/dhis/android/core/common/StorableObjectWithUid.java, core/src/main/java/org/hisp/dhis/android/core/enrollment/NewTrackerImporterEnrollmentTransformer.kt, core/src/main/java/org/hisp/dhis/android/core/event/NewTrackerImporterEventTransformer.kt, core/src/main/java/org/hisp/dhis/android/core/event/internal/EventTrackerImporterPostCall.kt, core/src/main/java/org/hisp/dhis/android/core/note/NewTrackerImporterNoteTransformer.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/NewTrackerImporterTranckedEntityTransformer.kt, core/src/main/java/org/hisp/dhis/android/core/tracker/importer/internal/JobQueryCall.kt, core/src/main/java/org/hisp/dhis/android/core/tracker/importer/internal/TrackedEntityInstanceTrackerImporterPostCall.kt
Solves [ANDROSDK-1341](https://jira.dhis2.org/browse/ANDROSDK-1341)
=> feat: [ANDROSDK-1341] New tracker importer: improve error handling

core/build.gradle, core/src/test/java/org/hisp/dhis/android/core/systeminfo/internal/SystemInfoCallShould.java
=> feat: [ANTLR-1.0.15] Update parser version 

build.gradle, core/plugins/gradle-mvn-push.gradle
Solves [ANDROSDK-1249](https://jira.dhis2.org/browse/ANDROSDK-1249)
=> feat: [ANDROSDK-1249] Configure dokka plugin

core/src/androidTest/java/org/hisp/dhis/android/core/event/internal/EventDownloadRealIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/relationship/internal/RelationshipDownloadAndPersistCallFactory.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceService.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackerQueryFactory.kt
Solves [ANDROSDK-1351](https://jira.dhis2.org/browse/ANDROSDK-1351)
=> fix: [ANDROSDK-1351] Fix TEI uid download doing extra call; fix related TEI download

build.gradle, core/build.gradle
Solves [ANDROSDK-1352](https://jira.dhis2.org/browse/ANDROSDK-1352)
=> fix: [ANDROSDK-1352] Remove dokka dependency as submodule

core/src/main/java/org/hisp/dhis/android/core/arch/api/authentication/internal/UserIdAuthenticatorHelper.kt, core/src/main/java/org/hisp/dhis/android/core/arch/helpers/UserHelper.java
Solves [ANDROSDK-1353](https://jira.dhis2.org/browse/ANDROSDK-1353).
=> feat: [ANDROSDK-1353] Align http header with backend

core/src/main/java/org/hisp/dhis/android/core/parser/internal/service/utils/ExpressionHelper.kt, core/src/test/java/org/hisp/dhis/android/core/parser/internal/service/utils/ExpressionHelperShould.kt
Solves [ANDROSDK-1354](https://jira.dhis2.org/browse/ANDROSDK-1354)
=>  fix: [ANDROSDK-1354] Validation rules: ignore non-numeric values 

core/src/main/java/org/hisp/dhis/android/core/program/programindicatorengine/internal/dataitem/ProgramItemAttribute.java, core/src/main/java/org/hisp/dhis/android/core/program/programindicatorengine/internal/dataitem/ProgramItemStageElement.java
Solves [ANDROSDK-1356](https://jira.dhis2.org/browse/ANDROSDK-1356)
=> fix: [ANDROSDK-1356] Fix null values for stage dataelements and attributes

core/src/main/java/org/hisp/dhis/android/core/event/internal/EventHandler.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityDataValueEntityDIModule.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityDataValueHandler.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityDataValueStore.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityDataValueStoreImpl.java, core/src/test/java/org/hisp/dhis/android/core/event/internal/EventHandlerShould.java
Solves [ANDROSDK-1360](https://jira.dhis2.org/browse/ANDROSDK-1360)
=> fix: [ANDROSDK-1360] Delete event datavalues if empty list

core/src/androidTest/java/org/hisp/dhis/android/core/analytics/eventlinelist/EventLineListIntegrationShould.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/linelist/EventLineListServiceImpl.kt, core/src/main/java/org/hisp/dhis/android/core/program/programindicatorengine/internal/ProgramIndicatorEngineImpl.kt
Solves [ANDROSDK-1363](https://jira.dhis2.org/browse/ANDROSDK-1363)
=> fix: [ANDROSDK-1363] Ignore deleted events in EventLineList service

core/build.gradle, core/src/main/AndroidManifest.xml
Solves [ANDROSDK-1364](https://jira.dhis2.org/browse/ANDROSDK-1364)
=> feat: [ANDROSDK-1364] Include openid parameter in sdk manifest file

docs/content/developer/about-this-android-guide.md, docs/content/developer/analytics.md, docs/content/developer/compatibility-strategy.md, docs/content/developer/compatibility.md, docs/content/developer/database.md, docs/content/developer/db-interaction.md, docs/content/developer/debugging.md, docs/content/developer/dhis2-services.md, docs/content/developer/error-management.md, docs/content/developer/getting-started.md, docs/content/developer/known-issues.md, docs/content/developer/modules-and-repositories.md, docs/content/developer/object-style.md, docs/content/developer/overview.md, docs/content/developer/program-indicator-engine.md, docs/content/developer/program-rule-engine.md, docs/content/developer/settings.md, docs/content/developer/sms.md, docs/content/developer/validation-rule-engine.md, docs/content/developer/workflow.md
Solves [ANDROSDK-1358](https://jira.dhis2.org/browse/ANDROSDK-1358)
=> feat: [ANDROSDK-1358-2] Fix documentation links

core/src/main/java/org/hisp/dhis/android/core/configuration/internal/MultiUserDatabaseManager.java, core/src/main/java/org/hisp/dhis/android/core/sms/data/localdbrepository/internal/LocalDbRepositoryImpl.java, core/src/main/java/org/hisp/dhis/android/core/sms/domain/repository/internal/LocalDbRepository.java, core/src/test/java/org/hisp/dhis/android/core/configuration/internal/MultiUserDatabaseManagerUnitShould.java, core/src/test/java/org/hisp/dhis/android/core/sms/mockrepos/MockLocalDbRepository.java
Solves [ANDROSDK-1367](https://jira.dhis2.org/browse/ANDROSDK-1367)
=> fix: [ANDROSDK-1367] Delete SMS config on new database

core/src/main/java/org/hisp/dhis/android/core/category/CategoryOption.java, core/src/main/java/org/hisp/dhis/android/core/category/CategoryOptionCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/category/internal/CategoryOptionCall.kt
Solves [ANDROSDK-1260](https://jira.dhis2.org/browse/ANDROSDK-1260)
=> fix: [ANDROSDK-1260] Do not download orgunits in CategoryOptions

core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstancePostPayloadGenerator.kt
Solves [ANDROSDK-1368](https://jira.dhis2.org/browse/ANDROSDK-1368)
=> feat: [ANDROSDK-1368] Update post tei page to 20

docs/content/developer/debugging.md
=> feat: [MASTER-DEV] Update flipper documentation

core/src/main/java/org/hisp/dhis/android/core/tracker/importer/internal/JobQueryCall.kt, core/src/main/java/org/hisp/dhis/android/core/tracker/importer/internal/JobReportHandler.kt
- Do not handle object if there is a more recent update to process
- Set status to TO_UPDATE when expected in job report but not present
Solves [ANDROSDK-1310](https://jira.dhis2.org/browse/ANDROSDK-1310)
=> feat: [ANDROSDK-1310] New tracker importer: consider job expected objects

core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceLocalQueryHelper.kt
Solves [ANDROSDK-1373](https://jira.dhis2.org/browse/ANDROSDK-1373)
=> fix: [ANDROSDK-1373] Filter OVERDUE/SCHEDULE events by eventStatus

core/src/main/java/org/hisp/dhis/android/core/program/programindicatorengine/internal/variable/ProgramVariableItem.java, core/src/main/java/org/hisp/dhis/android/core/program/programindicatorengine/internal/variable/VTeiCount.java, core/src/test/java/org/hisp/dhis/android/core/program/programindicatorengine/internal/ProgramIndicatorExecutorShould.kt
Solves [ANDROSDK-1375](https://jira.dhis2.org/browse/ANDROSDK-1375)
=> fix: [ANDROSDK-1375] Create VTeiCount variable

core/src/androidTest/java/org/hisp/dhis/android/core/program/programindicatorengine/ProgramIndicatorEngineIntegrationShould.kt, core/src/main/java/org/hisp/dhis/android/core/program/programindicatorengine/internal/dataitem/ProgramItemStageElement.java, core/src/test/java/org/hisp/dhis/android/core/program/programindicatorengine/internal/ProgramIndicatorExecutorShould.kt
Solves [ANDROSDK-1381](https://jira.dhis2.org/browse/ANDROSDK-1381)
=> fix: [ANDROSDK-1381] Pick most recent data value in repeatable stage 

core/src/main/java/org/hisp/dhis/android/core/period/internal/AbstractPeriodGenerator.java, core/src/test/java/org/hisp/dhis/android/core/period/internal/BiWeeklyPeriodGeneratorShould.java
Solves [ANDROSDK-1315](https://jira.dhis2.org/browse/ANDROSDK-1315).
=> feat: [androsdk-1315] Improve period generator to fix BiWeekly generation on some years

core/src/main/java/org/hisp/dhis/android/core/user/openid/OpenIDConnectHandlerImpl.kt
Solves [ANDROSDK-1391](https://jira.dhis2.org/browse/ANDROSDK-1391)
=> fix: [ANDROSDK-1391] Download token using IO scheduler

core/build.gradle, core/gradle.properties, core/src/main/java/org/hisp/dhis/android/core/event/internal/OldEventPostCall.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/OldTrackedEntityInstancePostCall.kt, docs/content/developer/getting-started.md, docs/dhis2_android_sdk_developer_guide_INDEX.md
Solves [ANDROSDK-1399](https://jira.dhis2.org/browse/ANDROSDK-1399)
=> fix: [ANDROSDK-1399] Catch any exception and restore states

core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceDownloadInternalCall.kt
Solves [ANDROSDK-1400](https://jira.dhis2.org/browse/ANDROSDK-1400)
=> fix: [ANDROSDK-1400] Do not overwrite enrollments if download by program

core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryCallFactory.java, core/src/test/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryCallShould.java
Solves [ANDROSDK-1401](https://jira.dhis2.org/browse/ANDROSDK-1401)
=> fix: [ANDROSDK-1401] Map ACTIVE to VISITED if version <= 2.33

core/src/main/java/org/hisp/dhis/android/core/common/internal/DataStatePropagator.kt, core/src/main/java/org/hisp/dhis/android/core/common/internal/DataStatePropagatorImpl.kt, core/src/main/java/org/hisp/dhis/android/core/enrollment/internal/EnrollmentImportHandler.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceObjectRepository.java, core/src/main/java/org/hisp/dhis/android/core/tracker/importer/internal/JobReportEnrollmentHandler.kt, core/src/main/java/org/hisp/dhis/android/core/tracker/importer/internal/JobReportEventHandler.kt, core/src/main/java/org/hisp/dhis/android/core/tracker/importer/internal/JobReportTrackedEntityHandler.kt, core/src/test/java/org/hisp/dhis/android/core/enrollment/internal/EnrollmentImportHandlerShould.java
Solves [ANDROSDK-1312](https://jira.dhis2.org/browse/ANDROSDK-1312)
=> feat: [ANDROSDK-1312-2] Tracker importer: manage deleted items

core/src/androidTest/java/org/hisp/dhis/android/core/analytics/aggregated/internal/evaluator/AnalyticsVisualizationRepositoryIntegrationShould.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/aggregated/AggregatedEntityDIModule.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/aggregated/AnalyticsVisualizationsRepository.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/aggregated/DimensionalResponse.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/aggregated/GridAnalyticsResponse.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/aggregated/internal/AnalyticsService.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/aggregated/internal/AnalyticsVisualizationsRepositoryImpl.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/aggregated/internal/AnalyticsVisualizationsRepositoryParams.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/aggregated/internal/AnalyticsVisualizationsService.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/aggregated/mock/DimensionalResponseSamples.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/aggregated/mock/GridAnalyticsResponseSamples.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/aggregated/mock/MockAnalyticsVisualizationsRepository.kt
Solves [ANDROSDK-1408](https://jira.dhis2.org/browse/ANDROSDK-1408)
=> feat: [ANDROSDK-1408] Implement Visualization repository filters

core/src/main/java/org/hisp/dhis/android/core/visualization/internal/VisualizationEntityDIModule.kt, core/src/main/java/org/hisp/dhis/android/core/visualization/internal/VisualizationHandler.kt, core/src/test/java/org/hisp/dhis/android/core/visualization/internal/VisualizationHandlerShould.java
Solves [ANDROSDK-1412](https://jira.dhis2.org/browse/ANDROSDK-1412).
=> fix: [androsdk-1412] Ensure AnalyticsDhisVisualizations are not removed on second sync

core/src/androidTest/java/org/hisp/dhis/android/core/organisationunit/internal/OrganisationUnitCallMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/organisationunit/internal/OrganisationUnitCall.java, core/src/main/java/org/hisp/dhis/android/core/organisationunit/internal/OrganisationUnitEntityDIModule.java, core/src/main/java/org/hisp/dhis/android/core/organisationunit/internal/OrganisationUnitHandlerImpl.java, core/src/test/java/org/hisp/dhis/android/core/organisationunit/internal/OrganisationUnitCallUnitShould.java
Solves [ANDROSDK-1393](https://jira.dhis2.org/browse/ANDROSDK-1393).
=> fix: [androsdk-1393] Remove outdated orgunits in synchronization

core/src/main/java/org/hisp/dhis/android/core/program/programindicatorengine/internal/ProgramIndicatorEngineImpl.kt, core/src/main/java/org/hisp/dhis/android/core/program/programindicatorengine/internal/ProgramIndicatorExecutor.kt, core/src/main/java/org/hisp/dhis/android/core/program/programindicatorengine/internal/function/D2Condition.java, core/src/main/java/org/hisp/dhis/android/core/program/programindicatorengine/internal/function/D2CountIfCondition.java, core/src/test/java/org/hisp/dhis/android/core/program/programindicatorengine/internal/ProgramIndicatorExecutorShould.kt
Solves [ANDROSDK-1416](https://jira.dhis2.org/browse/ANDROSDK-1416)
=> feat: [ANDROSDK-1416] Evaluate filter in ProramIndicatorEngine 

core/src/main/java/org/hisp/dhis/android/core/common/internal/DataStatePropagatorImpl.kt, core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/relationship/internal/RelationshipItemStore.kt, core/src/main/java/org/hisp/dhis/android/core/relationship/internal/RelationshipItemStoreImpl.kt
Solves [ANDROSDK-1420](https://jira.dhis2.org/browse/ANDROSDK-1420)
=> fix: [ANDROSDK-1420] Accept incomplete Relationships 

core/src/main/java/org/hisp/dhis/android/core/enrollment/Enrollment.java, core/src/main/java/org/hisp/dhis/android/core/enrollment/NewTrackerImporterEnrollment.java, core/src/main/java/org/hisp/dhis/android/core/event/Event.java, core/src/main/java/org/hisp/dhis/android/core/event/NewTrackerImporterEvent.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/NewTrackerImporterTrackedEntity.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstance.java
Solves [ANDROSDK-1422](https://jira.dhis2.org/browse/ANDROSDK-1422)
=> fix: [ANDROSDK-1422] Send createdAtClient and lastUpdatedAtClient properties

core/src/androidTest/java/org/hisp/dhis/android/core/analytics/aggregated/internal/evaluator/BaseEvaluatorIntegrationShould.kt, core/src/androidTest/java/org/hisp/dhis/android/core/analytics/aggregated/internal/evaluator/BaseEvaluatorSamples.kt, core/src/androidTest/java/org/hisp/dhis/android/core/analytics/aggregated/internal/evaluator/DataElementEvaluatorIntegrationShould.kt, core/src/androidTest/java/org/hisp/dhis/android/core/analytics/aggregated/internal/evaluator/ProgramIndicatorEvaluatorIntegrationShould.kt, core/src/androidTest/java/org/hisp/dhis/android/core/program/programindicatorengine/BaseTrackerDataIntegrationHelper.kt, core/src/androidTest/java/org/hisp/dhis/android/core/program/programindicatorengine/ProgramIndicatorEngineIntegrationShould.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/aggregated/internal/AnalyticsServiceEvaluatorHelper.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/aggregated/internal/evaluator/AnalyticsEvaluatorHelper.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/aggregated/internal/evaluator/DataElementEvaluator.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/aggregated/internal/evaluator/ProgramIndicatorEvaluator.kt
Partially solves [ANDROSDK-1404](https://jira.dhis2.org/browse/ANDROSDK-1404)
=> feat: [ANDROSDK-1404] Apply programIndicator analytics

core/src/androidTest/java/org/hisp/dhis/android/core/analytics/aggregated/internal/evaluator/BaseEvaluatorIntegrationShould.kt, core/src/androidTest/java/org/hisp/dhis/android/core/analytics/aggregated/internal/evaluator/IndicatorEvaluatorIntegrationShould.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/aggregated/internal/AnalyticsServiceEvaluatorHelper.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/aggregated/internal/AnalyticsServiceMetadataHelper.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/aggregated/internal/evaluator/IndicatorEvaluator.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/aggregated/internal/evaluator/indicatorengine/IndicatorContext.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/aggregated/internal/evaluator/indicatorengine/IndicatorEngine.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/aggregated/internal/evaluator/indicatorengine/IndicatorParserUtils.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/aggregated/internal/evaluator/indicatorengine/dataitem/DataElementItem.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/aggregated/internal/evaluator/indicatorengine/dataitem/ProgramIndicatorItem.kt, core/src/main/java/org/hisp/dhis/android/core/constant/internal/ConstantStore.kt, core/src/main/java/org/hisp/dhis/android/core/indicator/datasetindicatorengine/DataSetIndicatorEvaluator.kt, core/src/main/java/org/hisp/dhis/android/core/organisationunit/internal/OrganisationUnitGroupStore.kt, core/src/main/java/org/hisp/dhis/android/core/parser/internal/expression/CommonExpressionVisitor.java, core/src/main/java/org/hisp/dhis/android/core/parser/internal/service/ExpressionService.java, core/src/main/java/org/hisp/dhis/android/core/period/internal/PeriodHelper.java, core/src/test/java/org/hisp/dhis/android/core/analytics/aggregated/internal/AnalyticsServiceMetadataHelperShould.kt, core/src/test/java/org/hisp/dhis/android/core/parser/internal/expression/ExpressionServiceShould.java, core/src/test/java/org/hisp/dhis/android/core/period/internal/PeriodHelperShould.kt
Solves [ANDROSDK-1403](https://jira.dhis2.org/browse/ANDROSDK-1403)
=> feat: [ANDROSDK-1403] Implement indicatorEvalutor

core/src/main/java/org/hisp/dhis/android/core/arch/handlers/internal/IdentifiableDataHandlerImpl.kt
Solves [ANDROSDK-1425](https://jira.dhis2.org/browse/ANDROSDK-1425)
=> fix: [ANDROSDK-1425] Do not overwrite data if syncState is not valid

core/src/androidTest/java/org/hisp/dhis/android/core/analytics/eventlinelist/EventLineListIntegrationShould.kt, core/src/androidTest/java/org/hisp/dhis/android/core/analytics/eventlinelist/EventLineListSamples.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/linelist/EventLineListParams.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/linelist/EventLineListRepository.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/linelist/EventLineListRepositoryImpl.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/linelist/EventLineListServiceImpl.kt, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/internal/OrganisationUnitFilterConnector.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/internal/PeriodsFilterConnector.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/internal/ScopedFilterConnectorFactory.java, core/src/main/java/org/hisp/dhis/android/core/common/OrganisationUnitFilter.kt, core/src/test/java/org/hisp/dhis/android/core/analytics/linelist/EventLineListRepositoryShould.kt
Solves [ANDROSDK-1424](https://jira.dhis2.org/browse/ANDROSDK-1424)
=> feat: [ANDROSDK-1424] Implement evaluation of eventDate and orgunit filters

core/src/main/java/org/hisp/dhis/android/core/arch/api/internal/ServerURLVersionRedirectionInterceptor.kt, core/src/main/java/org/hisp/dhis/android/core/user/internal/LogInCall.kt, core/src/test/java/org/hisp/dhis/android/core/user/internal/LogInCallUnitShould.java
Solves [ANDROSDK-1426](https://jira.dhis2.org/browse/ANDROSDK-1426)
=> feat: [ANDROSDK-1426] Improve login error messages; fix multiple redirects

core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/internal/BasePayloadGeneratorMockIntegration.kt, core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/internal/OldTrackerImporterPayloadGeneratorMockIntegrationShould.kt, core/src/main/java/org/hisp/dhis/android/core/enrollment/internal/EnrollmentImportHandler.kt, core/src/main/java/org/hisp/dhis/android/core/event/EventService.kt, core/src/main/java/org/hisp/dhis/android/core/event/internal/EventImportHandler.kt, core/src/main/java/org/hisp/dhis/android/core/event/internal/OldEventPostCall.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/OldTrackerImporterPayloadGenerator.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/OldTrackerImporterPostCall.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceImportHandler.kt, core/src/test/java/org/hisp/dhis/android/core/enrollment/internal/EnrollmentImportHandlerShould.java, core/src/test/java/org/hisp/dhis/android/core/event/EventServiceShould.kt, core/src/test/java/org/hisp/dhis/android/core/event/internal/EventImportHandlerShould.java, core/src/test/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceImportHandlerShould.kt
Solves [ANDROSDK-1411](https://jira.dhis2.org/browse/ANDROSDK-1411)
=> feat: [ANDROSDK-1411] Do not include nonWritable TEIs and enrollments if not modified

core/src/main/java/org/hisp/dhis/android/core/tracker/importer/internal/JobQueryCall.kt
Solves [ANDROSDK-1343](https://jira.dhis2.org/browse/ANDROSDK-1343)
=> feat: [ANDROSDK-1343] New tracker importer: set initial delay 1s, interval 2s

core/src/androidTest/java/org/hisp/dhis/android/core/analytics/aggregated/internal/evaluator/ProgramIndicatorEvaluatorIntegrationShould.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/aggregated/internal/AnalyticsException.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/aggregated/internal/AnalyticsServiceMetadataHelper.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/aggregated/internal/evaluator/ProgramIndicatorEvaluatorHelper.kt, core/src/test/java/org/hisp/dhis/android/core/analytics/aggregated/internal/AnalyticsServiceMetadataHelperShould.kt
Solves [ANDROSDK-1434](https://jira.dhis2.org/browse/ANDROSDK-1434)
=> feat: [ANDROSDK-1434] Validate program indicator boundaries

core/src/androidTest/java/org/hisp/dhis/android/core/visualization/internal/DataDimensionItemProgramAttributeStoreIntegrationShould.kt, core/src/androidTest/java/org/hisp/dhis/android/core/visualization/internal/DataDimensionItemProgramDataElementStoreIntegrationShould.kt, core/src/main/java/org/hisp/dhis/android/core/arch/db/adapters/identifiable/internal/DataDimensionItemProgramAttributeWithUidColumnAdapter.java, core/src/main/java/org/hisp/dhis/android/core/arch/db/adapters/identifiable/internal/DataDimensionItemProgramDataElementWithUidColumnAdapter.java, core/src/main/java/org/hisp/dhis/android/core/arch/db/adapters/ignore/internal/IgnoreObjectWithUidColumnAdapter.java, core/src/main/java/org/hisp/dhis/android/core/visualization/DataDimensionItem.java, core/src/main/java/org/hisp/dhis/android/core/visualization/DataDimensionItemProgramAttribute.java, core/src/main/java/org/hisp/dhis/android/core/visualization/DataDimensionItemProgramDataElement.java, core/src/main/java/org/hisp/dhis/android/core/visualization/internal/DataDimensionItemProgramAttributeFields.kt, core/src/main/java/org/hisp/dhis/android/core/visualization/internal/DataDimensionItemProgramDataElementFields.kt, core/src/sharedTest/java/org/hisp/dhis/android/core/data/visualization/VisualizationSamples.kt, core/src/sharedTest/resources/visualization/visualization.json, core/src/test/java/org/hisp/dhis/android/core/visualization/VisualizationShould.java, core/src/test/java/org/hisp/dhis/android/core/visualization/VisualizationSimplifiedShould.java
Solves [ANDROSDK-1435](https://jira.dhis2.org/browse/ANDROSDK-1435)
=> fix: [ANDROSDK-1435] Visualisation: adapt programDataElement and programAttribute

core/src/androidTest/java/org/hisp/dhis/android/core/analytics/aggregated/internal/evaluator/IndicatorEvaluatorIntegrationShould.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/aggregated/internal/evaluator/indicatorengine/IndicatorContext.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/aggregated/internal/evaluator/indicatorengine/IndicatorEngine.kt
Complements [ANDROSDK-1404](https://jira.dhis2.org/browse/ANDROSDK-1404)
=> fix: [ANDROSDK-1404-3] Use ProgramIndicatorSQLEvaluator in IndicatorEngine

core/src/androidTest/java/org/hisp/dhis/android/core/analytics/aggregated/internal/evaluator/BaseEvaluatorIntegrationShould.kt, core/src/androidTest/java/org/hisp/dhis/android/core/analytics/aggregated/internal/evaluator/BaseEvaluatorSamples.kt, core/src/androidTest/java/org/hisp/dhis/android/core/analytics/aggregated/internal/evaluator/IndicatorEvaluatorIntegrationShould.kt, core/src/androidTest/java/org/hisp/dhis/android/core/analytics/aggregated/internal/evaluator/IndicatorSQLEvaluatorIntegrationShould.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/AnalyticsException.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/aggregated/AnalyticsModel.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/aggregated/internal/AnalyticsServiceMetadataHelper.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/aggregated/internal/evaluator/indicatorengine/IndicatorContext.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/aggregated/internal/evaluator/indicatorengine/IndicatorEngine.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/aggregated/internal/evaluator/indicatorengine/IndicatorSQLEngine.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/aggregated/internal/evaluator/indicatorengine/dataitem/DataElementItem.kt, core/src/test/java/org/hisp/dhis/android/core/analytics/aggregated/internal/AnalyticsServiceMetadataHelperShould.kt
Solves [ANDROSDK-1439](https://jira.dhis2.org/browse/ANDROSDK-1439)
=> feat: [ANDROSDK-1439] Add pretty name to metadata dataElementOperand

core/src/main/java/org/hisp/dhis/android/core/enrollment/NewTrackerImporterEnrollment.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/NewTrackerImporterTrackedEntityPostPayloadGenerator.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/NewTrackerImporterTrackedEntityPostPayloadGeneratorTask.kt, core/src/test/java/org/hisp/dhis/android/core/trackedentity/internal/NewTrackerImporterTrackedEntityPostPayloadGeneratorTaskShould.kt
Solves [ANDROSDK-1441](https://jira.dhis2.org/browse/ANDROSDK-1441)
=> fix: [ANDROSDK-1441] Include programAttributes in the enrollment payload

core/src/main/java/org/hisp/dhis/android/core/event/internal/EventDownloadCall.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceDownloadInternalCall.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackerQueryFactoryCommonHelper.kt
Complements [ANDROSDK-1413](https://jira.dhis2.org/browse/ANDROSDK-1413)
=> fix: [ANDROSDK-1413-3] Adapt Tracker download calls

core/src/main/java/org/hisp/dhis/android/core/event/internal/EventStoreImpl.kt, core/src/main/java/org/hisp/dhis/android/core/relationship/internal/RelationshipImportHandler.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityDataValueStoreImpl.java, core/src/main/java/org/hisp/dhis/android/core/tracker/importer/internal/JobReportRelationshipHandler.kt, core/src/test/java/org/hisp/dhis/android/core/relationship/internal/RelationshipImportHandlerShould.kt
Solves [ANDROSDK-1456](https://jira.dhis2.org/browse/ANDROSDK-1456)
=> fix: [ANDROSDK-1456] Include soft-modified events in POST call

core/src/androidTest/java/org/hisp/dhis/android/testapp/settings/AppearanceSettingsObjectRepositoryMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/settings/DataSetFilter.java, core/src/main/java/org/hisp/dhis/android/core/settings/HomeFilter.java, core/src/main/java/org/hisp/dhis/android/core/settings/ProgramFilter.java, core/src/sharedTest/resources/settings/appearance_settings.json
Solves [ANDROSDK-1461](https://jira.dhis2.org/browse/ANDROSDK-1461)
=> fix: [ANDROSDK-1461] Add default enum property to appearance filters

core/src/main/java/org/hisp/dhis/android/core/arch/handlers/internal/IdentifiableDataHandler.kt, core/src/main/java/org/hisp/dhis/android/core/arch/handlers/internal/IdentifiableDataHandlerImpl.kt, core/src/main/java/org/hisp/dhis/android/core/enrollment/internal/EnrollmentHandler.java, core/src/main/java/org/hisp/dhis/android/core/event/internal/EventDownloadCall.kt, core/src/main/java/org/hisp/dhis/android/core/relationship/internal/RelationshipDownloadAndPersistCallFactory.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceDownloadCall.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceDownloadInternalCall.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceHandler.java, core/src/test/java/org/hisp/dhis/android/core/enrollment/internal/EnrollmentHandlerShould.java, core/src/test/java/org/hisp/dhis/android/core/event/internal/EventHandlerShould.java, core/src/test/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceHandlerShould.java
Solves [ANDROSDK-1457](https://jira.dhis2.org/browse/ANDROSDK-1457).
=> fix: [androsdk-1457] Store tracker event relationships

core/src/main/java/org/hisp/dhis/android/core/arch/handlers/internal/IdentifiableDataHandlerImpl.kt, core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipItem.java, core/src/main/java/org/hisp/dhis/android/core/relationship/internal/RelationshipDHISVersionManager.java, core/src/test/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceHandlerShould.java
Solves [ANDROSDK-1463](https://jira.dhis2.org/browse/ANDROSDK-1463)
=> fix: [ANDROSDK-1463] Only persist owned relationships

core/src/main/java/org/hisp/dhis/android/core/arch/api/paging/internal/Paging.java, core/src/main/java/org/hisp/dhis/android/core/event/internal/EventDownloadCall.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceDownloadInternalCall.kt
Solves [ANDROSDK-1464](https://jira.dhis2.org/browse/ANDROSDK-1464).
=> feat: [androsdk-1464] Add hard limit to Event and TEI download calls

core/src/androidTest/java/org/hisp/dhis/android/core/common/internal/DataStatePropagatorIntegrationShould.kt, core/src/main/java/org/hisp/dhis/android/core/common/internal/DataStatePropagator.kt, core/src/main/java/org/hisp/dhis/android/core/common/internal/DataStatePropagatorImpl.kt, core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipObjectRepository.java, core/src/main/java/org/hisp/dhis/android/core/relationship/internal/RelationshipDHISVersionManager.java, core/src/main/java/org/hisp/dhis/android/core/relationship/internal/RelationshipImportHandler.kt, core/src/main/java/org/hisp/dhis/android/core/relationship/internal/RelationshipPostCall.kt, core/src/main/java/org/hisp/dhis/android/core/sms/data/localdbrepository/internal/LocalDbRepositoryImpl.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/OldTrackerImporterPayload.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/OldTrackerImporterPayloadGenerator.kt, core/src/test/java/org/hisp/dhis/android/core/relationship/internal/RelationshipDHISVersionManagerShould.java
Solves [ANDROSDK-1466](https://jira.dhis2.org/browse/ANDROSDK-1466)
=> fix: [ANDROSDK-1466] Persist all bidirectional relationships

core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryRepositoryScopeHelper.kt, core/src/test/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryRepositoryScopeHelperShould.kt
Solves [ANDROSDK-1462](https://jira.dhis2.org/browse/ANDROSDK-1462)
=> fix: [ANDROSDK-1462] Add followUp property in TEI filters

core/src/main/java/org/hisp/dhis/android/core/datavalue/internal/DataValueImportHandler.kt, core/src/main/java/org/hisp/dhis/android/core/datavalue/internal/conflicts/InvalidDataElementType37Conflict.kt, core/src/main/java/org/hisp/dhis/android/core/datavalue/internal/conflicts/InvalidDataElementTypeConflict.kt
Solves [ANDROSDK-1484](https://jira.dhis2.org/browse/ANDROSDK-1484)
=> fix: [ANDROSDK-1484] Adapt invalid value type message for 2.37 

build.gradle, core/build.gradle, gradle.properties
This PR updates gradle dependencies and improves build time.
=> feat: [gradle-dependencies-update] Update gradle dependencies

core/src/main/java/org/hisp/dhis/android/core/fileresource/internal/FileResourcePostCall.kt, core/src/main/java/org/hisp/dhis/android/core/fileresource/internal/FileResourceUtil.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/OldTrackerImporterFileResourcesPostCall.kt, core/src/main/java/org/hisp/dhis/android/core/tracker/importer/internal/TrackerImporterFileResourcesPostCall.kt
Solves [ANDROSDK-1485](https://jira.dhis2.org/browse/ANDROSDK-1485)
=> fix: [ANDROSDK-1485] Deal with missing file resources 

core/src/main/java/org/hisp/dhis/android/core/enrollment/internal/EnrollmentImportHandler.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceImportHandler.kt, core/src/test/java/org/hisp/dhis/android/core/enrollment/internal/EnrollmentImportHandlerShould.kt, core/src/test/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceImportHandlerShould.kt
Solves [ANDROSDK-1487](https://jira.dhis2.org/browse/ANDROSDK-1487)
=> fix: [ANDROSDK-1487] Handle deleted data in the server 

build.gradle, core/build.gradle, core/src/main/java/org/hisp/dhis/android/core/datavalue/internal/DataValueConflictParser.kt, core/src/main/java/org/hisp/dhis/android/core/datavalue/internal/conflicts/DataValueImportConflictItem.kt, core/src/main/java/org/hisp/dhis/android/core/datavalue/internal/conflicts/IndexedDataValueConflict.kt, core/src/main/java/org/hisp/dhis/android/core/datavalue/internal/conflicts/InvalidDataElementTypeConflict.kt, core/src/main/java/org/hisp/dhis/android/core/datavalue/internal/conflicts/LegacyDataValueImportConflictItem.kt, core/src/main/java/org/hisp/dhis/android/core/datavalue/internal/conflicts/PastExpiryDateConflict.kt, core/src/main/java/org/hisp/dhis/android/core/datavalue/internal/conflicts/PeriodAfterLatestOpenFutureConflict.kt, core/src/main/java/org/hisp/dhis/android/core/imports/internal/ImportConflict.java, core/src/sharedTest/resources/imports/import_conflict.json, core/src/test/java/org/hisp/dhis/android/core/datavalue/internal/conflicts/IndexedDataValueConflictShould.kt, core/src/test/java/org/hisp/dhis/android/core/imports/internal/ImportConflictShould.java, core/src/test/java/org/hisp/dhis/android/core/sms/mockrepos/testobjects/MockObjects.java, gradle.properties
Solves [ANDROSDK-1346](https://jira.dhis2.org/browse/ANDROSDK-1346).
Note: on top of https://github.com/dhis2/dhis2-android-sdk/pull/1691
=> feat: [androsdk-1346] Improve data value conflicts for 2.37v and later

.tx/config
Solves [ANDROSDK-1486](https://jira.dhis2.org/browse/ANDROSDK-1486).
=> feat: [androsdk-1486] Add transifex config

core/build.gradle, core/gradle.properties, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstancesEndpointCallFactory.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackerSyncLastUpdatedManager.kt, docs/content/developer/getting-started.md, docs/dhis2_android_sdk_developer_guide_INDEX.md
Solves [ANDROSDK-1495](https://jira.dhis2.org/browse/ANDROSDK-1495)
=> fix: [ANDROSDK-1495] Use lastUpdated in global download

core/src/androidTest/java/org/hisp/dhis/android/core/relationship/RelationshipCollectionRepositoryMockIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstancePostCallRealIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/relationship/internal/RelationshipManager.kt, core/src/main/java/org/hisp/dhis/android/core/relationship/internal/RelationshipOrphanCleanerImpl.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceImportHandler.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstancePostPayloadGenerator29.kt, core/src/sharedTest/resources/trackedentity/tracked_entity_instances.json
Solves [ANDROSDK-1490](https://jira.dhis2.org/browse/ANDROSDK-1490)
=> fix: [ANDROSDK-1490] Add RelationshipManager to control accessible relationships

core/src/androidTest/java/org/hisp/dhis/android/testapp/visualization/VisualizationCollectionRepositoryMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/arch/api/executors/internal/APIDownloader.kt, core/src/main/java/org/hisp/dhis/android/core/arch/api/executors/internal/APIDownloaderImpl.kt, core/src/main/java/org/hisp/dhis/android/core/arch/db/adapters/custom/internal/DbVisualizationLegendColumnAdapter.kt, core/src/main/java/org/hisp/dhis/android/core/visualization/VisualizationAPI36.kt, core/src/main/java/org/hisp/dhis/android/core/visualization/VisualizationCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/visualization/VisualizationLegend.java, core/src/main/java/org/hisp/dhis/android/core/visualization/internal/VisualizationCall.kt, core/src/main/java/org/hisp/dhis/android/core/visualization/internal/VisualizationFields.kt, core/src/main/java/org/hisp/dhis/android/core/visualization/internal/VisualizationService.kt, core/src/sharedTest/java/org/hisp/dhis/android/core/data/visualization/VisualizationSamples.kt, core/src/sharedTest/resources/visualization/visualization_api_36.json, core/src/test/java/org/hisp/dhis/android/core/visualization/VisualizationAPI36Should.kt
Solves [ANDROSDK-1497](https://jira.dhis2.org/browse/ANDROSDK-1497)
=> feat: [ANDROSDK-1497] Add Visualization model for < 2.37 

core/src/androidTest/java/org/hisp/dhis/android/testapp/user/AccountManagerMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/user/AccountManager.kt, core/src/main/java/org/hisp/dhis/android/core/user/internal/AccountManagerImpl.kt
Solves [ANDROSDK-1141](https://jira.dhis2.org/browse/ANDROSDK-1141)
=> feat: [ANDROSDK-1141] Implement DeleteAccount method in AccountManager

core/src/androidTest/java/org/hisp/dhis/android/core/MetadataCallRealIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/core/configuration/internal/DatabaseConfigurationMigrationIntegrationShould.kt, core/src/androidTest/java/org/hisp/dhis/android/core/utils/integration/mock/BaseMockIntegrationTest.java, core/src/main/java/org/hisp/dhis/android/core/D2Manager.kt, core/src/main/java/org/hisp/dhis/android/core/arch/db/access/DatabaseAdapter.java, core/src/main/java/org/hisp/dhis/android/core/arch/db/access/internal/DatabaseAdapterFactory.java, core/src/main/java/org/hisp/dhis/android/core/arch/db/access/internal/DatabaseImportExportImpl.kt, core/src/main/java/org/hisp/dhis/android/core/arch/db/access/internal/EncryptedDatabaseAdapter.java, core/src/main/java/org/hisp/dhis/android/core/arch/db/access/internal/EncryptedDatabaseOpenHelper.java, core/src/main/java/org/hisp/dhis/android/core/arch/db/access/internal/ParentDatabaseAdapter.java, core/src/main/java/org/hisp/dhis/android/core/arch/db/access/internal/UnencryptedDatabaseAdapter.java, core/src/main/java/org/hisp/dhis/android/core/arch/db/access/internal/UnencryptedDatabaseOpenHelper.java, core/src/main/java/org/hisp/dhis/android/core/arch/helpers/FileResourceDirectoryHelper.kt, core/src/main/java/org/hisp/dhis/android/core/configuration/internal/DatabaseConfigurationMigration.kt, core/src/main/java/org/hisp/dhis/android/core/configuration/internal/DatabaseNameGenerator.kt, core/src/main/java/org/hisp/dhis/android/core/configuration/internal/DatabasesConfiguration.java, core/src/main/java/org/hisp/dhis/android/core/configuration/internal/MultiUserDatabaseManager.kt, core/src/main/java/org/hisp/dhis/android/core/fileresource/internal/FileResourceModuleWiper.kt, core/src/main/java/org/hisp/dhis/android/core/user/internal/AccountManagerImpl.kt, core/src/sharedTest/resources/configuration/databases_configuration.json, core/src/test/java/org/hisp/dhis/android/core/arch/db/access/internal/UnencryptedDatabaseAdapterShould.java, core/src/test/java/org/hisp/dhis/android/core/configuration/internal/DatabasesConfigurationShould.kt, core/src/test/java/org/hisp/dhis/android/core/configuration/internal/MultiUserDatabaseManagerUnitShould.kt
Solves [ANDROSDK-1494](https://jira.dhis2.org/browse/ANDROSDK-1494)
=> feat: [ANDROSDK-1494] Create subfolder for file resources 

core/src/androidTest/java/org/hisp/dhis/android/core/configuration/internal/DatabaseConfigurationMigrationIntegrationShould.kt, core/src/main/java/org/hisp/dhis/android/core/configuration/internal/DatabaseConfigurationMigration.kt, core/src/main/java/org/hisp/dhis/android/core/configuration/internal/MultiUserDatabaseManager.kt
Fix a defect in the initialization of DatabaseConfiguration
=> fix: [MAX-ACCOUNTS-FIX] Fix initial account configuration

core/src/main/java/org/hisp/dhis/android/core/arch/db/adapters/custom/internal/NewTrackerImporterUserInfoColumnAdapter.kt, core/src/main/java/org/hisp/dhis/android/core/common/BaseIdentifiableObject.java, core/src/main/java/org/hisp/dhis/android/core/event/NewTrackerImporterEvent.java, core/src/main/java/org/hisp/dhis/android/core/event/NewTrackerImporterEventTransformer.kt, core/src/main/java/org/hisp/dhis/android/core/systeminfo/DHISPatchVersion.java, core/src/main/java/org/hisp/dhis/android/core/systeminfo/DHISVersion.java, core/src/main/java/org/hisp/dhis/android/core/systeminfo/DHISVersionManager.java, core/src/main/java/org/hisp/dhis/android/core/systeminfo/internal/DHISVersionManagerImpl.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/NewTrackerImporterUserInfo.java, core/src/main/java/org/hisp/dhis/android/core/tracker/TrackerPostParentCallHelper.kt, core/src/main/java/org/hisp/dhis/android/core/user/internal/UserCredentialsFields.java
Solves [ANDROSDK-1509](https://jira.dhis2.org/browse/ANDROSDK-1509)
=> feat: [ANDROSDK-1509] Adapt AssigendUser model in NTI 

core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceLocalQueryHelperMockIntegrationShould.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceLocalQueryHelper.kt
Solves [ANDROSDK-1506](https://jira.dhis2.org/browse/ANDROSDK-1506).
=> feat: [ANDROSDK-1506] Adapt TEI query not to return glass-protected TEIs 

core/src/androidTest/java/org/hisp/dhis/android/core/analytics/aggregated/internal/evaluator/BaseEvaluatorSamples.kt, core/src/androidTest/java/org/hisp/dhis/android/core/analytics/aggregated/internal/evaluator/IndicatorEvaluatorIntegrationShould.kt, core/src/androidTest/java/org/hisp/dhis/android/core/program/programindicatorengine/ProgramIndicatorSQLExecutorIntegrationShould.kt, core/src/main/java/org/hisp/dhis/android/core/parser/internal/expression/CommonExpressionVisitor.java, core/src/main/java/org/hisp/dhis/android/core/parser/internal/service/ExpressionService.java, core/src/main/java/org/hisp/dhis/android/core/program/programindicatorengine/internal/ProgramIndicatorEngineImpl.kt, core/src/main/java/org/hisp/dhis/android/core/program/programindicatorengine/internal/ProgramIndicatorExecutor.kt, core/src/main/java/org/hisp/dhis/android/core/program/programindicatorengine/internal/variable/ProgramVariableItem.kt, core/src/main/java/org/hisp/dhis/android/core/program/programindicatorengine/internal/variable/VProgramStageId.kt, core/src/main/java/org/hisp/dhis/android/core/program/programindicatorengine/internal/variable/VProgramStageName.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceDownloadInternalCall.kt, core/src/test/java/org/hisp/dhis/android/core/indicator/datasetindicatorengine/DataSetIndicatorEvaluatorShould.kt, core/src/test/java/org/hisp/dhis/android/core/parser/internal/expression/ExpressionServiceShould.java, core/src/test/java/org/hisp/dhis/android/core/program/programindicatorengine/internal/ProgramIndicatorExecutorShould.kt, docs/content/developer/analytics.md, docs/content/developer/program-indicator-engine.md
Partially solves [ANDROSDK-1376](https://jira.dhis2.org/browse/ANDROSDK-1376)
=> feat: [ANDROSDK-1376] Add programStageId and programStageName variables

core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceDownloadInternalCall.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackerQueryBundleInternalFactory.kt
Solves [ANDROSDK-1503](https://jira.dhis2.org/browse/ANDROSDK-1503).
=> fix: [ANDROSDK-1503] Add missing programStatus properity in TEI download 

core/src/main/java/org/hisp/dhis/android/core/tracker/importer/internal/JobReportEnrollmentHandler.kt, core/src/main/java/org/hisp/dhis/android/core/tracker/importer/internal/JobReportEventHandler.kt, core/src/main/java/org/hisp/dhis/android/core/tracker/importer/internal/JobReportRelationshipHandler.kt, core/src/main/java/org/hisp/dhis/android/core/tracker/importer/internal/JobReportTrackedEntityHandler.kt
Solves [ANDROSDK-1517](https://jira.dhis2.org/browse/ANDROSDK-1517).
=> fix: [ANDROSDK-1517] Handle non-existing events in the server when deleted

core/src/main/java/org/hisp/dhis/android/core/fileresource/internal/FileResourceUtil.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/NewTrackerImporterTrackedEntityPostStateManager.kt, core/src/main/java/org/hisp/dhis/android/core/tracker/importer/internal/JobQueryCall.kt
Solves [ANDROSDK-1521](https://jira.dhis2.org/browse/ANDROSDK-1521).
=> fix: [ANDROSDK-1521] Handle other errors in NTI report call 

core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceService.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstancesEndpointCallFactory.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryOnlineHelper.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryRepositoryScope.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryScopeOrderByItem.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryScopeOrderColumn.java
Solve [ANDROSDK-1527](https://jira.dhis2.org/browse/ANDROSDK-1527).
=> fix: [ANDROSDK-1527] Add explicit sortOrder property in TEI download 

core/src/main/java/org/hisp/dhis/android/core/arch/cleaners/internal/LinkCleaner.kt, core/src/main/java/org/hisp/dhis/android/core/arch/cleaners/internal/LinkCleanerImpl.kt, core/src/main/java/org/hisp/dhis/android/core/dataset/internal/DataSetEntityDIModule.java, core/src/main/java/org/hisp/dhis/android/core/organisationunit/internal/OrganisationUnitModuleDownloader.kt, core/src/main/java/org/hisp/dhis/android/core/program/internal/ProgramEntityDIModule.java
Solves [ANDROSDK-1528](https://jira.dhis2.org/browse/ANDROSDK-1528).
=> fix: [ANDROSDK-1528] Clean missing links after on-demand orgunit refresh 

core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryRepositoryScope.java
Solves a defect in [ANDROSDK-1527](https://jira.dhis2.org/browse/ANDROSDK-1527)
=> fix: [ANDROSDK-1527-DEF] Remove default orderBy created in TEI search

core/src/main/java/org/hisp/dhis/android/core/arch/handlers/internal/IdentifiableDataHandlerParams.kt, core/src/main/java/org/hisp/dhis/android/core/enrollment/internal/EnrollmentHandler.kt, core/src/main/java/org/hisp/dhis/android/core/enrollment/internal/EnrollmentPersistenceCallFactory.kt, core/src/main/java/org/hisp/dhis/android/core/event/internal/EventHandler.kt, core/src/main/java/org/hisp/dhis/android/core/event/internal/EventPersistenceCallFactory.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityAttributeValueStore.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityAttributeValueStoreImpl.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityEnrollmentOrphanCleaner.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityEnrollmentOrphanCleanerImpl.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceDownloadInternalCall.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceEntityDIModule.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceHandler.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstancePersistenceCallFactory.kt, core/src/main/java/org/hisp/dhis/android/core/tracker/importer/internal/TrackerImporterBreakTheGlassHelper.kt, core/src/sharedTest/resources/trackedentity/tracked_entity_instances.json, core/src/test/java/org/hisp/dhis/android/core/enrollment/internal/EnrollmentHandlerShould.kt, core/src/test/java/org/hisp/dhis/android/core/event/internal/EventHandlerShould.kt, core/src/test/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceHandlerShould.kt
Solves [ANDROSDK-1529](https://jira.dhis2.org/browse/ANDROSDK-1529).
=> fix: [ANDROSDK-1529] Do not remove protected enrollment in general sync 

core/src/main/java/org/hisp/dhis/android/core/common/ValueType.kt, core/src/main/java/org/hisp/dhis/android/core/sms/data/localdbrepository/internal/FileResourceCleaner.java
Solves [ANDROSDK-1530](https://jira.dhis2.org/browse/ANDROSDK-1530).
=> fix: [ANDROSDK-1530] Do not handle FILE_RESOURCE value type 

core/src/androidTest/java/org/hisp/dhis/android/testapp/trackedentity/search/TrackedEntityInstanceQueryCollectionRepositoryMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceLocalQueryHelper.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryDataFetcher.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryRepositoryScope.java
Solves [ANDROSDK-1533](https://jira.dhis2.org/browse/ANDROSDK-1533)
=> fix: [ANDROSDK-1533] Add ExcludeUids method in TEI search repository 

core/build.gradle, core/gradle.properties, docs/content/developer/analytics.md, docs/content/developer/compatibility.md, docs/content/developer/getting-started.md, docs/content/developer/program-rule-engine.md, docs/content/developer/settings.md, docs/content/developer/workflow.md, docs/dhis2_android_sdk_developer_guide_INDEX.md
Solves [ANDROSDK-1535](https://jira.dhis2.org/browse/ANDROSDK-1535).
=> feat: [ANDROSDK-1535] Update docs; update version to 1.6.0

core/src/androidTest/java/org/hisp/dhis/android/core/analytics/aggregated/internal/evaluator/AnalyticsRepositoryIntegrationShould.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/aggregated/internal/AnalyticsServiceDimensionHelper.kt
Solves a defect in [ANDROSDK-1543](https://jira.dhis2.org/browse/ANDROSDK-1543)
=> fix: [ANDROSDK-1543-DEFECT] Fix period order in analytics 

core/build.gradle, core/gradle.properties, core/src/main/java/org/hisp/dhis/android/core/D2Manager.kt, core/src/main/java/org/hisp/dhis/android/core/systeminfo/DHISPatchVersion.java, docs/content/developer/analytics.md, docs/content/developer/compatibility.md, docs/content/developer/getting-started.md, docs/content/developer/program-rule-engine.md, docs/content/developer/settings.md, docs/content/developer/workflow.md, docs/dhis2_android_sdk_developer_guide_INDEX.md
Solves [ANDROSDK-1554](https://jira.dhis2.org/browse/ANDROSDK-1554)
=> fix: [ANDROSDK-1554] Fix SMS version manager

core/src/main/java/org/hisp/dhis/android/core/trackedentity/AttributeValueFilter.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceFilterAPI37.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryRepositoryScopeHelper.kt
Solves [ANDROSDK-1558](https://jira.dhis2.org/browse/ANDROSDK-1558).
=> feat: [androsdk-1558] Adapt TrackedEntityInstanceQueryRepositoryScopeHelper to new TEIFilters properties.

core/src/main/java/org/hisp/dhis/android/core/period/internal/AbstractPeriodGenerator.java, core/src/test/java/org/hisp/dhis/android/core/period/internal/PeriodGeneratorShould.kt
Solves [ANDROSDK-1562](https://jira.dhis2.org/browse/ANDROSDK-1562)
=> fix: [ANDROSDK-1562] Make period generation methods synchronized 

core/src/androidTest/java/org/hisp/dhis/android/realservertests/generatedschema/tests/GeneratedSchemaUpdatesCheckerRealIntegrationShould.kt
Solves [ANDROSDK-1541](https://jira.dhis2.org/browse/ANDROSDK-1541).
=> fix: [androsdk-1541-2.38.1-update] Update test instance version to v2.38.1

core/src/androidTest/java/org/hisp/dhis/android/core/analytics/aggregated/internal/evaluator/AnalyticsRepositoryIntegrationShould.kt, core/src/androidTest/java/org/hisp/dhis/android/core/analytics/aggregated/internal/evaluator/DataElementSQLEvaluatorIntegrationShould.kt, core/src/androidTest/java/org/hisp/dhis/android/core/analytics/aggregated/internal/evaluator/EventDataItemSQLEvaluatorIntegrationShould.kt, core/src/androidTest/java/org/hisp/dhis/android/core/utils/integration/mock/BaseMockIntegrationTestFullDispatcher.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/AnalyticsException.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/aggregated/internal/evaluator/AnalyticsEvaluatorHelper.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/aggregated/internal/evaluator/DataElementSQLEvaluator.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/aggregated/internal/evaluator/EventDataItemSQLEvaluator.kt, core/src/main/java/org/hisp/dhis/android/core/arch/helpers/DateUtils.kt, core/src/main/java/org/hisp/dhis/android/core/program/programindicatorengine/internal/ProgramIndicatorSQLExecutor.kt, docs/content/developer/analytics.md
Solves [ANDROSDK-1570](https://jira.dhis2.org/browse/ANDROSDK-1570).
=> feat: [ANDROSDK-1570] Implement aggregation types

core/src/main/java/org/hisp/dhis/android/core/event/internal/EventQueryBundleInternalFactory.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackerQueryBundleInternalFactory.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackerQueryFactoryCommonHelper.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackerQueryInternalFactory.kt, core/src/test/java/org/hisp/dhis/android/core/event/internal/EventQueryBundleFactoryShould.kt
Solves [ANDROSDK-1559](https://jira.dhis2.org/browse/ANDROSDK-1559)
=> fix: [ANDROSDK-1559] Adapt limitByOrgunit parameter in event query 

core/src/androidTest/java/org/hisp/dhis/android/testapp/option/OptionServiceShould.kt, core/src/main/java/org/hisp/dhis/android/core/option/OptionModule.java, core/src/main/java/org/hisp/dhis/android/core/option/OptionService.kt, core/src/main/java/org/hisp/dhis/android/core/option/OptionServiceImpl.kt, core/src/main/java/org/hisp/dhis/android/core/option/internal/OptionModuleImpl.java
Added OptionService to handle search by displayName and options to hide or show
=> feat: OptionService

core/src/main/java/org/hisp/dhis/android/core/sms/data/smsrepository/internal/SmsReader.java, core/src/main/java/org/hisp/dhis/android/core/sms/data/smsrepository/internal/SmsRepositoryImpl.java, core/src/main/java/org/hisp/dhis/android/core/sms/domain/interactor/SmsSubmitCase.java, core/src/main/java/org/hisp/dhis/android/core/sms/domain/repository/SmsRepository.java, core/src/test/java/org/hisp/dhis/android/core/sms/SubmitTest.java, core/src/test/java/org/hisp/dhis/android/core/sms/mockrepos/MockSmsRepository.java, docs/content/developer/database.md, docs/content/developer/sms.md, docs/content/developer/workflow.md
Solves [ANDROSDK-1575](https://jira.dhis2.org/browse/ANDROSDK-1575).
=> feat: [ANDROSDK-1575] Add SMS methods to use external SMS app

core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/internal/ReadWriteWithUidCollectionRepositoryImpl.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/object/internal/ReadWriteWithUidDataObjectRepositoryImpl.java, core/src/main/java/org/hisp/dhis/android/core/common/internal/TrackerDataManager.kt, core/src/main/java/org/hisp/dhis/android/core/common/internal/TrackerDataManagerImpl.kt, core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentObjectRepository.java, core/src/main/java/org/hisp/dhis/android/core/event/EventCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/event/EventObjectRepository.java, core/src/main/java/org/hisp/dhis/android/core/note/NoteCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipObjectRepository.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceObjectRepository.java, core/src/test/java/org/hisp/dhis/android/core/common/internal/TrackerDataManagerShould.kt
Solves [ANDROSDK-1580](https://dhis2.atlassian.net/browse/ANDROSDK-1580)
=> fix: [ANDROSDK-1580] Create programOwner on new enrollment 

build.gradle, core/build.gradle, core/plugins/jacoco.gradle, docs/content/dev/coverage-report.md
Solves [ANDROSDK-9](https://dhis2.atlassian.net/browse/ANDROSDK-9)
=> feat: [ANDROSDK-9] Add code coverage reports

docs/content/developer/compatibility.md
Solves [ANDROSDK-1499](https://dhis2.atlassian.net/browse/ANDROSDK-1499)
=> doc: [ANDROSDK-1499] Add rule-engine compatibility

core/src/main/java/org/hisp/dhis/android/core/common/internal/TrackerDataManagerImpl.kt, core/src/main/java/org/hisp/dhis/android/core/tracker/importer/internal/TrackerImporterFileResourcesPostCall.kt, core/src/main/java/org/hisp/dhis/android/core/tracker/importer/internal/TrackerImporterPostCall.kt
Solves [ANDROSDK-1590](https://dhis2.atlassian.net/browse/ANDROSDK-1590).
=> fix: [ANDROSDK-1590] Handle program owners in NTI 

core/src/main/java/org/hisp/dhis/android/core/common/valuetype/validation/validators/NumberValidator.kt, core/src/test/java/org/hisp/dhis/android/core/common/valuetype/validation/validators/NumberValidatorShould.kt
Solves [ANDROSDK-1589](https://dhis2.atlassian.net/browse/ANDROSDK-1589)
=> fix: [ANDROSDK-1589] Do not accept decimal numbers starting with dots 

core/src/main/java/org/hisp/dhis/android/core/program/programindicatorengine/internal/ProgramIndicatorExecutor.kt, core/src/test/java/org/hisp/dhis/android/core/program/programindicatorengine/internal/ProgramIndicatorExecutorShould.kt
Solves [ANDROSDK-1594](https://dhis2.atlassian.net/browse/ANDROSDK-1594)
=> fix: [ANDROSDK-1594] ProgramIndicatorEngine: catch invalid expression 

core/src/main/java/org/hisp/dhis/android/core/programtheme/internal/ProgramThemeModuleWiper.kt, core/src/main/java/org/hisp/dhis/android/core/wipe/internal/D2ModuleWipers.java
Adds program theme module wiper.
=> feat: [ANDROSDK-1574] Adds program theme module wiper

.idea/gradle.xml, Jenkinsfile, build.gradle, core/build.gradle, core/plugins/gradle-mvn-push.gradle, core/src/androidTest/AndroidManifest.xml, core/src/androidTest/java/org/hisp/dhis/android/core/utils/DatabaseRemover.kt, core/src/androidTest/java/org/hisp/dhis/android/core/utils/runner/D2JunitRunner.kt, core/src/androidTest/java/org/hisp/dhis/android/core/utils/runner/D2JunitTestListener.kt, instrumented-test-app/build.gradle, instrumented-test-app/gradle.properties, instrumented-test-app/src/main/AndroidManifest.xml, instrumented-test-app/src/main/java/org/hisp/dhis/android/instrumentedTestApp/TestLabActivity.kt, instrumented-test-app/src/main/res/values/strings.xml, runChecks.sh, scripts/browserstackJenkins.sh, scripts/config_jenkins.init, settings.gradle
Prepare the project to run on Jenkins CI (DHIS2 hosted).
Importante changes:
- A new module called "instrumented-test-app" has been created. The purpose of this module is to create a dummy application that imports the SDK. This app is used to run the instrumentation tests in Browserstack.
=> feat: [JENKINS-SETUP] Add Jenkins configuration

core/src/main/java/org/hisp/dhis/android/core/program/programindicatorengine/internal/ProgramIndicatorEngineImpl.kt, core/src/main/java/org/hisp/dhis/android/core/program/programindicatorengine/internal/dataitem/ProgramItemAttribute.kt, core/src/main/java/org/hisp/dhis/android/core/program/programindicatorengine/internal/dataitem/ProgramItemStageElement.kt, core/src/main/java/org/hisp/dhis/android/core/program/programindicatorengine/internal/function/D2HasValue.kt, core/src/main/java/org/hisp/dhis/android/core/program/programindicatorengine/internal/variable/VValueCount.kt, core/src/main/java/org/hisp/dhis/android/core/program/programindicatorengine/internal/variable/VZeroPosValueCount.kt, core/src/test/java/org/hisp/dhis/android/core/program/programindicatorengine/internal/ProgramIndicatorExecutorShould.kt
Solves [ANDROSDK-1604](https://dhis2.atlassian.net/browse/ANDROSDK-1604)
=> fix: [DC-1604] Catch missing items in indicator engine

core/src/androidTest/java/org/hisp/dhis/android/testapp/dataset/DataSetCollectionRepositoryMockIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/testapp/dataset/DataSetModuleMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/arch/db/stores/internal/LinkStore.kt, core/src/main/java/org/hisp/dhis/android/core/arch/db/stores/internal/LinkStoreImpl.kt, core/src/main/java/org/hisp/dhis/android/core/arch/handlers/internal/LinkHandlerImpl.kt, core/src/sharedTest/resources/dataset/data_sets.json
Solves [ANDROSDK-1607](https://dhis2.atlassian.net/browse/ANDROSDK-1607)
=> fix: [ANDROSDK-1607] Ignore duplicated links 

core/build.gradle
Solves [ANDROSDK-1611](https://dhis2.atlassian.net/browse/ANDROSDK-1611)
=> fix: [ANDROSDK-1611] Update SQLCipher to version 4.4.3

core/src/androidTest/java/org/hisp/dhis/android/testapp/settings/AnalyticsDhisVisualizationsSettingObjectRepositoryMockIntegrationShould.kt, core/src/main/java/org/hisp/dhis/android/core/settings/AnalyticsDhisVisualizationsSettingObjectRepository.java
Solves [ANDROSDK-1566](https://dhis2.atlassian.net/browse/ANDROSDK-1566).
=> feat: [ANDROSDK-1613] Add methods to filter visualization settings by dataset and program

core/src/androidTest/java/org/hisp/dhis/android/testapp/usecase/stock/StockUseCaseCollectionRepositoryMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/object/internal/ReadOnlyWithTransformerObjectRepositoryImpl.kt
Solves [ANDROSDK-1596](https://dhis2.atlassian.net/browse/ANDROSDK-1596).
=> fix: [ANDROSDK-1596] Fix nullPointer on blockingExists method

core/src/androidTest/java/org/hisp/dhis/android/core/utils/integration/mock/BaseMockIntegrationTestFullDispatcher.kt, core/src/androidTest/java/org/hisp/dhis/android/testapp/datavalue/DataValueConflictCollectionRepositoryMockIntegrationShould.kt, core/src/main/java/org/hisp/dhis/android/core/datavalue/DataValueByDataSetQueryHelper.kt, core/src/main/java/org/hisp/dhis/android/core/datavalue/DataValueCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/datavalue/DataValueConflictCollectionRepository.java, core/src/main/java/org/hisp/dhis/android/core/datavalue/DataValueModule.java, core/src/main/java/org/hisp/dhis/android/core/datavalue/internal/DataValueConflictDIModule.kt, core/src/main/java/org/hisp/dhis/android/core/datavalue/internal/DataValueModuleImpl.java, core/src/main/java/org/hisp/dhis/android/core/datavalue/internal/DataValueStore.java, core/src/sharedTest/java/org/hisp/dhis/android/core/data/datavalue/DataValueConflictSamples.kt
Solves [ANDROSDK-1612](https://dhis2.atlassian.net/browse/ANDROSDK-1612).
=> feat: [ANDROSDK-1612] Add a data value conflict repository

core/src/androidTest/java/org/hisp/dhis/android/testapp/user/AccountManagerMockIntegrationShould.kt, core/src/main/java/org/hisp/dhis/android/core/configuration/internal/DatabasesConfiguration.java, core/src/main/java/org/hisp/dhis/android/core/configuration/internal/MultiUserDatabaseManager.kt, core/src/main/java/org/hisp/dhis/android/core/user/AccountManager.kt, core/src/main/java/org/hisp/dhis/android/core/user/internal/AccountManagerImpl.kt
Solves [ANDROSDK-1631](https://dhis2.atlassian.net/browse/ANDROSDK-1631)
[ANDROSDK-1631]: https://dhis2.atlassian.net/browse/ANDROSDK-1631?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: [ANDROSDK-1631] Make maxAccounts property nullable, meaning limitless

core/build.gradle, core/src/sharedTest/java/org/hisp/dhis/android/core/data/event/EventDataFilterSamples.kt, core/src/sharedTest/java/org/hisp/dhis/android/core/data/trackedentity/AttributeValueFilterSamples.kt
Solves [ANDROSDK-1632](https://dhis2.atlassian.net/browse/ANDROSDK-1632)
[ANDROSDK-1632]: https://dhis2.atlassian.net/browse/ANDROSDK-1632?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: [ANDROSDK-1632] Add coreLibraryDesugaring 

core/src/main/java/org/hisp/dhis/android/core/common/ValueType.kt
Solves [ANDROSDK-1636](https://dhis2.atlassian.net/browse/ANDROSDK-1636)
[ANDROSDK-1636]: https://dhis2.atlassian.net/browse/ANDROSDK-1636?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: [ANDROSDK-1636] Add MULTI_TEXT value type to model

core/src/androidTest/java/org/hisp/dhis/android/core/analytics/aggregated/internal/evaluator/IndicatorEvaluatorIntegrationBaseShould.kt, core/src/main/java/org/hisp/dhis/android/core/parser/internal/expression/ParserUtils.kt, core/src/main/java/org/hisp/dhis/android/core/parser/internal/expression/literal/NullLiteral.kt, core/src/main/java/org/hisp/dhis/android/core/parser/internal/expression/literal/RegenerateLiteral.kt, core/src/main/java/org/hisp/dhis/android/core/parser/internal/service/utils/ExpressionHelper.kt, core/src/test/java/org/hisp/dhis/android/core/parser/internal/expression/ExpressionServiceShould.kt, docs/content/developer/analytics.md
Solves [ANDROSDK-1629](https://dhis2.atlassian.net/browse/ANDROSDK-1629)
[ANDROSDK-1629]: https://dhis2.atlassian.net/browse/ANDROSDK-1629?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: [ANDROSDK-1629] Analytics: add NULL literal 

core/src/main/java/org/hisp/dhis/android/core/event/internal/EventPostParentCall.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstancePostParentCall.kt, core/src/main/java/org/hisp/dhis/android/core/tracker/TrackerPostParentCallHelper.kt, core/src/test/java/org/hisp/dhis/android/core/tracker/TrackerPostParentCallHelperShould.kt
Solves [ANDROSDK-1634](https://dhis2.atlassian.net/browse/ANDROSDK-1634)
[ANDROSDK-1634]: https://dhis2.atlassian.net/browse/ANDROSDK-1634?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: [ANDROSDK-1634] Use new tracker importer by default when version >= 2.40

core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceCallMockIntegrationShould.kt, core/src/main/java/org/hisp/dhis/android/core/tracker/exporter/TrackerDownloadCall.kt, core/src/sharedTest/resources/trackedentity/tracked_entity_instances_with_relationship.json
Solves [ANDROSDK-1645](https://dhis2.atlassian.net/browse/ANDROSDK-1645)
[ANDROSDK-1645]: https://dhis2.atlassian.net/browse/ANDROSDK-1645?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [ANDROSDK-1645] Wrap download call in a single transaction 

core/src/main/java/org/hisp/dhis/android/core/enrollment/internal/EnrollmentFields.kt, core/src/main/java/org/hisp/dhis/android/core/enrollment/internal/NewEnrollmentFields.kt, core/src/main/java/org/hisp/dhis/android/core/event/internal/EventFields.kt, core/src/main/java/org/hisp/dhis/android/core/event/internal/NewEventFields.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/NewTrackedEntityInstanceFields.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceFields.kt
Solves [ANDROSDK-1653](https://dhis2.atlassian.net/browse/ANDROSDK-1653)
[ANDROSDK-1653]: https://dhis2.atlassian.net/browse/ANDROSDK-1653?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [ANDROSDK-1653] Download createdAtClient and updatedAtClient properties

README.md, core/src/main/java/org/hisp/dhis/android/core/common/ValueTypeRenderingType.java
Solves [ANDROSDK-1654](https://dhis2.atlassian.net/browse/ANDROSDK-1654)
[ANDROSDK-1654]: https://dhis2.atlassian.net/browse/ANDROSDK-1654?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: [ANDROSDK-1654] Add Coverage and Lines budges to README file 

core/src/main/java/org/hisp/dhis/android/core/common/ValueTypeRenderingType.java
Solves [ANDROSDK-1640](https://dhis2.atlassian.net/browse/ANDROSDK-1640)
[ANDROSDK-1640]: https://dhis2.atlassian.net/browse/ANDROSDK-1640?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: [ANDROSDK-1640] Add CANVAS ValueTypeRenderingType

core/build.gradle.kts, docs/content/developer/compatibility.md, docs/content/developer/program-rule-engine.md
Solves [ANDROSDK-1450](https://dhis2.atlassian.net/browse/ANDROSDK-1450)
[ANDROSDK-1450]: https://dhis2.atlassian.net/browse/ANDROSDK-1450?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: [ANDROSDK-1450] Update dhis2-antlr-expression-parser; bump dependencies

core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/NewTrackedEntityEndpointCallFactory.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceLocalQueryHelper.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryCallFactory.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryOnline.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryOnlineHelper.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryRepositoryScopeHelper.kt, core/src/test/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryCallShould.kt, core/src/test/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryOnlineHelperShould.kt
Solves [ANDROSDK-1657](https://dhis2.atlassian.net/browse/ANDROSDK-1657)
[ANDROSDK-1657]: https://dhis2.atlassian.net/browse/ANDROSDK-1657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [ANDROSDK-1657] Support multiple filters in tracker search

core/build.gradle.kts
Solves [ANDROSDK-1660](ANDROSDK-1660).
[ANDROSDK-1660]: https://dhis2.atlassian.net/browse/ANDROSDK-1660?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [ANDROSDK-1660] Decrease jackson version to 2.13.4

core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/NewTrackedEntityEndpointCallFactory.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryCallFactory.kt, core/src/test/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryCallShould.kt
Solves [ANDROSDK-1661](https://dhis2.atlassian.net/browse/ANDROSDK-1661)
[ANDROSDK-1661]: https://dhis2.atlassian.net/browse/ANDROSDK-1661?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [ANDROSDK-1661] Create multiple queries for multiple orgunits in event search

core/src/main/java/org/hisp/dhis/android/core/systeminfo/DHISVersionManager.kt, core/src/main/java/org/hisp/dhis/android/core/systeminfo/internal/DHISVersionManagerImpl.kt, core/src/test/java/org/hisp/dhis/android/core/systeminfo/internal/DHISVersionManagerShould.kt
Solves [ANDROSDK-1662](https://dhis2.atlassian.net/browse/ANDROSDK-1662)
[ANDROSDK-1662]: https://dhis2.atlassian.net/browse/ANDROSDK-1662?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [ANDROSDK-1662] Add shortcut method to check version equality

core/src/main/java/org/hisp/dhis/android/core/arch/storage/internal/AndroidInsecureStore.java, core/src/main/java/org/hisp/dhis/android/core/arch/storage/internal/AndroidSecureStore.java, core/src/main/java/org/hisp/dhis/android/core/arch/storage/internal/ChunkedSecureStore.kt, core/src/main/java/org/hisp/dhis/android/core/arch/storage/internal/InMemorySecureStore.java, core/src/main/java/org/hisp/dhis/android/core/arch/storage/internal/InMemoryUnsecureStore.java, core/src/test/java/org/hisp/dhis/android/core/arch/storage/internal/ChunkedSecureStoreShould.kt
Solves [ANDROSDK-1377](https://dhis2.atlassian.net/browse/ANDROSDK-1377).
[ANDROSDK-1377]: https://dhis2.atlassian.net/browse/ANDROSDK-1377?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [ANDROSDK-1377] Delete Credentials as a fallback on key error 

core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityEnrollmentOrphanCleanerImpl.kt
Solves [ANDROSDK-1672](https://dhis2.atlassian.net/browse/ANDROSDK-1672)
[ANDROSDK-1672]: https://dhis2.atlassian.net/browse/ANDROSDK-1672?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [ANDROSDK-1672] Do not delete other enrollments when querying by program

core/src/androidTest/java/org/hisp/dhis/android/core/program/internal/ProgramEndpointCallMockIntegrationShould.kt, core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceCallBaseMockIntegrationShould.kt, core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceDownloadCallEnqueableMockIntegrationShould.kt, core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceDownloadCallMockIntegrationShould.kt, core/src/androidTest/java/org/hisp/dhis/android/testapp/organisationunit/OrganisationUnitCollectionRepositoryMockIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramCollectionRepositoryMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/arch/api/executors/internal/RxCoroutineWrapper.kt, core/src/main/java/org/hisp/dhis/android/core/event/internal/EventDownloadCall.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/NewTrackedEntityEndpointCallFactory.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceDownloadCall.kt, core/src/main/java/org/hisp/dhis/android/core/tracker/exporter/TrackerDownloadCall.kt, core/src/sharedTest/resources/organisationunit/organisation_units.json, core/src/sharedTest/resources/program/programs.json, core/src/sharedTest/resources/settings/synchronization_settings.json, core/src/test/java/org/hisp/dhis/android/core/settings/SynchronizationSettingsShould.java
Solves [ANDROSDK-1675](https://dhis2.atlassian.net/browse/ANDROSDK-1675)
[ANDROSDK-1675]: https://dhis2.atlassian.net/browse/ANDROSDK-1675?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [ANDROSDK-1675] Add custom rxSingle wrapper implementation

core/src/androidTest/java/org/hisp/dhis/android/core/program/programindicatorengine/ProgramIndicatorSQLExecutorIntegrationShould.kt, core/src/main/java/org/hisp/dhis/android/core/parser/internal/expression/ParserUtils.kt, core/src/main/java/org/hisp/dhis/android/core/parser/internal/expression/function/FunctionIf.kt, core/src/main/java/org/hisp/dhis/android/core/parser/internal/expression/function/FunctionIs.kt, core/src/test/java/org/hisp/dhis/android/core/parser/internal/expression/ExpressionServiceShould.kt
Solves [ANDROSDK-1686](https://dhis2.atlassian.net/browse/ANDROSDK-1686)
[ANDROSDK-1686]: https://dhis2.atlassian.net/browse/ANDROSDK-1686?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [ANDROSDK-1686] Implement 'is' function

core/src/main/java/org/hisp/dhis/android/core/map/MapModule.kt, core/src/main/java/org/hisp/dhis/android/core/map/internal/MapModuleImpl.kt, core/src/main/java/org/hisp/dhis/android/core/map/layer/MapLayerDownloader.kt, core/src/main/java/org/hisp/dhis/android/core/map/layer/internal/MapLayerDownloadParams.kt, core/src/main/java/org/hisp/dhis/android/core/map/layer/internal/MapLayerEntityDIModule.kt, core/src/main/java/org/hisp/dhis/android/core/map/layer/internal/bing/BingCallFactory.kt, core/src/main/java/org/hisp/dhis/android/core/map/layer/internal/bing/BingService.kt, core/src/main/java/org/hisp/dhis/android/core/settings/internal/SettingService.kt, core/src/main/java/org/hisp/dhis/android/core/settings/internal/SystemSettingCall.kt, core/src/main/java/org/hisp/dhis/android/core/settings/internal/SystemSettingsFields.kt
Solves [ANDROSDK-1690](https://dhis2.atlassian.net/browse/ANDROSDK-1690)
[ANDROSDK-1690]: https://dhis2.atlassian.net/browse/ANDROSDK-1690?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [ANDROSDK-1690] Add network timeout parameter to MapLayerDownloader

core/src/androidTest/java/org/hisp/dhis/android/core/analytics/aggregated/internal/evaluator/ExpressionDimensionItemEvaluatorIntegrationBaseShould.kt, core/src/androidTest/java/org/hisp/dhis/android/core/analytics/aggregated/internal/evaluator/IndicatorEvaluatorIntegrationBaseShould.kt, core/src/androidTest/java/org/hisp/dhis/android/core/indicator/internal/IndicatorUidsSeekerMockIntegrationShould.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/aggregated/internal/AnalyticsService.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/aggregated/internal/evaluator/indicatorengine/IndicatorSQLEngine.kt, core/src/main/java/org/hisp/dhis/android/core/parser/internal/service/ExpressionService.kt
Defect [ANDROSDK-1687](https://dhis2.atlassian.net/browse/ANDROSDK-1687)
[ANDROSDK-1687]: https://dhis2.atlassian.net/browse/ANDROSDK-1687?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [ANDROSDK-1687] Catch NaN evaluations in expressionService 

core/gradle.properties, core/src/main/assets/migrations/147.sql, core/src/main/java/org/hisp/dhis/android/core/arch/db/access/internal/BaseDatabaseOpenHelper.java, docs/content/developer/getting-started.md
Solves [ANDROSDK-1692](https://dhis2.atlassian.net/browse/ANDROSDK-1692)
[ANDROSDK-1692]: https://dhis2.atlassian.net/browse/ANDROSDK-1692?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [ANDROSDK-1692] Remove analytics settings with missing visualizations 

core/src/androidTest/java/org/hisp/dhis/android/core/data/database/ObjectStoreAbstractIntegrationShould.kt, core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/internal/BasePayloadGeneratorMockIntegration.kt, core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/internal/OldTrackerImporterPayloadGeneratorMockIntegrationShould.kt, core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityDataValueStoreIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/arch/db/querybuilders/internal/WhereClauseBuilder.java, core/src/main/java/org/hisp/dhis/android/core/event/internal/EventImportHandler.kt, core/src/main/java/org/hisp/dhis/android/core/program/internal/ProgramStageDataElementStore.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/OldTrackerImporterPayloadGenerator.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityDataValueStore.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityDataValueStoreImpl.java, core/src/main/java/org/hisp/dhis/android/core/tracker/importer/internal/JobReportEventHandler.kt, core/src/test/java/org/hisp/dhis/android/core/event/internal/EventImportHandlerShould.kt
Solves [ANDROSDK-1704](https://dhis2.atlassian.net/browse/ANDROSDK-1704)
[ANDROSDK-1704]: https://dhis2.atlassian.net/browse/ANDROSDK-1704?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [ANDROSDK-1706] Do not include unassigned programStageDataElements in POST call

core/src/main/java/org/hisp/dhis/android/core/relationship/internal/RelationshipOrphanCleanerImpl.java
Solves [ANDROSDK-1715](https://dhis2.atlassian.net/browse/ANDROSDK-1715).
[ANDROSDK-1715]: https://dhis2.atlassian.net/browse/ANDROSDK-1715?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [ANDROSDK-1715] Correct relationship orphan cleaner comparison bug

core/src/main/java/org/hisp/dhis/android/core/arch/d2/internal/D2DIComponent.kt, core/src/main/java/org/hisp/dhis/android/core/category/internal/CategoryInternalModule.kt, core/src/main/java/org/hisp/dhis/android/core/category/internal/CategoryModuleDownloader.kt, core/src/main/java/org/hisp/dhis/android/core/category/internal/CategoryPackageDIModule.kt, core/src/main/java/org/hisp/dhis/android/core/dataapproval/internal/DataApprovalPackageDIModule.kt, core/src/main/java/org/hisp/dhis/android/core/dataset/internal/DataSetModuleDownloader.kt, core/src/main/java/org/hisp/dhis/android/core/dataset/internal/DataSetPackageDIModule.kt, core/src/main/java/org/hisp/dhis/android/core/datavalue/internal/DataValuePackageDIModule.kt, core/src/main/java/org/hisp/dhis/android/core/domain/aggregated/data/internal/AggregatedDataCall.kt, core/src/main/java/org/hisp/dhis/android/core/event/internal/EventPackageDIModule.kt, core/src/main/java/org/hisp/dhis/android/core/legendset/internal/LegendPackageDIModule.kt, core/src/main/java/org/hisp/dhis/android/core/option/internal/OptionGroupCall.java, core/src/main/java/org/hisp/dhis/android/core/option/internal/OptionPackageDIModule.kt, core/src/main/java/org/hisp/dhis/android/core/organisationunit/internal/OrganisationUnitLevelEntityDIModule.kt, core/src/main/java/org/hisp/dhis/android/core/program/internal/ProgramCall.java, core/src/main/java/org/hisp/dhis/android/core/program/internal/ProgramIndicatorModuleDownloader.kt, core/src/main/java/org/hisp/dhis/android/core/program/internal/ProgramModuleDownloader.kt, core/src/main/java/org/hisp/dhis/android/core/program/internal/ProgramPackageDIModule.kt, core/src/main/java/org/hisp/dhis/android/core/programstageworkinglist/internal/ProgramStageWorkingListPackageDIModule.kt, core/src/main/java/org/hisp/dhis/android/core/relationship/internal/RelationshipPackageDIModule.kt, core/src/main/java/org/hisp/dhis/android/core/relationship/internal/RelationshipTypeCall.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityPackageDIModule.kt, core/src/main/java/org/hisp/dhis/android/core/validation/internal/ValidationPackageDIModule.kt, core/src/main/java/org/hisp/dhis/android/core/validation/internal/ValidationRuleCall.java, core/src/main/java/org/hisp/dhis/android/core/visualization/internal/VisualizationInternalModule.kt, core/src/main/java/org/hisp/dhis/android/core/visualization/internal/VisualizationModuleDownloader.kt, core/src/main/java/org/hisp/dhis/android/core/visualization/internal/VisualizationPackageDIModule.kt, core/src/test/java/org/hisp/dhis/android/core/program/internal/ProgramModuleDownloaderShould.kt
Solves [ANDROSDK-1702](https://dhis2.atlassian.net/browse/ANDROSDK-1702).
[ANDROSDK-1702]: https://dhis2.atlassian.net/browse/ANDROSDK-1702?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor: [ANDROSDK-1702] Injection of generic call classes removed

core/src/main/java/org/hisp/dhis/android/core/arch/db/adapters/enums/internal/D2ErrorCodeColumnAdapter.java, core/src/main/java/org/hisp/dhis/android/core/maintenance/D2Error.java
Solves [ANDROSDK-1719](https://dhis2.atlassian.net/browse/ANDROSDK-1719).
[ANDROSDK-1719]: https://dhis2.atlassian.net/browse/ANDROSDK-1719?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix: [ANDROSDK-1719] Adds D2Error default D2ErrorCode

core/src/androidTest/java/org/hisp/dhis/android/core/domain/metadata/MetadataCallMockIntegrationShould.kt, core/src/main/java/org/hisp/dhis/android/core/arch/call/internal/CompletableProvider.kt, core/src/main/java/org/hisp/dhis/android/core/arch/call/internal/DownloadProvider.kt, core/src/main/java/org/hisp/dhis/android/core/arch/modules/internal/UntypedSuspendModuleDownloader.kt, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/object/internal/ReadOnlyFirstObjectWithDownloadRepositoryImpl.kt, core/src/main/java/org/hisp/dhis/android/core/domain/aggregated/data/internal/AggregatedDataCall.kt, core/src/main/java/org/hisp/dhis/android/core/domain/metadata/MetadataCall.kt, core/src/main/java/org/hisp/dhis/android/core/domain/metadata/internal/MetadataModuleImpl.kt, core/src/main/java/org/hisp/dhis/android/core/systeminfo/internal/SystemInfoCall.kt, core/src/main/java/org/hisp/dhis/android/core/systeminfo/internal/SystemInfoModuleDownloader.kt, core/src/main/java/org/hisp/dhis/android/core/systeminfo/internal/SystemInfoService.kt, core/src/main/java/org/hisp/dhis/android/core/tracker/exporter/TrackerDownloadCall.kt, core/src/main/java/org/hisp/dhis/android/core/user/internal/LogInCall.kt, core/src/test/java/org/hisp/dhis/android/core/arch/api/executors/internal/CoroutineAPICallExecutorMock.kt, core/src/test/java/org/hisp/dhis/android/core/common/BaseCallShould.java, core/src/test/java/org/hisp/dhis/android/core/domain/metadata/MetadataCallShould.kt, core/src/test/java/org/hisp/dhis/android/core/systeminfo/internal/SystemInfoCallShould.kt, core/src/test/java/org/hisp/dhis/android/core/user/internal/LogInCallUnitShould.kt
Solves [ANDROSDK-1729](https://dhis2.atlassian.net/browse/ANDROSDK-1729)
=> refactor: [ANDROSDK-1729] Replace RxJava in SystemInfo call 

core/src/main/java/org/hisp/dhis/android/core/enrollment/internal/EnrollmentEndpointCallFactory.kt, core/src/main/java/org/hisp/dhis/android/core/enrollment/internal/EnrollmentService.kt, core/src/main/java/org/hisp/dhis/android/core/enrollment/internal/NewEnrollmentEndpointCallFactory.kt, core/src/main/java/org/hisp/dhis/android/core/enrollment/internal/OldEnrollmentEndpointCallFactory.kt, core/src/main/java/org/hisp/dhis/android/core/event/internal/EventEndpointCallFactory.kt, core/src/main/java/org/hisp/dhis/android/core/event/internal/EventService.kt, core/src/main/java/org/hisp/dhis/android/core/event/internal/NewEventEndpointCallFactory.kt, core/src/main/java/org/hisp/dhis/android/core/event/internal/OldEventEndpointCallFactory.kt, core/src/main/java/org/hisp/dhis/android/core/relationship/internal/RelationshipDownloadAndPersistCallFactory.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/NewTrackedEntityEndpointCallFactory.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/OldTrackedEntityEndpointCallFactory.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityEndpointCallFactory.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceService.kt, core/src/main/java/org/hisp/dhis/android/core/tracker/exporter/TrackerDownloadCall.kt, core/src/main/java/org/hisp/dhis/android/core/tracker/exporter/TrackerExporterService.kt, core/src/main/java/org/hisp/dhis/android/core/user/internal/UserInternalModule.kt
Solves [ANDROSDK-1730](https://dhis2.atlassian.net/browse/ANDROSDK-1730)
=> refactor: [ANDROSDK-1730] Refactor RelationshipCallFactory to coroutines 

core/src/main/java/org/hisp/dhis/android/core/arch/api/executors/internal/APICallExecutorImpl.java, core/src/main/java/org/hisp/dhis/android/core/arch/api/executors/internal/APIErrorMapper.kt
Complements (ANDROSDK-1719)[https://dhis2.atlassian.net/browse/ANDROSDK-1719]
=> fix: [ANDROSDK-1719-2] Apply default errorCode 

core/build.gradle.kts, core/src/androidTest/java/org/hisp/dhis/android/core/datavalue/internal/DataValueEndpointCallRealIntegrationShould.kt, core/src/androidTest/java/org/hisp/dhis/android/core/event/internal/EventCallFactory.kt, core/src/androidTest/java/org/hisp/dhis/android/core/event/internal/EventEndpointCallRealIntegrationShould.kt, core/src/androidTest/java/org/hisp/dhis/android/core/event/internal/EventPostCallRealIntegrationShould.kt, core/src/androidTest/java/org/hisp/dhis/android/core/user/internal/LogoutCallRealIntegrationShould.kt, core/src/androidTest/java/org/hisp/dhis/android/core/wipe/WipeDBCallRealIntegrationShould.kt, core/src/main/java/org/hisp/dhis/android/core/event/internal/EventDownloadCall.kt, core/src/main/java/org/hisp/dhis/android/core/event/internal/EventEndpointCallFactory.kt, core/src/main/java/org/hisp/dhis/android/core/event/internal/EventService.kt, core/src/main/java/org/hisp/dhis/android/core/event/internal/NewEventEndpointCallFactory.kt, core/src/main/java/org/hisp/dhis/android/core/event/internal/OldEventEndpointCallFactory.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/NewTrackedEntityEndpointCallFactory.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/OldTrackedEntityEndpointCallFactory.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityEndpointCallFactory.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceDownloadCall.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/TrackedEntityInstanceService.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryCallFactory.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryDataFetcher.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryOnlineHelper.kt, core/src/main/java/org/hisp/dhis/android/core/tracker/exporter/TrackerDownloadCall.kt, core/src/main/java/org/hisp/dhis/android/core/tracker/exporter/TrackerExporterService.kt, core/src/test/java/org/hisp/dhis/android/core/arch/api/executors/internal/CoroutineAPICallExecutorShould.kt, core/src/test/java/org/hisp/dhis/android/core/domain/metadata/MetadataCallShould.kt, core/src/test/java/org/hisp/dhis/android/core/event/internal/EventEndpointCallShould.kt, core/src/test/java/org/hisp/dhis/android/core/systeminfo/internal/SystemInfoCallShould.kt, core/src/test/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryCallShould.kt, core/src/test/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryDataSourceShould.kt
Solves [ANDROSDK-1731](https://dhis2.atlassian.net/browse/ANDROSDK-1731)
=> refactor: [ANDROSDK-1731] Refactor tracker calls to coroutines 

core/src/main/java/org/hisp/dhis/android/core/datavalue/internal/DataValueFileResourcePostCall.kt, core/src/main/java/org/hisp/dhis/android/core/fileresource/internal/FileResourcePostCall.kt, core/src/main/java/org/hisp/dhis/android/core/fileresource/internal/FileResourceService.kt, core/src/main/java/org/hisp/dhis/android/core/systeminfo/internal/PingCall.kt, core/src/main/java/org/hisp/dhis/android/core/systeminfo/internal/PingService.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/OldTrackerImporterFileResourcesPostCall.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/OldTrackerImporterPostCall.kt, core/src/main/java/org/hisp/dhis/android/core/tracker/importer/internal/TrackerImporterFileResourcesPostCall.kt, core/src/main/java/org/hisp/dhis/android/core/tracker/importer/internal/TrackerImporterPostCall.kt, core/src/test/java/org/hisp/dhis/android/core/tracker/importer/TrackerImporterFileResourcesPostCallShould.kt
Solves [ANDROSDK-1681](https://dhis2.atlassian.net/browse/ANDROSDK-1681)
=> refactor: [ANDROSDK-1681] Refactor fileResourceDownloadCall to coroutines 

core/src/main/java/org/hisp/dhis/android/core/arch/handlers/internal/HandlerBaseImpl.kt, core/src/main/java/org/hisp/dhis/android/core/map/layer/MapLayerDownloader.kt, core/src/main/java/org/hisp/dhis/android/core/map/layer/internal/MapLayerCallFactory.kt, core/src/main/java/org/hisp/dhis/android/core/map/layer/internal/bing/BingCallFactory.kt, core/src/main/java/org/hisp/dhis/android/core/map/layer/internal/osm/OSMCallFactory.kt
refactor:
- MapLayerDownloader and its dependencies to coroutines/fllow
=> refactor: [ANDROSDK-1713] Rxjava to coroutines in map call

core/src/main/java/org/hisp/dhis/android/core/arch/api/authentication/internal/OpenIDConnectAuthenticator.kt, core/src/main/java/org/hisp/dhis/android/core/arch/api/authentication/internal/PasswordAndCookieAuthenticator.kt, core/src/main/java/org/hisp/dhis/android/core/arch/api/authentication/internal/UserIdAuthenticatorHelper.kt, core/src/main/java/org/hisp/dhis/android/core/arch/helpers/UserHelper.kt, core/src/main/java/org/hisp/dhis/android/core/arch/storage/internal/Credentials.kt, core/src/main/java/org/hisp/dhis/android/core/user/internal/LogInCall.kt, core/src/main/java/org/hisp/dhis/android/core/user/internal/UserService.java, core/src/test/java/org/hisp/dhis/android/core/arch/helpers/UserHelperShould.kt
Solves [ANDROSDK-1739](https://dhis2.atlassian.net/browse/ANDROSDK-1739)
[ANDROSDK-1739]: https://dhis2.atlassian.net/browse/ANDROSDK-1739?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [ANDROSDK-1739] Replace authentication encoding to support special characters

core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/OldTrackerImporterPostCall.kt, core/src/main/java/org/hisp/dhis/android/core/tracker/importer/internal/TrackerImporterPostCall.kt, core/src/main/java/org/hisp/dhis/android/core/tracker/importer/internal/TrackerImporterProgramOwnerPostCall.kt
Solves [ANDROSDK-1694](https://dhis2.atlassian.net/browse/ANDROSDK-1694)
[ANDROSDK-1694]: https://dhis2.atlassian.net/browse/ANDROSDK-1694?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [ANDROSDK-1694] Remove initial programOwner post call

core/src/androidTest/java/org/hisp/dhis/android/testapp/trackedentity/search/TrackedEntitySearchCollectionRepositoryMockIntegrationShould.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntitySearchCollectionRepository.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntitySearchDataFetcher.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntitySearchDataFetcherHelper.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntitySearchDataSourceResult.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntitySearchItemAttribute.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntitySearchItemHelper.kt
Partially solves [ANDROSDK-1743](https://dhis2.atlassian.net/browse/ANDROSDK-1743)
[ANDROSDK-1743]: https://dhis2.atlassian.net/browse/ANDROSDK-1743?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: [ANDROSDK-1743-2] Add attributes and TEType to TrackedEntitySearchItem

core/src/main/java/org/hisp/dhis/android/core/arch/api/fields/internal/FieldsConverter.java, core/src/test/java/org/hisp/dhis/android/core/arch/api/fields/internal/FieldsConverterShould.java
Solves [ANDROSDK-1765](https://dhis2.atlassian.net/browse/ANDROSDK-1765)
[ANDROSDK-1765]: https://dhis2.atlassian.net/browse/ANDROSDK-1765?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [ANDROSDK-1765] Fix nestedField string generation

core/src/androidTest/java/org/hisp/dhis/android/core/MetadataCallRealIntegrationShould.kt, core/src/main/java/org/hisp/dhis/android/core/user/internal/IsUserLoggedInCallableFactory.kt, core/src/test/java/org/hisp/dhis/android/core/user/internal/IsUserLoggedInCallableShould.kt
Solves [ANDROSDK-1767](https://dhis2.atlassian.net/browse/ANDROSDK-1767)
[ANDROSDK-1767]: https://dhis2.atlassian.net/browse/ANDROSDK-1767?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [ANDROSDK-1767] Reinforce isLogged method

core/src/main/java/org/hisp/dhis/android/core/systeminfo/DHISVersion.kt, core/src/test/java/org/hisp/dhis/android/core/systeminfo/internal/DHISVersionShould.kt, core/src/test/java/org/hisp/dhis/android/core/systeminfo/internal/SystemInfoCallShould.kt
fix:
- Grant unsupported versions are not used feature:
feature:
- Handle unsupported versions smoothly
=> feat: [ANDROSDK-1741] Handle unsupported DHIS versions 

core/build.gradle.kts
build:
- Upgrade to Android API 34
=> build: [ANDROSDK-1771] Android API 34

core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetInstanceService.kt, core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetModule.kt, core/src/main/java/org/hisp/dhis/android/core/dataset/internal/DataSetInstanceServiceImpl.kt, core/src/main/java/org/hisp/dhis/android/core/dataset/internal/DataSetModuleImpl.kt
Expose DataSetInstanceService ([ANDROSDK-1778](https://dhis2.atlassian.net/browse/ANDROSDK-1778))
[ANDROSDK-1778]: https://dhis2.atlassian.net/browse/ANDROSDK-1778?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [ANDROSDK-1778] Expose DataSetInstanceService

core/src/main/java/org/hisp/dhis/android/core/arch/api/internal/ServicesDIModule.kt
Defect on [ANDROSDK-1699](https://dhis2.atlassian.net/browse/ANDROSDK-1699)
[ANDROSDK-1699]: https://dhis2.atlassian.net/browse/ANDROSDK-1699?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [ANDROSDK-1699-DEFECT] Remove duplicated ApiService in ServicesDI

core/src/androidTest/java/org/hisp/dhis/android/core/data/server/RealServerMother.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/NewTrackedEntityEndpointCallFactory.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/internal/OldTrackedEntityEndpointCallFactory.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryCallFactory.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryOnline.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryOnlineHelper.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryScopeOrderApiName.kt, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryScopeOrderByItem.java, core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryScopeOrderColumn.java, core/src/test/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryCallShould.kt
Solves [ANDROSDK-1733](https://dhis2.atlassian.net/browse/ANDROSDK-1733)
[ANDROSDK-1733]: https://dhis2.atlassian.net/browse/ANDROSDK-1733?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [ANDROSDK-1733] Fix orderBy clauses depending on endpoint version

core/src/androidTest/java/org/hisp/dhis/android/testapp/attribute/AttributeCollectionRespositoryMockIntegrationShould.kt, core/src/main/java/org/hisp/dhis/android/core/D2.kt, core/src/main/java/org/hisp/dhis/android/core/arch/d2/internal/D2Modules.kt, core/src/main/java/org/hisp/dhis/android/core/attribute/AttributeCollectionRepository.kt, core/src/main/java/org/hisp/dhis/android/core/attribute/AttributeModule.kt, core/src/main/java/org/hisp/dhis/android/core/attribute/AttributeModuleImpl.kt, core/src/sharedTest/resources/dataelement/data_elements.json, core/src/sharedTest/resources/program/program_stages.json, core/src/sharedTest/resources/program/programs.json, docs/content/developer/modules-and-repositories.md
feature:
- Expose Attributes (which are being saved but are not exposed)
=> feature: [ANDROSDK-1776] Expose attributes as repository

core/src/androidTest/java/org/hisp/dhis/android/testapp/dataset/DataSetInstanceServiceMockIntegrationShould.kt, core/src/main/java/org/hisp/dhis/android/core/dataset/internal/DataSetInstanceServiceImpl.kt, core/src/test/java/org/hisp/dhis/android/core/dataset/DataSetInstanceServiceShould.kt
Solves a bug in the evaluation of isExpired and isClosed conditions.
=> defect: [ANDROSDK-1787-2] DataSetInstanceService: fix isExpired and isClosed logic

core/src/main/java/org/hisp/dhis/android/core/common/valuetype/validation/validators/DateTimeValidator.kt, core/src/main/java/org/hisp/dhis/android/core/common/valuetype/validation/validators/DateValidator.kt, core/src/main/java/org/hisp/dhis/android/core/common/valuetype/validation/validators/TimeValidator.kt, core/src/test/java/org/hisp/dhis/android/core/common/valuetype/validation/validators/DateTimeValidatorShould.kt, core/src/test/java/org/hisp/dhis/android/core/common/valuetype/validation/validators/DateValidatorShould.kt, core/src/test/java/org/hisp/dhis/android/core/common/valuetype/validation/validators/TimeValidatorShould.kt
refactor:
- Date, Time and Datetime validators change to match new capture-app requirements
=> refactor: [ANDROSDK-1777] Date, Time and Datetime validators

build.gradle.kts, core/build.gradle.kts, gradle.properties, gradle/libs.versions.toml, instrumented-test-app/build.gradle.kts
Solves [ANDROSDK-1793](https://dhis2.atlassian.net/browse/ANDROSDK-1793)
[ANDROSDK-1793]: https://dhis2.atlassian.net/browse/ANDROSDK-1793?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ANDROSDK-1793] Bump versions (kotlin, gradle, dokka, desugaring)

core/src/androidTest/java/org/hisp/dhis/android/core/program/internal/ProgramEndpointCallMockIntegrationShould.kt
Solves [ANDROSDK-1783](https://dhis2.atlassian.net/browse/ANDROSDK-1783)
[ANDROSDK-1783]: https://dhis2.atlassian.net/browse/ANDROSDK-1783?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [ANDROSDK-1783] Fix integration test

docs/content/developer/workflow.md
Solves [ANDROSDK-1791](https://dhis2.atlassian.net/browse/ANDROSDK-1791)
[ANDROSDK-1791]: https://dhis2.atlassian.net/browse/ANDROSDK-1791?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> doc: [ANDROSDK-1791] Fix trackedEntity search documentation

core/src/main/java/org/hisp/dhis/android/core/program/internal/ProgramFields.kt, core/src/main/java/org/hisp/dhis/android/core/program/internal/ProgramStageFields.kt
Adds missing fields in the API request.
=> fix: [ANDROSDK-1806-DEFECT] Add missing API fields

core/src/androidTest/java/org/hisp/dhis/android/core/settings/SettingsModuleMockIntegrationShould.java, core/src/main/assets/migrations/159.sql, core/src/main/java/org/hisp/dhis/android/core/map/layer/internal/bing/BingBasemaps.kt, core/src/main/java/org/hisp/dhis/android/core/map/layer/internal/osm/OSMBaseMaps.kt, core/src/main/java/org/hisp/dhis/android/core/settings/SystemSetting.java, core/src/main/java/org/hisp/dhis/android/core/settings/SystemSettingCollectionRepository.kt, core/src/main/java/org/hisp/dhis/android/core/settings/SystemSettings.kt, core/src/main/java/org/hisp/dhis/android/core/settings/internal/SystemSettingsFields.kt, core/src/main/java/org/hisp/dhis/android/core/settings/internal/SystemSettingsSplitter.kt, core/src/sharedTest/resources/settings/system_settings.json, core/src/test/java/org/hisp/dhis/android/core/settings/SystemSettingsShould.kt, core/src/test/java/org/hisp/dhis/android/core/settings/internal/SystemSettingSplitterShould.kt
Solves [ANDROSDK-1803](https://dhis2.atlassian.net/browse/ANDROSDK-1803).
[ANDROSDK-1803]: https://dhis2.atlassian.net/browse/ANDROSDK-1803?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: [ANDROSDK-1803] Support for default base map key in System Settings

core/src/androidTest/java/org/hisp/dhis/android/core/analytics/aggregated/internal/evaluator/BaseEvaluatorIntegrationShould.kt, core/src/androidTest/java/org/hisp/dhis/android/core/analytics/aggregated/internal/evaluator/BaseEvaluatorSamples.kt, core/src/androidTest/java/org/hisp/dhis/android/core/analytics/trackerlinelist/TrackerLineListRepositoryEvaluatorShould.kt, core/src/main/java/org/hisp/dhis/android/core/parser/internal/expression/ParserUtils.kt, core/src/main/java/org/hisp/dhis/android/core/parser/internal/expression/function/FunctionContains.kt, core/src/main/java/org/hisp/dhis/android/core/parser/internal/expression/function/FunctionContainsItems.kt, core/src/test/java/org/hisp/dhis/android/core/parser/internal/expression/ExpressionServiceShould.kt, gradle/libs.versions.toml, gradle/wrapper/gradle-wrapper.properties
Solves [ANDROSDK-1801](https://dhis2.atlassian.net/browse/ANDROSDK-1801).
Implement "contains" and "containsItems" functions for the analytics engine.
[ANDROSDK-1801]: https://dhis2.atlassian.net/browse/ANDROSDK-1801?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: [ANDROSDK-1801] Add FunctionContains and FunctionContainsItems

core/src/androidTest/java/org/hisp/dhis/android/testapp/settings/AnalyticsDhisVisualizationsSettingObjectRepositoryMockIntegrationShould.kt, core/src/main/java/org/hisp/dhis/android/core/mockwebserver/Dhis2MockServer.java, core/src/main/java/org/hisp/dhis/android/core/settings/internal/AnalyticsDhisVisualizationCleaner.kt, core/src/main/java/org/hisp/dhis/android/core/visualization/internal/TrackerVisualizationHandler.kt, core/src/main/java/org/hisp/dhis/android/core/visualization/internal/VisualizationHandler.kt, core/src/sharedTest/resources/settings/analytics_settings_v2.json, core/src/sharedTest/resources/settings/analytics_settings_v3.json, core/src/test/java/org/hisp/dhis/android/core/settings/AnalyticsSettingAsserts.kt, core/src/test/java/org/hisp/dhis/android/core/visualization/internal/TrackerVisualizationHandlerShould.kt, core/src/test/java/org/hisp/dhis/android/core/visualization/internal/VisualizationHandlerShould.kt
Solves [ANDROSDK-1814](https://dhis2.atlassian.net/browse/ANDROSDK-1814)
[ANDROSDK-1814]: https://dhis2.atlassian.net/browse/ANDROSDK-1814?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [ANDROSDK-1814] Delete AnalytisDhisVisualization whose visualization is not downloaded

core/src/main/java/org/hisp/dhis/android/core/analytics/trackerlinelist/internal/TrackerLineListParams.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/trackerlinelist/internal/TrackerLineListRepositoryImpl.kt, core/src/main/java/org/hisp/dhis/android/core/util/CollectionExtensions.kt, core/src/test/java/org/hisp/dhis/android/core/analytics/trackerlinelist/TrackerLineListRepositoryShould.kt, core/src/test/java/org/hisp/dhis/android/core/analytics/trackerlinelist/internal/TrackerLineListParamsShould.kt
Solves [ANDROSDK-1828](https://dhis2.atlassian.net/browse/ANDROSDK-1828)
[ANDROSDK-1828]: https://dhis2.atlassian.net/browse/ANDROSDK-1828?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [ANDROSDK-1828] TrackerLineList: keep columns order

core/src/androidTest/java/org/hisp/dhis/android/core/analytics/trackerlinelist/TrackerLineListRepositoryEvaluatorShould.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/internal/AnalyticsModelHelper.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/trackerlinelist/TrackerLineListModel.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/trackerlinelist/TrackerLineListRepository.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/trackerlinelist/internal/TrackerLineListParams.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/trackerlinelist/internal/TrackerLineListRepositoryImpl.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/trackerlinelist/internal/TrackerLineListService.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/trackerlinelist/internal/TrackerLineListServiceMetadataHelper.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/trackerlinelist/internal/TrackerVisualizationMapper.kt, core/src/test/java/org/hisp/dhis/android/core/analytics/trackerlinelist/TrackerLineListRepositoryShould.kt, core/src/test/java/org/hisp/dhis/android/core/analytics/trackerlinelist/internal/TrackerLineListParamsShould.kt
Solves [ANDROSDK-1831](https://dhis2.atlassian.net/browse/ANDROSDK-1831)
[ANDROSDK-1831]: https://dhis2.atlassian.net/browse/ANDROSDK-1831?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [ANDROSDK-1831] TrackerLineList: make dataElement config more robust

core/src/androidTest/java/org/hisp/dhis/android/testapp/user/AccountManagerMockIntegrationShould.kt, core/src/main/java/org/hisp/dhis/android/core/user/AccountManager.kt, core/src/main/java/org/hisp/dhis/android/core/user/internal/AccountManagerImpl.kt
Solves [ANDROSDK-1833](https://dhis2.atlassian.net/browse/ANDROSDK-1833)
[ANDROSDK-1833]: https://dhis2.atlassian.net/browse/ANDROSDK-1833?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: [ANDROSDK-1833] Add method to retrieve current account

core/src/androidTest/java/org/hisp/dhis/android/core/analytics/trackerlinelist/TrackerLineListRepositoryEvaluatorShould.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/trackerlinelist/internal/TrackerLineListParams.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/trackerlinelist/internal/TrackerLineListRepositoryImpl.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/trackerlinelist/internal/TrackerLineListService.kt, core/src/main/java/org/hisp/dhis/android/core/arch/repositories/paging/PageConfig.kt
Solves [ANDROSDK-1829](https://dhis2.atlassian.net/browse/ANDROSDK-1829)
[ANDROSDK-1829]: https://dhis2.atlassian.net/browse/ANDROSDK-1829?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: [ANDROSDK-1829] Add paging to TrackerLineList repository

core/src/main/java/org/hisp/dhis/android/core/map/layer/internal/externalmap/ExternalMapLayerCallFactory.kt, core/src/sharedTest/resources/map/layer/externalmap/external_map_layers.json
Solves [ANDROSDK-1836](https://dhis2.atlassian.net/browse/ANDROSDK-1836)
[ANDROSDK-1836]: https://dhis2.atlassian.net/browse/ANDROSDK-1836?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [ANDROSDK-1836] Do not add ImageryProvider if no attribution

core/src/androidTest/java/org/hisp/dhis/android/core/analytics/trackerlinelist/TrackerLineListRepositoryEvaluatorShould.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/trackerlinelist/TrackerLineListModel.kt, core/src/main/java/org/hisp/dhis/android/core/analytics/trackerlinelist/internal/evaluator/NotSupportedEvaluator.kt
Solves [ANDROSDK-1837](https://dhis2.atlassian.net/browse/ANDROSDK-1837)
[ANDROSDK-1837]: https://dhis2.atlassian.net/browse/ANDROSDK-1837?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [ANDROSDK-1837] TrackerLineList fails to evaluate filtered lastUpdated

core/src/main/java/org/hisp/dhis/android/core/systeminfo/Ping.kt, core/src/main/java/org/hisp/dhis/android/core/systeminfo/SystemInfoModule.kt, core/src/main/java/org/hisp/dhis/android/core/systeminfo/internal/PingCall.kt, core/src/main/java/org/hisp/dhis/android/core/systeminfo/internal/PingImpl.kt, core/src/main/java/org/hisp/dhis/android/core/systeminfo/internal/PingService.kt, core/src/main/java/org/hisp/dhis/android/core/systeminfo/internal/SystemInfoModuleImpl.kt, core/src/test/java/org/hisp/dhis/android/core/systeminfo/internal/PingImplShould.kt, gradle/libs.versions.toml
Solves [ANDROSDK-1839](https://dhis2.atlassian.net/browse/ANDROSDK-1839).
[ANDROSDK-1839]: https://dhis2.atlassian.net/browse/ANDROSDK-1839?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: [ANDROSDK-1839] Create a service to ping the server

core/src/main/java/org/hisp/dhis/android/core/arch/api/internal/ParametersBuilder.kt, core/src/main/java/org/hisp/dhis/android/core/arch/api/internal/ServicesDIModule.kt, core/src/main/java/org/hisp/dhis/android/core/attribute/internal/AttributeService.kt, core/src/main/java/org/hisp/dhis/android/core/category/internal/CategoryComboService.kt, core/src/main/java/org/hisp/dhis/android/core/category/internal/CategoryOptionService.kt, core/src/main/java/org/hisp/dhis/android/core/category/internal/CategoryService.kt, core/src/main/java/org/hisp/dhis/android/core/dataapproval/internal/DataApprovalService.kt, core/src/main/java/org/hisp/dhis/android/core/dataelement/internal/DataElementService.kt, core/src/main/java/org/hisp/dhis/android/core/dataset/internal/DataSetService.kt, core/src/main/java/org/hisp/dhis/android/core/enrollment/internal/EnrollmentService.kt, core/src/main/java/org/hisp/dhis/android/core/event/internal/EventFilterService.kt, core/src/main/java/org/hisp/dhis/android/core/icon/internal/IconService.kt
Related task: [ANDROSDK-1884](https://dhis2.atlassian.net/jira/software/c/projects/ANDROSDK/boards/93?selectedIssue=ANDROSDK-1884)
[ANDROSDK-1884]: https://dhis2.atlassian.net/browse/ANDROSDK-1884?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: [ANDROSDK-1884] migrate services to Ktor

core/src/androidTest/java/org/hisp/dhis/android/core/dataset/internal/DataSetInstanceStoreIntegrationShould.kt, core/src/androidTest/java/org/hisp/dhis/android/testapp/dataset/DataSetCollectionRepositoryMockIntegrationShould.java, core/src/androidTest/java/org/hisp/dhis/android/testapp/dataset/DataSetInstanceCollectionRepositoryMockIntegrationShould.kt, core/src/androidTest/java/org/hisp/dhis/android/testapp/datavalue/DataValueCollectionRepositoryMockIntegrationShould.kt, core/src/main/java/org/hisp/dhis/android/core/dataset/internal/DataSetInstanceSQLStatementBuilder.kt, core/src/main/java/org/hisp/dhis/android/core/datavalue/DataValueByDataSetQueryHelper.kt, core/src/main/java/org/hisp/dhis/android/core/datavalue/DataValueCollectionRepository.kt, core/src/sharedTest/resources/datavalue/data_values.json, core/src/sharedTest/resources/datavalue/data_values_weekly.json, core/src/sharedTest/resources/organisationunit/organisation_units.json
Solves [ANDROSDK-1882](https://dhis2.atlassian.net/browse/ANDROSDK-1882)
[ANDROSDK-1882]: https://dhis2.atlassian.net/browse/ANDROSDK-1882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [ANDROSDK-1882] Filter assigned dataset orgunits in dataSetInstances 

core/src/main/java/org/hisp/dhis/android/core/analytics/trackerlinelist/internal/TrackerVisualizationMapper.kt, core/src/test/java/org/hisp/dhis/android/core/analytics/trackerlinelist/internal/TrackerVisualizationMapperShould.kt
fixes [this task](https://dhis2.atlassian.net/jira/software/c/projects/ANDROSDK/boards/93?selectedIssue=ANDROSDK-1898)
=> fix: [ANDROSDK-1898] Filter by Category not working in TrackerVisualization

Jenkinsfile
Related [task](https://dhis2.atlassian.net/jira/software/c/projects/ANDROSDK/boards/93?selectedIssue=ANDROSDK-1895)
=> chore: [ANDROSDK-1895] Set a timeout in sonarqube script to retry the step

core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntitySearchItemHelper.kt
fixes [this task](https://dhis2.atlassian.net/jira/software/c/projects/ANDROSDK/boards/93?selectedIssue=ANDROSDK-1889)
=> fix: [ANDROSDK-1889] fix isOnline evaluation

core/src/androidTest/java/org/hisp/dhis/android/core/period/PeriodMockIntegrationShould.java, core/src/main/java/org/hisp/dhis/android/core/arch/helpers/DateUtils.kt, core/src/main/java/org/hisp/dhis/android/core/parser/internal/service/dataitem/ItemYearlyPeriodCount.kt, core/src/main/java/org/hisp/dhis/android/core/period/PeriodType.kt, core/src/main/java/org/hisp/dhis/android/core/period/generator/internal/NMonthlyPeriodGenerator.kt, core/src/main/java/org/hisp/dhis/android/core/period/generator/internal/NMonthlyPeriodGeneratorFactory.kt, core/src/main/java/org/hisp/dhis/android/core/period/generator/internal/NMonthlyPeriodGenerators.kt, core/src/main/java/org/hisp/dhis/android/core/period/internal/ParentPeriodGeneratorImpl.kt, core/src/test/java/org/hisp/dhis/android/core/period/generator/internal/QuarterlyNovPeriodGeneratorShould.kt, core/src/test/java/org/hisp/dhis/android/core/period/generator/internal/QuarterlyPeriodGeneratorShould.kt
Solves [ANDROSDK-1899](https://dhis2.atlassian.net/browse/ANDROSDK-1899).
[ANDROSDK-1899]: https://dhis2.atlassian.net/browse/ANDROSDK-1899?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: [ANDROSDK-1899] Support for QuarterlyNov PeriodType

core/src/androidTest/java/org/hisp/dhis/android/core/analytics/eventlinelist/EventLineListIntegrationShould.kt, core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceLocalQueryHelperMockIntegrationShould.kt, core/src/main/java/org/hisp/dhis/android/core/common/DateFilterPeriodHelper.kt, core/src/test/java/org/hisp/dhis/android/core/common/DateFilterPeriodHelperShould.kt, core/src/test/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceLocalQueryHelperShould.kt, core/src/test/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryDataSourceShould.kt, core/src/test/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryOnlineHelperShould.kt
Solves [ANDROSDK-1903](https://dhis2.atlassian.net/browse/ANDROSDK-1903).
[ANDROSDK-1903]: https://dhis2.atlassian.net/browse/ANDROSDK-1903?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: [ANDROSDK-1903] Remove Calendar from DateFilterPeriodHelper

core/build.gradle.kts, core/config/config.yml, core/config/detekt.yml, gradle/libs.versions.toml, gradle/wrapper/gradle-wrapper.properties
Related task: [ANDROSDK-1874](https://dhis2.atlassian.net/jira/software/c/projects/ANDROSDK/boards/93?selectedIssue=ANDROSDK-1874)
[ANDROSDK-1874]: https://dhis2.atlassian.net/browse/ANDROSDK-1874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: [ANDROSDK-1874] Upgrade to Kotlin 2.0

core/src/main/java/org/hisp/dhis/android/core/visualization/TrackerVisualization.java, core/src/main/java/org/hisp/dhis/android/core/visualization/TrackerVisualizationCollectionRepository.kt, core/src/main/java/org/hisp/dhis/android/core/visualization/TrackerVisualizationDimension.java, core/src/main/java/org/hisp/dhis/android/core/visualization/internal/TrackerVisualizationDimensionHandler.kt, core/src/main/java/org/hisp/dhis/android/core/visualization/internal/TrackerVisualizationHandler.kt, core/src/main/java/org/hisp/dhis/android/core/visualization/internal/TrackerVisualizationNetworkHandler.kt, core/src/main/java/org/hisp/dhis/android/core/visualization/internal/VisualizationCall.kt, core/src/main/java/org/hisp/dhis/android/core/visualization/internal/VisualizationNetworkHandler.kt, core/src/main/java/org/hisp/dhis/android/network/trackervisualization/TrackerVisualizationDTO.kt, core/src/main/java/org/hisp/dhis/android/network/trackervisualization/TrackerVisualizationDimensionDTO.kt, core/src/main/java/org/hisp/dhis/android/network/trackervisualization/TrackerVisualizationDimensionFields.kt, core/src/main/java/org/hisp/dhis/android/network/trackervisualization/TrackerVisualizationDimensionRepetitionDTO.kt, core/src/main/java/org/hisp/dhis/android/network/trackervisualization/TrackerVisualizationDimensionRepetitionFields.kt, core/src/main/java/org/hisp/dhis/android/network/trackervisualization/TrackerVisualizationFields.kt, core/src/main/java/org/hisp/dhis/android/network/trackervisualization/TrackerVisualizationNetworkHandlerImpl.kt, core/src/main/java/org/hisp/dhis/android/network/trackervisualization/TrackerVisualizationService.kt, core/src/test/java/org/hisp/dhis/android/core/arch/api/fields/internal/FieldsStringGenerationShould.kt, core/src/test/java/org/hisp/dhis/android/core/visualization/TrackerVisualizationShould.kt, core/src/test/java/org/hisp/dhis/android/core/visualization/internal/TrackerVisualizationHandlerShould.kt
Solves [ANDROSDK-1970](https://dhis2.atlassian.net/browse/ANDROSDK-1970)
[ANDROSDK-1970]: https://dhis2.atlassian.net/browse/ANDROSDK-1970?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: [ANDROSDK-1970] Move TrackerVisualizationService to network

core/src/main/java/org/hisp/dhis/android/core/organisationunit/internal/OrganisationUnitLevelEndpointCall.kt, core/src/main/java/org/hisp/dhis/android/core/organisationunit/internal/OrganisationUnitLevelNetworkHandler.kt, core/src/main/java/org/hisp/dhis/android/network/organisationunitlevel/OrganisationUnitLevelDTO.kt, core/src/main/java/org/hisp/dhis/android/network/organisationunitlevel/OrganisationUnitLevelFields.kt, core/src/main/java/org/hisp/dhis/android/network/organisationunitlevel/OrganisationUnitLevelNetworkHandlerImpl.kt, core/src/main/java/org/hisp/dhis/android/network/organisationunitlevel/OrganisationUnitLevelService.kt, core/src/test/java/org/hisp/dhis/android/core/arch/api/fields/internal/FieldsStringGenerationShould.kt, core/src/test/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitLevelShould.kt
Solves [ANDROSDK-1999](https://dhis2.atlassian.net/browse/ANDROSDK-1999)
[ANDROSDK-1999]: https://dhis2.atlassian.net/browse/ANDROSDK-1999?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ANDROSDK-1999] Move OrganisationUnitLevel to api layer

core/src/main/java/org/hisp/dhis/android/core/usecase/stock/InternalStockUseCase.java, core/src/main/java/org/hisp/dhis/android/core/usecase/stock/InternalStockUseCaseTransaction.java, core/src/main/java/org/hisp/dhis/android/core/usecase/stock/internal/StockUseCaseNetworkHandler.kt, core/src/main/java/org/hisp/dhis/android/network/usecase/stock/StockUseCaseDTO.kt, core/src/main/java/org/hisp/dhis/android/network/usecase/stock/StockUseCaseNetworkHandlerImpl.kt, core/src/main/java/org/hisp/dhis/android/network/usecase/stock/StockUseCaseService.kt, core/src/main/java/org/hisp/dhis/android/network/usecase/stock/StockUseCaseTransactionDTO.kt, core/src/test/java/org/hisp/dhis/android/core/usecase/stock/InternalStockUseCaseShould.kt, core/src/test/java/org/hisp/dhis/android/core/usecase/stock/StockUseCaseCallShould.kt
Solves [ANDROSDK-2005](https://dhis2.atlassian.net/browse/ANDROSDK-2005)
[ANDROSDK-2005]: https://dhis2.atlassian.net/browse/ANDROSDK-2005?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: [ANDROSDK-2005] Move StockUseCase to api layer

core/src/main/java/org/hisp/dhis/android/core/fileresource/FileResource.java, core/src/main/java/org/hisp/dhis/android/core/fileresource/FileResourceInternalAccessor.kt, core/src/main/java/org/hisp/dhis/android/core/fileresource/internal/FileResourceDownloadCall.kt, core/src/main/java/org/hisp/dhis/android/core/fileresource/internal/FileResourceNetworkHandler.kt, core/src/main/java/org/hisp/dhis/android/core/fileresource/internal/FileResourcePostCall.kt, core/src/main/java/org/hisp/dhis/android/network/fileresource/FileResourceDTO.kt, core/src/main/java/org/hisp/dhis/android/network/fileresource/FileResourceFields.kt, core/src/main/java/org/hisp/dhis/android/network/fileresource/FileResourceNetworkHandlerImpl.kt, core/src/main/java/org/hisp/dhis/android/network/fileresource/FileResourceService.kt, core/src/test/java/org/hisp/dhis/android/core/arch/api/fields/internal/FieldsStringGenerationShould.kt, core/src/test/java/org/hisp/dhis/android/core/fileresource/FileResourceShould.kt
Related task: [ANDROSDK-2013](https://dhis2.atlassian.net/jira/software/c/projects/ANDROSDK/boards/154?selectedIssue=ANDROSDK-2013)
[ANDROSDK-2013]: https://dhis2.atlassian.net/browse/ANDROSDK-2013?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: [ANDROSDK-2013] Move FileResourceService to api layer

core/api/core.api, core/src/androidTest/java/org/hisp/dhis/android/testapp/dataset/DataSetInstanceServiceMockIntegrationShould.kt, core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetInstanceService.kt, core/src/main/java/org/hisp/dhis/android/core/dataset/internal/DataSetInstanceServiceImpl.kt, core/src/test/java/org/hisp/dhis/android/core/dataset/DataSetInstanceServiceShould.kt
Solves [ANDROSDK-2034](https://dhis2.atlassian.net/browse/ANDROSDK-2034).
[ANDROSDK-2034]: https://dhis2.atlassian.net/browse/ANDROSDK-2034?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feature: [ANDROSDK-2034] Add methods to handle missing mandatory data element operands and fields combinations

core/api/core.api, core/build.gradle.kts, core/src/main/java/org/hisp/dhis/android/core/settings/CustomIntentContext.kt, core/src/main/java/org/hisp/dhis/android/core/settings/CustomIntentService.kt, core/src/main/java/org/hisp/dhis/android/core/settings/SettingModule.kt, core/src/main/java/org/hisp/dhis/android/core/settings/internal/CustomIntentServiceImpl.kt, core/src/main/java/org/hisp/dhis/android/core/settings/internal/SettingModuleImpl.kt, core/src/main/java/org/hisp/dhis/android/network/settings/CustomIntentResponseDataDTO.kt, core/src/test/java/org/hisp/dhis/android/core/settings/CustomIntentServiceShould.kt, gradle/libs.versions.toml
[ANDROSDK-2043](https://dhis2.atlassian.net/browse/ANDROSDK-2043)
Adds a service to evaluate the request parameters of the custom intent.
[ANDROSDK-2043]: https://dhis2.atlassian.net/browse/ANDROSDK-2043?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: [ANDROSDK-2043] Add CustomIntentService to evaluate request params

core/api/core.api, core/src/main/java/org/hisp/dhis/android/core/settings/CustomIntentContext.kt, core/src/main/java/org/hisp/dhis/android/core/settings/internal/CustomIntentServiceImpl.kt, core/src/test/java/org/hisp/dhis/android/core/settings/CustomIntentServiceShould.kt, gradle/libs.versions.toml
This PR updates the expression-parser to use the includes the AndroidCustomIntent mode. This mode adds support for new variables and some d2 functions.
The Android app will have to update the code to pass the new context.
=> feat: [ANDROSDK-2043-2] Update expression-parser library (custom intent variables)
